// Seed: 1788985433
module module_0 (
    input wire id_0,
    output wand id_1,
    input tri id_2
    , id_23,
    input wor id_3,
    input supply0 id_4,
    input supply1 id_5,
    input wand id_6,
    input supply1 id_7,
    output uwire id_8,
    output uwire id_9,
    output wor id_10,
    output wor id_11,
    input uwire id_12,
    output uwire id_13,
    output uwire id_14,
    input supply0 id_15,
    output tri id_16,
    output tri id_17,
    output supply0 module_0,
    input supply1 id_19,
    input tri id_20,
    output wor id_21
);
endmodule
module module_1 (
    input tri0 id_0,
    output wor id_1,
    input wor id_2,
    input tri1 id_3,
    output tri id_4,
    input wor id_5,
    input tri1 id_6,
    output tri0 id_7,
    input supply1 id_8,
    input tri0 id_9,
    output uwire id_10,
    input wire id_11,
    input tri1 id_12,
    input wire id_13,
    input wire id_14,
    output supply1 id_15,
    input tri1 id_16,
    output tri1 id_17,
    input uwire id_18,
    input tri1 id_19,
    input wand id_20,
    input supply1 id_21
);
  assign id_1 = +1'b0;
  module_0(
      id_2,
      id_10,
      id_2,
      id_19,
      id_9,
      id_19,
      id_0,
      id_11,
      id_17,
      id_10,
      id_4,
      id_15,
      id_21,
      id_1,
      id_4,
      id_21,
      id_10,
      id_10,
      id_1,
      id_18,
      id_3,
      id_7
  );
endmodule
