// Seed: 642414903
module module_0 (
    input  tri0 id_0,
    output wand id_1
);
  assign id_1 = id_0;
  module_2 modCall_1 (
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0
  );
  assign modCall_1.type_5 = 0;
  assign module_1.id_1 = 0;
endmodule
module module_1 (
    output tri1 id_0,
    output supply1 id_1,
    output tri1 id_2,
    id_5,
    input wire id_3
);
  wire id_6;
  module_0 modCall_1 (
      id_3,
      id_0
  );
endmodule
module module_2 (
    input wor id_0,
    input tri id_1,
    input wand id_2,
    input tri1 id_3,
    input supply0 id_4,
    output tri id_5,
    output wand id_6,
    input supply1 id_7,
    input wor id_8,
    input supply0 id_9,
    input wand id_10,
    input tri id_11,
    output tri0 id_12,
    output wor id_13,
    output supply0 id_14,
    output wand id_15,
    input supply0 id_16,
    input tri1 id_17,
    id_52,
    output tri id_18,
    input tri id_19,
    input tri0 id_20,
    output tri id_21,
    output supply1 id_22,
    output tri id_23,
    input wire id_24,
    output uwire id_25,
    input wor id_26,
    output tri0 id_27,
    input supply0 id_28,
    input wor id_29,
    output supply1 id_30,
    output uwire id_31,
    output tri1 id_32,
    output wire id_33,
    input wor id_34,
    input supply0 id_35,
    input wand id_36,
    input wire id_37,
    input uwire id_38,
    output uwire id_39,
    output wire id_40,
    input wor id_41,
    input tri1 id_42,
    input wand id_43,
    output tri1 id_44,
    input tri id_45,
    input tri id_46,
    output wor id_47,
    input tri id_48,
    input supply1 id_49,
    input tri1 id_50
);
  assign id_18 = 1;
endmodule
