// Seed: 357130974
module module_0 (
    input tri0 id_0#(
        .\id_57 ($display),
        .id_58  (-1),
        .id_59  (1 - id_9)
    ),
    output supply0 id_1,
    output uwire id_2,
    input tri id_3,
    output supply1 id_4,
    output tri0 id_5,
    input tri1 id_6,
    output wand id_7,
    output wire id_8,
    input supply0 id_9,
    output uwire id_10,
    input wire id_11,
    input wor id_12,
    input uwire id_13,
    id_60,
    output supply1 id_14,
    output wand id_15,
    output wor id_16,
    id_61,
    output wand id_17,
    input uwire id_18,
    output wand id_19,
    output uwire id_20,
    output tri id_21,
    input tri1 id_22,
    input wand id_23,
    input supply1 id_24,
    output tri0 id_25,
    output tri1 id_26,
    output wor id_27,
    output wor id_28,
    output wire id_29,
    output tri0 id_30,
    input tri id_31,
    output wand id_32,
    input wand id_33,
    id_62,
    output uwire id_34,
    output tri0 id_35,
    input supply1 id_36#(
        .id_63(1),
        .id_64(id_64)
    ),
    output wand id_37,
    input wand id_38,
    input supply0 id_39,
    output uwire id_40,
    id_65,
    input supply0 id_41,
    output tri id_42,
    input supply1 id_43,
    input tri id_44,
    output supply1 id_45,
    input uwire id_46,
    input wand id_47,
    output tri0 id_48,
    input tri0 id_49,
    input supply0 id_50,
    output wor id_51,
    input tri0 id_52,
    id_66,
    input tri id_53,
    input supply1 id_54,
    output tri0 id_55
);
endmodule
module module_1 (
    input tri id_0,
    input tri0 id_1,
    output supply0 id_2,
    input tri id_3,
    input uwire id_4,
    input tri0 id_5,
    input wand id_6,
    output logic id_7,
    input logic id_8,
    output wire id_9,
    input uwire id_10,
    input supply1 id_11
);
  assign id_7 = id_8;
  module_0 modCall_1 (
      id_10,
      id_2,
      id_9,
      id_5,
      id_2,
      id_2,
      id_5,
      id_9,
      id_2,
      id_0,
      id_9,
      id_1,
      id_5,
      id_0,
      id_9,
      id_9,
      id_9,
      id_2,
      id_5,
      id_9,
      id_2,
      id_2,
      id_4,
      id_10,
      id_11,
      id_9,
      id_9,
      id_9,
      id_2,
      id_9,
      id_9,
      id_6,
      id_9,
      id_1,
      id_9,
      id_2,
      id_1,
      id_2,
      id_1,
      id_0,
      id_9,
      id_3,
      id_9,
      id_0,
      id_1,
      id_9,
      id_5,
      id_6,
      id_2,
      id_6,
      id_1,
      id_2,
      id_3,
      id_4,
      id_5,
      id_2
  );
  id_13(
      .id_0(-1), .id_1(id_9), .id_2(1)
  );
  always id_9 = $display(id_8);
  assign id_7 = id_8;
  initial id_7 <= "";
  wire id_14;
endmodule
