// Seed: 2161130409
module module_0 (
    input uwire id_0,
    input wand id_1,
    input wand id_2,
    input tri id_3,
    input tri1 id_4,
    input wor id_5,
    input supply1 id_6,
    input wire id_7,
    input tri0 id_8,
    output uwire id_9,
    input wire id_10,
    input tri0 id_11,
    input wand id_12,
    input tri0 id_13,
    input uwire id_14,
    output tri1 id_15,
    output supply1 id_16,
    output supply1 id_17,
    output tri0 id_18,
    input supply0 void id_19,
    id_36,
    output wire id_20,
    output wand id_21,
    input tri0 id_22,
    id_37 = -1,
    input wor id_23,
    input supply0 id_24,
    output supply1 id_25,
    input wor id_26,
    input tri id_27,
    input tri0 id_28,
    input wand id_29,
    input tri id_30,
    output wor id_31,
    input uwire id_32,
    id_38,
    input tri0 id_33,
    input tri id_34
);
  parameter id_39 = 1'd0;
  assign module_1.id_2 = 0;
endmodule
program module_1 (
    output supply1 id_0,
    input supply0 id_1,
    output wand id_2,
    output supply1 id_3,
    output wand id_4,
    input tri1 id_5,
    output wire id_6
);
  parameter id_8 = id_1 !== -1'h0;
  module_0 modCall_1 (
      id_1,
      id_5,
      id_5,
      id_1,
      id_1,
      id_1,
      id_5,
      id_5,
      id_5,
      id_3,
      id_1,
      id_5,
      id_5,
      id_1,
      id_1,
      id_2,
      id_0,
      id_3,
      id_3,
      id_5,
      id_4,
      id_3,
      id_1,
      id_1,
      id_1,
      id_2,
      id_5,
      id_1,
      id_1,
      id_1,
      id_5,
      id_6,
      id_1,
      id_1,
      id_1
  );
endmodule
