// Seed: 784163297
module module_0 (
    output supply1 id_0,
    input wand id_1,
    output wor id_2,
    id_41,
    output tri1 id_3,
    input uwire id_4,
    input wand id_5,
    output tri1 id_6,
    input wor id_7,
    output supply0 id_8,
    input wand id_9,
    output wor id_10,
    output tri id_11,
    input uwire id_12,
    input supply0 id_13,
    input supply0 id_14,
    output supply1 id_15,
    input supply0 id_16,
    id_42,
    output tri1 id_17,
    output uwire id_18,
    input supply1 id_19,
    input tri id_20,
    input wor id_21,
    input tri0 id_22,
    input supply1 id_23,
    input wor id_24,
    input wor id_25,
    output supply1 id_26,
    input wire id_27,
    input tri1 id_28,
    output uwire id_29,
    input supply1 id_30,
    input wor id_31,
    input tri id_32,
    output tri0 id_33,
    input uwire id_34,
    input wor id_35,
    output uwire id_36,
    input wire id_37,
    input tri id_38,
    input wand id_39
);
  wire id_43;
endmodule
module module_1 (
    output tri0 id_0,
    input uwire id_1,
    input tri1 id_2,
    output uwire id_3,
    input tri id_4,
    inout supply0 id_5,
    input tri0 id_6,
    output wand id_7,
    input wire id_8
);
  assign id_3 = id_2;
  module_0 modCall_1 (
      id_3,
      id_1,
      id_0,
      id_0,
      id_5,
      id_5,
      id_5,
      id_1,
      id_3,
      id_2,
      id_5,
      id_0,
      id_5,
      id_1,
      id_1,
      id_0,
      id_2,
      id_0,
      id_5,
      id_5,
      id_2,
      id_2,
      id_2,
      id_5,
      id_2,
      id_8,
      id_3,
      id_6,
      id_8,
      id_0,
      id_8,
      id_2,
      id_1,
      id_0,
      id_4,
      id_1,
      id_0,
      id_2,
      id_8,
      id_2
  );
  assign modCall_1.id_9 = 0;
  wire id_10;
  wire id_11;
  if (-1) assign id_3 = id_5;
endmodule
