// Seed: 562859961
module module_0 (
    input uwire id_0,
    output wand id_1,
    input wor id_2,
    output wand id_3,
    output wire id_4,
    output supply0 id_5,
    input tri1 id_6,
    output uwire id_7,
    input supply0 id_8,
    input tri0 id_9,
    input wand id_10,
    input wire id_11,
    input uwire id_12,
    output uwire id_13,
    input supply0 id_14,
    input wire id_15,
    output tri0 id_16,
    output wand id_17,
    input supply1 id_18,
    input tri0 id_19,
    input wor id_20
);
endmodule
module module_1 (
    input wire id_0,
    output uwire id_1,
    input wire id_2,
    output tri id_3,
    input tri1 id_4,
    input wire id_5,
    output wor id_6,
    input supply0 id_7,
    input supply1 id_8,
    input tri0 id_9,
    output tri0 id_10,
    input supply1 id_11,
    output wand id_12,
    output wor id_13,
    output wire id_14,
    output wor id_15,
    input tri id_16,
    id_28,
    input supply0 id_17,
    input supply0 id_18,
    output supply0 id_19,
    output wor id_20,
    input tri1 id_21,
    output tri1 id_22,
    output wand id_23,
    output tri0 id_24,
    input wand id_25,
    output wand id_26
);
  wire id_29;
  module_0 modCall_1 (
      id_8,
      id_3,
      id_5,
      id_20,
      id_14,
      id_23,
      id_5,
      id_6,
      id_7,
      id_8,
      id_5,
      id_8,
      id_5,
      id_14,
      id_5,
      id_4,
      id_10,
      id_20,
      id_18,
      id_17,
      id_4
  );
  assign modCall_1.type_28 = 0;
endmodule
