// Seed: 566516594
module module_0 (
    output uwire id_0,
    input wor id_1,
    input wire id_2,
    input supply0 id_3,
    input supply1 id_4,
    input wand id_5,
    input tri id_6,
    output wire id_7,
    input tri1 id_8,
    output tri1 id_9,
    input tri1 id_10,
    output tri id_11,
    output tri0 id_12,
    input supply0 id_13,
    id_41,
    input wand id_14,
    output uwire id_15,
    output wire id_16,
    input tri id_17,
    input supply1 id_18,
    id_42,
    output tri0 id_19,
    input wor id_20,
    output tri1 id_21,
    input uwire id_22,
    output wand id_23,
    id_43 = -1,
    input tri1 id_24,
    input tri1 id_25,
    input wor id_26,
    input wor id_27,
    input tri id_28,
    input wire id_29,
    input wor id_30,
    input wor id_31,
    input supply1 id_32,
    input wor id_33,
    output uwire id_34,
    input wor id_35,
    input uwire id_36,
    input uwire id_37,
    input tri0 id_38,
    output tri1 id_39
);
  id_44(
      1, -1'b0 - id_37
  );
endmodule
module module_1 (
    input wand id_0,
    input tri0 id_1,
    input tri1 id_2,
    output supply1 id_3,
    input tri id_4
);
  wire id_6;
  module_0 modCall_1 (
      id_3,
      id_0,
      id_2,
      id_1,
      id_0,
      id_2,
      id_4,
      id_3,
      id_2,
      id_3,
      id_4,
      id_3,
      id_3,
      id_1,
      id_4,
      id_3,
      id_3,
      id_4,
      id_2,
      id_3,
      id_4,
      id_3,
      id_0,
      id_3,
      id_1,
      id_0,
      id_1,
      id_4,
      id_4,
      id_4,
      id_2,
      id_4,
      id_4,
      id_1,
      id_3,
      id_0,
      id_1,
      id_0,
      id_0,
      id_3
  );
  assign modCall_1.type_56 = 0;
  localparam id_7 = id_7;
endmodule
