// Seed: 3906414329
module module_0 (
    output wor id_0,
    input wire id_1,
    input supply0 id_2,
    input supply0 id_3,
    input supply0 id_4,
    input wor id_5,
    input tri1 id_6,
    input tri1 id_7,
    output tri1 id_8,
    input tri id_9,
    input supply1 id_10,
    output wire id_11,
    input uwire id_12,
    input wire id_13,
    output tri0 id_14,
    output tri0 id_15,
    output supply1 id_16,
    input wand id_17,
    input wand id_18,
    output tri0 id_19,
    input wand id_20,
    input wand id_21,
    input wire id_22,
    output wor id_23,
    output supply0 id_24,
    output wand id_25
);
endmodule
module module_1 (
    input tri0 id_0,
    input supply0 id_1,
    input tri1 id_2,
    input wire id_3,
    output wire id_4,
    input wire id_5,
    output tri0 id_6,
    output wor id_7,
    input wire id_8,
    input wand id_9,
    input uwire id_10,
    output tri0 id_11,
    input wor id_12,
    output supply1 id_13,
    output wire id_14,
    input wor id_15,
    input supply0 id_16,
    output supply0 id_17
);
  module_0 modCall_1 (
      id_4,
      id_16,
      id_0,
      id_2,
      id_2,
      id_3,
      id_3,
      id_10,
      id_11,
      id_10,
      id_5,
      id_4,
      id_15,
      id_12,
      id_4,
      id_11,
      id_4,
      id_10,
      id_8,
      id_4,
      id_9,
      id_8,
      id_0,
      id_4,
      id_11,
      id_14
  );
  assign modCall_1.type_28 = 0;
endmodule
