// Seed: 1378765057
module module_0 (
    output supply0 id_0,
    output tri0 id_1,
    input tri1 id_2,
    input uwire id_3,
    input supply0 id_4,
    input uwire id_5,
    input wand id_6,
    input wand id_7,
    output supply0 id_8,
    output supply1 id_9,
    input tri1 id_10,
    input supply1 id_11,
    input wand id_12,
    input wire id_13,
    input supply0 id_14,
    output uwire id_15,
    input uwire id_16,
    input supply1 id_17,
    input wire id_18,
    input uwire id_19,
    input tri0 id_20,
    output tri1 id_21,
    output wand id_22,
    output supply0 id_23,
    input supply1 id_24,
    output tri1 id_25,
    input tri1 id_26,
    output tri0 id_27,
    input supply1 id_28,
    output tri id_29,
    output supply0 id_30,
    output tri0 id_31,
    output wire id_32,
    input wor id_33,
    output wire id_34,
    input wand id_35,
    input tri0 id_36,
    input tri1 id_37,
    input tri id_38,
    input tri0 id_39,
    input wire id_40,
    output tri1 id_41,
    input uwire id_42,
    input wand id_43,
    input supply1 id_44,
    input tri0 id_45,
    output uwire id_46,
    id_59,
    input wire id_47,
    output wor id_48,
    output tri0 id_49,
    input uwire id_50,
    input wor id_51,
    input wor id_52,
    input uwire id_53,
    input wor id_54,
    input wire id_55,
    output uwire id_56,
    output tri id_57
);
  wire id_60;
  assign module_1.type_5 = 0;
  always if (1 - 1) id_22 = -1;
  id_61(
      ""
  );
  wire id_62;
endmodule
module module_1 (
    input tri0 id_0,
    output tri id_1,
    input tri0 id_2,
    input uwire id_3,
    input wand id_4,
    input supply0 id_5,
    output wire id_6,
    input tri1 id_7,
    input wand id_8,
    input wor id_9,
    output uwire id_10
);
  module_0 modCall_1 (
      id_10,
      id_6,
      id_7,
      id_9,
      id_7,
      id_2,
      id_8,
      id_8,
      id_10,
      id_10,
      id_3,
      id_8,
      id_9,
      id_3,
      id_4,
      id_6,
      id_3,
      id_7,
      id_4,
      id_3,
      id_0,
      id_1,
      id_10,
      id_10,
      id_7,
      id_6,
      id_5,
      id_6,
      id_2,
      id_10,
      id_1,
      id_1,
      id_6,
      id_5,
      id_6,
      id_2,
      id_3,
      id_9,
      id_8,
      id_2,
      id_2,
      id_1,
      id_9,
      id_7,
      id_9,
      id_8,
      id_6,
      id_7,
      id_1,
      id_1,
      id_2,
      id_3,
      id_9,
      id_8,
      id_8,
      id_5,
      id_1,
      id_6
  );
endmodule
