// Seed: 1317606006
program module_0 (
    input tri0 id_0,
    input uwire id_1,
    output tri id_2,
    output tri id_3,
    output tri0 id_4,
    input wor id_5,
    input wand id_6,
    output tri0 id_7,
    output wire id_8,
    input uwire id_9,
    input supply1 id_10,
    output tri id_11,
    output wire id_12,
    input supply0 id_13,
    output uwire id_14,
    input wor id_15,
    input tri id_16,
    input tri id_17,
    output tri0 id_18,
    input tri id_19,
    input uwire id_20,
    input uwire id_21,
    output tri id_22,
    input tri1 id_23,
    input uwire id_24,
    input tri0 id_25,
    input tri id_26,
    input uwire id_27,
    input wand id_28,
    input wand id_29,
    input supply1 id_30,
    input supply0 id_31,
    output wor id_32,
    input wor id_33,
    input wand id_34,
    input wire id_35
);
  tri0 id_37 = id_13 == -1;
  wire id_38;
endmodule
module module_1 (
    input wor id_0,
    output wor id_1,
    output supply1 id_2,
    input wand id_3,
    input supply1 id_4,
    output tri id_5,
    input wire id_6,
    input tri id_7,
    output wor id_8,
    input supply1 id_9,
    input tri id_10,
    input tri id_11,
    output supply0 void id_12,
    output tri0 id_13,
    output wand id_14,
    output wand id_15,
    output tri1 id_16,
    input tri0 id_17
);
  module_0 modCall_1 (
      id_4,
      id_11,
      id_14,
      id_2,
      id_2,
      id_3,
      id_4,
      id_5,
      id_2,
      id_17,
      id_10,
      id_15,
      id_15,
      id_7,
      id_8,
      id_11,
      id_3,
      id_17,
      id_8,
      id_4,
      id_6,
      id_10,
      id_16,
      id_4,
      id_11,
      id_0,
      id_7,
      id_10,
      id_3,
      id_0,
      id_4,
      id_7,
      id_8,
      id_11,
      id_6,
      id_17
  );
  assign modCall_1.id_11 = 0;
endmodule
