// Seed: 3980079671
module module_0 (
    output wire id_0,
    input wire id_1,
    output tri1 id_2,
    input supply1 id_3,
    output tri id_4
    , id_40,
    output tri id_5,
    input supply0 id_6,
    input uwire id_7,
    input supply1 id_8,
    input tri1 id_9,
    output tri id_10,
    input wand id_11,
    output supply0 id_12,
    input wand id_13,
    output wor id_14,
    input wire id_15,
    input wire id_16,
    output tri0 id_17,
    input uwire id_18,
    input uwire id_19,
    input wor id_20,
    input wor id_21,
    input uwire id_22,
    output uwire id_23,
    output tri id_24,
    input wand id_25,
    output wire id_26,
    input wor id_27,
    input supply0 id_28,
    input supply1 id_29,
    input wand id_30,
    input supply1 id_31,
    input supply0 id_32,
    input supply1 id_33,
    input tri id_34,
    output wor id_35,
    input tri1 id_36,
    output tri id_37,
    output wand id_38
);
  wire id_41;
endmodule
module module_1 (
    input wand id_0,
    input wor id_1,
    input supply1 id_2,
    input uwire id_3,
    output wor id_4,
    output wire id_5,
    input uwire id_6,
    output supply0 id_7,
    input supply0 id_8,
    output uwire id_9,
    input supply0 id_10
);
  always return 1;
  module_0 modCall_1 (
      id_9,
      id_3,
      id_7,
      id_2,
      id_7,
      id_9,
      id_10,
      id_8,
      id_3,
      id_10,
      id_9,
      id_8,
      id_9,
      id_3,
      id_4,
      id_3,
      id_10,
      id_7,
      id_0,
      id_3,
      id_10,
      id_2,
      id_10,
      id_4,
      id_7,
      id_6,
      id_5,
      id_0,
      id_2,
      id_10,
      id_3,
      id_0,
      id_6,
      id_1,
      id_3,
      id_9,
      id_6,
      id_9,
      id_4
  );
  assign modCall_1.id_0 = 0;
  wire id_12;
endmodule
