// Seed: 4130164841
module module_0 (
    output wand id_0,
    input uwire id_1,
    output supply0 id_2,
    output tri0 id_3,
    input wire id_4,
    output wire id_5
    , id_56,
    input wire id_6,
    output tri0 id_7,
    output wor id_8,
    output supply1 id_9,
    input wire id_10,
    input wor id_11,
    output supply0 id_12,
    input supply0 id_13,
    output supply1 id_14,
    output supply1 id_15,
    output wire id_16,
    output wire id_17,
    input tri0 id_18,
    input wor id_19,
    input tri0 id_20,
    input supply1 id_21,
    input wor id_22,
    input supply1 id_23,
    input wand id_24,
    input wor id_25,
    output wor id_26,
    input uwire id_27,
    input supply1 id_28,
    input tri1 id_29,
    input wor id_30,
    input tri0 id_31,
    input uwire id_32,
    output tri id_33,
    input wor id_34,
    output wor id_35,
    input uwire id_36,
    input tri1 id_37,
    input wire id_38,
    input tri id_39,
    input uwire id_40,
    output uwire id_41,
    output tri id_42,
    input tri id_43,
    output tri0 id_44,
    input tri1 id_45,
    output tri0 id_46,
    output tri0 id_47,
    input supply1 id_48,
    input supply0 id_49,
    output supply1 id_50,
    input tri0 id_51,
    output wire id_52,
    output wire id_53,
    input wor id_54
);
  wire id_57;
  wand id_58, id_59 = (id_11) | 1'b0;
  assign id_53 = 1;
endmodule
module module_1 (
    output uwire id_0,
    input supply0 id_1,
    output wire id_2,
    output wor id_3,
    input uwire id_4,
    output logic id_5
);
  assign id_0 = id_1;
  initial id_5 <= 1;
  module_0(
      id_2,
      id_4,
      id_2,
      id_3,
      id_1,
      id_3,
      id_4,
      id_3,
      id_2,
      id_3,
      id_4,
      id_1,
      id_2,
      id_1,
      id_3,
      id_0,
      id_0,
      id_3,
      id_1,
      id_4,
      id_4,
      id_4,
      id_4,
      id_1,
      id_1,
      id_4,
      id_2,
      id_4,
      id_4,
      id_4,
      id_1,
      id_4,
      id_4,
      id_0,
      id_1,
      id_3,
      id_1,
      id_1,
      id_1,
      id_4,
      id_4,
      id_3,
      id_0,
      id_1,
      id_2,
      id_1,
      id_0,
      id_3,
      id_4,
      id_4,
      id_2,
      id_4,
      id_3,
      id_3,
      id_4
  );
endmodule
