// Seed: 2695886958
module module_0 (
    output wor id_0,
    input tri0 id_1,
    output uwire id_2,
    output tri0 id_3,
    input supply1 id_4,
    input wand id_5,
    output uwire id_6,
    output tri1 id_7,
    input uwire id_8,
    output wor id_9,
    input wor id_10,
    output uwire id_11,
    output wor id_12,
    input wire id_13,
    input uwire id_14
    , id_47,
    output tri id_15
    , id_48,
    input wire id_16,
    input uwire id_17,
    output wire id_18,
    output tri0 id_19,
    input uwire id_20,
    input uwire id_21,
    output supply0 id_22,
    input wire id_23,
    output wand id_24,
    input supply1 id_25,
    output tri1 id_26[-1 : 1],
    input supply1 id_27,
    output supply0 id_28,
    input wand id_29,
    input supply0 id_30,
    input tri0 id_31,
    output uwire id_32,
    input tri0 id_33,
    input wire id_34,
    input tri1 id_35,
    input uwire id_36,
    input supply0 id_37,
    output uwire id_38,
    input wand id_39,
    input wire id_40,
    output supply0 id_41,
    output uwire id_42,
    input wand id_43,
    input supply1 id_44,
    input tri0 id_45
);
endmodule
module module_1 (
    input tri0 id_0,
    output tri0 id_1,
    output supply0 id_2,
    input supply1 id_3
);
  logic id_5;
  module_0 modCall_1 (
      id_2,
      id_3,
      id_2,
      id_1,
      id_3,
      id_3,
      id_2,
      id_1,
      id_3,
      id_2,
      id_3,
      id_1,
      id_2,
      id_0,
      id_3,
      id_1,
      id_3,
      id_3,
      id_2,
      id_1,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_3,
      id_1,
      id_0,
      id_1,
      id_3,
      id_0,
      id_0,
      id_1,
      id_3,
      id_0,
      id_0,
      id_3,
      id_0,
      id_1,
      id_0,
      id_0,
      id_2,
      id_1,
      id_3,
      id_3,
      id_3
  );
  assign modCall_1.id_14 = 0;
endmodule
