// Seed: 3870240259
module module_0 (
    input wire id_0
    , id_39,
    output tri1 id_1,
    input supply1 id_2,
    output tri id_3,
    input tri id_4,
    output supply0 id_5,
    output uwire id_6,
    input supply1 id_7
    , id_40,
    input tri1 id_8,
    input tri id_9,
    input wand id_10,
    input supply0 id_11,
    input wand id_12,
    input wor id_13,
    input wire id_14,
    output wire id_15,
    output wire id_16,
    input uwire id_17,
    output uwire id_18,
    input wor id_19,
    input wor id_20,
    input uwire id_21,
    output uwire id_22,
    output tri id_23,
    input wand id_24,
    output wire id_25,
    output wor id_26,
    output supply0 id_27,
    input supply1 id_28,
    output wand id_29,
    input supply1 id_30
    , id_41,
    output supply0 id_31,
    input supply1 id_32,
    input tri id_33,
    input wor id_34,
    input tri1 id_35,
    input tri id_36,
    input wand id_37
);
  assign id_29 = 1;
  wire id_42, id_43;
  assign id_40 = id_4;
endmodule
module module_1 (
    input tri0 id_0,
    input wire id_1,
    input wand id_2,
    output tri1 id_3,
    output tri0 id_4#(.id_14(1)),
    input wor id_5,
    output tri1 id_6,
    output supply1 id_7,
    input tri0 id_8,
    input supply0 id_9,
    output supply1 id_10,
    input tri1 id_11,
    input wor id_12
);
  wire id_15;
  module_0 modCall_1 (
      id_8,
      id_6,
      id_11,
      id_4,
      id_9,
      id_4,
      id_7,
      id_5,
      id_1,
      id_12,
      id_9,
      id_2,
      id_8,
      id_12,
      id_8,
      id_7,
      id_4,
      id_12,
      id_4,
      id_5,
      id_9,
      id_2,
      id_10,
      id_3,
      id_8,
      id_6,
      id_10,
      id_4,
      id_5,
      id_4,
      id_8,
      id_10,
      id_2,
      id_8,
      id_2,
      id_2,
      id_2,
      id_0
  );
  assign modCall_1.id_13 = 0;
endmodule
