// Seed: 3795753280
module module_0 (
    input wire id_0,
    input supply1 id_1,
    output supply1 id_2,
    output tri0 id_3,
    input tri id_4,
    output supply0 id_5,
    output wor id_6,
    output wor id_7,
    output tri0 id_8,
    output supply0 id_9,
    output supply0 id_10,
    input wor id_11,
    input wor id_12,
    input wire id_13,
    input supply0 id_14,
    output tri0 id_15,
    output wire id_16,
    output tri id_17,
    input tri0 id_18,
    input supply1 id_19,
    output tri1 id_20,
    input uwire id_21,
    output wor id_22,
    input wor id_23,
    output tri1 id_24,
    output tri1 id_25,
    input supply1 id_26,
    input wire id_27,
    output wire id_28,
    input tri1 id_29,
    output wire id_30,
    input uwire id_31,
    output tri0 id_32,
    input supply1 id_33,
    output wor id_34,
    input wor id_35,
    output tri0 id_36
);
endmodule
module module_1 (
    input tri1 id_0,
    output supply1 id_1,
    input uwire id_2,
    output tri0 id_3,
    input uwire id_4,
    input tri id_5,
    input wor id_6,
    input wor id_7,
    output wor id_8,
    input wor id_9,
    output wor id_10
);
  wire id_12;
  wire id_13;
  module_0(
      id_0,
      id_5,
      id_8,
      id_3,
      id_2,
      id_8,
      id_10,
      id_10,
      id_10,
      id_8,
      id_1,
      id_0,
      id_6,
      id_5,
      id_5,
      id_10,
      id_1,
      id_8,
      id_7,
      id_2,
      id_10,
      id_2,
      id_10,
      id_0,
      id_3,
      id_3,
      id_7,
      id_2,
      id_10,
      id_4,
      id_10,
      id_7,
      id_8,
      id_9,
      id_10,
      id_7,
      id_3
  );
  wire id_14;
endmodule
