// Seed: 2830034336
module module_0 (
    input wand id_0,
    input wor id_1,
    output wire id_2,
    input tri id_3,
    output tri1 id_4,
    output supply1 id_5,
    output tri1 id_6,
    input wire id_7,
    input wand id_8,
    input wire id_9,
    output tri0 id_10,
    output supply1 id_11,
    input supply0 id_12,
    input supply1 id_13,
    input tri0 id_14,
    input tri0 id_15,
    input tri1 id_16,
    output tri0 id_17,
    input supply0 id_18,
    input wire module_0,
    output supply1 id_20,
    input tri id_21,
    input tri id_22,
    input supply0 id_23,
    output uwire id_24,
    output uwire id_25,
    input uwire id_26,
    input wor id_27,
    input wor id_28,
    output uwire id_29,
    input uwire id_30,
    input tri id_31,
    input wand id_32,
    input wire id_33,
    input wor id_34,
    output supply0 id_35,
    input supply1 id_36,
    input wand id_37,
    output supply1 id_38
);
  wire id_40;
endmodule
module module_1 (
    output wand id_0,
    input wire id_1,
    input wand id_2,
    output supply1 id_3,
    input wand id_4,
    output tri id_5,
    output tri1 id_6,
    output wor id_7
);
  tri  id_9 = id_4, id_10;
  wire id_11;
  module_0(
      id_2,
      id_2,
      id_6,
      id_9,
      id_6,
      id_5,
      id_10,
      id_9,
      id_2,
      id_10,
      id_10,
      id_7,
      id_9,
      id_2,
      id_1,
      id_9,
      id_10,
      id_6,
      id_4,
      id_2,
      id_10,
      id_9,
      id_9,
      id_2,
      id_5,
      id_5,
      id_4,
      id_9,
      id_2,
      id_10,
      id_2,
      id_9,
      id_2,
      id_4,
      id_2,
      id_5,
      id_2,
      id_10,
      id_5
  );
endmodule
