// Seed: 378650681
module module_0 (
    output tri1 id_0
    , id_40,
    input wand id_1,
    output tri0 id_2,
    input wand id_3,
    input tri id_4,
    input wire id_5,
    input uwire id_6,
    input wor id_7,
    input tri0 id_8,
    input tri0 id_9,
    output supply0 id_10,
    input tri1 id_11,
    output wor id_12,
    input tri id_13,
    output wire id_14,
    output uwire id_15,
    output wand id_16,
    output tri0 id_17,
    input uwire id_18,
    input tri0 id_19,
    input tri id_20,
    input wor id_21,
    input supply1 id_22,
    output uwire id_23,
    input tri1 id_24,
    input wire id_25,
    input supply1 id_26,
    output wor id_27,
    output wor id_28,
    input supply1 id_29,
    output tri0 id_30,
    output wor id_31,
    input tri id_32,
    output supply1 id_33,
    input uwire id_34,
    output wor id_35,
    input tri1 id_36,
    output wand id_37,
    input wand id_38
);
  assign id_35 = 1;
endmodule
module module_1 (
    input uwire id_0,
    input tri   id_1
);
  assign id_3 = id_0;
  wire id_4;
  module_0(
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_1,
      id_3,
      id_1,
      id_3,
      id_0,
      id_3,
      id_1,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_0,
      id_0,
      id_3,
      id_0,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_1,
      id_3,
      id_3,
      id_3,
      id_0,
      id_3,
      id_3
  );
endmodule
