// Seed: 116391687
module module_0 (
    input wire id_0,
    input wor id_1,
    output tri0 id_2,
    input tri0 id_3,
    output tri1 id_4,
    input tri1 id_5,
    input tri1 id_6,
    output supply1 id_7,
    output tri0 id_8,
    output tri id_9,
    input tri id_10,
    input supply0 id_11,
    output uwire id_12,
    input tri id_13,
    input uwire id_14,
    output wor id_15,
    input tri1 id_16,
    output uwire id_17,
    input supply0 id_18,
    input supply0 id_19,
    output wor id_20,
    output tri id_21,
    output tri id_22,
    input tri0 id_23,
    input wor id_24,
    input wor id_25
    , id_32,
    input wire id_26,
    input wor id_27,
    output wand id_28,
    output wand id_29,
    output uwire id_30
);
endmodule
module module_1 (
    input wand id_0,
    input wire id_1,
    output wand id_2,
    input supply1 id_3,
    input wand id_4,
    input tri id_5
    , id_9,
    input tri1 id_6,
    input wor id_7
);
  assign id_2 = 1 > 1;
  module_0(
      id_3,
      id_1,
      id_2,
      id_0,
      id_2,
      id_3,
      id_6,
      id_2,
      id_2,
      id_2,
      id_4,
      id_0,
      id_2,
      id_1,
      id_3,
      id_2,
      id_7,
      id_2,
      id_1,
      id_5,
      id_2,
      id_2,
      id_2,
      id_5,
      id_6,
      id_0,
      id_3,
      id_6,
      id_2,
      id_2,
      id_2
  );
endmodule
