// This program was cloned from: https://github.com/ajcci/sky130_ajc_ip__por
// License: Apache License 2.0

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 16.0.6 -fPIC -Os) */

module sky130_ef_sc_hd__decap_12();
endmodule

module sky130_ef_sc_hd__fill_12();
endmodule

module sky130_ef_sc_hd__fill_4();
endmodule

module sky130_ef_sc_hd__fill_8();
endmodule

module sky130_fd_sc_hd__a2111o_1(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2111o_2(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2111o_4(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2111oi_0(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2111oi_1(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2111oi_2(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2111oi_4(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a211o_1(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a211o_2(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a211o_4(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a211oi_1(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a211oi_2(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a211oi_4(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21bo_1(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21bo_2(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21bo_4(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21boi_0(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21boi_1(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21boi_2(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21boi_4(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21o_1(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21o_2(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21o_4(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a21oi_1(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21oi_2(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a21oi_4(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a221o_1(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a221o_2(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a221o_4(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a221oi_1(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a221oi_2(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a221oi_4(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a222oi_1(Y, A1, A2, B1, B2, C1, C2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  input C2;
  wire C2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a22o_1(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a22o_2(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a22o_4(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a22oi_1(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a22oi_2(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a22oi_4(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2bb2o_1(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2bb2o_2(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2bb2o_4(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a2bb2oi_1(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2bb2oi_2(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a2bb2oi_4(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a311o_1(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a311o_2(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a311o_4(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a311oi_1(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a311oi_2(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a311oi_4(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a31o_1(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a31o_2(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a31o_4(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a31oi_1(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a31oi_2(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a31oi_4(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a32o_1(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a32o_2(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a32o_4(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a32oi_1(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a32oi_2(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a32oi_4(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a41o_1(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a41o_2(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a41o_4(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__a41oi_1(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a41oi_2(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__a41oi_4(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__and2_0(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2_1(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2_2(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2_4(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2b_1(X, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2b_2(X, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and2b_4(X, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3_1(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3_2(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3_4(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3b_1(X, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3b_2(X, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and3b_4(X, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4_1(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4_2(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4_4(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4b_1(X, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4b_2(X, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4b_4(X, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4bb_1(X, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4bb_2(X, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__and4bb_4(X, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_12(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_16(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_6(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__buf_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__bufbuf_16(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__bufbuf_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__bufinv_16(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__bufinv_8(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkbuf_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkbuf_16(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkbuf_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkbuf_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkbuf_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s15_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s15_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s18_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s18_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s25_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s25_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s50_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s50_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__clkinv_1(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinv_16(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinv_2(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinv_4(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinv_8(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinvlp_2(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__clkinvlp_4(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__conb_1(HI, LO);
  output HI;
  wire HI;
  output LO;
  wire LO;
endmodule

module sky130_fd_sc_hd__decap_12();
endmodule

module sky130_fd_sc_hd__decap_3();
endmodule

module sky130_fd_sc_hd__decap_4();
endmodule

module sky130_fd_sc_hd__decap_6();
endmodule

module sky130_fd_sc_hd__decap_8();
endmodule

module sky130_fd_sc_hd__dfbbn_1(Q, Q_N, D, CLK_N, SET_B, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfbbn_2(Q, Q_N, D, CLK_N, SET_B, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfbbp_1(Q, Q_N, D, CLK, SET_B, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfrbp_1(Q, Q_N, CLK, D, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfrbp_2(Q, Q_N, CLK, D, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfrtn_1(Q, CLK_N, D, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfrtp_1(Q, CLK, D, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfrtp_2(Q, CLK, D, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfrtp_4(Q, CLK, D, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dfsbp_1(Q, Q_N, CLK, D, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfsbp_2(Q, Q_N, CLK, D, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfstp_1(Q, CLK, D, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfstp_2(Q, CLK, D, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfstp_4(Q, CLK, D, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__dfxbp_1(Q, Q_N, CLK, D);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__dfxbp_2(Q, Q_N, CLK, D);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__dfxtp_1(Q, CLK, D);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dfxtp_2(Q, CLK, D);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dfxtp_4(Q, CLK, D);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__diode_2(DIODE);
  input DIODE;
  wire DIODE;
endmodule

module sky130_fd_sc_hd__dlclkp_1(GCLK, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
endmodule

module sky130_fd_sc_hd__dlclkp_2(GCLK, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
endmodule

module sky130_fd_sc_hd__dlclkp_4(GCLK, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
endmodule

module sky130_fd_sc_hd__dlrbn_1(Q, Q_N, RESET_B, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrbn_2(Q, Q_N, RESET_B, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrbp_1(Q, Q_N, RESET_B, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrbp_2(Q, Q_N, RESET_B, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtn_1(Q, RESET_B, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtn_2(Q, RESET_B, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtn_4(Q, RESET_B, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtp_1(Q, RESET_B, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtp_2(Q, RESET_B, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlrtp_4(Q, RESET_B, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
endmodule

module sky130_fd_sc_hd__dlxbn_1(Q, Q_N, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__dlxbn_2(Q, Q_N, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__dlxbp_1(Q, Q_N, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__dlxtn_1(Q, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dlxtn_2(Q, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dlxtn_4(Q, D, GATE_N);
  input D;
  wire D;
  input GATE_N;
  wire GATE_N;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dlxtp_1(Q, D, GATE);
  input D;
  wire D;
  input GATE;
  wire GATE;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__dlygate4sd1_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__dlygate4sd2_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__dlygate4sd3_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__dlymetal6s2s_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__dlymetal6s4s_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__dlymetal6s6s_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__ebufn_1(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__ebufn_2(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__ebufn_4(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__ebufn_8(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__edfxbp_1(Q, Q_N, CLK, D, DE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
endmodule

module sky130_fd_sc_hd__edfxtp_1(Q, CLK, D, DE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
endmodule

module sky130_fd_sc_hd__einvn_0(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvn_1(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvn_2(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvn_4(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvn_8(Z, A, TE_B);
  input A;
  wire A;
  input TE_B;
  wire TE_B;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvp_1(Z, A, TE);
  input A;
  wire A;
  input TE;
  wire TE;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvp_2(Z, A, TE);
  input A;
  wire A;
  input TE;
  wire TE;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvp_4(Z, A, TE);
  input A;
  wire A;
  input TE;
  wire TE;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__einvp_8(Z, A, TE);
  input A;
  wire A;
  input TE;
  wire TE;
  output Z;
  wire Z;
endmodule

module sky130_fd_sc_hd__fa_1(COUT, SUM, A, B, CIN);
  input A;
  wire A;
  input B;
  wire B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fa_2(COUT, SUM, A, B, CIN);
  input A;
  wire A;
  input B;
  wire B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fa_4(COUT, SUM, A, B, CIN);
  input A;
  wire A;
  input B;
  wire B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fah_1(COUT, SUM, A, B, CI);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fahcin_1(COUT, SUM, A, B, CIN);
  input A;
  wire A;
  input B;
  wire B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fahcon_1(COUT_N, SUM, A, B, CI);
  input A;
  wire A;
  input B;
  wire B;
  input CI;
  wire CI;
  output COUT_N;
  wire COUT_N;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__fill_1();
endmodule

module sky130_fd_sc_hd__fill_2();
endmodule

module sky130_fd_sc_hd__fill_4();
endmodule

module sky130_fd_sc_hd__fill_8();
endmodule

module sky130_fd_sc_hd__ha_1(COUT, SUM, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__ha_2(COUT, SUM, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__ha_4(COUT, SUM, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output COUT;
  wire COUT;
  output SUM;
  wire SUM;
endmodule

module sky130_fd_sc_hd__inv_1(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_12(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_16(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_2(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_4(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_6(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__inv_8(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_bleeder_1(SHORT);
  input SHORT;
  wire SHORT;
endmodule

module sky130_fd_sc_hd__lpflow_clkbufkapwr_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_clkbufkapwr_16(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_clkbufkapwr_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_clkbufkapwr_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_clkbufkapwr_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_clkinvkapwr_1(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_clkinvkapwr_16(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_clkinvkapwr_2(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_clkinvkapwr_4(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_clkinvkapwr_8(Y, A);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__lpflow_decapkapwr_12();
endmodule

module sky130_fd_sc_hd__lpflow_decapkapwr_3();
endmodule

module sky130_fd_sc_hd__lpflow_decapkapwr_4();
endmodule

module sky130_fd_sc_hd__lpflow_decapkapwr_6();
endmodule

module sky130_fd_sc_hd__lpflow_decapkapwr_8();
endmodule

module sky130_fd_sc_hd__lpflow_inputiso0n_1(X, A, SLEEP_B);
  input A;
  wire A;
  input SLEEP_B;
  wire SLEEP_B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso0p_1(X, A, SLEEP);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso1n_1(X, A, SLEEP_B);
  input A;
  wire A;
  input SLEEP_B;
  wire SLEEP_B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso1p_1(X, A, SLEEP);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_inputisolatch_1(Q, D, SLEEP_B);
  input D;
  wire D;
  output Q;
  wire Q;
  input SLEEP_B;
  wire SLEEP_B;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_1(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_16(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_2(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_4(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_8(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrckapwr_16(X, SLEEP, A);
  input A;
  wire A;
  input SLEEP;
  wire SLEEP;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_hl_isowell_tap_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_1(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_2(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__lpflow_lsbuf_lh_isowell_tap_4(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__macro_sparecell(LO);
  output LO;
  wire LO;
endmodule

module sky130_fd_sc_hd__maj3_1(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__maj3_2(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__maj3_4(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux2_1(X, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux2_2(X, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux2_4(X, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux2_8(X, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux2i_1(Y, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__mux2i_2(Y, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__mux2i_4(Y, A0, A1, S);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input S;
  wire S;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__mux4_1(X, A0, A1, A2, A3, S0, S1);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux4_2(X, A0, A1, A2, A3, S0, S1);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__mux4_4(X, A0, A1, A2, A3, S0, S1);
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__nand2_1(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2_2(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2_4(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2_8(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2b_1(Y, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2b_2(Y, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand2b_4(Y, A_N, B);
  input A_N;
  wire A_N;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3_1(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3_2(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3_4(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3b_1(Y, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3b_2(Y, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand3b_4(Y, A_N, B, C);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4_1(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4_2(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4_4(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4b_1(Y, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4b_2(Y, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4b_4(Y, A_N, B, C, D);
  input A_N;
  wire A_N;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4bb_1(Y, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4bb_2(Y, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nand4bb_4(Y, A_N, B_N, C, D);
  input A_N;
  wire A_N;
  input B_N;
  wire B_N;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2_1(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2_2(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2_4(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2_8(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2b_1(Y, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2b_2(Y, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor2b_4(Y, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3_1(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3_2(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3_4(Y, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3b_1(Y, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3b_2(Y, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor3b_4(Y, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4_1(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4_2(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4_4(Y, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4b_1(Y, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4b_2(Y, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4b_4(Y, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4bb_1(Y, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4bb_2(Y, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__nor4bb_4(Y, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2111a_1(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2111a_2(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2111a_4(X, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2111ai_1(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2111ai_2(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2111ai_4(Y, A1, A2, B1, C1, D1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  input D1;
  wire D1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o211a_1(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o211a_2(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o211a_4(X, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o211ai_1(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o211ai_2(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o211ai_4(Y, A1, A2, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21a_1(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21a_2(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21a_4(X, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21ai_0(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21ai_1(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21ai_2(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21ai_4(Y, A1, A2, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21ba_1(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21ba_2(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21ba_4(X, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o21bai_1(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21bai_2(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o21bai_4(Y, A1, A2, B1_N);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1_N;
  wire B1_N;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o221a_1(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o221a_2(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o221a_4(X, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o221ai_1(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o221ai_2(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o221ai_4(Y, A1, A2, B1, B2, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o22a_1(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o22a_2(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o22a_4(X, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o22ai_1(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o22ai_2(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o22ai_4(Y, A1, A2, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2bb2a_1(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2bb2a_2(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2bb2a_4(X, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o2bb2ai_1(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2bb2ai_2(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o2bb2ai_4(Y, A1_N, A2_N, B1, B2);
  input A1_N;
  wire A1_N;
  input A2_N;
  wire A2_N;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o311a_1(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o311a_2(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o311a_4(X, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o311ai_0(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o311ai_1(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o311ai_2(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o311ai_4(Y, A1, A2, A3, B1, C1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input C1;
  wire C1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o31a_1(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o31a_2(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o31a_4(X, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o31ai_1(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o31ai_2(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o31ai_4(Y, A1, A2, A3, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o32a_1(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o32a_2(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o32a_4(X, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o32ai_1(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o32ai_2(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o32ai_4(Y, A1, A2, A3, B1, B2);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B1;
  wire B1;
  input B2;
  wire B2;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o41a_1(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o41a_2(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o41a_4(X, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__o41ai_1(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o41ai_2(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__o41ai_4(Y, A1, A2, A3, A4, B1);
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input A4;
  wire A4;
  input B1;
  wire B1;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__or2_0(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2_1(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2_2(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2_4(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2b_1(X, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2b_2(X, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or2b_4(X, A, B_N);
  input A;
  wire A;
  input B_N;
  wire B_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3_1(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3_2(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3_4(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3b_1(X, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3b_2(X, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or3b_4(X, A, B, C_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4_1(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4_2(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4_4(X, A, B, C, D);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4b_1(X, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4b_2(X, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4b_4(X, A, B, C, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4bb_1(X, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4bb_2(X, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__or4bb_4(X, A, B, C_N, D_N);
  input A;
  wire A;
  input B;
  wire B;
  input C_N;
  wire C_N;
  input D_N;
  wire D_N;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__probe_p_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__probec_p_8(X, A);
  input A;
  wire A;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__sdfbbn_1(Q, Q_N, D, SCD, SCE, CLK_N, SET_B, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfbbn_2(Q, Q_N, D, SCD, SCE, CLK_N, SET_B, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfbbp_1(Q, Q_N, D, SCD, SCE, CLK, SET_B, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfrbp_1(Q, Q_N, CLK, D, SCD, SCE, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfrbp_2(Q, Q_N, CLK, D, SCD, SCE, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfrtn_1(Q, CLK_N, D, SCD, SCE, RESET_B);
  input CLK_N;
  wire CLK_N;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfrtp_1(Q, CLK, D, SCD, SCE, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfrtp_2(Q, CLK, D, SCD, SCE, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfrtp_4(Q, CLK, D, SCD, SCE, RESET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input RESET_B;
  wire RESET_B;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfsbp_1(Q, Q_N, CLK, D, SCD, SCE, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfsbp_2(Q, Q_N, CLK, D, SCD, SCE, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfstp_1(Q, CLK, D, SCD, SCE, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfstp_2(Q, CLK, D, SCD, SCE, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfstp_4(Q, CLK, D, SCD, SCE, SET_B);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
  input SET_B;
  wire SET_B;
endmodule

module sky130_fd_sc_hd__sdfxbp_1(Q, Q_N, CLK, D, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfxbp_2(Q, Q_N, CLK, D, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfxtp_1(Q, CLK, D, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfxtp_2(Q, CLK, D, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdfxtp_4(Q, CLK, D, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdlclkp_1(GCLK, SCE, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdlclkp_2(GCLK, SCE, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sdlclkp_4(GCLK, SCE, GATE, CLK);
  input CLK;
  wire CLK;
  input GATE;
  wire GATE;
  output GCLK;
  wire GCLK;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sedfxbp_1(Q, Q_N, CLK, D, DE, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sedfxbp_2(Q, Q_N, CLK, D, DE, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  output Q_N;
  wire Q_N;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sedfxtp_1(Q, CLK, D, DE, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sedfxtp_2(Q, CLK, D, DE, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__sedfxtp_4(Q, CLK, D, DE, SCD, SCE);
  input CLK;
  wire CLK;
  input D;
  wire D;
  input DE;
  wire DE;
  output Q;
  wire Q;
  input SCD;
  wire SCD;
  input SCE;
  wire SCE;
endmodule

module sky130_fd_sc_hd__tap_1();
endmodule

module sky130_fd_sc_hd__tap_2();
endmodule

module sky130_fd_sc_hd__tapvgnd2_1();
endmodule

module sky130_fd_sc_hd__tapvgnd_1();
endmodule

module sky130_fd_sc_hd__tapvpwrvgnd_1();
endmodule

module sky130_fd_sc_hd__xnor2_1(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__xnor2_2(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__xnor2_4(Y, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule

module sky130_fd_sc_hd__xnor3_1(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xnor3_2(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xnor3_4(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor2_1(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor2_2(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor2_4(X, A, B);
  input A;
  wire A;
  input B;
  wire B;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor3_1(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor3_2(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule

module sky130_fd_sc_hd__xor3_4(X, A, B, C);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output X;
  wire X;
endmodule
