// This program was cloned from: https://github.com/GoodKook/ETRI-0.5u-CMOS-MPW-DK-Example--FIR8
// License: GNU General Public License v3.0

/* Generated by Yosys 0.38+88 (git sha1 38f1b0b12, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "../../../source/fir_pe.v:9.1-89.10" *)
module fir_pe(clk, Cin, Xin, Xout, Yin, Yout, Rdy, Vld, Vld_LED);
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _000_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _001_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _002_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _003_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _004_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _005_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _006_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _020_;
  wire [7:0] _021_;
  wire _022_;
  wire [3:0] _023_;
  wire [3:0] _024_;
  wire _025_;
  (* src = "../../../source/fir_pe.v:11.17-11.20" *)
  input [7:0] Cin;
  wire [7:0] Cin;
  (* src = "../../../source/fir_pe.v:22.21-22.28" *)
  wire [4:0] LoadCtl;
  (* src = "../../../source/fir_pe.v:16.17-16.20" *)
  input Rdy;
  wire Rdy;
  (* src = "../../../source/fir_pe.v:17.17-17.20" *)
  output Vld;
  wire Vld;
  (* src = "../../../source/fir_pe.v:18.17-18.24" *)
  output Vld_LED;
  wire Vld_LED;
  (* src = "../../../source/fir_pe.v:12.17-12.20" *)
  input [3:0] Xin;
  wire [3:0] Xin;
  (* src = "../../../source/fir_pe.v:38.27-38.31" *)
  wire [3:0] XinH;
  (* src = "../../../source/fir_pe.v:55.21-55.26" *)
  wire [7:0] XinHL;
  (* src = "../../../source/fir_pe.v:38.21-38.25" *)
  wire [3:0] XinL;
  (* src = "../../../source/fir_pe.v:13.17-13.21" *)
  output [3:0] Xout;
  wire [3:0] Xout;
  (* src = "../../../source/fir_pe.v:14.17-14.20" *)
  input [3:0] Yin;
  wire [3:0] Yin;
  (* src = "../../../source/fir_pe.v:45.39-45.43" *)
  wire [3:0] Yin0;
  (* src = "../../../source/fir_pe.v:45.33-45.37" *)
  wire [3:0] Yin1;
  (* src = "../../../source/fir_pe.v:45.27-45.31" *)
  wire [3:0] Yin2;
  (* src = "../../../source/fir_pe.v:45.21-45.25" *)
  wire [3:0] Yin3;
  (* src = "../../../source/fir_pe.v:56.21-56.28" *)
  wire [15:0] Yin3210;
  (* src = "../../../source/fir_pe.v:15.17-15.21" *)
  output [3:0] Yout;
  wire [3:0] Yout;
  (* src = "../../../source/fir_pe.v:54.24-54.26" *)
  wire [15:0] _y;
  (* src = "../../../source/fir_pe.v:10.17-10.20" *)
  input clk;
  wire clk;
  (* src = "../../../source/fir_pe.v:54.21-54.22" *)
  wire [15:0] y;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _026_ (
    .I0(LoadCtl[0]),
    .I1(LoadCtl[1]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _027_ (
    .I0(LoadCtl[1]),
    .I1(LoadCtl[2]),
    .I2(LoadCtl[0]),
    .I3(LoadCtl[3]),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _028_ (
    .I0(LoadCtl[1]),
    .I1(LoadCtl[0]),
    .I2(LoadCtl[2]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _029_ (
    .I0(y[12]),
    .I1(y[8]),
    .I2(y[4]),
    .I3(LoadCtl[2]),
    .I4(LoadCtl[1]),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _030_ (
    .I0(y[0]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _031_ (
    .I0(_000_),
    .I1(_001_),
    .O(_015_),
    .S(LoadCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _032_ (
    .I0(y[13]),
    .I1(y[9]),
    .I2(y[5]),
    .I3(LoadCtl[2]),
    .I4(LoadCtl[1]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _033_ (
    .I0(y[1]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _034_ (
    .I0(_002_),
    .I1(_003_),
    .O(_016_),
    .S(LoadCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _035_ (
    .I0(y[14]),
    .I1(y[10]),
    .I2(y[6]),
    .I3(LoadCtl[2]),
    .I4(LoadCtl[1]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _036_ (
    .I0(y[2]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _037_ (
    .I0(_004_),
    .I1(_005_),
    .O(_017_),
    .S(LoadCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _038_ (
    .I0(y[15]),
    .I1(y[11]),
    .I2(y[7]),
    .I3(LoadCtl[2]),
    .I4(LoadCtl[1]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _039_ (
    .I0(y[3]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _040_ (
    .I0(_006_),
    .I1(_007_),
    .O(_018_),
    .S(LoadCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _041_ (
    .I0(XinH[0]),
    .I1(XinL[0]),
    .I2(LoadCtl[0]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _042_ (
    .I0(XinH[1]),
    .I1(XinL[1]),
    .I2(LoadCtl[0]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _043_ (
    .I0(XinH[2]),
    .I1(XinL[2]),
    .I2(LoadCtl[0]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _044_ (
    .I0(XinH[3]),
    .I1(XinL[3]),
    .I2(LoadCtl[0]),
    .O(_014_)
  );
  BUFG _045_ (
    .I(_019_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _046_ (
    .C(_025_),
    .CE(_008_),
    .D(_023_[0]),
    .Q(XinH[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _047_ (
    .C(_025_),
    .CE(_008_),
    .D(_023_[1]),
    .Q(XinH[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _048_ (
    .C(_025_),
    .CE(_008_),
    .D(_023_[2]),
    .Q(XinH[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _049_ (
    .C(_025_),
    .CE(_008_),
    .D(_023_[3]),
    .Q(XinH[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _050_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[0]),
    .Q(y[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _051_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[1]),
    .Q(y[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _052_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[2]),
    .Q(y[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _053_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[3]),
    .Q(y[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _054_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[4]),
    .Q(y[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _055_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[5]),
    .Q(y[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _056_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[6]),
    .Q(y[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _057_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[7]),
    .Q(y[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _058_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[8]),
    .Q(y[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _059_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[9]),
    .Q(y[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _060_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[10]),
    .Q(y[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _061_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[11]),
    .Q(y[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _062_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[12]),
    .Q(y[12]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _063_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[13]),
    .Q(y[13]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _064_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[14]),
    .Q(y[14]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:57.5-63.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _065_ (
    .C(_025_),
    .CE(LoadCtl[4]),
    .D(_y[15]),
    .Q(y[15]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _066_ (
    .C(_025_),
    .CE(_010_),
    .D(_024_[0]),
    .Q(Yin3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _067_ (
    .C(_025_),
    .CE(_010_),
    .D(_024_[1]),
    .Q(Yin3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _068_ (
    .C(_025_),
    .CE(_010_),
    .D(_024_[2]),
    .Q(Yin3[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _069_ (
    .C(_025_),
    .CE(_010_),
    .D(_024_[3]),
    .Q(Yin3[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _070_ (
    .C(_025_),
    .CE(_009_),
    .D(_024_[0]),
    .Q(Yin2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _071_ (
    .C(_025_),
    .CE(_009_),
    .D(_024_[1]),
    .Q(Yin2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _072_ (
    .C(_025_),
    .CE(_009_),
    .D(_024_[2]),
    .Q(Yin2[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _073_ (
    .C(_025_),
    .CE(_009_),
    .D(_024_[3]),
    .Q(Yin2[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _074_ (
    .C(_025_),
    .CE(_008_),
    .D(_024_[0]),
    .Q(Yin1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _075_ (
    .C(_025_),
    .CE(_008_),
    .D(_024_[1]),
    .Q(Yin1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _076_ (
    .C(_025_),
    .CE(_008_),
    .D(_024_[2]),
    .Q(Yin1[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _077_ (
    .C(_025_),
    .CE(_008_),
    .D(_024_[3]),
    .Q(Yin1[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _078_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_024_[0]),
    .Q(Yin0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _079_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_024_[1]),
    .Q(Yin0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _080_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_024_[2]),
    .Q(Yin0[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:46.5-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _081_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_024_[3]),
    .Q(Yin0[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _082_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_023_[0]),
    .Q(XinL[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _083_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_023_[1]),
    .Q(XinL[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _084_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_023_[2]),
    .Q(XinL[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:39.5-43.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _085_ (
    .C(_025_),
    .CE(LoadCtl[0]),
    .D(_023_[3]),
    .Q(XinL[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:24.5-33.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _086_ (
    .C(_025_),
    .CE(1'h1),
    .D(_022_),
    .Q(LoadCtl[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:24.5-33.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _087_ (
    .C(_025_),
    .CE(1'h1),
    .D(LoadCtl[0]),
    .Q(LoadCtl[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:24.5-33.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _088_ (
    .C(_025_),
    .CE(1'h1),
    .D(LoadCtl[1]),
    .Q(LoadCtl[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:24.5-33.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _089_ (
    .C(_025_),
    .CE(1'h1),
    .D(LoadCtl[2]),
    .Q(LoadCtl[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:24.5-33.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _090_ (
    .C(_025_),
    .CE(1'h1),
    .D(LoadCtl[3]),
    .Q(LoadCtl[4]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF _091_ (
    .I(Cin[0]),
    .O(_021_[0])
  );
  (* keep = 32'd1 *)
  IBUF _092_ (
    .I(Cin[1]),
    .O(_021_[1])
  );
  (* keep = 32'd1 *)
  IBUF _093_ (
    .I(Cin[2]),
    .O(_021_[2])
  );
  (* keep = 32'd1 *)
  IBUF _094_ (
    .I(Cin[3]),
    .O(_021_[3])
  );
  (* keep = 32'd1 *)
  IBUF _095_ (
    .I(Cin[4]),
    .O(_021_[4])
  );
  (* keep = 32'd1 *)
  IBUF _096_ (
    .I(Cin[5]),
    .O(_021_[5])
  );
  (* keep = 32'd1 *)
  IBUF _097_ (
    .I(Cin[6]),
    .O(_021_[6])
  );
  (* keep = 32'd1 *)
  IBUF _098_ (
    .I(Cin[7]),
    .O(_021_[7])
  );
  (* keep = 32'd1 *)
  IBUF _099_ (
    .I(Rdy),
    .O(_022_)
  );
  (* keep = 32'd1 *)
  OBUF _100_ (
    .I(LoadCtl[4]),
    .O(Vld)
  );
  (* keep = 32'd1 *)
  OBUF _101_ (
    .I(LoadCtl[4]),
    .O(Vld_LED)
  );
  (* keep = 32'd1 *)
  IBUF _102_ (
    .I(Xin[0]),
    .O(_023_[0])
  );
  (* keep = 32'd1 *)
  IBUF _103_ (
    .I(Xin[1]),
    .O(_023_[1])
  );
  (* keep = 32'd1 *)
  IBUF _104_ (
    .I(Xin[2]),
    .O(_023_[2])
  );
  (* keep = 32'd1 *)
  IBUF _105_ (
    .I(Xin[3]),
    .O(_023_[3])
  );
  (* keep = 32'd1 *)
  OBUF _106_ (
    .I(_011_),
    .O(Xout[0])
  );
  (* keep = 32'd1 *)
  OBUF _107_ (
    .I(_012_),
    .O(Xout[1])
  );
  (* keep = 32'd1 *)
  OBUF _108_ (
    .I(_013_),
    .O(Xout[2])
  );
  (* keep = 32'd1 *)
  OBUF _109_ (
    .I(_014_),
    .O(Xout[3])
  );
  (* keep = 32'd1 *)
  IBUF _110_ (
    .I(Yin[0]),
    .O(_024_[0])
  );
  (* keep = 32'd1 *)
  IBUF _111_ (
    .I(Yin[1]),
    .O(_024_[1])
  );
  (* keep = 32'd1 *)
  IBUF _112_ (
    .I(Yin[2]),
    .O(_024_[2])
  );
  (* keep = 32'd1 *)
  IBUF _113_ (
    .I(Yin[3]),
    .O(_024_[3])
  );
  (* keep = 32'd1 *)
  OBUF _114_ (
    .I(_015_),
    .O(Yout[0])
  );
  (* keep = 32'd1 *)
  OBUF _115_ (
    .I(_016_),
    .O(Yout[1])
  );
  (* keep = 32'd1 *)
  OBUF _116_ (
    .I(_017_),
    .O(Yout[2])
  );
  (* keep = 32'd1 *)
  OBUF _117_ (
    .I(_018_),
    .O(Yout[3])
  );
  (* keep = 32'd1 *)
  IBUF _118_ (
    .I(clk),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../../../source/fir_pe.v:61.19-61.30|/usr/local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/usr/local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/usr/local/bin/../share/yosys/xilinx/xc7_dsp_map.v:30.4-48.3" *)
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(1'h1),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _119_ (
    .A({ 22'h000000, XinH, XinL }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 10'h000, _021_ }),
    .BCIN(18'h00000),
    .C({ 32'h00000000, Yin3, Yin2, Yin1, Yin0 }),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .CEP(LoadCtl[4]),
    .CLK(_025_),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h35),
    .P({ _020_, _y }),
    .PCIN(48'h000000000000),
    .RSTP(1'h0)
  );
  assign XinHL = { XinH, XinL };
  assign Yin3210 = { Yin3, Yin2, Yin1, Yin0 };
endmodule
