// This program was cloned from: https://github.com/HKUSTGZ-MICS-LYU/FlattenRTL
// License: MIT License

/* Generated by Yosys 0.37+15 (git sha1 6282c1f27, gcc 10.5.0-1ubuntu1~20.04 -fPIC -Os) */

(* src = "adder.v:38.1-61.10" *)
module adder_16bit(a, b, cin, sum, cout);
  (* src = "adder.v:47.16-53.6|adder.v:9.26-9.31|adder.v:22.16-28.6" *)
  wire [4:0] _00_;
  (* src = "adder.v:47.16-53.6|adder.v:9.26-9.37|adder.v:22.16-28.6" *)
  wire [4:0] _01_;
  (* src = "adder.v:47.16-53.6|adder.v:9.26-9.31|adder.v:29.16-35.6" *)
  wire [4:0] _02_;
  (* src = "adder.v:47.16-53.6|adder.v:9.26-9.37|adder.v:29.16-35.6" *)
  wire [4:0] _03_;
  (* src = "adder.v:54.16-60.6|adder.v:9.26-9.31|adder.v:22.16-28.6" *)
  wire [4:0] _04_;
  (* src = "adder.v:54.16-60.6|adder.v:9.26-9.37|adder.v:22.16-28.6" *)
  wire [4:0] _05_;
  (* src = "adder.v:54.16-60.6|adder.v:9.26-9.31|adder.v:29.16-35.6" *)
  wire [4:0] _06_;
  (* src = "adder.v:54.16-60.6|adder.v:9.26-9.37|adder.v:29.16-35.6" *)
  wire [4:0] _07_;
  (* src = "adder.v:39.18-39.19" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "adder.v:40.18-40.19" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "adder.v:46.10-46.15" *)
  wire carry;
  (* src = "adder.v:41.11-41.14" *)
  input cin;
  wire cin;
  (* src = "adder.v:43.12-43.16" *)
  output cout;
  wire cout;
  (* hdlname = "lower_half a" *)
  (* src = "adder.v:47.16-53.6|adder.v:14.17-14.18" *)
  wire [7:0] \lower_half.a ;
  (* hdlname = "lower_half b" *)
  (* src = "adder.v:47.16-53.6|adder.v:15.17-15.18" *)
  wire [7:0] \lower_half.b ;
  (* hdlname = "lower_half carry" *)
  (* src = "adder.v:47.16-53.6|adder.v:21.10-21.15" *)
  wire \lower_half.carry ;
  (* hdlname = "lower_half cin" *)
  (* src = "adder.v:47.16-53.6|adder.v:16.11-16.14" *)
  wire \lower_half.cin ;
  (* hdlname = "lower_half cout" *)
  (* src = "adder.v:47.16-53.6|adder.v:18.12-18.16" *)
  wire \lower_half.cout ;
  (* hdlname = "lower_half lower_half a" *)
  (* src = "adder.v:47.16-53.6|adder.v:2.17-2.18|adder.v:22.16-28.6" *)
  wire [3:0] \lower_half.lower_half.a ;
  (* hdlname = "lower_half lower_half b" *)
  (* src = "adder.v:47.16-53.6|adder.v:3.17-3.18|adder.v:22.16-28.6" *)
  wire [3:0] \lower_half.lower_half.b ;
  (* hdlname = "lower_half lower_half cin" *)
  (* src = "adder.v:47.16-53.6|adder.v:4.11-4.14|adder.v:22.16-28.6" *)
  wire \lower_half.lower_half.cin ;
  (* hdlname = "lower_half lower_half cout" *)
  (* src = "adder.v:47.16-53.6|adder.v:6.12-6.16|adder.v:22.16-28.6" *)
  wire \lower_half.lower_half.cout ;
  (* hdlname = "lower_half lower_half sum" *)
  (* src = "adder.v:47.16-53.6|adder.v:5.18-5.21|adder.v:22.16-28.6" *)
  wire [3:0] \lower_half.lower_half.sum ;
  (* hdlname = "lower_half sum" *)
  (* src = "adder.v:47.16-53.6|adder.v:17.18-17.21" *)
  wire [7:0] \lower_half.sum ;
  (* hdlname = "lower_half upper_half a" *)
  (* src = "adder.v:47.16-53.6|adder.v:2.17-2.18|adder.v:29.16-35.6" *)
  wire [3:0] \lower_half.upper_half.a ;
  (* hdlname = "lower_half upper_half b" *)
  (* src = "adder.v:47.16-53.6|adder.v:3.17-3.18|adder.v:29.16-35.6" *)
  wire [3:0] \lower_half.upper_half.b ;
  (* hdlname = "lower_half upper_half cin" *)
  (* src = "adder.v:47.16-53.6|adder.v:4.11-4.14|adder.v:29.16-35.6" *)
  wire \lower_half.upper_half.cin ;
  (* hdlname = "lower_half upper_half cout" *)
  (* src = "adder.v:47.16-53.6|adder.v:6.12-6.16|adder.v:29.16-35.6" *)
  wire \lower_half.upper_half.cout ;
  (* hdlname = "lower_half upper_half sum" *)
  (* src = "adder.v:47.16-53.6|adder.v:5.18-5.21|adder.v:29.16-35.6" *)
  wire [3:0] \lower_half.upper_half.sum ;
  (* src = "adder.v:42.19-42.22" *)
  output [15:0] sum;
  wire [15:0] sum;
  (* hdlname = "upper_half a" *)
  (* src = "adder.v:54.16-60.6|adder.v:14.17-14.18" *)
  wire [7:0] \upper_half.a ;
  (* hdlname = "upper_half b" *)
  (* src = "adder.v:54.16-60.6|adder.v:15.17-15.18" *)
  wire [7:0] \upper_half.b ;
  (* hdlname = "upper_half carry" *)
  (* src = "adder.v:54.16-60.6|adder.v:21.10-21.15" *)
  wire \upper_half.carry ;
  (* hdlname = "upper_half cin" *)
  (* src = "adder.v:54.16-60.6|adder.v:16.11-16.14" *)
  wire \upper_half.cin ;
  (* hdlname = "upper_half cout" *)
  (* src = "adder.v:54.16-60.6|adder.v:18.12-18.16" *)
  wire \upper_half.cout ;
  (* hdlname = "upper_half lower_half a" *)
  (* src = "adder.v:54.16-60.6|adder.v:2.17-2.18|adder.v:22.16-28.6" *)
  wire [3:0] \upper_half.lower_half.a ;
  (* hdlname = "upper_half lower_half b" *)
  (* src = "adder.v:54.16-60.6|adder.v:3.17-3.18|adder.v:22.16-28.6" *)
  wire [3:0] \upper_half.lower_half.b ;
  (* hdlname = "upper_half lower_half cin" *)
  (* src = "adder.v:54.16-60.6|adder.v:4.11-4.14|adder.v:22.16-28.6" *)
  wire \upper_half.lower_half.cin ;
  (* hdlname = "upper_half lower_half cout" *)
  (* src = "adder.v:54.16-60.6|adder.v:6.12-6.16|adder.v:22.16-28.6" *)
  wire \upper_half.lower_half.cout ;
  (* hdlname = "upper_half lower_half sum" *)
  (* src = "adder.v:54.16-60.6|adder.v:5.18-5.21|adder.v:22.16-28.6" *)
  wire [3:0] \upper_half.lower_half.sum ;
  (* hdlname = "upper_half sum" *)
  (* src = "adder.v:54.16-60.6|adder.v:17.18-17.21" *)
  wire [7:0] \upper_half.sum ;
  (* hdlname = "upper_half upper_half a" *)
  (* src = "adder.v:54.16-60.6|adder.v:2.17-2.18|adder.v:29.16-35.6" *)
  wire [3:0] \upper_half.upper_half.a ;
  (* hdlname = "upper_half upper_half b" *)
  (* src = "adder.v:54.16-60.6|adder.v:3.17-3.18|adder.v:29.16-35.6" *)
  wire [3:0] \upper_half.upper_half.b ;
  (* hdlname = "upper_half upper_half cin" *)
  (* src = "adder.v:54.16-60.6|adder.v:4.11-4.14|adder.v:29.16-35.6" *)
  wire \upper_half.upper_half.cin ;
  (* hdlname = "upper_half upper_half cout" *)
  (* src = "adder.v:54.16-60.6|adder.v:6.12-6.16|adder.v:29.16-35.6" *)
  wire \upper_half.upper_half.cout ;
  (* hdlname = "upper_half upper_half sum" *)
  (* src = "adder.v:54.16-60.6|adder.v:5.18-5.21|adder.v:29.16-35.6" *)
  wire [3:0] \upper_half.upper_half.sum ;
  assign _00_ = \lower_half.lower_half.a  + (* src = "adder.v:47.16-53.6|adder.v:9.26-9.31|adder.v:22.16-28.6" *) \lower_half.lower_half.b ;
  assign _01_ = _00_ + (* src = "adder.v:47.16-53.6|adder.v:9.26-9.37|adder.v:22.16-28.6" *) \lower_half.lower_half.cin ;
  assign _02_ = \lower_half.upper_half.a  + (* src = "adder.v:47.16-53.6|adder.v:9.26-9.31|adder.v:29.16-35.6" *) \lower_half.upper_half.b ;
  assign _03_ = _02_ + (* src = "adder.v:47.16-53.6|adder.v:9.26-9.37|adder.v:29.16-35.6" *) \lower_half.upper_half.cin ;
  assign _04_ = \upper_half.lower_half.a  + (* src = "adder.v:54.16-60.6|adder.v:9.26-9.31|adder.v:22.16-28.6" *) \upper_half.lower_half.b ;
  assign _05_ = _04_ + (* src = "adder.v:54.16-60.6|adder.v:9.26-9.37|adder.v:22.16-28.6" *) \upper_half.lower_half.cin ;
  assign _06_ = \upper_half.upper_half.a  + (* src = "adder.v:54.16-60.6|adder.v:9.26-9.31|adder.v:29.16-35.6" *) \upper_half.upper_half.b ;
  assign _07_ = _06_ + (* src = "adder.v:54.16-60.6|adder.v:9.26-9.37|adder.v:29.16-35.6" *) \upper_half.upper_half.cin ;
  assign { \lower_half.lower_half.cout , \lower_half.lower_half.sum  } = _01_;
  assign \lower_half.carry  = \lower_half.lower_half.cout ;
  assign \lower_half.sum [3:0] = \lower_half.lower_half.sum ;
  assign \lower_half.lower_half.cin  = \lower_half.cin ;
  assign \lower_half.lower_half.b  = \lower_half.b [3:0];
  assign \lower_half.lower_half.a  = \lower_half.a [3:0];
  assign { \lower_half.upper_half.cout , \lower_half.upper_half.sum  } = _03_;
  assign \lower_half.cout  = \lower_half.upper_half.cout ;
  assign \lower_half.sum [7:4] = \lower_half.upper_half.sum ;
  assign \lower_half.upper_half.cin  = \lower_half.carry ;
  assign \lower_half.upper_half.b  = \lower_half.b [7:4];
  assign \lower_half.upper_half.a  = \lower_half.a [7:4];
  assign carry = \lower_half.cout ;
  assign sum[7:0] = \lower_half.sum ;
  assign \lower_half.cin  = cin;
  assign \lower_half.b  = b[7:0];
  assign \lower_half.a  = a[7:0];
  assign { \upper_half.lower_half.cout , \upper_half.lower_half.sum  } = _05_;
  assign \upper_half.carry  = \upper_half.lower_half.cout ;
  assign \upper_half.sum [3:0] = \upper_half.lower_half.sum ;
  assign \upper_half.lower_half.cin  = \upper_half.cin ;
  assign \upper_half.lower_half.b  = \upper_half.b [3:0];
  assign \upper_half.lower_half.a  = \upper_half.a [3:0];
  assign { \upper_half.upper_half.cout , \upper_half.upper_half.sum  } = _07_;
  assign \upper_half.cout  = \upper_half.upper_half.cout ;
  assign \upper_half.sum [7:4] = \upper_half.upper_half.sum ;
  assign \upper_half.upper_half.cin  = \upper_half.carry ;
  assign \upper_half.upper_half.b  = \upper_half.b [7:4];
  assign \upper_half.upper_half.a  = \upper_half.a [7:4];
  assign cout = \upper_half.cout ;
  assign sum[15:8] = \upper_half.sum ;
  assign \upper_half.cin  = carry;
  assign \upper_half.b  = b[15:8];
  assign \upper_half.a  = a[15:8];
endmodule

(* src = "adder.v:63.1-86.10" *)
module adder_32bit(a, b, cin, sum, cout);
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *)
  wire [4:0] _00_;
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *)
  wire [4:0] _01_;
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *)
  wire [4:0] _02_;
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *)
  wire [4:0] _03_;
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *)
  wire [4:0] _04_;
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *)
  wire [4:0] _05_;
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *)
  wire [4:0] _06_;
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *)
  wire [4:0] _07_;
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *)
  wire [4:0] _08_;
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *)
  wire [4:0] _09_;
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *)
  wire [4:0] _10_;
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *)
  wire [4:0] _11_;
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *)
  wire [4:0] _12_;
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *)
  wire [4:0] _13_;
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *)
  wire [4:0] _14_;
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *)
  wire [4:0] _15_;
  (* src = "adder.v:64.18-64.19" *)
  input [31:0] a;
  wire [31:0] a;
  (* src = "adder.v:65.18-65.19" *)
  input [31:0] b;
  wire [31:0] b;
  (* src = "adder.v:71.10-71.15" *)
  wire carry;
  (* src = "adder.v:66.11-66.14" *)
  input cin;
  wire cin;
  (* src = "adder.v:68.12-68.16" *)
  output cout;
  wire cout;
  (* hdlname = "lower_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:39.18-39.19" *)
  wire [15:0] \lower_half.a ;
  (* hdlname = "lower_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:40.18-40.19" *)
  wire [15:0] \lower_half.b ;
  (* hdlname = "lower_half carry" *)
  (* src = "adder.v:72.17-78.6|adder.v:46.10-46.15" *)
  wire \lower_half.carry ;
  (* hdlname = "lower_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:41.11-41.14" *)
  wire \lower_half.cin ;
  (* hdlname = "lower_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:43.12-43.16" *)
  wire \lower_half.cout ;
  (* hdlname = "lower_half lower_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:14.17-14.18|adder.v:47.16-53.6" *)
  wire [7:0] \lower_half.lower_half.a ;
  (* hdlname = "lower_half lower_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:15.17-15.18|adder.v:47.16-53.6" *)
  wire [7:0] \lower_half.lower_half.b ;
  (* hdlname = "lower_half lower_half carry" *)
  (* src = "adder.v:72.17-78.6|adder.v:21.10-21.15|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.carry ;
  (* hdlname = "lower_half lower_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:16.11-16.14|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.cin ;
  (* hdlname = "lower_half lower_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:18.12-18.16|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.cout ;
  (* hdlname = "lower_half lower_half lower_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:2.17-2.18|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.lower_half.a ;
  (* hdlname = "lower_half lower_half lower_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:3.17-3.18|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.lower_half.b ;
  (* hdlname = "lower_half lower_half lower_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:4.11-4.14|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.lower_half.cin ;
  (* hdlname = "lower_half lower_half lower_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:6.12-6.16|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.lower_half.cout ;
  (* hdlname = "lower_half lower_half lower_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:5.18-5.21|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.lower_half.sum ;
  (* hdlname = "lower_half lower_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:17.18-17.21|adder.v:47.16-53.6" *)
  wire [7:0] \lower_half.lower_half.sum ;
  (* hdlname = "lower_half lower_half upper_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:2.17-2.18|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.upper_half.a ;
  (* hdlname = "lower_half lower_half upper_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:3.17-3.18|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.upper_half.b ;
  (* hdlname = "lower_half lower_half upper_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:4.11-4.14|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.upper_half.cin ;
  (* hdlname = "lower_half lower_half upper_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:6.12-6.16|adder.v:47.16-53.6" *)
  wire \lower_half.lower_half.upper_half.cout ;
  (* hdlname = "lower_half lower_half upper_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:5.18-5.21|adder.v:47.16-53.6" *)
  wire [3:0] \lower_half.lower_half.upper_half.sum ;
  (* hdlname = "lower_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:42.19-42.22" *)
  wire [15:0] \lower_half.sum ;
  (* hdlname = "lower_half upper_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:14.17-14.18|adder.v:54.16-60.6" *)
  wire [7:0] \lower_half.upper_half.a ;
  (* hdlname = "lower_half upper_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:15.17-15.18|adder.v:54.16-60.6" *)
  wire [7:0] \lower_half.upper_half.b ;
  (* hdlname = "lower_half upper_half carry" *)
  (* src = "adder.v:72.17-78.6|adder.v:21.10-21.15|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.carry ;
  (* hdlname = "lower_half upper_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:16.11-16.14|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.cin ;
  (* hdlname = "lower_half upper_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:18.12-18.16|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.cout ;
  (* hdlname = "lower_half upper_half lower_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:2.17-2.18|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.lower_half.a ;
  (* hdlname = "lower_half upper_half lower_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:3.17-3.18|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.lower_half.b ;
  (* hdlname = "lower_half upper_half lower_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:4.11-4.14|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.lower_half.cin ;
  (* hdlname = "lower_half upper_half lower_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:6.12-6.16|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.lower_half.cout ;
  (* hdlname = "lower_half upper_half lower_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:5.18-5.21|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.lower_half.sum ;
  (* hdlname = "lower_half upper_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:17.18-17.21|adder.v:54.16-60.6" *)
  wire [7:0] \lower_half.upper_half.sum ;
  (* hdlname = "lower_half upper_half upper_half a" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:2.17-2.18|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.upper_half.a ;
  (* hdlname = "lower_half upper_half upper_half b" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:3.17-3.18|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.upper_half.b ;
  (* hdlname = "lower_half upper_half upper_half cin" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:4.11-4.14|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.upper_half.cin ;
  (* hdlname = "lower_half upper_half upper_half cout" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:6.12-6.16|adder.v:54.16-60.6" *)
  wire \lower_half.upper_half.upper_half.cout ;
  (* hdlname = "lower_half upper_half upper_half sum" *)
  (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:5.18-5.21|adder.v:54.16-60.6" *)
  wire [3:0] \lower_half.upper_half.upper_half.sum ;
  (* src = "adder.v:67.19-67.22" *)
  output [31:0] sum;
  wire [31:0] sum;
  (* hdlname = "upper_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:39.18-39.19" *)
  wire [15:0] \upper_half.a ;
  (* hdlname = "upper_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:40.18-40.19" *)
  wire [15:0] \upper_half.b ;
  (* hdlname = "upper_half carry" *)
  (* src = "adder.v:79.17-85.6|adder.v:46.10-46.15" *)
  wire \upper_half.carry ;
  (* hdlname = "upper_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:41.11-41.14" *)
  wire \upper_half.cin ;
  (* hdlname = "upper_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:43.12-43.16" *)
  wire \upper_half.cout ;
  (* hdlname = "upper_half lower_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:14.17-14.18|adder.v:47.16-53.6" *)
  wire [7:0] \upper_half.lower_half.a ;
  (* hdlname = "upper_half lower_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:15.17-15.18|adder.v:47.16-53.6" *)
  wire [7:0] \upper_half.lower_half.b ;
  (* hdlname = "upper_half lower_half carry" *)
  (* src = "adder.v:79.17-85.6|adder.v:21.10-21.15|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.carry ;
  (* hdlname = "upper_half lower_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:16.11-16.14|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.cin ;
  (* hdlname = "upper_half lower_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:18.12-18.16|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.cout ;
  (* hdlname = "upper_half lower_half lower_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:2.17-2.18|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.lower_half.a ;
  (* hdlname = "upper_half lower_half lower_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:3.17-3.18|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.lower_half.b ;
  (* hdlname = "upper_half lower_half lower_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:4.11-4.14|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.lower_half.cin ;
  (* hdlname = "upper_half lower_half lower_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:6.12-6.16|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.lower_half.cout ;
  (* hdlname = "upper_half lower_half lower_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:5.18-5.21|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.lower_half.sum ;
  (* hdlname = "upper_half lower_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:17.18-17.21|adder.v:47.16-53.6" *)
  wire [7:0] \upper_half.lower_half.sum ;
  (* hdlname = "upper_half lower_half upper_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:2.17-2.18|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.upper_half.a ;
  (* hdlname = "upper_half lower_half upper_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:3.17-3.18|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.upper_half.b ;
  (* hdlname = "upper_half lower_half upper_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:4.11-4.14|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.upper_half.cin ;
  (* hdlname = "upper_half lower_half upper_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:6.12-6.16|adder.v:47.16-53.6" *)
  wire \upper_half.lower_half.upper_half.cout ;
  (* hdlname = "upper_half lower_half upper_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:5.18-5.21|adder.v:47.16-53.6" *)
  wire [3:0] \upper_half.lower_half.upper_half.sum ;
  (* hdlname = "upper_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:42.19-42.22" *)
  wire [15:0] \upper_half.sum ;
  (* hdlname = "upper_half upper_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:14.17-14.18|adder.v:54.16-60.6" *)
  wire [7:0] \upper_half.upper_half.a ;
  (* hdlname = "upper_half upper_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:15.17-15.18|adder.v:54.16-60.6" *)
  wire [7:0] \upper_half.upper_half.b ;
  (* hdlname = "upper_half upper_half carry" *)
  (* src = "adder.v:79.17-85.6|adder.v:21.10-21.15|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.carry ;
  (* hdlname = "upper_half upper_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:16.11-16.14|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.cin ;
  (* hdlname = "upper_half upper_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:18.12-18.16|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.cout ;
  (* hdlname = "upper_half upper_half lower_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:2.17-2.18|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.lower_half.a ;
  (* hdlname = "upper_half upper_half lower_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:3.17-3.18|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.lower_half.b ;
  (* hdlname = "upper_half upper_half lower_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:4.11-4.14|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.lower_half.cin ;
  (* hdlname = "upper_half upper_half lower_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:6.12-6.16|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.lower_half.cout ;
  (* hdlname = "upper_half upper_half lower_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:5.18-5.21|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.lower_half.sum ;
  (* hdlname = "upper_half upper_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:17.18-17.21|adder.v:54.16-60.6" *)
  wire [7:0] \upper_half.upper_half.sum ;
  (* hdlname = "upper_half upper_half upper_half a" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:2.17-2.18|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.upper_half.a ;
  (* hdlname = "upper_half upper_half upper_half b" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:3.17-3.18|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.upper_half.b ;
  (* hdlname = "upper_half upper_half upper_half cin" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:4.11-4.14|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.upper_half.cin ;
  (* hdlname = "upper_half upper_half upper_half cout" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:6.12-6.16|adder.v:54.16-60.6" *)
  wire \upper_half.upper_half.upper_half.cout ;
  (* hdlname = "upper_half upper_half upper_half sum" *)
  (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:5.18-5.21|adder.v:54.16-60.6" *)
  wire [3:0] \upper_half.upper_half.upper_half.sum ;
  assign _00_ = \lower_half.lower_half.lower_half.a  + (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *) \lower_half.lower_half.lower_half.b ;
  assign _01_ = _00_ + (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *) \lower_half.lower_half.lower_half.cin ;
  assign _02_ = \lower_half.lower_half.upper_half.a  + (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *) \lower_half.lower_half.upper_half.b ;
  assign _03_ = _02_ + (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *) \lower_half.lower_half.upper_half.cin ;
  assign _04_ = \lower_half.upper_half.lower_half.a  + (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *) \lower_half.upper_half.lower_half.b ;
  assign _05_ = _04_ + (* src = "adder.v:72.17-78.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *) \lower_half.upper_half.lower_half.cin ;
  assign _06_ = \lower_half.upper_half.upper_half.a  + (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *) \lower_half.upper_half.upper_half.b ;
  assign _07_ = _06_ + (* src = "adder.v:72.17-78.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *) \lower_half.upper_half.upper_half.cin ;
  assign _08_ = \upper_half.lower_half.lower_half.a  + (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *) \upper_half.lower_half.lower_half.b ;
  assign _09_ = _08_ + (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *) \upper_half.lower_half.lower_half.cin ;
  assign _10_ = \upper_half.lower_half.upper_half.a  + (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:47.16-53.6" *) \upper_half.lower_half.upper_half.b ;
  assign _11_ = _10_ + (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:47.16-53.6" *) \upper_half.lower_half.upper_half.cin ;
  assign _12_ = \upper_half.upper_half.lower_half.a  + (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *) \upper_half.upper_half.lower_half.b ;
  assign _13_ = _12_ + (* src = "adder.v:79.17-85.6|adder.v:22.16-28.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *) \upper_half.upper_half.lower_half.cin ;
  assign _14_ = \upper_half.upper_half.upper_half.a  + (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.31|adder.v:54.16-60.6" *) \upper_half.upper_half.upper_half.b ;
  assign _15_ = _14_ + (* src = "adder.v:79.17-85.6|adder.v:29.16-35.6|adder.v:9.26-9.37|adder.v:54.16-60.6" *) \upper_half.upper_half.upper_half.cin ;
  assign { \lower_half.lower_half.lower_half.cout , \lower_half.lower_half.lower_half.sum  } = _01_;
  assign \lower_half.lower_half.carry  = \lower_half.lower_half.lower_half.cout ;
  assign \lower_half.lower_half.sum [3:0] = \lower_half.lower_half.lower_half.sum ;
  assign \lower_half.lower_half.lower_half.cin  = \lower_half.lower_half.cin ;
  assign \lower_half.lower_half.lower_half.b  = \lower_half.lower_half.b [3:0];
  assign \lower_half.lower_half.lower_half.a  = \lower_half.lower_half.a [3:0];
  assign { \lower_half.lower_half.upper_half.cout , \lower_half.lower_half.upper_half.sum  } = _03_;
  assign \lower_half.lower_half.cout  = \lower_half.lower_half.upper_half.cout ;
  assign \lower_half.lower_half.sum [7:4] = \lower_half.lower_half.upper_half.sum ;
  assign \lower_half.lower_half.upper_half.cin  = \lower_half.lower_half.carry ;
  assign \lower_half.lower_half.upper_half.b  = \lower_half.lower_half.b [7:4];
  assign \lower_half.lower_half.upper_half.a  = \lower_half.lower_half.a [7:4];
  assign \lower_half.carry  = \lower_half.lower_half.cout ;
  assign \lower_half.sum [7:0] = \lower_half.lower_half.sum ;
  assign \lower_half.lower_half.cin  = \lower_half.cin ;
  assign \lower_half.lower_half.b  = \lower_half.b [7:0];
  assign \lower_half.lower_half.a  = \lower_half.a [7:0];
  assign { \lower_half.upper_half.lower_half.cout , \lower_half.upper_half.lower_half.sum  } = _05_;
  assign \lower_half.upper_half.carry  = \lower_half.upper_half.lower_half.cout ;
  assign \lower_half.upper_half.sum [3:0] = \lower_half.upper_half.lower_half.sum ;
  assign \lower_half.upper_half.lower_half.cin  = \lower_half.upper_half.cin ;
  assign \lower_half.upper_half.lower_half.b  = \lower_half.upper_half.b [3:0];
  assign \lower_half.upper_half.lower_half.a  = \lower_half.upper_half.a [3:0];
  assign { \lower_half.upper_half.upper_half.cout , \lower_half.upper_half.upper_half.sum  } = _07_;
  assign \lower_half.upper_half.cout  = \lower_half.upper_half.upper_half.cout ;
  assign \lower_half.upper_half.sum [7:4] = \lower_half.upper_half.upper_half.sum ;
  assign \lower_half.upper_half.upper_half.cin  = \lower_half.upper_half.carry ;
  assign \lower_half.upper_half.upper_half.b  = \lower_half.upper_half.b [7:4];
  assign \lower_half.upper_half.upper_half.a  = \lower_half.upper_half.a [7:4];
  assign \lower_half.cout  = \lower_half.upper_half.cout ;
  assign \lower_half.sum [15:8] = \lower_half.upper_half.sum ;
  assign \lower_half.upper_half.cin  = \lower_half.carry ;
  assign \lower_half.upper_half.b  = \lower_half.b [15:8];
  assign \lower_half.upper_half.a  = \lower_half.a [15:8];
  assign carry = \lower_half.cout ;
  assign sum[15:0] = \lower_half.sum ;
  assign \lower_half.cin  = cin;
  assign \lower_half.b  = b[15:0];
  assign \lower_half.a  = a[15:0];
  assign { \upper_half.lower_half.lower_half.cout , \upper_half.lower_half.lower_half.sum  } = _09_;
  assign \upper_half.lower_half.carry  = \upper_half.lower_half.lower_half.cout ;
  assign \upper_half.lower_half.sum [3:0] = \upper_half.lower_half.lower_half.sum ;
  assign \upper_half.lower_half.lower_half.cin  = \upper_half.lower_half.cin ;
  assign \upper_half.lower_half.lower_half.b  = \upper_half.lower_half.b [3:0];
  assign \upper_half.lower_half.lower_half.a  = \upper_half.lower_half.a [3:0];
  assign { \upper_half.lower_half.upper_half.cout , \upper_half.lower_half.upper_half.sum  } = _11_;
  assign \upper_half.lower_half.cout  = \upper_half.lower_half.upper_half.cout ;
  assign \upper_half.lower_half.sum [7:4] = \upper_half.lower_half.upper_half.sum ;
  assign \upper_half.lower_half.upper_half.cin  = \upper_half.lower_half.carry ;
  assign \upper_half.lower_half.upper_half.b  = \upper_half.lower_half.b [7:4];
  assign \upper_half.lower_half.upper_half.a  = \upper_half.lower_half.a [7:4];
  assign \upper_half.carry  = \upper_half.lower_half.cout ;
  assign \upper_half.sum [7:0] = \upper_half.lower_half.sum ;
  assign \upper_half.lower_half.cin  = \upper_half.cin ;
  assign \upper_half.lower_half.b  = \upper_half.b [7:0];
  assign \upper_half.lower_half.a  = \upper_half.a [7:0];
  assign { \upper_half.upper_half.lower_half.cout , \upper_half.upper_half.lower_half.sum  } = _13_;
  assign \upper_half.upper_half.carry  = \upper_half.upper_half.lower_half.cout ;
  assign \upper_half.upper_half.sum [3:0] = \upper_half.upper_half.lower_half.sum ;
  assign \upper_half.upper_half.lower_half.cin  = \upper_half.upper_half.cin ;
  assign \upper_half.upper_half.lower_half.b  = \upper_half.upper_half.b [3:0];
  assign \upper_half.upper_half.lower_half.a  = \upper_half.upper_half.a [3:0];
  assign { \upper_half.upper_half.upper_half.cout , \upper_half.upper_half.upper_half.sum  } = _15_;
  assign \upper_half.upper_half.cout  = \upper_half.upper_half.upper_half.cout ;
  assign \upper_half.upper_half.sum [7:4] = \upper_half.upper_half.upper_half.sum ;
  assign \upper_half.upper_half.upper_half.cin  = \upper_half.upper_half.carry ;
  assign \upper_half.upper_half.upper_half.b  = \upper_half.upper_half.b [7:4];
  assign \upper_half.upper_half.upper_half.a  = \upper_half.upper_half.a [7:4];
  assign \upper_half.cout  = \upper_half.upper_half.cout ;
  assign \upper_half.sum [15:8] = \upper_half.upper_half.sum ;
  assign \upper_half.upper_half.cin  = \upper_half.carry ;
  assign \upper_half.upper_half.b  = \upper_half.b [15:8];
  assign \upper_half.upper_half.a  = \upper_half.a [15:8];
  assign cout = \upper_half.cout ;
  assign sum[31:16] = \upper_half.sum ;
  assign \upper_half.cin  = carry;
  assign \upper_half.b  = b[31:16];
  assign \upper_half.a  = a[31:16];
endmodule

(* src = "adder.v:1.1-11.10" *)
module adder_4bit(a, b, cin, sum, cout);
  (* src = "adder.v:9.26-9.31" *)
  wire [4:0] _0_;
  (* src = "adder.v:9.26-9.37" *)
  wire [4:0] _1_;
  (* src = "adder.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "adder.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "adder.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  assign _0_ = a + (* src = "adder.v:9.26-9.31" *) b;
  assign _1_ = _0_ + (* src = "adder.v:9.26-9.37" *) cin;
  assign { cout, sum } = _1_;
endmodule

(* src = "adder.v:13.1-36.10" *)
module adder_8bit(a, b, cin, sum, cout);
  (* src = "adder.v:22.16-28.6|adder.v:9.26-9.31" *)
  wire [4:0] _0_;
  (* src = "adder.v:22.16-28.6|adder.v:9.26-9.37" *)
  wire [4:0] _1_;
  (* src = "adder.v:29.16-35.6|adder.v:9.26-9.31" *)
  wire [4:0] _2_;
  (* src = "adder.v:29.16-35.6|adder.v:9.26-9.37" *)
  wire [4:0] _3_;
  (* src = "adder.v:14.17-14.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "adder.v:15.17-15.18" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "adder.v:21.10-21.15" *)
  wire carry;
  (* src = "adder.v:16.11-16.14" *)
  input cin;
  wire cin;
  (* src = "adder.v:18.12-18.16" *)
  output cout;
  wire cout;
  (* hdlname = "lower_half a" *)
  (* src = "adder.v:22.16-28.6|adder.v:2.17-2.18" *)
  wire [3:0] \lower_half.a ;
  (* hdlname = "lower_half b" *)
  (* src = "adder.v:22.16-28.6|adder.v:3.17-3.18" *)
  wire [3:0] \lower_half.b ;
  (* hdlname = "lower_half cin" *)
  (* src = "adder.v:22.16-28.6|adder.v:4.11-4.14" *)
  wire \lower_half.cin ;
  (* hdlname = "lower_half cout" *)
  (* src = "adder.v:22.16-28.6|adder.v:6.12-6.16" *)
  wire \lower_half.cout ;
  (* hdlname = "lower_half sum" *)
  (* src = "adder.v:22.16-28.6|adder.v:5.18-5.21" *)
  wire [3:0] \lower_half.sum ;
  (* src = "adder.v:17.18-17.21" *)
  output [7:0] sum;
  wire [7:0] sum;
  (* hdlname = "upper_half a" *)
  (* src = "adder.v:29.16-35.6|adder.v:2.17-2.18" *)
  wire [3:0] \upper_half.a ;
  (* hdlname = "upper_half b" *)
  (* src = "adder.v:29.16-35.6|adder.v:3.17-3.18" *)
  wire [3:0] \upper_half.b ;
  (* hdlname = "upper_half cin" *)
  (* src = "adder.v:29.16-35.6|adder.v:4.11-4.14" *)
  wire \upper_half.cin ;
  (* hdlname = "upper_half cout" *)
  (* src = "adder.v:29.16-35.6|adder.v:6.12-6.16" *)
  wire \upper_half.cout ;
  (* hdlname = "upper_half sum" *)
  (* src = "adder.v:29.16-35.6|adder.v:5.18-5.21" *)
  wire [3:0] \upper_half.sum ;
  assign _0_ = \lower_half.a  + (* src = "adder.v:22.16-28.6|adder.v:9.26-9.31" *) \lower_half.b ;
  assign _1_ = _0_ + (* src = "adder.v:22.16-28.6|adder.v:9.26-9.37" *) \lower_half.cin ;
  assign _2_ = \upper_half.a  + (* src = "adder.v:29.16-35.6|adder.v:9.26-9.31" *) \upper_half.b ;
  assign _3_ = _2_ + (* src = "adder.v:29.16-35.6|adder.v:9.26-9.37" *) \upper_half.cin ;
  assign { \lower_half.cout , \lower_half.sum  } = _1_;
  assign carry = \lower_half.cout ;
  assign sum[3:0] = \lower_half.sum ;
  assign \lower_half.cin  = cin;
  assign \lower_half.b  = b[3:0];
  assign \lower_half.a  = a[3:0];
  assign { \upper_half.cout , \upper_half.sum  } = _3_;
  assign cout = \upper_half.cout ;
  assign sum[7:4] = \upper_half.sum ;
  assign \upper_half.cin  = carry;
  assign \upper_half.b  = b[7:4];
  assign \upper_half.a  = a[7:4];
endmodule
