// Seed: 3234944609
module module_0 (
    output tri1 id_0,
    input supply1 id_1,
    output uwire id_2,
    input tri1 id_3,
    output tri id_4,
    input supply0 id_5,
    input tri0 id_6,
    input supply1 id_7,
    output tri1 id_8,
    input supply1 id_9,
    output tri1 id_10,
    output wor id_11,
    output tri id_12,
    input tri1 id_13,
    input supply0 id_14,
    output wand id_15,
    output uwire id_16,
    input supply0 id_17,
    output tri1 id_18,
    input supply0 id_19,
    input wor id_20,
    output wor id_21,
    input supply0 id_22,
    output wor id_23,
    input wor id_24,
    input wire id_25,
    output tri0 id_26,
    input wand id_27,
    output wor id_28,
    output tri0 id_29
);
  assign id_8 = id_6;
endmodule
module module_1 (
    input wor id_0,
    input wand id_1,
    output tri0 id_2,
    output wire id_3,
    input supply0 id_4,
    output tri id_5,
    output tri1 id_6,
    input uwire id_7,
    input tri0 id_8,
    input supply1 id_9,
    input tri1 id_10,
    input tri0 id_11,
    input tri1 id_12,
    output wor id_13
);
  wire id_15;
  module_0(
      id_6,
      id_11,
      id_3,
      id_4,
      id_2,
      id_4,
      id_7,
      id_4,
      id_3,
      id_12,
      id_13,
      id_2,
      id_3,
      id_12,
      id_8,
      id_3,
      id_2,
      id_12,
      id_3,
      id_7,
      id_10,
      id_2,
      id_10,
      id_2,
      id_8,
      id_9,
      id_2,
      id_4,
      id_5,
      id_5
  );
endmodule
