// Seed: 1750116051
module module_0 (
    input supply1 id_0,
    input supply0 id_1,
    input supply1 id_2,
    input wor id_3,
    input wire id_4,
    input wand id_5,
    input tri id_6,
    input uwire id_7,
    input supply0 id_8,
    input tri id_9,
    output wor id_10,
    output tri1 id_11,
    input tri id_12,
    input wand id_13,
    input supply1 id_14,
    output wand id_15,
    input wire id_16,
    input wand id_17,
    output wand id_18,
    input uwire id_19,
    input wor id_20,
    output wor id_21,
    input uwire id_22,
    output uwire id_23,
    input uwire id_24,
    input supply0 id_25,
    input tri id_26,
    input tri id_27,
    input supply1 id_28,
    output wire id_29,
    input wire id_30,
    input tri1 id_31,
    output supply1 id_32
    , id_42,
    output tri1 id_33,
    output tri id_34,
    output wand id_35,
    input supply0 id_36,
    input wand id_37,
    input wor id_38
    , id_43,
    input wire id_39,
    input supply1 id_40
);
  wire id_44;
endmodule
module module_1 (
    input wand id_0,
    input wire id_1,
    output uwire id_2,
    input supply1 id_3,
    input supply1 id_4,
    input supply1 id_5,
    input wand id_6,
    input tri0 id_7,
    output uwire id_8
);
  assign id_2 = 1;
  tri0 id_10 = id_3;
  module_0 modCall_1 (
      id_10,
      id_5,
      id_4,
      id_1,
      id_4,
      id_5,
      id_6,
      id_1,
      id_10,
      id_1,
      id_10,
      id_2,
      id_5,
      id_1,
      id_10,
      id_2,
      id_7,
      id_5,
      id_8,
      id_6,
      id_6,
      id_10,
      id_1,
      id_2,
      id_0,
      id_3,
      id_0,
      id_1,
      id_10,
      id_8,
      id_1,
      id_0,
      id_8,
      id_2,
      id_10,
      id_10,
      id_5,
      id_4,
      id_0,
      id_3,
      id_5
  );
  assign modCall_1.id_19 = 0;
endmodule
