// Seed: 541206325
module module_0 (
    input wand id_0,
    input wor id_1,
    input wire id_2,
    input tri id_3,
    output uwire id_4,
    input wor id_5,
    output wand id_6,
    output uwire id_7,
    output tri0 id_8,
    input wand id_9,
    input wand id_10,
    output tri id_11,
    output wand id_12,
    input wand id_13,
    input wire id_14,
    output wor id_15,
    input supply1 id_16,
    input tri0 id_17,
    output wire id_18,
    input uwire id_19,
    output tri1 id_20,
    output wand id_21,
    output supply1 id_22,
    input uwire id_23,
    output supply1 id_24,
    input wire id_25,
    input supply0 id_26,
    output supply0 id_27,
    input wire id_28,
    input tri1 id_29,
    output supply0 id_30,
    input wire id_31,
    output wor id_32,
    output wire id_33,
    output tri id_34,
    output supply1 id_35,
    input wand id_36,
    input tri0 id_37
    , id_43,
    input tri1 id_38,
    input tri1 id_39,
    input tri0 id_40,
    output uwire id_41
);
  wire id_44 = 1;
endmodule
module module_1 (
    input  wire id_0,
    input  wire id_1,
    output wand id_2
);
  assign id_2 = 1;
  module_0(
      id_0,
      id_1,
      id_1,
      id_0,
      id_2,
      id_1,
      id_2,
      id_2,
      id_2,
      id_1,
      id_1,
      id_2,
      id_2,
      id_0,
      id_1,
      id_2,
      id_0,
      id_0,
      id_2,
      id_1,
      id_2,
      id_2,
      id_2,
      id_1,
      id_2,
      id_0,
      id_1,
      id_2,
      id_0,
      id_0,
      id_2,
      id_0,
      id_2,
      id_2,
      id_2,
      id_2,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_2
  );
endmodule
