// Seed: 2537105270
module module_0 (
    output tri1 id_0,
    input supply0 id_1,
    output wire id_2,
    output wire id_3,
    output supply0 id_4,
    output supply0 id_5,
    output wire id_6,
    output supply1 id_7,
    input wor id_8,
    output wire id_9,
    input tri id_10,
    input supply1 id_11,
    input wand id_12,
    output tri0 id_13,
    input tri1 id_14,
    output tri1 id_15,
    output tri0 id_16,
    output tri id_17,
    input uwire id_18,
    input supply1 id_19,
    output wand id_20,
    input tri1 id_21,
    input uwire id_22,
    output wire id_23,
    input uwire id_24,
    output wand id_25,
    input wor id_26,
    input uwire id_27,
    output tri id_28,
    input wand id_29,
    output wor id_30,
    output wire id_31,
    input tri0 id_32,
    output wand id_33,
    output wand id_34,
    input tri id_35,
    output wand id_36,
    output wand id_37
);
  assign id_36 = 1;
endmodule
module module_1 (
    input wand id_0,
    input supply1 id_1,
    input supply0 id_2,
    inout tri id_3,
    input tri id_4,
    input supply0 id_5,
    output wor id_6
);
  assign id_3 = 1 == 1'b0;
  module_0(
      id_3,
      id_5,
      id_6,
      id_3,
      id_3,
      id_3,
      id_6,
      id_3,
      id_2,
      id_3,
      id_3,
      id_2,
      id_4,
      id_6,
      id_1,
      id_6,
      id_6,
      id_3,
      id_2,
      id_3,
      id_3,
      id_3,
      id_2,
      id_6,
      id_2,
      id_3,
      id_5,
      id_4,
      id_6,
      id_4,
      id_6,
      id_3,
      id_0,
      id_6,
      id_6,
      id_3,
      id_3,
      id_6
  );
  wand id_8, id_9 = id_4;
  assign id_6 = id_8;
endmodule
