// Seed: 1237417177
module module_0 (
    output uwire id_0,
    input supply1 id_1,
    output supply1 id_2,
    output supply1 id_3,
    output supply1 id_4,
    input supply1 id_5,
    input uwire id_6,
    input supply0 id_7,
    input tri1 id_8,
    output supply1 id_9,
    input wor id_10,
    output supply1 id_11,
    input tri0 id_12,
    input tri1 id_13,
    input uwire id_14,
    output tri0 id_15,
    input uwire id_16,
    output tri0 id_17,
    output tri id_18,
    input uwire id_19,
    input tri0 id_20,
    input supply1 id_21,
    input tri0 id_22,
    input supply1 id_23,
    input tri id_24,
    input supply0 id_25,
    input uwire id_26,
    input tri0 id_27,
    input wand id_28,
    input wire id_29,
    input wire id_30,
    input wand id_31,
    input wor id_32,
    output wire id_33,
    output wor id_34,
    output tri id_35,
    output tri0 id_36,
    input wire id_37,
    output wand id_38,
    input wor id_39,
    output wor id_40,
    input wor id_41,
    output tri1 id_42
);
  wire id_44;
  wire id_45;
endmodule
module module_1 (
    input  tri0  id_0,
    input  uwire id_1,
    input  wor   id_2,
    input  tri   id_3,
    input  tri   id_4,
    input  tri0  id_5,
    output uwire id_6
);
  module_0(
      id_6,
      id_5,
      id_6,
      id_6,
      id_6,
      id_0,
      id_1,
      id_1,
      id_2,
      id_6,
      id_3,
      id_6,
      id_4,
      id_0,
      id_1,
      id_6,
      id_1,
      id_6,
      id_6,
      id_3,
      id_1,
      id_3,
      id_2,
      id_4,
      id_2,
      id_3,
      id_5,
      id_4,
      id_4,
      id_4,
      id_5,
      id_1,
      id_0,
      id_6,
      id_6,
      id_6,
      id_6,
      id_1,
      id_6,
      id_2,
      id_6,
      id_4,
      id_6
  );
  assign id_6 = 1;
endmodule
