// Seed: 1970058917
module module_0 (
    input uwire id_0,
    input uwire id_1,
    input uwire id_2,
    output wor id_3,
    output wor id_4,
    output uwire id_5,
    input uwire id_6,
    output tri id_7,
    input supply0 id_8,
    input tri id_9,
    output tri id_10,
    input supply1 id_11,
    input wire id_12,
    input wire id_13,
    input tri1 id_14,
    output supply1 id_15,
    input tri1 id_16,
    input tri id_17,
    output wand id_18,
    output wire id_19,
    input wor id_20,
    output supply0 id_21,
    output supply1 id_22,
    output wand id_23,
    input supply1 id_24,
    input supply0 id_25,
    output supply1 id_26,
    output tri id_27,
    input wor id_28,
    input tri1 id_29,
    input tri id_30,
    input wand id_31,
    input supply1 id_32,
    input wand id_33
);
  assign module_1.type_6 = 0;
endmodule
module module_1 (
    input uwire id_0,
    input wor id_1,
    output tri id_2,
    input tri id_3,
    input supply0 id_4,
    output uwire id_5,
    input wand id_6,
    input wor id_7,
    input uwire id_8,
    input uwire id_9,
    input tri id_10,
    input supply1 id_11,
    output tri id_12
);
  id_14(
      id_2, id_10, 1
  );
  module_0 modCall_1 (
      id_8,
      id_10,
      id_6,
      id_12,
      id_5,
      id_2,
      id_6,
      id_5,
      id_4,
      id_3,
      id_12,
      id_3,
      id_4,
      id_3,
      id_11,
      id_12,
      id_6,
      id_3,
      id_12,
      id_2,
      id_0,
      id_12,
      id_12,
      id_2,
      id_4,
      id_11,
      id_12,
      id_12,
      id_1,
      id_1,
      id_4,
      id_9,
      id_8,
      id_11
  );
endmodule
