// Seed: 2379240619
module module_0 (
    input supply0 id_0
    , id_42,
    input wand id_1,
    output uwire id_2,
    input supply0 id_3,
    input supply1 id_4,
    output supply0 id_5,
    input tri0 id_6,
    output tri id_7,
    input supply0 id_8,
    input tri id_9,
    input tri id_10,
    input wor id_11,
    input uwire id_12
    , id_43,
    input wor id_13,
    input uwire id_14,
    output uwire id_15,
    input tri id_16,
    input supply1 id_17,
    output supply0 id_18,
    input tri0 id_19,
    input wor id_20,
    input wor id_21,
    input supply0 id_22,
    input wand id_23,
    output wand id_24,
    output tri0 id_25,
    input tri0 id_26,
    output wand id_27,
    output tri1 id_28,
    output tri1 id_29,
    input wor id_30,
    input wand id_31,
    input supply0 id_32,
    input wor id_33,
    output wor id_34
    , id_44,
    output wire id_35,
    input tri1 id_36,
    output tri1 id_37,
    input tri id_38,
    input tri0 id_39,
    output tri id_40
);
  wire id_45;
endmodule
module module_1 (
    input  wor  id_0,
    input  tri1 id_1,
    input  wire id_2,
    output tri1 id_3
);
  always @(id_1) id_3 = id_2 ^ 1'b0;
  module_0(
      id_2,
      id_2,
      id_3,
      id_2,
      id_2,
      id_3,
      id_2,
      id_3,
      id_2,
      id_0,
      id_1,
      id_1,
      id_1,
      id_2,
      id_0,
      id_3,
      id_0,
      id_2,
      id_3,
      id_0,
      id_0,
      id_2,
      id_0,
      id_0,
      id_3,
      id_3,
      id_2,
      id_3,
      id_3,
      id_3,
      id_2,
      id_0,
      id_1,
      id_0,
      id_3,
      id_3,
      id_0,
      id_3,
      id_2,
      id_1,
      id_3
  );
endmodule
