// Seed: 3126564069
module module_0 (
    output tri id_0,
    input wor id_1,
    input uwire id_2,
    input tri id_3,
    input tri0 id_4,
    output wor id_5
    , id_45,
    output wire id_6,
    input wire id_7,
    output supply0 id_8,
    input wire id_9,
    output tri id_10,
    input supply1 id_11,
    output uwire id_12,
    input wire id_13,
    input tri id_14,
    output uwire id_15,
    input tri0 id_16,
    input tri0 id_17,
    output supply1 id_18,
    output tri0 id_19,
    input uwire id_20,
    output wire id_21,
    input tri id_22,
    input supply1 id_23,
    input uwire id_24,
    input tri id_25,
    input uwire id_26,
    input wand id_27,
    input wand id_28,
    output tri id_29,
    input wor id_30,
    input wand id_31,
    input tri id_32,
    output supply1 id_33,
    output wor id_34,
    input tri id_35,
    output tri0 id_36,
    input tri id_37,
    input wire id_38,
    output tri0 id_39,
    input supply1 id_40,
    input tri id_41,
    input tri0 id_42,
    output wor id_43
);
endmodule
module module_1 (
    input wand id_0,
    input supply0 id_1,
    input uwire id_2,
    output supply0 id_3
);
  logic id_5;
  assign id_5[-1==""] = -1 ? -1 : -1;
  module_0 modCall_1 (
      id_3,
      id_2,
      id_2,
      id_0,
      id_0,
      id_3,
      id_3,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_3,
      id_0,
      id_0,
      id_3,
      id_1,
      id_2,
      id_3,
      id_3,
      id_1,
      id_3,
      id_2,
      id_0,
      id_1,
      id_2,
      id_0,
      id_1,
      id_0,
      id_3,
      id_1,
      id_0,
      id_0,
      id_3,
      id_3,
      id_0,
      id_3,
      id_0,
      id_1,
      id_3,
      id_0,
      id_0,
      id_0,
      id_3
  );
  wire id_6;
  assign id_6 = -1;
  assign id_5 = ((id_0));
endmodule
