// Seed: 2539813106
module module_0 (
    output wor id_0,
    input wor id_1,
    output wire id_2,
    output tri id_3,
    input supply1 id_4,
    output supply1 id_5,
    output tri0 id_6,
    input wand id_7,
    input uwire id_8,
    input tri1 id_9,
    input supply0 id_10,
    input uwire id_11,
    output tri0 id_12,
    input supply1 id_13,
    input wor id_14,
    input wire id_15,
    output tri0 id_16,
    output wire id_17,
    input tri id_18,
    input tri0 id_19,
    output wire id_20,
    input wire id_21,
    input wand id_22,
    input wire id_23,
    output wor id_24,
    input supply0 id_25,
    output wand id_26,
    input wand id_27,
    input supply1 id_28,
    input supply0 id_29,
    input wand id_30,
    output wor id_31,
    input supply0 id_32,
    input uwire id_33,
    output tri id_34,
    input wand id_35,
    input tri id_36,
    input wand id_37,
    input tri0 id_38,
    output supply1 id_39
);
  assign id_12 = -1'b0 == 1;
  assign module_1._id_4 = 0;
  logic id_41, id_42;
  assign id_0 = id_22;
endmodule
module module_1 #(
    parameter id_4 = 32'd11
) (
    input  wand  id_0,
    output tri0  id_1,
    input  wor   id_2,
    input  tri1  id_3,
    input  tri1  _id_4,
    input  wire  id_5,
    input  uwire id_6,
    input  tri   id_7,
    output uwire id_8,
    output wire  id_9
);
  logic [1 : id_4] id_11, id_12;
  module_0 modCall_1 (
      id_9,
      id_7,
      id_1,
      id_9,
      id_7,
      id_1,
      id_8,
      id_6,
      id_2,
      id_6,
      id_2,
      id_5,
      id_9,
      id_2,
      id_3,
      id_3,
      id_9,
      id_8,
      id_3,
      id_2,
      id_8,
      id_5,
      id_3,
      id_2,
      id_9,
      id_6,
      id_1,
      id_0,
      id_2,
      id_0,
      id_2,
      id_9,
      id_6,
      id_5,
      id_8,
      id_6,
      id_6,
      id_6,
      id_6,
      id_1
  );
endmodule
