// Seed: 2559921383
module module_0 (
    input tri id_0,
    input uwire id_1,
    input tri1 id_2,
    output tri id_3,
    input wire id_4,
    input tri0 id_5,
    input tri0 id_6,
    input tri1 id_7,
    output supply1 id_8,
    input tri0 id_9,
    output wor id_10,
    input wire id_11,
    input wand id_12,
    input tri0 id_13,
    output wand id_14,
    output tri0 id_15,
    input uwire id_16,
    input tri id_17,
    output wire id_18,
    input wand id_19,
    input tri id_20,
    output tri id_21,
    output wire id_22,
    output uwire id_23,
    output wor id_24,
    input wor id_25,
    input tri id_26,
    input uwire id_27,
    input tri0 id_28,
    output wor id_29,
    output tri1 id_30,
    input supply1 id_31,
    input uwire id_32,
    output wor id_33
);
  assign id_29 = 1;
  assign module_1.id_13 = 0;
endmodule
module module_1 (
    inout logic id_0,
    output supply1 id_1
    , id_23,
    output supply0 id_2,
    output supply1 id_3,
    output tri id_4,
    input wor id_5,
    output tri1 id_6,
    input tri id_7,
    input wand id_8,
    output supply1 id_9,
    output supply0 id_10,
    input wor id_11,
    input wire id_12,
    input wand id_13,
    output tri id_14,
    input uwire id_15,
    input uwire id_16,
    input wor id_17,
    output wand id_18,
    input supply1 id_19,
    input wand id_20,
    output wire id_21
);
  always @(*) begin : LABEL_0
    assign id_2 = id_0;
  end
  wire id_24;
  module_0 modCall_1 (
      id_7,
      id_12,
      id_13,
      id_6,
      id_16,
      id_16,
      id_20,
      id_20,
      id_1,
      id_15,
      id_2,
      id_12,
      id_8,
      id_19,
      id_1,
      id_18,
      id_7,
      id_7,
      id_18,
      id_5,
      id_19,
      id_18,
      id_4,
      id_21,
      id_4,
      id_7,
      id_12,
      id_20,
      id_5,
      id_3,
      id_10,
      id_15,
      id_11,
      id_6
  );
endmodule
