// Seed: 3106042210
module module_0 (
    output tri0 id_0,
    input tri0 id_1,
    output supply0 id_2,
    output wand id_3,
    output tri1 id_4,
    input wand id_5,
    output tri0 id_6,
    input wand id_7,
    input tri1 id_8,
    input wor id_9,
    output tri id_10,
    input wire id_11,
    output uwire id_12,
    input wand id_13,
    output tri0 id_14,
    output tri0 id_15,
    input tri0 id_16,
    input wor id_17,
    output tri id_18,
    input wire id_19,
    input uwire id_20,
    input wor id_21,
    input uwire id_22,
    output tri0 id_23,
    output tri id_24,
    input wor id_25,
    input supply1 id_26,
    input uwire id_27,
    input tri1 id_28,
    output wire id_29
);
  wire id_31;
  assign id_4 = id_22;
endmodule
module module_1 (
    input wor id_0,
    input wand id_1,
    output uwire id_2,
    input tri0 id_3,
    input wand id_4,
    input wire id_5,
    input uwire id_6,
    output uwire id_7,
    output supply1 id_8,
    input supply0 id_9,
    output wand id_10,
    input wire id_11,
    output supply0 id_12
);
  assign id_7 = id_9 == {1{~id_0 === 1}};
  module_0 modCall_1 (
      id_8,
      id_5,
      id_8,
      id_7,
      id_2,
      id_9,
      id_7,
      id_9,
      id_6,
      id_5,
      id_2,
      id_0,
      id_2,
      id_5,
      id_8,
      id_12,
      id_1,
      id_9,
      id_7,
      id_4,
      id_6,
      id_1,
      id_0,
      id_10,
      id_2,
      id_3,
      id_3,
      id_11,
      id_0,
      id_10
  );
  assign modCall_1.id_12 = 0;
endmodule
