// Seed: 2118731175
module module_0 (
    input tri id_0,
    input uwire id_1
    , id_33,
    input uwire id_2,
    input tri id_3,
    input tri0 id_4,
    input tri1 id_5,
    output tri0 id_6,
    input tri0 id_7,
    input wire id_8,
    input supply1 id_9,
    output supply1 id_10,
    output supply0 id_11,
    input supply0 id_12,
    output wor id_13,
    output wire id_14,
    input supply1 id_15,
    output wor id_16,
    input tri0 id_17,
    output supply1 id_18,
    input supply0 id_19,
    input supply1 id_20,
    output tri0 id_21,
    input wire id_22,
    output wire id_23,
    input wor id_24,
    input wand id_25,
    output supply0 id_26,
    output wand id_27,
    output tri id_28,
    output tri1 id_29,
    input supply1 id_30,
    output tri1 id_31
);
endmodule
module module_1 (
    input wand id_0,
    input wire id_1,
    input wand id_2,
    input tri0 id_3,
    input wor id_4,
    output supply0 id_5,
    input supply1 id_6,
    output supply0 id_7,
    input tri id_8,
    input wire id_9,
    output tri0 id_10,
    output wor id_11,
    input supply0 id_12,
    output supply0 id_13,
    input supply0 id_14,
    output uwire id_15
);
  logic id_17;
  ;
  module_0 modCall_1 (
      id_6,
      id_8,
      id_3,
      id_12,
      id_1,
      id_4,
      id_13,
      id_12,
      id_2,
      id_4,
      id_7,
      id_15,
      id_3,
      id_5,
      id_7,
      id_12,
      id_10,
      id_2,
      id_5,
      id_4,
      id_12,
      id_7,
      id_3,
      id_10,
      id_0,
      id_0,
      id_11,
      id_15,
      id_11,
      id_5,
      id_1,
      id_7
  );
endmodule
