// Seed: 2914427851
module module_0 (
    input tri1 id_0,
    output supply0 id_1,
    input supply0 id_2,
    input supply1 id_3,
    output uwire id_4,
    output tri0 id_5,
    output tri0 id_6,
    output tri0 id_7,
    input supply0 id_8,
    input supply1 id_9
    , id_38,
    input tri id_10,
    input wire id_11,
    output wire id_12,
    input tri1 id_13,
    output supply1 id_14,
    input tri1 id_15,
    output supply1 id_16,
    input uwire id_17,
    input supply1 id_18,
    output wor id_19,
    output wand id_20,
    output tri0 id_21,
    input uwire id_22,
    input wor id_23,
    output uwire id_24,
    output supply0 id_25,
    input uwire id_26,
    input wor id_27,
    output tri0 id_28,
    input tri1 id_29,
    input wor id_30,
    output tri1 id_31
    , id_39,
    input supply0 id_32,
    input supply0 id_33,
    input wor id_34,
    output tri1 id_35,
    input wor id_36
);
  assign id_35 = 1;
endmodule
module module_1 (
    input supply0 id_0,
    output tri0 id_1,
    input tri1 id_2,
    input tri id_3,
    input wand id_4
);
  wire id_6;
  module_0(
      id_2,
      id_1,
      id_2,
      id_3,
      id_1,
      id_1,
      id_1,
      id_1,
      id_2,
      id_3,
      id_4,
      id_0,
      id_1,
      id_3,
      id_1,
      id_4,
      id_1,
      id_4,
      id_2,
      id_1,
      id_1,
      id_1,
      id_0,
      id_4,
      id_1,
      id_1,
      id_2,
      id_4,
      id_1,
      id_4,
      id_2,
      id_1,
      id_4,
      id_0,
      id_2,
      id_1,
      id_3
  );
endmodule
