// Seed: 3942019228
module module_0 (
    input wand id_0,
    output supply1 id_1,
    input supply1 id_2,
    input tri0 id_3,
    input tri id_4,
    input wand id_5,
    input tri id_6,
    input tri0 id_7,
    input tri id_8,
    input wire id_9,
    input wor id_10,
    input supply1 id_11,
    input wand id_12,
    output wire id_13,
    output uwire id_14,
    output tri0 id_15,
    output tri0 id_16,
    input supply1 id_17,
    output wor id_18,
    input tri1 id_19,
    input wor id_20,
    input tri id_21,
    output tri0 id_22,
    output tri id_23,
    input wire id_24,
    output tri id_25,
    input wire id_26,
    output tri0 id_27,
    input supply0 id_28,
    input wire id_29,
    output wor id_30,
    output wor id_31,
    input supply0 id_32,
    output supply0 id_33,
    input supply1 id_34,
    input supply1 id_35,
    output wire id_36
);
endmodule
module module_1 (
    output tri0  id_0,
    output uwire id_1,
    output wor   id_2,
    input  tri   id_3,
    input  tri1  id_4,
    output tri1  id_5,
    input  tri0  id_6,
    input  tri1  id_7
);
  wand id_9 = id_7;
  wire id_10;
  supply1 id_11 = id_4;
  integer id_12, id_13, id_14;
  assign id_5 = 1;
  always @(id_7) @(1'b0);
  module_0(
      id_7,
      id_9,
      id_4,
      id_9,
      id_4,
      id_9,
      id_11,
      id_4,
      id_3,
      id_9,
      id_4,
      id_9,
      id_3,
      id_2,
      id_11,
      id_2,
      id_5,
      id_4,
      id_2,
      id_3,
      id_6,
      id_7,
      id_5,
      id_5,
      id_3,
      id_11,
      id_11,
      id_1,
      id_3,
      id_11,
      id_2,
      id_9,
      id_7,
      id_11,
      id_6,
      id_11,
      id_2
  );
endmodule
