// Seed: 2356953671
module module_0 (
    input supply0 id_0,
    input tri1 id_1,
    output wire id_2,
    input wire id_3,
    input tri id_4,
    output supply1 id_5,
    input wand id_6,
    input tri0 id_7,
    input wor id_8,
    input supply0 id_9,
    input supply0 id_10,
    input wire id_11,
    input supply1 id_12,
    output uwire id_13,
    input supply1 id_14,
    input wand id_15,
    input tri1 id_16,
    output uwire id_17,
    input wire id_18,
    input tri1 id_19,
    input tri1 id_20,
    input tri0 id_21,
    output tri id_22,
    input tri id_23,
    input wire id_24,
    output wire id_25,
    output wand id_26,
    output wand id_27,
    input wand id_28,
    output supply0 id_29,
    output supply1 id_30,
    input wand id_31,
    output wand id_32,
    input tri id_33,
    input tri id_34,
    output supply0 id_35,
    input wor id_36,
    input tri id_37,
    input wor id_38,
    input uwire id_39,
    input uwire id_40,
    output wire id_41
);
  wire id_43;
  wire id_44;
  uwire  id_45  =  id_24  ,  id_46  ,  id_47  ,  id_48  ,  id_49  ,  id_50  ,  id_51  ,  id_52  ,  id_53  ,  id_54  ,  id_55  ,  id_56  ,  id_57  ;
endmodule
module module_1 (
    input tri id_0,
    input supply1 id_1,
    output wire id_2,
    input tri id_3,
    input supply0 id_4,
    output uwire id_5,
    input uwire id_6,
    output uwire id_7
);
  module_0 modCall_1 (
      id_1,
      id_0,
      id_5,
      id_0,
      id_6,
      id_5,
      id_1,
      id_6,
      id_3,
      id_3,
      id_0,
      id_0,
      id_6,
      id_7,
      id_3,
      id_6,
      id_0,
      id_7,
      id_3,
      id_6,
      id_4,
      id_3,
      id_7,
      id_4,
      id_0,
      id_7,
      id_5,
      id_5,
      id_0,
      id_2,
      id_5,
      id_6,
      id_7,
      id_4,
      id_1,
      id_5,
      id_6,
      id_4,
      id_3,
      id_4,
      id_4,
      id_5
  );
  assign modCall_1.id_45 = 0;
endmodule
