// Seed: 3260157185
macromodule module_0 (
    input wire id_0,
    input uwire id_1,
    input supply0 id_2,
    input supply1 id_3,
    input wand id_4,
    output wor id_5,
    input supply0 id_6,
    input uwire id_7,
    output uwire id_8,
    input wire id_9,
    input wand id_10,
    output supply0 id_11,
    output tri0 id_12,
    input uwire id_13,
    input tri id_14,
    output supply1 id_15,
    output tri0 id_16,
    output tri1 id_17,
    input wor id_18,
    input supply0 id_19,
    output tri id_20,
    input supply1 id_21,
    input tri id_22,
    input supply1 id_23,
    output uwire id_24,
    input wand id_25,
    input tri0 id_26,
    output tri0 id_27,
    input supply0 id_28,
    input wor id_29,
    output tri0 id_30,
    input tri id_31,
    input supply1 id_32,
    input tri0 id_33,
    input wor id_34
);
endmodule
module module_1 (
    output wire  id_0,
    output wand  id_1,
    output tri0  id_2,
    input  wire  id_3,
    output tri0  id_4,
    input  tri1  id_5,
    input  uwire id_6,
    input  tri0  id_7
);
  assign id_0 = (id_7);
  module_0(
      id_7,
      id_5,
      id_5,
      id_5,
      id_6,
      id_4,
      id_5,
      id_6,
      id_0,
      id_3,
      id_3,
      id_0,
      id_1,
      id_3,
      id_3,
      id_2,
      id_0,
      id_2,
      id_3,
      id_6,
      id_4,
      id_3,
      id_7,
      id_7,
      id_0,
      id_7,
      id_5,
      id_4,
      id_3,
      id_6,
      id_4,
      id_6,
      id_3,
      id_6,
      id_6
  );
endmodule
