// Seed: 3783061761
module module_0 (
    input wire id_0
    , id_25,
    input wand id_1,
    input supply0 id_2,
    output supply0 id_3,
    input tri1 id_4,
    output uwire id_5,
    output tri0 id_6,
    input wor id_7,
    input supply1 id_8,
    input uwire id_9,
    input wand id_10,
    output wor id_11,
    input tri0 id_12,
    output wand id_13,
    input wire id_14,
    input uwire id_15,
    input uwire id_16,
    input supply0 id_17,
    output tri0 id_18,
    input uwire id_19,
    input tri0 id_20,
    output wand id_21,
    input tri id_22,
    output tri0 id_23
);
endmodule
module module_1 (
    output tri id_0,
    output wor id_1,
    input tri1 id_2,
    output supply0 id_3,
    input wand id_4,
    input uwire id_5,
    input supply0 id_6,
    output wire id_7,
    input tri1 id_8,
    input supply1 id_9,
    output tri1 id_10,
    output uwire id_11,
    input supply1 id_12,
    input tri1 id_13,
    input tri1 id_14,
    output tri id_15
);
  module_0 modCall_1 (
      id_6,
      id_5,
      id_14,
      id_10,
      id_5,
      id_3,
      id_11,
      id_4,
      id_14,
      id_14,
      id_12,
      id_0,
      id_6,
      id_10,
      id_2,
      id_14,
      id_12,
      id_6,
      id_0,
      id_12,
      id_8,
      id_7,
      id_8,
      id_7
  );
  assign modCall_1.type_0 = 0;
endmodule
