// Seed: 2937339170
module module_0 (
    output wor id_0,
    input uwire id_1,
    input wor id_2,
    output tri id_3,
    output supply0 id_4,
    input uwire id_5,
    output wand id_6,
    input supply0 id_7,
    input tri id_8,
    output uwire id_9
    , id_68,
    input uwire id_10,
    output tri id_11,
    output supply1 id_12,
    input tri id_13,
    output tri1 id_14,
    output tri id_15,
    output wire id_16,
    input tri1 id_17,
    output supply0 id_18,
    input supply1 id_19
    , id_69,
    input supply0 id_20,
    input tri0 id_21
    , id_70,
    input tri id_22,
    input supply0 id_23,
    input tri0 id_24,
    input wor id_25
    , id_71,
    input wor id_26,
    input supply0 id_27,
    input wand id_28,
    output wand id_29,
    input tri0 id_30,
    input tri0 id_31,
    output wand id_32,
    input tri1 id_33,
    input tri1 id_34,
    input wor id_35,
    input wand id_36,
    input supply0 id_37,
    input wor id_38,
    input wor id_39,
    output uwire id_40,
    output tri0 id_41,
    output tri1 id_42,
    input tri0 id_43,
    output tri0 id_44,
    output supply1 id_45,
    input tri0 id_46,
    inout tri0 id_47,
    input wand id_48,
    input wand id_49,
    output tri0 id_50,
    output wire id_51,
    output supply0 id_52#(
        .id_72(~1),
        .id_73(id_72)
    ),
    input uwire id_53,
    output uwire id_54,
    input wire id_55,
    output wand id_56,
    input tri0 id_57,
    input wor id_58,
    output wand id_59,
    input uwire id_60,
    output supply1 id_61,
    input supply0 id_62,
    input wand id_63,
    input wire id_64,
    input supply0 id_65,
    output tri1 id_66
);
  wire id_74;
  assign module_1.id_2 = 0;
endmodule
module module_1 (
    input wire id_0,
    output uwire id_1
    , id_6,
    input supply0 id_2,
    output wire id_3,
    input supply0 id_4
);
  supply1 id_7 = (((id_0)));
  wire id_8;
  module_0 modCall_1 (
      id_1,
      id_0,
      id_4,
      id_1,
      id_7,
      id_4,
      id_1,
      id_7,
      id_7,
      id_3,
      id_0,
      id_7,
      id_7,
      id_7,
      id_3,
      id_7,
      id_3,
      id_2,
      id_3,
      id_7,
      id_4,
      id_7,
      id_4,
      id_4,
      id_0,
      id_2,
      id_4,
      id_4,
      id_0,
      id_7,
      id_4,
      id_7,
      id_3,
      id_4,
      id_7,
      id_0,
      id_2,
      id_2,
      id_7,
      id_4,
      id_7,
      id_1,
      id_7,
      id_4,
      id_1,
      id_3,
      id_2,
      id_7,
      id_7,
      id_2,
      id_3,
      id_3,
      id_3,
      id_7,
      id_3,
      id_7,
      id_3,
      id_0,
      id_0,
      id_3,
      id_2,
      id_7,
      id_7,
      id_2,
      id_2,
      id_2,
      id_1
  );
endmodule
