// Seed: 1915325249
module module_0 (
    input supply1 id_0,
    output wor id_1,
    output tri1 id_2,
    input uwire id_3,
    input supply0 id_4,
    input tri0 id_5,
    output tri0 id_6,
    output wire id_7,
    input wire id_8,
    output tri1 id_9,
    input supply0 id_10,
    output tri1 id_11,
    input wor id_12,
    input supply0 id_13,
    input tri0 id_14,
    output supply0 id_15,
    output wor id_16,
    input uwire id_17,
    input wor id_18,
    input wand id_19,
    input wire id_20,
    input tri0 id_21,
    input wand id_22,
    output tri1 id_23,
    output tri0 id_24
    , id_32,
    input wand id_25,
    output tri0 id_26,
    input tri id_27,
    output wire id_28,
    input tri id_29,
    output tri0 id_30
);
endmodule
module module_1 (
    output tri1  id_0,
    input  wor   id_1,
    input  tri   id_2,
    input  tri0  id_3,
    input  uwire id_4
);
  wire id_6;
  module_0(
      id_2,
      id_0,
      id_0,
      id_1,
      id_2,
      id_3,
      id_0,
      id_0,
      id_2,
      id_0,
      id_4,
      id_0,
      id_1,
      id_3,
      id_3,
      id_0,
      id_0,
      id_4,
      id_2,
      id_3,
      id_3,
      id_4,
      id_3,
      id_0,
      id_0,
      id_4,
      id_0,
      id_4,
      id_0,
      id_4,
      id_0
  );
endmodule
