// Seed: 601263078
module module_0 (
    input tri id_0,
    input supply0 id_1,
    input uwire id_2,
    input wire id_3,
    output wire id_4,
    output supply1 id_5,
    output tri1 id_6,
    output supply1 id_7,
    input uwire id_8,
    output uwire id_9,
    input wor id_10,
    input wor id_11,
    output uwire id_12,
    input uwire id_13,
    input tri id_14,
    input tri id_15,
    input wand id_16,
    input wire id_17,
    input tri1 id_18,
    input tri id_19,
    output wand id_20#(1),
    input supply0 id_21,
    input wand id_22,
    input wor id_23,
    output wire id_24,
    input wire id_25,
    input tri0 id_26,
    output supply1 id_27,
    input supply0 id_28,
    input supply1 id_29,
    output tri0 id_30,
    input tri0 id_31,
    input tri1 id_32,
    input tri0 id_33,
    output tri id_34,
    input tri id_35,
    output uwire id_36,
    input uwire id_37,
    input wire id_38,
    input supply1 id_39,
    input supply1 id_40,
    input wor id_41,
    output supply0 id_42,
    input supply1 id_43,
    input wand id_44,
    input supply1 id_45,
    output supply0 id_46
);
endmodule
module module_1 (
    input  tri1 id_0,
    output wor  id_1
    , id_5,
    input  tri  id_2,
    input  wand id_3
);
  wire id_6;
  module_0(
      id_2,
      id_0,
      id_2,
      id_3,
      id_1,
      id_1,
      id_1,
      id_1,
      id_2,
      id_1,
      id_3,
      id_0,
      id_1,
      id_3,
      id_3,
      id_0,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_3,
      id_0,
      id_0,
      id_1,
      id_0,
      id_2,
      id_1,
      id_0,
      id_0,
      id_1,
      id_2,
      id_0,
      id_0,
      id_1,
      id_3,
      id_1,
      id_3,
      id_0,
      id_3,
      id_0,
      id_3,
      id_1,
      id_0,
      id_2,
      id_0,
      id_1
  );
  supply1 id_7 = id_0;
  assign id_1 = 1;
endmodule
