// Seed: 555141050
module module_0 (
    input uwire id_0,
    input wire id_1,
    output tri0 id_2,
    output uwire id_3,
    output uwire id_4,
    input supply1 id_5,
    input tri1 id_6,
    input supply0 id_7,
    input supply0 id_8,
    output tri1 id_9,
    output tri id_10,
    input supply0 id_11,
    output tri id_12,
    output wor id_13,
    input wire id_14,
    input tri id_15,
    input tri1 id_16,
    output tri1 id_17,
    input tri0 id_18,
    input uwire id_19,
    output wor id_20,
    input wor id_21,
    output tri1 id_22,
    output tri1 id_23,
    input wand id_24,
    output uwire id_25,
    input supply0 id_26,
    input tri1 id_27,
    input tri1 id_28,
    output wand id_29,
    input uwire id_30,
    input supply1 id_31,
    input uwire id_32,
    input tri id_33,
    output wand id_34,
    output supply1 id_35
);
endmodule
module module_1 (
    input tri id_0,
    input supply1 id_1,
    output tri id_2,
    output uwire id_3,
    input supply0 id_4,
    input wor id_5,
    input wand id_6,
    output supply1 id_7,
    output supply0 id_8,
    input supply1 id_9
    , id_14, id_15,
    input uwire id_10,
    output wand id_11,
    input tri0 id_12
);
  module_0 modCall_1 (
      id_0,
      id_6,
      id_11,
      id_11,
      id_2,
      id_4,
      id_0,
      id_4,
      id_1,
      id_2,
      id_3,
      id_10,
      id_7,
      id_8,
      id_4,
      id_1,
      id_4,
      id_3,
      id_4,
      id_5,
      id_11,
      id_1,
      id_7,
      id_2,
      id_0,
      id_8,
      id_9,
      id_4,
      id_4,
      id_8,
      id_10,
      id_1,
      id_9,
      id_6,
      id_2,
      id_2
  );
  assign modCall_1.type_19 = 0;
endmodule
