// Seed: 690766979
module module_0 (
    output tri0 id_0,
    input wand id_1,
    input tri1 id_2,
    output wand id_3,
    output supply0 id_4,
    input wor id_5,
    output wor id_6,
    output tri0 id_7,
    output wand id_8,
    input tri1 id_9,
    output wor id_10,
    input wand id_11,
    output supply0 id_12,
    input wor id_13,
    input wor id_14,
    input wire id_15,
    input tri1 id_16,
    output tri1 id_17,
    input tri0 id_18,
    output supply0 id_19,
    input tri id_20,
    output tri0 id_21,
    input supply0 id_22,
    input supply1 id_23,
    input supply0 id_24,
    input supply0 id_25,
    input wand id_26,
    output uwire id_27,
    input supply0 id_28,
    input tri id_29,
    output tri id_30,
    output wor id_31,
    input uwire id_32,
    input wor id_33,
    input uwire id_34,
    input uwire id_35
    , id_40,
    output tri id_36,
    inout supply1 id_37,
    input tri id_38
);
endmodule
module module_1 (
    input wor id_0,
    input wire id_1,
    output tri id_2,
    output wor id_3,
    input supply1 id_4,
    input wor id_5
    , id_13,
    input uwire id_6,
    output wor id_7,
    input wor id_8,
    input wor id_9,
    output tri1 id_10,
    output tri1 id_11
    , id_14
);
  assign id_13 = id_8;
  module_0(
      id_3,
      id_4,
      id_6,
      id_7,
      id_14,
      id_9,
      id_14,
      id_14,
      id_11,
      id_6,
      id_10,
      id_9,
      id_2,
      id_14,
      id_0,
      id_4,
      id_6,
      id_3,
      id_14,
      id_3,
      id_0,
      id_13,
      id_6,
      id_8,
      id_4,
      id_4,
      id_6,
      id_14,
      id_1,
      id_1,
      id_3,
      id_13,
      id_8,
      id_1,
      id_0,
      id_0,
      id_3,
      id_14,
      id_6
  );
endmodule
