// Seed: 3093447625
module module_0 (
    output tri id_0,
    output tri id_1,
    output uwire id_2,
    output tri0 id_3,
    output tri0 id_4,
    output supply1 id_5,
    output supply0 id_6,
    output supply1 id_7,
    input tri1 id_8,
    output uwire id_9,
    output wire id_10,
    input supply1 id_11,
    input supply1 id_12,
    input supply0 id_13,
    input supply0 id_14,
    output wor id_15,
    input wire id_16,
    input supply1 id_17,
    input tri0 id_18,
    input tri0 id_19,
    input wire id_20,
    output wire id_21
);
endmodule
module module_1 (
    input wor id_0,
    output wand id_1
    , id_19,
    output supply1 id_2,
    input wor id_3,
    output uwire id_4,
    input supply1 id_5,
    output tri1 id_6,
    input wor id_7,
    output wor id_8,
    input supply1 id_9,
    input tri0 id_10,
    input wor id_11,
    output tri0 id_12,
    input wire id_13,
    input wire id_14,
    output wire id_15,
    input wire id_16,
    input tri0 id_17
);
  module_0(
      id_4,
      id_6,
      id_6,
      id_4,
      id_1,
      id_6,
      id_4,
      id_4,
      id_9,
      id_2,
      id_8,
      id_17,
      id_13,
      id_10,
      id_11,
      id_1,
      id_16,
      id_7,
      id_11,
      id_14,
      id_14,
      id_12
  );
endmodule
