// Seed: 3761971603
module module_0 (
    input tri1 id_0,
    output supply0 id_1,
    input tri1 id_2,
    input supply1 id_3,
    input wor id_4,
    input wire id_5,
    output uwire id_6,
    input supply0 id_7,
    input wor id_8,
    input wor id_9,
    output supply0 id_10,
    input tri0 id_11,
    input supply0 id_12,
    output wor id_13,
    input uwire id_14,
    input wor id_15,
    input uwire id_16,
    input wire id_17,
    input tri1 id_18,
    input tri0 id_19,
    input tri0 id_20,
    input wire id_21,
    input wand id_22,
    input wire id_23,
    output tri0 id_24,
    input wand id_25,
    input tri1 id_26,
    output tri0 id_27,
    output wand id_28,
    input tri0 id_29,
    input tri id_30,
    input wire id_31,
    input tri id_32,
    output tri0 id_33,
    input uwire id_34,
    input tri0 id_35,
    input wire id_36
    , id_39,
    input uwire id_37
);
  wire id_40;
  assign module_1.id_0 = 0;
endmodule
module module_1 (
    input wand id_0,
    input wor id_1,
    input tri0 id_2,
    output uwire id_3,
    input supply1 id_4,
    output supply0 id_5,
    input wand id_6
);
  wire id_8;
  module_0 modCall_1 (
      id_2,
      id_5,
      id_4,
      id_0,
      id_6,
      id_4,
      id_5,
      id_6,
      id_6,
      id_0,
      id_3,
      id_0,
      id_6,
      id_3,
      id_2,
      id_2,
      id_0,
      id_2,
      id_6,
      id_6,
      id_4,
      id_6,
      id_1,
      id_4,
      id_3,
      id_2,
      id_4,
      id_5,
      id_3,
      id_4,
      id_4,
      id_6,
      id_6,
      id_3,
      id_1,
      id_0,
      id_2,
      id_2
  );
endmodule
