// Seed: 1810023537
module module_0 (
    input wire id_0,
    input wire id_1,
    output tri1 id_2,
    output tri id_3,
    output tri0 id_4,
    output tri id_5,
    input uwire id_6,
    input wor id_7,
    input tri1 id_8,
    input supply1 id_9,
    output wand id_10,
    output tri1 id_11,
    output wand id_12,
    input tri id_13,
    output wand id_14,
    input supply0 id_15,
    input uwire id_16,
    input supply0 id_17,
    output tri id_18,
    input tri1 id_19,
    input supply1 id_20,
    input supply0 id_21,
    input supply0 id_22,
    output supply0 id_23,
    output wand id_24,
    input tri0 id_25,
    input wand id_26,
    input tri0 id_27,
    input wor id_28,
    input wire id_29,
    input supply0 id_30,
    output wand id_31,
    input uwire id_32
);
  uwire id_34 = 1;
  assign module_1.id_8 = 0;
endmodule
module module_1 (
    input supply0 id_0,
    input supply0 id_1,
    input wor id_2,
    output supply0 id_3,
    input wor id_4,
    input wor id_5,
    output uwire id_6,
    input wor id_7,
    output supply1 id_8,
    inout wand id_9
);
  xor primCall (id_9, id_1, id_2, id_4, id_5, id_7, id_0);
  module_0 modCall_1 (
      id_2,
      id_2,
      id_8,
      id_9,
      id_9,
      id_6,
      id_7,
      id_1,
      id_2,
      id_1,
      id_8,
      id_3,
      id_3,
      id_1,
      id_9,
      id_4,
      id_4,
      id_4,
      id_8,
      id_7,
      id_7,
      id_2,
      id_1,
      id_3,
      id_9,
      id_9,
      id_0,
      id_1,
      id_2,
      id_5,
      id_9,
      id_8,
      id_9
  );
endmodule
