// Seed: 2652145991
module module_0 (
    input wand id_0,
    input wand id_1,
    input tri id_2,
    output uwire id_3,
    input supply1 id_4,
    input tri id_5,
    output wire id_6,
    input uwire id_7,
    output tri id_8,
    input wor id_9,
    output wand id_10,
    input tri id_11,
    output supply1 id_12,
    output wor id_13,
    input tri id_14,
    output tri0 id_15,
    inout tri id_16,
    input wire id_17,
    output uwire id_18,
    input tri0 id_19,
    input supply1 id_20,
    output wire id_21,
    output wire id_22,
    input wor id_23,
    input tri0 id_24,
    output tri id_25,
    input tri id_26,
    input wor id_27,
    output uwire id_28,
    input supply0 id_29,
    output wire id_30,
    input tri id_31
);
  assign module_1.id_0 = 0;
endmodule
module module_1 (
    input tri1  id_0,
    input uwire id_1,
    input tri1  id_2,
    input tri   id_3
);
  assign id_5 = id_1;
  module_0 modCall_1 (
      id_3,
      id_3,
      id_5,
      id_5,
      id_3,
      id_1,
      id_5,
      id_5,
      id_5,
      id_5,
      id_5,
      id_1,
      id_5,
      id_5,
      id_3,
      id_5,
      id_5,
      id_3,
      id_5,
      id_0,
      id_5,
      id_5,
      id_5,
      id_3,
      id_5,
      id_5,
      id_0,
      id_1,
      id_5,
      id_2,
      id_5,
      id_0
  );
endmodule
