// Seed: 3009317632
module module_0 (
    input supply0 id_0,
    input supply1 id_1,
    input tri id_2,
    input tri1 id_3
    , id_52,
    output tri1 id_4,
    input wire id_5,
    output wor id_6,
    input tri1 id_7,
    input wor id_8,
    input tri0 id_9,
    output wire id_10,
    input wand id_11,
    output tri0 id_12,
    input tri0 id_13,
    output tri0 id_14,
    input supply0 id_15,
    input tri0 id_16,
    input uwire id_17,
    output wire id_18,
    input wand id_19,
    input tri0 id_20,
    output tri id_21,
    input uwire id_22,
    input tri0 id_23,
    input wor id_24,
    output tri0 id_25,
    output wand id_26,
    input supply0 id_27,
    output wor id_28
    , id_53,
    input tri1 id_29,
    output uwire id_30,
    output wor id_31
    , id_54,
    input tri0 id_32,
    input wor id_33,
    output uwire id_34,
    input uwire id_35,
    input wire id_36,
    output uwire id_37,
    output wand id_38,
    input supply1 id_39,
    output tri1 id_40,
    output wor id_41,
    input wand id_42,
    input tri1 id_43,
    input wand id_44,
    output uwire id_45,
    input tri1 id_46,
    input wire id_47,
    input tri1 id_48,
    input supply1 id_49,
    input tri id_50
);
  assign id_25 = id_20 / id_24;
  id_55(
      id_38, 1
  );
endmodule
module module_1 (
    input  tri   id_0,
    output tri1  id_1,
    output uwire id_2,
    input  wor   id_3,
    input  tri1  id_4,
    input  uwire id_5
);
  assign id_2 = id_3;
  module_0(
      id_3,
      id_0,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_4,
      id_3,
      id_5,
      id_1,
      id_0,
      id_1,
      id_3,
      id_1,
      id_4,
      id_0,
      id_4,
      id_2,
      id_3,
      id_3,
      id_2,
      id_0,
      id_5,
      id_5,
      id_2,
      id_1,
      id_4,
      id_1,
      id_4,
      id_2,
      id_2,
      id_4,
      id_0,
      id_2,
      id_3,
      id_3,
      id_2,
      id_1,
      id_4,
      id_1,
      id_2,
      id_5,
      id_0,
      id_4,
      id_1,
      id_0,
      id_3,
      id_4,
      id_5,
      id_5
  );
endmodule
