// Seed: 2524691300
module module_0 (
    output wand id_0,
    input tri0 id_1,
    input wor id_2,
    output uwire id_3,
    output wire id_4,
    input wire id_5,
    input supply0 id_6,
    output supply1 id_7,
    input supply0 id_8,
    output wire id_9,
    input supply0 id_10,
    output tri1 id_11,
    input uwire id_12,
    output tri1 id_13,
    output wire id_14,
    output tri0 id_15,
    input uwire id_16,
    output tri id_17
    , id_34,
    output tri0 id_18,
    input wor id_19,
    input supply0 id_20,
    input tri id_21,
    input tri id_22,
    output tri0 id_23,
    input uwire id_24,
    output tri1 id_25,
    input tri1 id_26,
    output supply1 id_27,
    input wor id_28,
    input uwire id_29,
    input tri1 id_30,
    input tri id_31,
    input wor id_32
);
endmodule
module module_1 (
    inout  tri1  id_0,
    output uwire id_1
);
  module_0(
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0
  );
endmodule
