// Seed: 1929438882
module module_0 (
    input wor id_0,
    output wire id_1,
    input wand id_2,
    output tri0 id_3,
    input uwire id_4,
    input wire id_5,
    output wand id_6,
    input supply1 id_7,
    output tri0 id_8,
    input wand id_9,
    output tri id_10,
    input wand id_11,
    output wand id_12,
    output tri0 id_13,
    input wire id_14,
    input wor id_15,
    input wand id_16,
    output tri id_17,
    input supply1 id_18,
    input wor id_19,
    input wire id_20,
    input supply1 id_21,
    input supply1 id_22,
    output wand id_23,
    input wor id_24,
    input tri id_25,
    output tri0 id_26,
    input tri id_27
    , id_35,
    output wand id_28,
    input tri id_29,
    input tri0 id_30,
    output tri1 id_31,
    output wor id_32,
    output tri id_33
);
  wire id_36;
endmodule
module module_1 (
    input supply0 id_0,
    input wire id_1,
    output supply1 id_2,
    output wire id_3,
    output tri1 id_4,
    input supply0 id_5,
    inout wire id_6,
    output wor id_7,
    output supply0 id_8,
    output uwire id_9,
    output supply1 id_10,
    output wand id_11,
    input tri1 id_12,
    input uwire id_13,
    input wire id_14,
    output uwire id_15
);
  wire id_17;
  module_0(
      id_6,
      id_11,
      id_13,
      id_11,
      id_1,
      id_5,
      id_8,
      id_12,
      id_2,
      id_13,
      id_9,
      id_14,
      id_10,
      id_2,
      id_1,
      id_12,
      id_13,
      id_7,
      id_5,
      id_0,
      id_12,
      id_14,
      id_14,
      id_6,
      id_0,
      id_0,
      id_11,
      id_6,
      id_11,
      id_1,
      id_1,
      id_4,
      id_15,
      id_11
  );
endmodule
