// Seed: 1598936312
module module_0 (
    input supply0 id_0,
    input supply1 id_1,
    input wor id_2,
    input wire id_3,
    input wand id_4,
    input tri id_5,
    output uwire id_6,
    input uwire id_7,
    output wand id_8,
    input supply1 id_9,
    input supply0 id_10,
    input supply1 id_11,
    input tri id_12,
    output wor id_13,
    output tri1 id_14,
    input tri id_15,
    input wand id_16,
    output supply1 id_17,
    output wor id_18,
    input wor id_19,
    output uwire id_20,
    output uwire id_21,
    input uwire id_22,
    output supply0 id_23,
    output tri id_24,
    input tri id_25,
    input supply1 id_26,
    output wire id_27,
    input wire id_28,
    output tri1 id_29,
    input supply1 id_30,
    input tri1 id_31,
    input tri id_32,
    output wand id_33,
    input supply0 id_34,
    input wand id_35,
    input wor id_36,
    input wire id_37,
    input wire id_38
);
  wire id_40;
  assign id_24 = id_22;
  assign id_18 = id_37 - 1'h0;
  assign module_1.type_1 = 0;
  wire id_41;
endmodule
module module_1 (
    input supply1 id_0,
    input supply1 id_1,
    input wire id_2,
    input uwire id_3,
    input uwire id_4,
    output tri id_5
);
  nand primCall (id_5, id_0, id_1, id_2, id_4, id_3);
  module_0 modCall_1 (
      id_2,
      id_0,
      id_2,
      id_1,
      id_0,
      id_3,
      id_5,
      id_4,
      id_5,
      id_1,
      id_4,
      id_1,
      id_1,
      id_5,
      id_5,
      id_4,
      id_0,
      id_5,
      id_5,
      id_3,
      id_5,
      id_5,
      id_0,
      id_5,
      id_5,
      id_0,
      id_1,
      id_5,
      id_4,
      id_5,
      id_2,
      id_4,
      id_4,
      id_5,
      id_2,
      id_3,
      id_3,
      id_3,
      id_0
  );
endmodule
