// Seed: 1352836192
module module_0 (
    output uwire id_0,
    input wor id_1,
    input uwire id_2,
    output supply1 id_3,
    input tri id_4,
    output tri1 id_5,
    output tri id_6,
    input wire id_7,
    input tri id_8,
    input wor id_9,
    input tri id_10,
    input tri id_11,
    output supply0 id_12,
    input uwire id_13,
    input wand id_14,
    input supply0 id_15,
    output supply0 id_16,
    input supply1 id_17,
    input uwire id_18,
    output tri1 id_19,
    output uwire id_20,
    output tri0 id_21
    , id_34,
    output tri1 id_22,
    input tri0 id_23,
    input tri0 id_24,
    input supply1 id_25,
    output tri0 id_26,
    output tri0 id_27,
    output wand id_28,
    input wand id_29,
    output tri0 id_30,
    output wire id_31,
    input supply0 id_32
);
endmodule
module module_1 (
    output supply0 id_0,
    input wor id_1,
    output tri0 id_2,
    input tri id_3,
    input tri id_4,
    input tri0 id_5,
    input uwire id_6,
    input tri1 id_7
);
  assign id_0 = 1;
  module_0(
      id_2,
      id_5,
      id_5,
      id_0,
      id_6,
      id_2,
      id_0,
      id_6,
      id_3,
      id_3,
      id_3,
      id_7,
      id_2,
      id_3,
      id_3,
      id_5,
      id_0,
      id_7,
      id_3,
      id_0,
      id_0,
      id_0,
      id_0,
      id_4,
      id_7,
      id_7,
      id_2,
      id_2,
      id_0,
      id_4,
      id_2,
      id_0,
      id_3
  );
endmodule
