// Seed: 2189968115
module module_0 (
    input tri0 id_0,
    output tri0 id_1,
    input wand id_2,
    input wand id_3,
    output tri0 id_4,
    input wire id_5,
    input supply0 id_6,
    input uwire id_7,
    output supply1 id_8,
    input tri0 id_9,
    input tri0 id_10,
    output tri1 id_11,
    output tri0 id_12,
    input uwire id_13,
    output tri1 id_14,
    output wire id_15,
    output tri id_16,
    input tri1 id_17,
    output uwire id_18,
    output wire id_19,
    input wand id_20,
    input tri0 id_21,
    input wor id_22,
    input wand id_23,
    output uwire id_24,
    input supply1 id_25,
    input supply0 id_26,
    output wand id_27,
    input wire id_28,
    output supply0 id_29,
    input tri1 id_30
);
  wire id_32;
  assign module_1.id_5 = 0;
endmodule
module module_1 (
    input tri id_0
    , id_13,
    output wand id_1,
    input supply1 id_2,
    output tri1 id_3,
    input wor id_4,
    inout tri id_5,
    input supply1 id_6,
    input supply0 id_7,
    output wand id_8,
    output wire id_9,
    input wand id_10,
    input tri id_11
);
  module_0 modCall_1 (
      id_11,
      id_5,
      id_6,
      id_5,
      id_8,
      id_4,
      id_7,
      id_10,
      id_3,
      id_5,
      id_5,
      id_1,
      id_3,
      id_5,
      id_8,
      id_1,
      id_1,
      id_7,
      id_8,
      id_9,
      id_6,
      id_11,
      id_0,
      id_10,
      id_9,
      id_7,
      id_7,
      id_9,
      id_0,
      id_5,
      id_4
  );
endmodule
