// Seed: 130149523
module module_0 (
    output wire id_0,
    input wor id_1,
    input uwire id_2,
    input wire id_3,
    output uwire id_4,
    input supply0 id_5,
    output uwire id_6,
    input wand id_7,
    input tri id_8,
    input wor id_9,
    output wor id_10,
    input uwire id_11,
    input tri0 id_12,
    input wor id_13,
    input wire id_14,
    input uwire id_15,
    output tri0 id_16,
    input supply1 id_17,
    output uwire id_18,
    input supply1 id_19,
    output tri0 id_20,
    input wire id_21,
    input tri id_22
);
endmodule
module module_1 (
    input wand id_0
    , id_19,
    input tri0 id_1,
    output supply0 id_2,
    output wor id_3,
    input wor id_4,
    input tri0 id_5,
    input supply0 id_6,
    output tri id_7,
    input tri0 id_8,
    input wand id_9,
    input tri1 id_10,
    output tri1 id_11,
    input wor id_12,
    input wand id_13
    , id_20,
    input wand id_14,
    input supply0 id_15,
    input wor id_16,
    input tri0 id_17
);
  module_0 modCall_1 (
      id_2,
      id_1,
      id_6,
      id_4,
      id_3,
      id_6,
      id_3,
      id_9,
      id_15,
      id_9,
      id_2,
      id_5,
      id_10,
      id_12,
      id_16,
      id_0,
      id_2,
      id_6,
      id_7,
      id_14,
      id_2,
      id_5,
      id_6
  );
endmodule
