// Seed: 2610808232
module module_0 (
    input wor id_0,
    input tri0 id_1,
    input uwire id_2,
    output wire id_3,
    input tri0 id_4,
    input wire module_0,
    output wor id_6,
    input wire id_7,
    output tri0 id_8,
    input supply1 id_9,
    input tri id_10,
    output tri0 id_11,
    output tri id_12,
    output wor id_13,
    input tri0 id_14,
    output tri0 id_15,
    input tri0 id_16,
    input wand id_17,
    input tri1 id_18,
    input tri1 id_19
    , id_36,
    output supply0 id_20,
    output wand id_21,
    output wand id_22,
    output supply1 id_23,
    output tri0 id_24,
    output uwire id_25,
    output wand id_26,
    input wand id_27,
    input tri id_28,
    output tri0 id_29,
    input wire id_30,
    output wor id_31,
    output wor id_32,
    input tri1 id_33,
    input tri0 id_34
);
endmodule
module module_1 (
    output uwire id_0,
    inout  wor   id_1,
    output tri   id_2,
    input  tri0  id_3,
    input  tri   id_4
);
  wire id_6, id_7;
  module_0 modCall_1 (
      id_3,
      id_1,
      id_4,
      id_2,
      id_3,
      id_3,
      id_1,
      id_1,
      id_2,
      id_4,
      id_3,
      id_2,
      id_2,
      id_0,
      id_1,
      id_1,
      id_1,
      id_3,
      id_3,
      id_3,
      id_1,
      id_0,
      id_2,
      id_2,
      id_2,
      id_2,
      id_0,
      id_4,
      id_4,
      id_1,
      id_3,
      id_1,
      id_0,
      id_3,
      id_1
  );
  assign modCall_1.id_27 = 0;
endmodule
