// Seed: 2082061259
module module_0 (
    input tri id_0,
    input wor id_1,
    output uwire id_2,
    input wor id_3,
    output wor id_4,
    output tri id_5,
    input wor id_6,
    output tri module_0,
    input wand id_8,
    input supply1 id_9,
    output uwire id_10,
    output wor id_11,
    input wire id_12,
    input tri1 id_13,
    output uwire id_14,
    output tri0 id_15,
    input wire id_16,
    input wor id_17,
    input uwire id_18,
    input supply0 id_19,
    input uwire id_20,
    input uwire id_21,
    input wand id_22,
    input wand id_23,
    input wor id_24,
    input uwire id_25
);
endmodule
module module_1 (
    output wor id_0,
    input wand id_1,
    input wand id_2,
    output supply0 id_3,
    input supply1 id_4,
    input uwire id_5,
    input wire id_6,
    output tri0 id_7,
    input wand id_8,
    output uwire id_9,
    input wire id_10,
    input tri0 id_11,
    input wire id_12,
    output tri1 id_13,
    output tri1 id_14,
    input wire id_15,
    input wor id_16,
    input tri0 id_17,
    input supply1 id_18
);
  assign id_3 = 1 + "";
  module_0 modCall_1 (
      id_4,
      id_10,
      id_7,
      id_5,
      id_0,
      id_3,
      id_4,
      id_9,
      id_2,
      id_2,
      id_14,
      id_13,
      id_18,
      id_6,
      id_0,
      id_9,
      id_16,
      id_12,
      id_11,
      id_8,
      id_8,
      id_16,
      id_10,
      id_12,
      id_2,
      id_15
  );
  assign modCall_1.id_18 = 0;
endmodule
