// Seed: 1334481201
module module_0 (
    output tri0 id_0,
    output wire id_1,
    output wire id_2,
    input supply0 id_3,
    input tri1 id_4,
    input wand id_5,
    output uwire id_6
    , id_34,
    output tri0 id_7,
    output wire id_8,
    output wire id_9,
    output tri0 id_10,
    output wor id_11,
    input tri0 id_12,
    input supply1 id_13,
    input wor id_14,
    input supply1 id_15,
    output wand id_16,
    output wor id_17,
    input wor id_18,
    input supply1 id_19,
    input wire id_20,
    input wor id_21
    , id_35,
    output supply0 id_22,
    input supply0 id_23,
    input supply1 id_24,
    output supply1 id_25,
    input wire id_26,
    input uwire id_27,
    input uwire module_0,
    output tri id_29,
    output tri id_30,
    input tri0 id_31,
    input tri1 id_32
    , id_36
);
endmodule
module module_1 (
    input uwire id_0,
    input wor id_1,
    output wor id_2,
    input tri1 id_3,
    input wand id_4,
    input supply0 id_5,
    input wor id_6,
    input wire id_7,
    input wor id_8
);
  wire id_10;
  module_0(
      id_2,
      id_2,
      id_2,
      id_8,
      id_4,
      id_5,
      id_2,
      id_2,
      id_2,
      id_2,
      id_2,
      id_2,
      id_5,
      id_1,
      id_8,
      id_3,
      id_2,
      id_2,
      id_3,
      id_6,
      id_6,
      id_0,
      id_2,
      id_0,
      id_8,
      id_2,
      id_0,
      id_1,
      id_5,
      id_2,
      id_2,
      id_0,
      id_8
  );
endmodule
