// Seed: 129513795
module module_0 (
    output supply1 id_0,
    input tri1 id_1,
    output wor id_2,
    output supply1 id_3,
    input tri1 id_4,
    output tri1 id_5,
    input tri id_6,
    input supply0 id_7,
    output uwire module_0,
    output tri id_9,
    output tri1 id_10,
    input supply0 id_11,
    input wand id_12,
    output uwire id_13,
    input supply0 id_14,
    input wire id_15,
    output tri0 id_16,
    input tri id_17,
    input tri1 id_18,
    output tri0 id_19,
    input supply1 id_20,
    output tri1 id_21,
    output supply0 id_22,
    input wor id_23,
    output wor id_24,
    input supply0 id_25,
    output wor id_26,
    output wor id_27,
    output wire id_28,
    input tri0 id_29,
    output wand id_30
);
  assign module_1.id_6 = 0;
endmodule
module module_1 (
    output tri id_0,
    input tri0 id_1,
    input supply1 id_2,
    input tri id_3,
    input supply0 id_4,
    output wand id_5,
    input tri0 id_6,
    output uwire id_7
);
  parameter id_9 = 1;
  module_0 modCall_1 (
      id_0,
      id_1,
      id_0,
      id_0,
      id_3,
      id_5,
      id_6,
      id_1,
      id_0,
      id_0,
      id_5,
      id_4,
      id_2,
      id_0,
      id_3,
      id_1,
      id_7,
      id_4,
      id_1,
      id_5,
      id_2,
      id_7,
      id_7,
      id_2,
      id_0,
      id_2,
      id_5,
      id_5,
      id_5,
      id_1,
      id_5
  );
  wire id_10;
endmodule
