// Seed: 1449303354
module module_0 (
    input supply0 id_0,
    input tri1 id_1,
    input tri1 id_2,
    input wor id_3,
    output wire id_4,
    input supply0 id_5,
    output wand id_6,
    input wire id_7,
    input uwire id_8,
    output uwire id_9,
    output tri1 id_10,
    output uwire id_11,
    input wor id_12,
    input supply0 id_13,
    input tri1 id_14,
    input tri id_15,
    input wand id_16,
    input supply0 id_17,
    input wire id_18,
    output wor id_19,
    input uwire id_20,
    output uwire id_21,
    input wand id_22,
    output tri0 id_23,
    input wire id_24,
    output wor id_25,
    input uwire id_26,
    output tri id_27,
    output wire id_28,
    input wor id_29
);
  assign id_6 = -1;
  assign module_1.id_20 = 0;
endmodule
module module_0 (
    input tri id_0,
    input tri1 id_1,
    input wand id_2,
    input supply0 id_3,
    input tri1 id_4,
    output tri id_5,
    output supply0 id_6,
    input tri0 id_7,
    output wor id_8,
    input supply0 id_9
    , id_24,
    output tri id_10,
    output supply1 id_11,
    input wire sample,
    input tri id_13,
    output uwire module_1,
    input tri0 id_15,
    input wand id_16,
    output tri id_17,
    input supply1 id_18,
    input supply1 id_19,
    input uwire id_20,
    inout uwire id_21,
    output uwire id_22
);
  wire id_25;
  module_0 modCall_1 (
      id_0,
      id_0,
      id_20,
      id_13,
      id_11,
      id_0,
      id_22,
      id_20,
      id_20,
      id_22,
      id_11,
      id_8,
      id_7,
      id_16,
      id_7,
      id_0,
      id_19,
      id_2,
      id_4,
      id_8,
      id_7,
      id_21,
      id_1,
      id_21,
      id_4,
      id_6,
      id_18,
      id_8,
      id_22,
      id_1
  );
endmodule
