// Seed: 109780610
module module_0 (
    input tri id_0,
    output tri0 id_1,
    output uwire id_2,
    input wand id_3,
    input tri0 id_4,
    output supply1 id_5,
    output wand id_6,
    input wire id_7,
    input wor id_8,
    input wor id_9,
    output tri1 id_10,
    input tri0 id_11,
    input supply1 id_12,
    input wand id_13,
    input tri1 id_14,
    output tri id_15,
    output uwire id_16,
    output wand id_17,
    output supply0 id_18,
    input tri1 id_19,
    input wire id_20,
    input wor id_21
    , id_42,
    input wire id_22,
    input tri0 id_23,
    output wire id_24,
    input tri0 id_25,
    output tri1 sample,
    input wor id_27,
    input tri0 id_28,
    input uwire id_29,
    input supply1 id_30,
    input tri id_31,
    input tri0 id_32,
    input tri sample,
    output wor module_0,
    input tri0 id_35,
    output tri0 id_36,
    input wand id_37,
    output tri0 id_38,
    input wand id_39,
    input uwire id_40
);
  assign id_26 = -1;
  wand id_43 = ~id_13 ==? 1;
endmodule
module module_1 (
    output tri  id_0,
    output wand id_1,
    input  tri0 id_2,
    input  tri0 id_3
);
  wire id_5;
  module_0 modCall_1 (
      id_3,
      id_0,
      id_0,
      id_3,
      id_3,
      id_1,
      id_0,
      id_2,
      id_3,
      id_2,
      id_1,
      id_2,
      id_3,
      id_3,
      id_3,
      id_0,
      id_1,
      id_1,
      id_0,
      id_2,
      id_2,
      id_3,
      id_2,
      id_3,
      id_1,
      id_2,
      id_0,
      id_2,
      id_3,
      id_2,
      id_3,
      id_2,
      id_2,
      id_2,
      id_1,
      id_2,
      id_0,
      id_2,
      id_1,
      id_2,
      id_3
  );
  assign modCall_1.id_36 = 0;
endmodule
