// Seed: 259780225
module module_0 (
    input tri id_0,
    input wor id_1,
    input wor id_2,
    input supply1 id_3,
    output tri1 id_4,
    input tri1 id_5,
    input tri1 id_6,
    input uwire id_7,
    output tri1 id_8,
    input uwire id_9,
    output tri id_10,
    input tri id_11,
    input wor id_12,
    input tri0 id_13,
    input tri id_14,
    output tri1 id_15,
    input tri1 id_16,
    input wire id_17,
    input tri0 id_18
    , id_43,
    input tri id_19,
    input tri id_20,
    output supply0 id_21,
    input wor id_22,
    output tri0 id_23,
    input supply1 id_24,
    input supply0 id_25,
    input wire id_26,
    input wire id_27,
    input uwire id_28,
    output supply0 id_29,
    output wand id_30,
    input tri0 id_31,
    input wor id_32,
    input wire id_33,
    input supply0 id_34,
    input tri1 id_35,
    input uwire id_36,
    output uwire id_37,
    output tri1 id_38,
    input wire id_39,
    input wor id_40,
    output wor id_41
);
  id_44 :
  assert property (@(posedge 1) 1'h0)
  else $display(1, 1, 1'b0, 1);
  assign module_1.id_5 = 0;
endmodule
module module_1 (
    input uwire id_0,
    output supply1 id_1,
    input tri1 id_2,
    output wand id_3,
    input tri0 id_4,
    input uwire id_5,
    input wire id_6
);
  module_0 modCall_1 (
      id_0,
      id_5,
      id_6,
      id_2,
      id_3,
      id_0,
      id_5,
      id_0,
      id_1,
      id_5,
      id_3,
      id_2,
      id_6,
      id_0,
      id_2,
      id_1,
      id_2,
      id_5,
      id_2,
      id_6,
      id_5,
      id_3,
      id_2,
      id_3,
      id_2,
      id_2,
      id_5,
      id_4,
      id_4,
      id_1,
      id_3,
      id_0,
      id_0,
      id_2,
      id_6,
      id_5,
      id_4,
      id_1,
      id_3,
      id_2,
      id_0,
      id_1
  );
  wire id_8;
  wire id_9;
endmodule
