// Seed: 461512631
module module_0 (
    output wire id_0,
    input tri0 id_1,
    output supply0 id_2,
    input wire id_3,
    input wire id_4,
    input tri0 id_5,
    output wor id_6,
    input tri0 id_7,
    input wire id_8,
    output tri1 id_9,
    input wand id_10,
    output uwire id_11,
    input tri0 id_12,
    output wor id_13,
    output supply1 id_14,
    input wire id_15
    , id_39,
    input wor id_16,
    input supply0 id_17,
    input supply1 id_18,
    output wor id_19,
    output supply1 id_20,
    input wand id_21,
    input wor id_22,
    input wor id_23,
    input uwire id_24,
    output supply1 id_25,
    input tri1 id_26,
    output wor id_27,
    output tri0 id_28,
    output uwire id_29,
    output tri id_30,
    input wor id_31,
    input wor id_32,
    input uwire id_33,
    input wire id_34,
    output tri id_35,
    output tri id_36,
    input wand id_37
);
  wire id_40;
  assign module_1.type_0 = 0;
  wire id_41;
endmodule
module module_0 (
    input tri1 id_0,
    input uwire id_1,
    input supply1 id_2,
    output supply1 id_3,
    input tri1 module_1,
    output wor id_5,
    input tri id_6,
    input tri1 id_7,
    input tri1 id_8,
    input tri1 id_9,
    output tri id_10,
    output supply0 id_11,
    input tri0 id_12
);
  module_0 modCall_1 (
      id_10,
      id_0,
      id_3,
      id_8,
      id_6,
      id_7,
      id_5,
      id_7,
      id_1,
      id_11,
      id_0,
      id_10,
      id_1,
      id_11,
      id_10,
      id_0,
      id_6,
      id_8,
      id_8,
      id_10,
      id_10,
      id_0,
      id_12,
      id_1,
      id_7,
      id_5,
      id_1,
      id_5,
      id_11,
      id_11,
      id_11,
      id_6,
      id_6,
      id_8,
      id_9,
      id_3,
      id_5,
      id_2
  );
endmodule
