// Seed: 3748465551
module module_0 (
    input wire id_0,
    input supply0 id_1,
    input supply0 id_2,
    input supply1 id_3,
    input uwire id_4,
    output supply1 id_5,
    input wand id_6,
    input tri1 id_7,
    input wire id_8,
    output tri1 id_9,
    input supply0 id_10,
    input wire module_0,
    input wor id_12,
    input wire id_13,
    output tri id_14,
    output supply1 id_15,
    input wand id_16,
    input tri0 id_17,
    input uwire id_18,
    input wire id_19,
    input uwire id_20,
    output wand id_21,
    output wor id_22,
    input uwire id_23,
    input tri id_24,
    output wand id_25,
    input wor id_26
);
  assign id_5 = id_17;
  assign module_1.id_12 = 0;
endmodule
module module_1 (
    output supply1 id_0,
    input tri0 id_1,
    output tri0 id_2,
    output supply0 id_3,
    input supply1 id_4,
    output wor id_5,
    input tri1 id_6,
    input tri id_7,
    input tri1 id_8,
    output tri0 id_9,
    input uwire id_10,
    input tri1 id_11,
    input tri0 id_12,
    output wire id_13,
    output wire id_14
);
  module_0 modCall_1 (
      id_8,
      id_11,
      id_4,
      id_4,
      id_4,
      id_2,
      id_7,
      id_4,
      id_1,
      id_5,
      id_1,
      id_7,
      id_7,
      id_12,
      id_2,
      id_14,
      id_4,
      id_12,
      id_4,
      id_7,
      id_10,
      id_2,
      id_0,
      id_12,
      id_8,
      id_9,
      id_11
  );
  assign id_0 = (1);
endmodule
