// Seed: 2759531852
module module_0 (
    input supply0 id_0,
    output wand id_1,
    input uwire id_2,
    input supply1 id_3,
    output supply1 id_4,
    input wand id_5,
    input supply0 id_6,
    input supply0 id_7,
    output wor id_8,
    input tri0 id_9,
    output supply1 id_10,
    output wand id_11,
    input wor id_12,
    output supply0 id_13,
    input tri id_14,
    input wire id_15,
    input wand id_16,
    input tri0 id_17,
    output tri id_18,
    output wor id_19,
    input uwire id_20,
    output uwire id_21,
    output wire id_22,
    output uwire id_23,
    input tri0 id_24,
    output tri0 id_25,
    output supply0 id_26,
    output supply0 id_27,
    input supply0 id_28
    , id_48,
    output wor id_29,
    input tri id_30,
    output supply1 id_31,
    output tri0 id_32,
    input uwire id_33,
    input wor id_34,
    input wor id_35,
    output supply1 id_36,
    input tri1 id_37,
    output wire id_38,
    output wor id_39,
    output wire id_40,
    output supply1 id_41,
    output supply0 id_42,
    input tri0 id_43,
    input supply0 id_44,
    input wand id_45,
    input tri0 id_46
);
  wire id_49;
endmodule
module module_1 (
    input tri0 id_0,
    output supply1 id_1,
    input tri0 id_2,
    input tri0 id_3,
    input wand id_4,
    output wand id_5,
    input tri0 id_6
);
  wire id_8;
  module_0(
      id_2,
      id_5,
      id_4,
      id_0,
      id_1,
      id_4,
      id_6,
      id_6,
      id_5,
      id_3,
      id_1,
      id_5,
      id_6,
      id_1,
      id_2,
      id_2,
      id_0,
      id_3,
      id_5,
      id_5,
      id_4,
      id_5,
      id_1,
      id_1,
      id_0,
      id_1,
      id_5,
      id_1,
      id_0,
      id_1,
      id_4,
      id_1,
      id_1,
      id_4,
      id_6,
      id_0,
      id_5,
      id_2,
      id_5,
      id_5,
      id_5,
      id_1,
      id_5,
      id_4,
      id_2,
      id_3,
      id_2
  );
endmodule
