// Seed: 1487195893
module module_0 (
    output supply1 id_0,
    input supply0 id_1,
    output wor id_2,
    output wand id_3,
    input supply1 id_4,
    input wire id_5,
    output wand id_6,
    input supply0 id_7,
    output supply1 id_8,
    output tri id_9,
    output wor id_10,
    input tri1 id_11,
    output tri id_12,
    input wand id_13,
    input supply1 id_14,
    output wand id_15,
    input tri id_16,
    output uwire id_17,
    input uwire id_18,
    output wor id_19,
    input wor id_20,
    output uwire id_21,
    input uwire id_22,
    output uwire id_23,
    input supply0 id_24,
    input tri id_25,
    output tri id_26,
    output supply1 id_27,
    input wire id_28,
    input wire id_29,
    input tri1 id_30,
    output supply1 id_31,
    input tri1 id_32,
    input tri id_33,
    input wand id_34,
    output supply0 id_35,
    input wand id_36,
    output wor id_37
);
  wire id_39;
  id_40(
      .id_0(id_26), .id_1(1), .id_2(1'd0), .id_3(id_13), .id_4(1)
  );
endmodule
module module_1 (
    output supply0 id_0,
    input wire id_1,
    output supply1 id_2,
    input wire id_3,
    input tri1 id_4,
    input supply0 id_5,
    input wire id_6,
    input wor id_7,
    input supply0 id_8,
    input uwire id_9
);
  wire id_11;
  module_0(
      id_2,
      id_7,
      id_0,
      id_2,
      id_7,
      id_1,
      id_0,
      id_8,
      id_0,
      id_0,
      id_2,
      id_8,
      id_0,
      id_3,
      id_4,
      id_0,
      id_3,
      id_0,
      id_4,
      id_2,
      id_3,
      id_2,
      id_9,
      id_0,
      id_6,
      id_6,
      id_2,
      id_0,
      id_3,
      id_5,
      id_3,
      id_0,
      id_6,
      id_5,
      id_3,
      id_2,
      id_6,
      id_2
  );
endmodule
