// Seed: 2726010843
module module_0 (
    input wand id_0,
    input wor id_1,
    input tri0 id_2,
    output wand id_3,
    input supply0 id_4,
    input tri1 id_5,
    output wor id_6,
    input supply0 id_7,
    input uwire id_8,
    output wor id_9,
    input uwire id_10,
    input wor id_11,
    output supply1 id_12,
    input wor id_13,
    input wor id_14,
    output wire id_15,
    input tri id_16,
    output wor id_17,
    output supply1 id_18,
    input wire id_19,
    output supply1 id_20,
    output supply0 id_21,
    input tri1 id_22,
    output uwire id_23,
    input wire id_24,
    input wand id_25,
    input supply1 id_26,
    input wand id_27,
    output tri id_28,
    output uwire id_29,
    output supply1 id_30,
    output uwire id_31,
    output wand id_32,
    output tri1 id_33,
    input tri1 id_34,
    output supply0 id_35,
    output uwire id_36,
    input wand id_37,
    output tri1 id_38,
    input tri1 id_39,
    input wor id_40
);
  wor id_42, id_43 = id_7;
endmodule
module module_1 (
    inout supply1 id_0,
    input wand id_1,
    output uwire id_2,
    output wire id_3,
    output wand id_4,
    output supply0 id_5
    , id_18, id_19,
    input supply1 id_6,
    input wor id_7,
    input uwire id_8,
    input wire id_9,
    output wand id_10,
    output tri0 id_11,
    input supply1 id_12,
    output supply1 id_13,
    input wire id_14,
    input supply1 id_15,
    input tri id_16
);
  initial id_10 = 1;
  module_0(
      id_0,
      id_6,
      id_6,
      id_5,
      id_1,
      id_6,
      id_4,
      id_9,
      id_15,
      id_3,
      id_14,
      id_15,
      id_13,
      id_6,
      id_6,
      id_10,
      id_16,
      id_11,
      id_11,
      id_8,
      id_3,
      id_3,
      id_12,
      id_5,
      id_0,
      id_9,
      id_16,
      id_0,
      id_0,
      id_10,
      id_5,
      id_2,
      id_3,
      id_3,
      id_12,
      id_2,
      id_0,
      id_15,
      id_13,
      id_1,
      id_7
  );
endmodule
