// Seed: 601105169
module module_0 (
    output tri id_0,
    output tri1 id_1,
    input tri1 id_2,
    output supply1 id_3,
    input tri1 id_4,
    input uwire id_5,
    input supply1 id_6,
    output supply0 id_7,
    output wand id_8,
    input uwire id_9,
    input supply0 id_10,
    input wire id_11,
    input wor id_12,
    output tri0 id_13,
    input tri id_14,
    output wand id_15,
    output tri0 id_16,
    input tri1 id_17,
    input tri1 id_18,
    input tri id_19,
    input supply0 id_20,
    output tri0 id_21,
    output supply1 id_22,
    input tri1 id_23,
    output supply0 id_24,
    output wor id_25,
    output wor id_26,
    input supply0 id_27,
    input wor id_28,
    input wor id_29
);
  wire id_31 = id_29;
  assign id_26 = 1;
endmodule
module module_0 (
    input supply0 id_0,
    input supply1 id_1,
    input wand id_2,
    output wor id_3,
    output tri1 id_4,
    output tri id_5,
    input wand id_6,
    input supply1 id_7,
    input tri id_8,
    input supply1 id_9,
    input supply0 id_10,
    input wor id_11,
    output wire id_12,
    output wand id_13,
    input tri id_14,
    input uwire id_15,
    output uwire id_16,
    input wor id_17,
    input supply1 id_18,
    output wand id_19,
    input wire module_1,
    input wand id_21
);
  assign id_19 = $display;
  module_0 modCall_1 (
      id_19,
      id_13,
      id_7,
      id_5,
      id_0,
      id_18,
      id_14,
      id_12,
      id_3,
      id_2,
      id_14,
      id_15,
      id_9,
      id_4,
      id_0,
      id_3,
      id_12,
      id_7,
      id_1,
      id_8,
      id_8,
      id_3,
      id_5,
      id_6,
      id_4,
      id_5,
      id_3,
      id_6,
      id_8,
      id_7
  );
  assign modCall_1.type_15 = 0;
endmodule
