// Seed: 3295484329
module module_0 (
    input supply1 id_0,
    output tri id_1,
    output supply1 id_2,
    output tri id_3,
    input uwire id_4,
    output tri0 id_5,
    input wand id_6,
    output tri0 id_7
    , id_41,
    output supply0 id_8,
    output wor id_9,
    output wire id_10,
    input supply0 id_11,
    input wor id_12,
    output tri0 id_13,
    output tri1 id_14,
    input tri0 id_15,
    output wire id_16,
    output supply0 id_17,
    input wand id_18,
    output wire id_19,
    output wor id_20,
    output tri0 id_21,
    output supply1 id_22,
    input tri1 id_23,
    input uwire id_24,
    input tri id_25,
    input tri0 id_26,
    input tri id_27,
    input wire id_28,
    output tri0 id_29,
    input tri1 id_30,
    input wire id_31,
    input wand id_32,
    output tri id_33,
    input tri id_34,
    output wire id_35,
    output uwire id_36,
    input wor id_37,
    input wor id_38,
    input wor id_39
);
  assign id_35 = id_0 == id_25;
  assign module_1.type_0 = 0;
endmodule
module module_1 (
    input  wor  id_0,
    output tri1 id_1
);
  wire id_3;
  module_0 modCall_1 (
      id_0,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0
  );
endmodule
