// Seed: 3217890065
module module_0 (
    output supply1 id_0,
    output tri id_1
    , id_43,
    output supply0 id_2,
    output wor id_3,
    input tri0 id_4,
    output wor id_5,
    input supply0 id_6,
    input wor id_7,
    input tri id_8,
    input uwire id_9,
    input tri0 id_10,
    output wand id_11,
    output tri0 id_12,
    input wand id_13,
    input wire id_14,
    input wor id_15,
    output supply1 id_16,
    input tri1 id_17,
    output tri0 id_18,
    output wire id_19,
    input supply0 id_20,
    input tri1 id_21,
    output wand id_22,
    output supply1 id_23,
    input tri1 id_24,
    output wor id_25,
    input supply1 id_26,
    input supply0 id_27,
    input tri0 id_28,
    input supply1 id_29,
    input tri0 id_30,
    output tri id_31,
    output tri1 id_32,
    output tri0 id_33,
    input uwire id_34,
    output tri1 id_35,
    output tri0 id_36,
    input wire id_37,
    input wire id_38,
    output wire id_39,
    output tri0 id_40,
    input supply1 id_41
);
  id_44();
  assign id_32 = 1 == id_20;
  wire id_45;
endmodule
module module_1 (
    input  wand id_0,
    input  tri0 id_1,
    output wire id_2
);
  wire id_4;
  module_0 modCall_1 (
      id_2,
      id_2,
      id_2,
      id_2,
      id_1,
      id_2,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_2,
      id_2,
      id_1,
      id_0,
      id_0,
      id_2,
      id_0,
      id_2,
      id_2,
      id_0,
      id_1,
      id_2,
      id_2,
      id_0,
      id_2,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_2,
      id_2,
      id_2,
      id_0,
      id_2,
      id_2,
      id_0,
      id_0,
      id_2,
      id_2,
      id_1
  );
  assign modCall_1.type_18 = 0;
endmodule
