// Seed: 2099452077
module module_0 (
    input supply0 id_0,
    input tri id_1,
    output tri0 id_2,
    input tri1 id_3,
    input wire id_4,
    input tri1 id_5,
    input tri0 id_6,
    input tri id_7,
    input wand id_8,
    input uwire id_9,
    output wire id_10,
    output wand id_11,
    input wand id_12,
    input uwire module_0,
    input wor id_14,
    input wand id_15,
    output supply1 id_16,
    input supply1 id_17,
    input wor id_18,
    input tri id_19,
    input uwire id_20,
    input supply0 id_21,
    output wand id_22,
    input tri0 id_23,
    input wand id_24,
    input tri id_25,
    input wire id_26,
    input uwire id_27,
    output tri0 id_28,
    input uwire id_29,
    output wor id_30,
    input tri id_31
);
endmodule
module module_1 (
    input wire id_0,
    input wand id_1,
    output supply1 id_2,
    input supply1 id_3,
    output tri id_4,
    input supply1 id_5,
    output supply1 id_6,
    output wand id_7,
    input tri0 id_8,
    input wire id_9
);
  wire  id_11  ,  id_12  ,  id_13  ,  id_14  ,  id_15  ,  id_16  ,  id_17  ,  id_18  ,  id_19  ,  id_20  ,  id_21  ,  id_22  ,  id_23  ,  id_24  ,  id_25  ,  id_26  ;
  module_0 modCall_1 (
      id_5,
      id_8,
      id_4,
      id_9,
      id_8,
      id_3,
      id_0,
      id_8,
      id_1,
      id_0,
      id_6,
      id_7,
      id_8,
      id_5,
      id_0,
      id_3,
      id_2,
      id_5,
      id_1,
      id_3,
      id_0,
      id_3,
      id_4,
      id_1,
      id_1,
      id_5,
      id_9,
      id_8,
      id_2,
      id_8,
      id_4,
      id_0
  );
endmodule
