// Seed: 2191232973
module module_0 (
    output wand id_0,
    input tri1 id_1,
    output tri1 id_2,
    output wand id_3,
    input wire id_4,
    output wor id_5,
    input supply0 id_6,
    output wand id_7,
    output wand id_8,
    input wor id_9,
    input supply0 id_10,
    output supply0 id_11,
    input supply0 id_12,
    output wor id_13,
    input wire id_14,
    output tri1 id_15,
    output tri id_16,
    input supply1 id_17,
    output tri0 id_18,
    output tri1 id_19,
    input wor id_20,
    output uwire id_21,
    input wor id_22,
    output wor id_23,
    input supply0 id_24,
    input supply1 id_25,
    input supply0 id_26,
    input supply0 id_27,
    output wor id_28,
    output wand id_29
    , id_38,
    input wor id_30,
    output supply0 id_31,
    input wor id_32,
    input uwire id_33,
    output wand id_34,
    output tri id_35,
    input wand id_36
);
  wire id_39;
  assign module_1.id_1 = 0;
endmodule
module module_1 (
    output supply0 id_0,
    input wor id_1
);
  assign id_0 = id_1;
  module_0 modCall_1 (
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1
  );
endmodule
