// Seed: 2387233476
module module_0 (
    input tri0 id_0,
    input tri1 id_1,
    output supply1 id_2,
    input wor id_3,
    input wire id_4
    , id_45,
    output tri0 id_5,
    output tri id_6,
    output wand id_7,
    output wand id_8,
    output tri1 id_9,
    input tri id_10,
    input uwire id_11,
    input wand id_12,
    output uwire id_13,
    input wand id_14,
    output tri1 id_15,
    output tri0 module_0,
    input supply1 id_17,
    output wand id_18,
    input uwire id_19,
    input tri0 id_20,
    output supply1 id_21,
    input wand id_22,
    input wand id_23,
    input supply0 id_24,
    input tri1 id_25,
    output wire id_26,
    input wor id_27,
    input wire id_28,
    input tri0 id_29,
    input wire id_30,
    output tri0 id_31,
    output tri1 id_32,
    input wor id_33,
    input tri0 id_34,
    input uwire id_35,
    output supply1 id_36,
    output wor id_37,
    input tri id_38,
    input tri0 id_39,
    output tri id_40,
    output uwire id_41,
    input tri0 id_42,
    input supply0 id_43
);
  always @(*) id_8 = 1;
endmodule
module module_1 (
    input  uwire id_0,
    input  uwire id_1,
    output tri   id_2
);
  assign id_2 = 1'd0;
  id_4(
      id_1 == 1, 1, 1
  ); module_0(
      id_1,
      id_0,
      id_2,
      id_1,
      id_1,
      id_2,
      id_2,
      id_2,
      id_2,
      id_2,
      id_1,
      id_1,
      id_1,
      id_2,
      id_0,
      id_2,
      id_2,
      id_0,
      id_2,
      id_0,
      id_0,
      id_2,
      id_0,
      id_0,
      id_0,
      id_1,
      id_2,
      id_1,
      id_0,
      id_1,
      id_0,
      id_2,
      id_2,
      id_0,
      id_0,
      id_1,
      id_2,
      id_2,
      id_0,
      id_1,
      id_2,
      id_2,
      id_1,
      id_0
  );
  wire id_5;
endmodule
