// Seed: 680229565
module module_0 (
    output uwire id_0,
    input wire id_1,
    output tri1 id_2,
    input wor id_3,
    output wor id_4,
    input tri0 id_5,
    input tri1 id_6,
    output tri id_7,
    input supply1 id_8,
    output wire id_9,
    input wire id_10,
    output supply1 id_11,
    input tri1 id_12,
    input tri1 id_13,
    input wor id_14,
    input wor id_15,
    input uwire id_16,
    input tri1 id_17,
    input tri0 id_18,
    input wor id_19,
    input tri1 id_20,
    output tri0 id_21,
    input uwire id_22,
    input tri1 id_23,
    input wand id_24,
    input supply1 id_25,
    output tri1 id_26,
    input uwire id_27,
    input supply1 id_28,
    input wand id_29,
    input tri id_30,
    input wor id_31,
    output wand id_32,
    output tri0 id_33,
    input tri id_34
);
  wire id_36, id_37;
  wire id_38;
  wire id_39;
endmodule
module module_1 (
    output supply1 id_0,
    input wor id_1,
    output supply1 id_2,
    input tri0 id_3,
    input tri1 id_4,
    input uwire id_5
);
  wire id_7;
  module_0(
      id_0,
      id_5,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_0,
      id_5,
      id_2,
      id_3,
      id_2,
      id_4,
      id_4,
      id_1,
      id_1,
      id_1,
      id_3,
      id_3,
      id_3,
      id_1,
      id_0,
      id_3,
      id_4,
      id_1,
      id_3,
      id_0,
      id_4,
      id_4,
      id_4,
      id_5,
      id_1,
      id_0,
      id_2,
      id_1
  );
endmodule
