// Seed: 2595196430
module module_0 (
    output wor id_0,
    output tri0 id_1,
    output uwire id_2
    , id_53,
    output uwire id_3,
    input tri0 id_4,
    output supply1 id_5,
    input wand id_6,
    input uwire id_7,
    output wor id_8,
    input wor id_9
    , id_54,
    output uwire id_10,
    input wor id_11,
    input wire id_12,
    input uwire id_13,
    output wire id_14,
    output tri id_15,
    output wire id_16,
    input tri1 id_17,
    input wire id_18,
    input tri0 id_19,
    input uwire id_20,
    output uwire id_21,
    output supply0 id_22,
    output wire id_23,
    input wand id_24,
    input supply1 id_25,
    input tri1 id_26
    , id_55,
    output supply1 id_27,
    input supply0 id_28,
    input wand id_29,
    input supply0 id_30,
    input tri0 id_31,
    output uwire id_32,
    input tri0 id_33,
    input wire id_34,
    output tri1 id_35,
    output uwire id_36,
    input supply0 id_37,
    output uwire id_38,
    input wand id_39,
    input uwire id_40,
    input supply0 id_41,
    input uwire id_42,
    input wand id_43,
    input supply1 id_44,
    input tri0 id_45,
    input wire id_46,
    input tri id_47,
    input tri0 id_48,
    input tri id_49,
    input wor id_50,
    output supply1 id_51
);
  always #id_56 id_51 = 1;
  wire id_57;
  wire id_58;
endmodule
module module_1 (
    output uwire id_0,
    input wand id_1,
    input tri0 id_2,
    input supply1 id_3,
    output tri1 id_4,
    input wor id_5
);
  wire id_7;
  module_0(
      id_0,
      id_4,
      id_4,
      id_0,
      id_5,
      id_0,
      id_1,
      id_1,
      id_0,
      id_5,
      id_0,
      id_2,
      id_2,
      id_2,
      id_0,
      id_4,
      id_0,
      id_3,
      id_2,
      id_3,
      id_1,
      id_0,
      id_4,
      id_4,
      id_2,
      id_3,
      id_5,
      id_4,
      id_5,
      id_1,
      id_5,
      id_1,
      id_0,
      id_2,
      id_1,
      id_4,
      id_4,
      id_1,
      id_0,
      id_2,
      id_3,
      id_5,
      id_3,
      id_2,
      id_2,
      id_5,
      id_1,
      id_3,
      id_5,
      id_3,
      id_3,
      id_4
  );
endmodule
