// Seed: 1723726208
module module_0 (
    output wand id_0,
    input uwire id_1,
    output wor id_2,
    input wire id_3,
    input supply0 id_4,
    input tri0 id_5
    , id_61,
    input supply1 id_6,
    input uwire id_7,
    output tri0 id_8,
    output tri1 id_9,
    input wand id_10,
    input tri0 id_11,
    input tri0 id_12,
    output tri0 id_13,
    input wor id_14,
    output tri id_15,
    output tri0 id_16,
    output tri id_17,
    input tri1 id_18,
    output supply1 id_19
    , id_62,
    input tri1 id_20,
    input supply0 id_21,
    input supply1 id_22,
    output supply0 id_23,
    input supply0 id_24,
    input uwire id_25,
    output tri id_26,
    input wor id_27,
    output wand id_28,
    input supply0 id_29,
    input wor id_30,
    input wand id_31,
    input supply1 id_32,
    input tri1 id_33,
    input uwire id_34,
    output wand id_35,
    input tri1 sample,
    output wor id_37,
    output uwire id_38,
    input supply1 id_39,
    output tri1 module_0,
    output supply1 id_41,
    output uwire id_42,
    input tri0 id_43,
    input wor id_44,
    input tri1 id_45,
    output tri0 id_46,
    input wire id_47,
    input tri0 id_48,
    input wire id_49,
    input wor id_50,
    input wire id_51,
    input tri1 id_52,
    input supply0 id_53,
    input wand id_54,
    output wand id_55,
    output supply1 id_56,
    input tri0 id_57,
    output uwire id_58,
    output wand id_59
);
endmodule
module module_1 (
    input uwire id_0,
    input wor id_1,
    output uwire id_2,
    input tri0 id_3,
    input wor id_4,
    input wand id_5,
    input wand id_6,
    input supply0 id_7
    , id_10,
    input wor id_8
);
  generate
    integer id_11;
    ;
    assign id_11 = id_4;
  endgenerate
  module_0 modCall_1 (
      id_2,
      id_6,
      id_2,
      id_8,
      id_6,
      id_1,
      id_7,
      id_7,
      id_2,
      id_2,
      id_1,
      id_7,
      id_5,
      id_2,
      id_3,
      id_2,
      id_2,
      id_2,
      id_3,
      id_2,
      id_0,
      id_8,
      id_8,
      id_2,
      id_5,
      id_5,
      id_2,
      id_8,
      id_2,
      id_0,
      id_8,
      id_0,
      id_5,
      id_4,
      id_7,
      id_2,
      id_5,
      id_2,
      id_2,
      id_5,
      id_2,
      id_2,
      id_2,
      id_6,
      id_8,
      id_7,
      id_2,
      id_6,
      id_6,
      id_8,
      id_1,
      id_0,
      id_1,
      id_7,
      id_7,
      id_2,
      id_2,
      id_4,
      id_2,
      id_2
  );
  assign modCall_1.id_5 = 0;
endmodule
