// Seed: 4240381626
module module_0 (
    input wand id_0,
    input supply0 id_1,
    output wand id_2,
    input tri id_3,
    output tri1 id_4
    , id_26,
    input supply1 id_5,
    output tri1 id_6,
    output wire id_7,
    input wor id_8,
    input wire id_9,
    output wire id_10,
    input tri0 id_11,
    input supply1 id_12,
    output supply0 id_13,
    output supply1 id_14,
    output tri0 id_15,
    input tri0 id_16,
    input tri1 id_17,
    input wire id_18,
    output supply1 module_0,
    input tri id_20,
    input tri id_21,
    input supply0 id_22,
    input uwire id_23,
    input uwire id_24
);
  wire id_27;
endmodule
module module_1 (
    input supply1 id_0,
    input wor id_1,
    output tri0 id_2,
    output supply0 id_3,
    input supply0 id_4,
    input uwire id_5,
    input tri id_6,
    input tri1 id_7,
    output supply1 id_8,
    input supply1 id_9,
    output supply1 id_10,
    input uwire id_11,
    input wire id_12,
    input supply0 id_13,
    output wire id_14,
    output uwire id_15,
    output wand id_16
);
  module_0(
      id_6,
      id_11,
      id_3,
      id_5,
      id_15,
      id_5,
      id_8,
      id_2,
      id_1,
      id_7,
      id_16,
      id_9,
      id_4,
      id_2,
      id_14,
      id_2,
      id_7,
      id_7,
      id_5,
      id_16,
      id_12,
      id_7,
      id_4,
      id_6,
      id_0
  );
endmodule
