// Seed: 1093011129
module module_0 (
    input tri id_0,
    input supply0 id_1,
    input wor id_2,
    input wand id_3,
    input tri0 id_4,
    input supply1 id_5,
    input supply0 id_6,
    input tri0 id_7,
    input wire id_8,
    output wand id_9,
    input supply1 id_10,
    output tri0 id_11,
    input uwire id_12,
    output wand id_13,
    output supply0 id_14,
    input tri id_15,
    input wor id_16,
    output supply1 id_17,
    input supply0 id_18,
    input wand id_19,
    output tri0 id_20,
    input tri1 id_21,
    output wire id_22
    , id_41,
    output supply1 id_23,
    input supply1 id_24,
    input wor id_25,
    input tri id_26,
    input uwire id_27,
    output wand id_28,
    output tri id_29
    , id_42,
    input supply0 id_30#(.id_43(!id_10)),
    input tri1 id_31,
    input uwire id_32,
    output tri1 id_33,
    output tri0 id_34,
    input supply0 id_35,
    input tri id_36,
    input wand id_37,
    output tri1 id_38,
    output wor id_39
);
endmodule
module module_1 (
    input tri1 id_0,
    input wire id_1,
    input tri0 id_2,
    input supply0 id_3,
    output uwire id_4,
    output wand id_5,
    input supply1 id_6,
    output tri1 id_7,
    input uwire id_8,
    input uwire id_9,
    input tri0 id_10
);
  wire id_12;
  module_0(
      id_10,
      id_10,
      id_8,
      id_8,
      id_6,
      id_2,
      id_3,
      id_9,
      id_1,
      id_7,
      id_0,
      id_4,
      id_1,
      id_7,
      id_5,
      id_0,
      id_6,
      id_5,
      id_8,
      id_10,
      id_7,
      id_0,
      id_4,
      id_7,
      id_8,
      id_10,
      id_1,
      id_6,
      id_4,
      id_7,
      id_8,
      id_6,
      id_6,
      id_4,
      id_7,
      id_8,
      id_1,
      id_3,
      id_5,
      id_7
  );
endmodule
