// Seed: 4102188242
module module_0 (
    input uwire id_0,
    input supply0 id_1,
    input wire id_2,
    input wor id_3,
    input uwire id_4,
    input tri0 id_5,
    input tri id_6,
    input wand id_7,
    input tri1 id_8,
    input wor id_9,
    input supply1 id_10,
    input tri1 id_11,
    input wor id_12,
    input wire id_13,
    input tri id_14,
    output wand id_15,
    output wire id_16,
    input supply1 id_17,
    input tri id_18,
    input supply1 id_19,
    output tri1 id_20,
    input tri id_21,
    input wire id_22,
    output supply1 id_23,
    input supply0 id_24,
    output supply1 id_25,
    input supply1 id_26,
    input wire id_27,
    output wand id_28,
    output tri id_29,
    input supply1 id_30
);
endmodule
module module_1 (
    input tri id_0,
    input tri0 id_1,
    input supply0 id_2,
    output wand id_3,
    input uwire id_4,
    input tri1 id_5,
    output wire id_6
    , id_19,
    output tri1 id_7,
    input tri1 id_8,
    inout tri1 id_9,
    input wire id_10,
    input uwire id_11,
    input wor id_12,
    input wire id_13,
    output wand id_14,
    output uwire id_15,
    output wire id_16,
    input supply1 id_17
);
  or primCall (
      id_9,
      id_12,
      id_4,
      id_17,
      id_1,
      id_10,
      id_21,
      id_8,
      id_5,
      id_0,
      id_2,
      id_11,
      id_13,
      id_19,
      id_20
  );
  wire id_20;
  tri  id_21 = 1;
  assign id_15 = 1;
  module_0 modCall_1 (
      id_0,
      id_13,
      id_2,
      id_8,
      id_2,
      id_8,
      id_4,
      id_12,
      id_0,
      id_10,
      id_12,
      id_12,
      id_9,
      id_4,
      id_0,
      id_7,
      id_16,
      id_1,
      id_1,
      id_8,
      id_3,
      id_17,
      id_5,
      id_6,
      id_4,
      id_3,
      id_9,
      id_1,
      id_15,
      id_7,
      id_9
  );
  assign modCall_1.type_15 = 0;
endmodule
