// Seed: 3003051478
module module_0 (
    input tri1 id_0,
    output tri1 id_1,
    output wire id_2,
    input tri id_3,
    output tri0 id_4,
    input supply0 id_5,
    output wand id_6,
    input uwire id_7,
    input tri1 id_8,
    output uwire id_9
    , id_34,
    input wor id_10,
    input wire id_11,
    input wand id_12,
    input uwire id_13,
    input wire id_14,
    output supply0 id_15,
    input supply1 id_16,
    input tri id_17,
    input tri1 id_18,
    input wire id_19,
    input supply1 id_20,
    input tri id_21,
    input supply0 id_22,
    input tri0 id_23,
    output tri1 id_24,
    input supply1 id_25,
    output wire id_26,
    output wand id_27,
    input tri id_28,
    input wire id_29,
    input wor id_30,
    input tri1 id_31,
    input supply1 id_32
);
  assign id_27 = id_30;
endmodule
module module_1 (
    output supply0 id_0,
    output wire id_1,
    input wor id_2,
    input tri1 id_3,
    input uwire id_4,
    input tri0 id_5,
    input wire id_6,
    output uwire id_7,
    output uwire id_8,
    output wor id_9,
    output wire id_10,
    output supply1 id_11,
    output wand id_12
);
  parameter id_14 = -1;
  module_0 modCall_1 (
      id_3,
      id_10,
      id_12,
      id_3,
      id_9,
      id_2,
      id_11,
      id_5,
      id_4,
      id_10,
      id_5,
      id_3,
      id_4,
      id_3,
      id_2,
      id_12,
      id_6,
      id_3,
      id_4,
      id_3,
      id_2,
      id_6,
      id_6,
      id_6,
      id_12,
      id_4,
      id_11,
      id_1,
      id_4,
      id_5,
      id_4,
      id_4,
      id_5
  );
  assign modCall_1.id_25 = 0;
endmodule
