// Seed: 3288780199
module module_0 (
    input supply0 id_0,
    input uwire id_1,
    input wire id_2,
    output tri id_3,
    output tri id_4,
    input tri0 id_5,
    output wor id_6,
    input wire id_7,
    output tri id_8,
    output supply1 id_9,
    input uwire id_10,
    input wire id_11,
    output tri id_12,
    input uwire id_13,
    input tri0 id_14,
    input tri0 id_15,
    output tri id_16,
    input tri0 id_17,
    input wire id_18,
    output supply1 id_19,
    input tri0 id_20,
    input uwire id_21,
    output wire id_22,
    input tri id_23,
    input supply1 id_24,
    output uwire id_25,
    input tri id_26,
    output uwire id_27,
    input wor id_28,
    input wand id_29,
    output wand id_30,
    output tri id_31,
    input wor id_32,
    output wand id_33,
    output tri id_34,
    output supply1 id_35,
    output wor id_36,
    output tri id_37,
    input tri0 id_38,
    output tri id_39,
    output wire id_40,
    input wor id_41,
    output wand id_42,
    input tri0 id_43,
    input tri id_44,
    input uwire id_45,
    output uwire id_46,
    output tri id_47,
    input tri1 id_48,
    input uwire id_49,
    input tri0 id_50,
    input tri id_51,
    input uwire id_52,
    input wand id_53,
    input wand id_54,
    output supply1 id_55,
    input supply0 id_56,
    input wor id_57,
    input wor id_58,
    input wand id_59,
    input wire id_60,
    input tri0 id_61,
    input tri id_62,
    input wor id_63,
    input wire id_64,
    output wor id_65,
    input wand id_66,
    input wire id_67
    , id_71,
    input wire id_68,
    input wand id_69
);
  assign id_71 = 1;
endmodule
module module_1 (
    input wor id_0,
    output tri1 id_1,
    output wire id_2,
    input tri0 id_3,
    input wire id_4,
    output wire id_5,
    input supply0 id_6,
    output wand id_7
);
  logic id_9;
  module_0 modCall_1 (
      id_3,
      id_3,
      id_4,
      id_1,
      id_5,
      id_3,
      id_5,
      id_6,
      id_7,
      id_2,
      id_4,
      id_0,
      id_5,
      id_6,
      id_3,
      id_0,
      id_2,
      id_4,
      id_4,
      id_5,
      id_4,
      id_4,
      id_2,
      id_3,
      id_6,
      id_2,
      id_3,
      id_1,
      id_3,
      id_0,
      id_5,
      id_2,
      id_0,
      id_2,
      id_1,
      id_1,
      id_7,
      id_2,
      id_3,
      id_2,
      id_1,
      id_0,
      id_7,
      id_3,
      id_0,
      id_0,
      id_5,
      id_1,
      id_6,
      id_4,
      id_4,
      id_0,
      id_3,
      id_4,
      id_6,
      id_2,
      id_3,
      id_4,
      id_6,
      id_4,
      id_4,
      id_6,
      id_6,
      id_4,
      id_4,
      id_2,
      id_0,
      id_4,
      id_4,
      id_6
  );
  assign modCall_1.id_64 = 0;
endmodule
