// Seed: 846293200
module module_0 (
    output wor id_0,
    output tri0 id_1,
    output supply0 id_2,
    output wor id_3,
    output wire id_4,
    input wor id_5,
    input supply0 id_6,
    input supply1 id_7,
    input wand id_8,
    input supply0 id_9,
    input uwire id_10,
    input tri1 id_11,
    output wire id_12,
    output uwire id_13,
    input tri id_14,
    output tri id_15,
    input wire id_16,
    input tri0 id_17,
    input uwire id_18,
    input supply0 id_19,
    input wand id_20,
    output tri0 id_21,
    input wire id_22,
    output wire id_23,
    output supply0 id_24,
    output tri id_25,
    input supply1 id_26,
    output tri0 id_27,
    input tri1 id_28,
    input supply1 id_29,
    output tri id_30,
    output wire id_31,
    input tri id_32,
    input tri1 id_33,
    output wand id_34
);
  wire id_36;
  wire id_37;
  assign id_12 = id_10 ==? 1;
endmodule
module module_1 (
    input wand id_0,
    input wand id_1,
    input supply1 id_2,
    output tri1 id_3,
    output wire id_4,
    input wor id_5,
    input wire id_6,
    input tri0 id_7,
    output supply0 id_8,
    output tri0 id_9,
    input uwire id_10,
    input wand id_11,
    input wand id_12,
    output tri id_13
);
  parameter id_15 = 1;
  module_0 modCall_1 (
      id_8,
      id_3,
      id_4,
      id_4,
      id_9,
      id_2,
      id_7,
      id_5,
      id_1,
      id_12,
      id_1,
      id_7,
      id_3,
      id_8,
      id_2,
      id_3,
      id_0,
      id_12,
      id_6,
      id_7,
      id_10,
      id_8,
      id_10,
      id_3,
      id_8,
      id_9,
      id_2,
      id_4,
      id_5,
      id_10,
      id_8,
      id_9,
      id_2,
      id_6,
      id_4
  );
  assign modCall_1.id_7 = 0;
endmodule
