// Seed: 2957747302
module module_0 (
    input tri id_0,
    input wire id_1,
    output wor id_2,
    input supply1 id_3,
    output tri1 id_4,
    input tri0 id_5,
    output supply0 id_6,
    input tri id_7,
    output wire id_8,
    output tri1 id_9,
    output supply1 id_10,
    input wor id_11,
    output wire id_12,
    input supply0 id_13,
    input uwire id_14,
    output tri id_15,
    input tri1 id_16,
    input wor id_17,
    output wand id_18,
    input supply1 id_19,
    input wire id_20,
    input tri1 id_21,
    input uwire id_22,
    input wand id_23,
    input supply0 id_24,
    input tri0 id_25,
    output tri id_26,
    output tri1 id_27,
    input tri1 id_28,
    output tri1 id_29,
    output wire id_30,
    input uwire id_31,
    input wor id_32,
    output wire id_33,
    input wand id_34,
    output uwire id_35,
    input wire id_36,
    input supply0 id_37,
    input supply1 id_38,
    input tri id_39,
    input tri module_0
    , id_47,
    input uwire id_41,
    output tri0 id_42,
    output tri id_43,
    output wand id_44,
    output supply1 id_45
);
endmodule
module module_1 (
    input tri id_0,
    input tri id_1,
    output supply0 id_2,
    input wire id_3,
    input tri id_4,
    input wor id_5,
    input tri0 id_6,
    input uwire id_7,
    input wor id_8,
    output supply1 id_9
);
  tri0 id_11;
  module_0 modCall_1 (
      id_0,
      id_7,
      id_2,
      id_7,
      id_9,
      id_1,
      id_2,
      id_8,
      id_9,
      id_2,
      id_9,
      id_8,
      id_9,
      id_3,
      id_4,
      id_9,
      id_3,
      id_7,
      id_2,
      id_3,
      id_0,
      id_1,
      id_4,
      id_3,
      id_6,
      id_6,
      id_2,
      id_9,
      id_3,
      id_2,
      id_9,
      id_0,
      id_6,
      id_2,
      id_3,
      id_2,
      id_6,
      id_1,
      id_6,
      id_6,
      id_3,
      id_1,
      id_9,
      id_2,
      id_9,
      id_2
  );
  assign modCall_1.id_27 = 0;
  assign id_11 = 1'd0;
  wire id_12;
endmodule
