// Seed: 154478371
module module_0 (
    output tri0 id_0,
    output tri0 id_1,
    input wor id_2,
    input wor id_3,
    input uwire id_4,
    input wand id_5,
    output tri id_6,
    input supply1 id_7,
    input wand id_8,
    input tri id_9,
    input wand id_10,
    input tri1 id_11,
    input wor id_12,
    output wand id_13,
    input tri1 id_14,
    output wand id_15,
    output tri0 id_16,
    input supply0 id_17,
    input tri1 id_18,
    input supply1 id_19,
    input wand id_20,
    input wor id_21,
    output tri id_22,
    input tri id_23,
    input supply0 id_24,
    input wand id_25,
    input supply0 id_26,
    input wire id_27,
    output supply0 id_28,
    output wor id_29,
    input supply1 id_30,
    input supply0 id_31
    , id_48,
    output supply1 id_32,
    input uwire id_33,
    input tri1 id_34,
    input wire id_35,
    input tri0 id_36,
    input wire id_37,
    output tri id_38,
    output uwire id_39,
    input tri0 id_40,
    input uwire id_41,
    input wand id_42,
    input tri1 id_43,
    input wor id_44,
    input wire id_45,
    output tri1 id_46
);
  assign id_46 = 1;
endmodule
module module_1 (
    output uwire id_0,
    input  tri0  id_1,
    input  logic id_2,
    output logic id_3
);
  always @(posedge 1) id_3 <= id_2;
  wire id_5;
  assign id_3 = 1;
  module_0(
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0
  );
  wire id_6;
endmodule
