// Seed: 2148904889
module module_0 (
    input tri id_0,
    output uwire id_1
    , id_45,
    input supply0 id_2,
    output uwire id_3,
    input tri1 id_4,
    input tri1 id_5,
    input wor id_6,
    input wire id_7,
    output tri id_8,
    output tri id_9,
    input tri0 id_10,
    output supply1 id_11,
    input wor id_12,
    input tri id_13,
    input supply1 id_14,
    input uwire id_15,
    input tri0 id_16,
    output wand id_17,
    output supply1 id_18,
    input supply1 id_19,
    input supply1 id_20,
    input wire id_21,
    input wire id_22,
    output tri id_23,
    input wire id_24
    , id_46,
    input wand id_25,
    output tri0 id_26,
    input wor id_27,
    output supply1 id_28,
    input supply0 id_29,
    input supply0 id_30,
    input uwire id_31,
    input tri id_32,
    output wand id_33,
    input wire id_34,
    output uwire id_35,
    input tri1 id_36,
    input tri id_37,
    input wand id_38,
    output tri0 id_39,
    input tri1 id_40,
    output tri0 id_41,
    output wire id_42,
    input uwire id_43
);
endmodule
module module_1 (
    input tri1 id_0,
    output tri1 id_1,
    output wor id_2,
    input tri1 id_3,
    output supply1 id_4
);
  assign id_2 = 1;
  module_0(
      id_3,
      id_2,
      id_3,
      id_4,
      id_3,
      id_3,
      id_0,
      id_0,
      id_1,
      id_4,
      id_3,
      id_1,
      id_3,
      id_0,
      id_3,
      id_0,
      id_3,
      id_2,
      id_2,
      id_0,
      id_0,
      id_3,
      id_3,
      id_4,
      id_3,
      id_3,
      id_4,
      id_0,
      id_1,
      id_3,
      id_0,
      id_0,
      id_0,
      id_2,
      id_0,
      id_2,
      id_3,
      id_0,
      id_3,
      id_4,
      id_0,
      id_4,
      id_1,
      id_3
  );
  wire id_6;
endmodule
