// Seed: 136367762
module module_0 (
    input wor id_0,
    input supply0 id_1,
    input supply1 id_2,
    output wand id_3,
    input tri id_4,
    input uwire id_5,
    output uwire id_6,
    output wor id_7,
    output wire id_8,
    input wand id_9
    , id_18,
    output supply1 id_10,
    input supply0 id_11,
    input supply1 id_12,
    output tri id_13,
    input wor id_14,
    input tri1 id_15,
    input tri id_16
);
  wire id_19;
  assign module_1.id_12 = 0;
endmodule
module module_1 (
    input wand id_0,
    output tri1 id_1,
    input uwire id_2,
    output supply1 id_3,
    input wire id_4,
    input supply0 id_5,
    output supply0 id_6,
    input wire id_7,
    input uwire id_8,
    input wire id_9,
    input uwire id_10,
    output wand id_11,
    output wor id_12,
    output uwire id_13,
    input tri id_14,
    input wand id_15,
    output wor id_16,
    input wire id_17,
    input supply1 id_18,
    input tri1 id_19,
    output supply0 id_20,
    output wire id_21,
    output wor id_22,
    input wire id_23,
    input tri id_24,
    input supply1 id_25,
    output wand id_26,
    input tri0 id_27,
    input tri1 id_28,
    output tri1 id_29,
    output tri0 id_30,
    input tri id_31,
    output tri id_32,
    input wire id_33,
    output wire id_34,
    output wand id_35,
    output wand id_36,
    input wand id_37,
    output supply0 id_38,
    input supply1 id_39,
    output wand id_40,
    inout tri0 id_41
);
  logic id_43;
  ;
  module_0 modCall_1 (
      id_18,
      id_2,
      id_33,
      id_21,
      id_33,
      id_15,
      id_41,
      id_41,
      id_1,
      id_37,
      id_36,
      id_25,
      id_7,
      id_13,
      id_31,
      id_37,
      id_10
  );
endmodule
