// Seed: 117540867
module module_0 (
    inout tri1 id_0,
    input tri0 id_1,
    input tri id_2,
    output tri id_3,
    output tri id_4,
    input uwire id_5,
    output tri1 id_6,
    input supply0 id_7,
    output tri id_8,
    output tri id_9
    , id_37,
    output uwire id_10,
    output wand id_11,
    input supply0 id_12,
    input wire id_13,
    input wand id_14,
    input supply0 id_15,
    output tri0 id_16,
    input wire id_17,
    input supply1 id_18,
    input tri id_19,
    output tri id_20,
    input wor id_21,
    input wand id_22,
    output wire id_23,
    input supply1 id_24,
    input supply1 id_25,
    output supply1 id_26,
    output wand id_27,
    input wire id_28,
    input wire id_29,
    output supply0 id_30,
    input supply0 id_31,
    input tri0 id_32,
    inout wire id_33,
    input tri0 id_34,
    input tri id_35
);
  wire id_38;
endmodule
module module_1 (
    input supply1 id_0,
    input tri id_1
);
  assign id_3 = id_0;
  assign id_3 = id_0 - id_3;
  module_0(
      id_3,
      id_1,
      id_1,
      id_3,
      id_3,
      id_1,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_3,
      id_0,
      id_3,
      id_1,
      id_0,
      id_3,
      id_3,
      id_0,
      id_1,
      id_3,
      id_0,
      id_1,
      id_3,
      id_1,
      id_0,
      id_3,
      id_3,
      id_0,
      id_0,
      id_3,
      id_0,
      id_3,
      id_3,
      id_0,
      id_1
  );
endmodule
