// Seed: 604352277
macromodule module_0 (
    input tri0 id_0,
    input supply0 id_1,
    output tri1 id_2,
    input wire id_3,
    output tri1 id_4,
    input wand id_5,
    input tri id_6,
    input wand id_7,
    input uwire id_8,
    input wire id_9,
    output tri1 id_10,
    input wire id_11,
    output wand id_12,
    input tri1 id_13,
    input wor id_14,
    output tri id_15,
    input supply1 id_16,
    output tri1 id_17,
    input supply0 id_18,
    input supply0 id_19,
    input uwire id_20,
    input uwire id_21,
    input uwire id_22,
    output wire id_23,
    input uwire id_24,
    input uwire id_25,
    output tri id_26,
    output wire id_27,
    input wand id_28,
    input wand id_29,
    input uwire id_30,
    output wand id_31,
    input tri0 id_32,
    input supply1 id_33,
    input wor id_34,
    input tri0 id_35,
    input wand id_36,
    output uwire id_37,
    input uwire id_38
);
  wire id_40;
  ;
endmodule
module module_1 (
    input supply1 id_0,
    input wand id_1,
    input uwire id_2,
    input tri1 id_3,
    output supply1 id_4,
    input wand id_5,
    output tri1 id_6
);
  module_0 modCall_1 (
      id_3,
      id_5,
      id_6,
      id_2,
      id_6,
      id_0,
      id_1,
      id_1,
      id_2,
      id_5,
      id_6,
      id_2,
      id_6,
      id_0,
      id_1,
      id_6,
      id_1,
      id_6,
      id_2,
      id_3,
      id_1,
      id_3,
      id_2,
      id_4,
      id_2,
      id_3,
      id_6,
      id_4,
      id_5,
      id_1,
      id_5,
      id_6,
      id_0,
      id_2,
      id_1,
      id_3,
      id_1,
      id_6,
      id_0
  );
  assign modCall_1.id_9 = 0;
endmodule
