// Seed: 1287869746
module module_0 (
    input tri id_0,
    output wand id_1,
    input wor id_2,
    input wor id_3,
    input uwire id_4,
    output tri id_5,
    output uwire id_6,
    output tri0 id_7,
    input wire id_8,
    input tri0 id_9,
    output supply0 id_10,
    input uwire id_11,
    output wire id_12,
    input uwire id_13,
    input wor id_14,
    input supply1 id_15,
    input tri0 id_16,
    output wire id_17,
    output tri0 id_18,
    input wand id_19,
    input supply0 id_20,
    output wand id_21,
    input tri id_22,
    input tri1 id_23,
    input supply0 id_24,
    output wor id_25
);
  assign module_1.id_6 = 0;
  assign #id_27 id_12 = 1;
endmodule
module module_1 (
    input supply0 id_0,
    input tri0 id_1,
    input wire id_2,
    input wire id_3,
    output tri1 id_4,
    input wor id_5,
    input wor id_6,
    input wire id_7,
    input wand id_8,
    input uwire id_9,
    input wire id_10,
    input wor id_11,
    input tri id_12,
    input uwire id_13,
    input wand id_14,
    input supply0 id_15,
    input wand id_16,
    input wand id_17
);
  wire id_19;
  module_0 modCall_1 (
      id_0,
      id_4,
      id_6,
      id_5,
      id_1,
      id_4,
      id_4,
      id_4,
      id_2,
      id_3,
      id_4,
      id_17,
      id_4,
      id_6,
      id_11,
      id_10,
      id_16,
      id_4,
      id_4,
      id_8,
      id_14,
      id_4,
      id_10,
      id_12,
      id_2,
      id_4
  );
endmodule
