// Seed: 2168222966
module module_0 (
    output wor id_0,
    output wor id_1,
    input uwire id_2,
    input supply1 id_3,
    input wand id_4,
    output wand id_5,
    output uwire id_6,
    output uwire id_7,
    input tri1 id_8,
    input wand id_9,
    input supply0 id_10,
    input tri1 id_11,
    input supply1 id_12,
    input tri id_13,
    input wand id_14,
    input wand id_15,
    input tri1 id_16,
    output tri1 id_17,
    input tri id_18,
    input tri0 id_19,
    input wand id_20,
    input uwire id_21,
    output supply1 id_22,
    input uwire id_23,
    input wor id_24,
    input tri id_25,
    output supply1 id_26,
    input tri1 id_27,
    output wire id_28
);
endmodule
module module_1 (
    input  wand  id_0,
    output uwire id_1,
    input  tri   id_2,
    input  tri   id_3,
    output tri   id_4,
    output tri   id_5
);
  module_0 modCall_1 (
      id_1,
      id_5,
      id_2,
      id_3,
      id_0,
      id_1,
      id_4,
      id_4,
      id_2,
      id_3,
      id_3,
      id_0,
      id_2,
      id_3,
      id_3,
      id_0,
      id_0,
      id_4,
      id_2,
      id_3,
      id_3,
      id_3,
      id_5,
      id_0,
      id_3,
      id_0,
      id_1,
      id_0,
      id_4
  );
endmodule
