// Seed: 1619310732
module module_0 (
    output wire id_0,
    input wor id_1,
    input tri1 id_2,
    input uwire id_3,
    output wand id_4
    , id_39,
    output wand id_5,
    input uwire id_6,
    input wand id_7,
    input supply0 id_8,
    input tri1 id_9,
    output tri id_10,
    output wand id_11,
    output wand id_12,
    output uwire id_13,
    input tri0 id_14,
    input tri0 id_15,
    input tri id_16,
    output wor id_17,
    input supply1 id_18,
    input uwire id_19,
    output uwire id_20,
    input tri0 id_21,
    input wand id_22,
    input wire id_23,
    output tri id_24,
    input supply1 id_25,
    output tri id_26,
    input tri id_27,
    input uwire id_28,
    input supply1 id_29,
    output supply1 id_30,
    output tri1 id_31,
    input tri id_32,
    input supply0 id_33,
    input wor id_34,
    input wire id_35,
    input supply0 id_36,
    output tri1 id_37
);
  logic id_40;
endmodule
module module_1 (
    input  tri0 id_0,
    output wand id_1
);
  module_0 modCall_1 (
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1
  );
  assign modCall_1.id_30 = 0;
endmodule
