// Seed: 47196825
module module_0 (
    output uwire id_0,
    output tri1 id_1,
    input wire id_2,
    input supply0 id_3,
    input tri0 id_4,
    output wor id_5,
    input wor id_6,
    output wire id_7,
    input wand id_8,
    output uwire id_9,
    input tri id_10,
    input tri id_11,
    input wire id_12,
    output tri0 id_13,
    input wire id_14,
    output tri1 id_15,
    input tri1 id_16,
    input tri1 id_17,
    output supply0 id_18,
    output wor id_19,
    output supply0 id_20,
    output supply1 id_21,
    output uwire id_22,
    output supply0 id_23,
    input wand id_24,
    output tri0 id_25,
    output wire id_26
);
endmodule
module module_1 (
    output wand id_0,
    output supply0 id_1,
    output tri0 id_2,
    input uwire id_3,
    output tri1 id_4,
    output wire id_5,
    output wire id_6,
    output tri id_7,
    output uwire id_8,
    output tri id_9,
    input tri id_10,
    output wire id_11,
    input tri id_12,
    output supply0 id_13,
    input tri1 id_14,
    input supply1 id_15,
    input supply1 id_16,
    output tri0 id_17,
    output tri0 id_18,
    input supply1 id_19,
    input tri id_20,
    input uwire id_21,
    input wire id_22,
    input tri1 id_23,
    output tri1 id_24,
    input wor id_25,
    input wand id_26,
    input tri0 id_27,
    output uwire id_28
);
  wire id_30;
  module_0 modCall_1 (
      id_6,
      id_6,
      id_22,
      id_22,
      id_22,
      id_7,
      id_16,
      id_4,
      id_10,
      id_24,
      id_14,
      id_16,
      id_3,
      id_2,
      id_23,
      id_6,
      id_3,
      id_12,
      id_2,
      id_5,
      id_24,
      id_8,
      id_6,
      id_8,
      id_23,
      id_11,
      id_9
  );
  assign modCall_1.id_5 = 0;
endmodule
