/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [9:0] _00_;
  reg [5:0] _01_;
  reg [17:0] _02_;
  reg [5:0] _03_;
  wire [6:0] celloutsig_0_10z;
  wire [10:0] celloutsig_0_11z;
  wire [3:0] celloutsig_0_12z;
  wire [2:0] celloutsig_0_13z;
  wire [7:0] celloutsig_0_14z;
  wire [11:0] celloutsig_0_20z;
  wire [2:0] celloutsig_0_28z;
  wire [2:0] celloutsig_0_29z;
  wire [2:0] celloutsig_0_2z;
  wire [6:0] celloutsig_0_32z;
  wire [8:0] celloutsig_0_3z;
  wire celloutsig_0_47z;
  wire [22:0] celloutsig_0_49z;
  wire [5:0] celloutsig_0_4z;
  wire [5:0] celloutsig_0_50z;
  wire [2:0] celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire [10:0] celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire [2:0] celloutsig_0_9z;
  wire [13:0] celloutsig_1_0z;
  wire [4:0] celloutsig_1_18z;
  wire [8:0] celloutsig_1_19z;
  wire [6:0] celloutsig_1_2z;
  wire celloutsig_1_7z;
  wire [6:0] celloutsig_1_8z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  always_ff @(posedge celloutsig_1_19z[0], posedge clkin_data[32])
    if (clkin_data[32]) _02_ <= 18'h00000;
    else _02_ <= in_data[70:53];
  always_ff @(negedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _01_ <= 6'h00;
    else _01_ <= celloutsig_1_2z[6:1];
  always_ff @(negedge celloutsig_1_19z[0], posedge clkin_data[32])
    if (clkin_data[32]) _00_ <= 10'h000;
    else _00_ <= in_data[39:30];
  always_ff @(posedge celloutsig_1_19z[0], posedge clkin_data[32])
    if (clkin_data[32]) _03_ <= 6'h00;
    else _03_ <= celloutsig_0_32z[5:0];
  assign celloutsig_0_50z = in_data[86:81] & { _03_[4:2], celloutsig_0_13z };
  assign celloutsig_1_0z = in_data[159:146] & in_data[173:160];
  assign celloutsig_0_5z = _02_[3:1] & celloutsig_0_4z[2:0];
  assign celloutsig_1_18z = celloutsig_1_2z[4:0] & { celloutsig_1_8z[3:0], celloutsig_1_7z };
  assign celloutsig_1_19z = { celloutsig_1_2z[6:4], _01_ } & { celloutsig_1_8z[1], celloutsig_1_7z, celloutsig_1_2z };
  assign celloutsig_0_11z = { _00_, celloutsig_0_6z } & { _00_[7:4], celloutsig_0_10z };
  assign celloutsig_0_28z = _00_[4:2] & celloutsig_0_11z[3:1];
  assign celloutsig_1_2z = celloutsig_1_0z[11:5] % { 1'h1, in_data[123:118] };
  assign celloutsig_0_10z = { celloutsig_0_5z[1], celloutsig_0_4z } % { 1'h1, celloutsig_0_9z[1:0], celloutsig_0_2z, celloutsig_0_8z };
  assign celloutsig_0_12z = { _02_[8], celloutsig_0_9z } % { 1'h1, celloutsig_0_9z[2:1], in_data[0] };
  assign celloutsig_0_13z = celloutsig_0_4z[4:2] % { 1'h1, celloutsig_0_7z[5:4] };
  assign celloutsig_0_14z = { celloutsig_0_12z[2:1], celloutsig_0_13z, celloutsig_0_9z } % { 1'h1, celloutsig_0_12z[0], celloutsig_0_4z };
  assign celloutsig_0_29z = { celloutsig_0_2z[0], celloutsig_0_8z, celloutsig_0_6z } % { 1'h1, celloutsig_0_20z[1:0] };
  assign celloutsig_0_2z = - in_data[88:86];
  assign celloutsig_0_3z = - _00_[9:1];
  assign celloutsig_0_49z = - { celloutsig_0_14z[4:2], celloutsig_0_29z, celloutsig_0_13z, celloutsig_0_13z, celloutsig_0_32z, celloutsig_0_28z, celloutsig_0_47z };
  assign celloutsig_0_4z = - _02_[11:6];
  assign celloutsig_1_8z = - celloutsig_1_0z[8:2];
  assign celloutsig_0_7z = - { _02_[10:3], celloutsig_0_5z };
  assign celloutsig_0_9z = - { in_data[94:93], celloutsig_0_6z };
  assign celloutsig_0_20z = - { celloutsig_0_7z[7:1], celloutsig_0_8z, celloutsig_0_2z, celloutsig_0_6z };
  assign celloutsig_0_32z = - { celloutsig_0_28z[0], celloutsig_0_4z };
  assign celloutsig_0_47z = ^ celloutsig_0_3z[4:1];
  assign celloutsig_1_7z = ^ in_data[180:177];
  assign celloutsig_0_6z = ^ _02_[14:0];
  assign celloutsig_0_8z = ^ _02_[15:12];
  assign { out_data[132:128], out_data[104:96], out_data[54:32], out_data[5:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_49z, celloutsig_0_50z };
endmodule
