/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [11:0] _00_;
  reg [2:0] _01_;
  reg [3:0] _02_;
  reg [10:0] _03_;
  wire celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire [7:0] celloutsig_0_5z;
  wire [8:0] celloutsig_0_6z;
  wire [47:0] celloutsig_0_7z;
  wire celloutsig_1_0z;
  wire celloutsig_1_12z;
  wire celloutsig_1_18z;
  wire [7:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [6:0] celloutsig_1_2z;
  wire [6:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire [12:0] celloutsig_1_5z;
  wire [12:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_12z = celloutsig_1_4z ? celloutsig_1_0z : celloutsig_1_3z[3];
  assign celloutsig_1_0z = ~(in_data[178] | in_data[121]);
  assign celloutsig_1_7z = ~(celloutsig_1_1z | celloutsig_1_5z[0]);
  assign celloutsig_0_0z = ~in_data[10];
  assign celloutsig_0_2z = celloutsig_0_0z ^ celloutsig_0_1z;
  always_ff @(negedge celloutsig_1_18z, posedge clkin_data[32])
    if (clkin_data[32]) _01_ <= 3'h0;
    else _01_ <= in_data[34:32];
  always_ff @(negedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _02_ <= 4'h0;
    else _02_ <= { celloutsig_1_3z[2:1], celloutsig_1_1z, celloutsig_1_7z };
  reg [4:0] _11_;
  always_ff @(negedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _11_ <= 5'h00;
    else _11_ <= { celloutsig_1_6z[6], _02_ };
  assign _00_[6:2] = _11_;
  always_ff @(negedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _03_ <= 11'h000;
    else _03_ <= celloutsig_1_5z[10:0];
  assign celloutsig_1_19z = { celloutsig_1_3z[5:0], celloutsig_1_18z, celloutsig_1_4z } & { _03_[9:3], celloutsig_1_1z };
  assign celloutsig_0_5z = { in_data[50:47], celloutsig_0_0z, celloutsig_0_2z, celloutsig_0_3z, celloutsig_0_1z } / { 1'h1, in_data[10:4] };
  assign celloutsig_0_7z = in_data[70:23] / { 1'h1, in_data[23:2], celloutsig_0_5z, celloutsig_0_5z, celloutsig_0_1z, celloutsig_0_5z };
  assign celloutsig_1_1z = celloutsig_1_0z & ~(in_data[156]);
  assign celloutsig_1_4z = celloutsig_1_2z[1] & ~(celloutsig_1_1z);
  assign celloutsig_0_6z = _01_[0] ? { celloutsig_0_5z[7:1], celloutsig_0_1z, celloutsig_0_0z } : { 1'h0, celloutsig_0_5z };
  assign celloutsig_1_2z = in_data[168] ? { in_data[188:185], celloutsig_1_0z, celloutsig_1_1z, celloutsig_1_0z } : in_data[121:115];
  assign celloutsig_1_5z = celloutsig_1_0z ? { in_data[136:125], celloutsig_1_4z } : { celloutsig_1_3z[5:0], celloutsig_1_2z };
  assign celloutsig_1_6z = celloutsig_1_5z[2] ? { celloutsig_1_3z[3:0], celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_3z } : in_data[133:121];
  assign celloutsig_0_3z = celloutsig_0_2z & celloutsig_0_1z;
  assign celloutsig_1_18z = _00_[5] & celloutsig_1_12z;
  assign celloutsig_1_3z = { in_data[113:111], celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_1z } ^ in_data[132:126];
  assign celloutsig_0_1z = ~((in_data[6] & in_data[37]) | celloutsig_0_0z);
  assign { _00_[11:10], _00_[8:7], _00_[1:0] } = { celloutsig_1_6z[1:0], celloutsig_1_1z, celloutsig_1_12z, celloutsig_1_12z, celloutsig_1_7z };
  assign { out_data[128], out_data[103:96], out_data[40:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_6z, celloutsig_0_7z[43:12] };
endmodule
