/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [2:0] _01_;
  reg [2:0] _02_;
  wire [40:0] celloutsig_0_0z;
  wire [13:0] celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire [7:0] celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire [10:0] celloutsig_1_14z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [5:0] celloutsig_1_2z;
  wire [5:0] celloutsig_1_3z;
  wire [2:0] celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [3:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire [8:0] celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_5z = _00_ | celloutsig_0_0z[26];
  assign celloutsig_1_7z = celloutsig_1_2z[5] | celloutsig_1_5z;
  assign celloutsig_0_2z = celloutsig_0_0z[1] | in_data[54];
  reg [2:0] _06_;
  always_ff @(negedge clkin_data[0], posedge celloutsig_1_18z)
    if (celloutsig_1_18z) _06_ <= 3'h0;
    else _06_ <= { celloutsig_0_2z, celloutsig_0_2z, celloutsig_0_2z };
  assign { _01_[2:1], _00_ } = _06_;
  always_ff @(negedge clkin_data[32], posedge clkin_data[64])
    if (clkin_data[64]) _02_ <= 3'h0;
    else _02_ <= celloutsig_1_0z[4:2];
  assign celloutsig_0_0z = in_data[63:23] & in_data[62:22];
  assign celloutsig_1_3z = { celloutsig_1_0z[5:3], _02_ } & in_data[136:131];
  assign celloutsig_1_4z = celloutsig_1_0z[4:2] & celloutsig_1_0z[6:4];
  assign celloutsig_0_1z = celloutsig_0_0z[23:10] & celloutsig_0_0z[28:15];
  assign celloutsig_0_4z = { in_data[83:80], _01_[2:1], _00_, celloutsig_0_2z } > celloutsig_0_1z[13:6];
  assign celloutsig_1_5z = celloutsig_1_2z[4:0] > celloutsig_1_0z[7:3];
  assign celloutsig_1_18z = { celloutsig_1_14z[5], celloutsig_1_6z, celloutsig_1_2z } > { celloutsig_1_6z[2:1], celloutsig_1_9z };
  assign celloutsig_1_19z = { celloutsig_1_6z[2:1], celloutsig_1_10z, celloutsig_1_8z } || { in_data[179:177], celloutsig_1_8z };
  assign celloutsig_1_6z = { _02_, celloutsig_1_5z } * celloutsig_1_3z[5:2];
  assign celloutsig_1_9z = { celloutsig_1_4z[2:1], celloutsig_1_8z, celloutsig_1_2z } * { celloutsig_1_2z[5:3], celloutsig_1_4z, celloutsig_1_4z };
  assign celloutsig_1_14z = { celloutsig_1_10z, celloutsig_1_10z, celloutsig_1_5z, celloutsig_1_7z, celloutsig_1_10z, celloutsig_1_4z, celloutsig_1_4z } * { celloutsig_1_4z[2:1], celloutsig_1_5z, celloutsig_1_7z, celloutsig_1_10z, celloutsig_1_3z };
  assign celloutsig_1_8z = { celloutsig_1_2z[5:4], celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_7z } != { _02_[1], celloutsig_1_0z, celloutsig_1_7z, celloutsig_1_7z, celloutsig_1_5z };
  assign celloutsig_1_10z = { celloutsig_1_0z[6], celloutsig_1_7z, celloutsig_1_8z } != celloutsig_1_4z;
  assign celloutsig_1_0z = ~ in_data[153:146];
  assign celloutsig_1_2z = { celloutsig_1_0z[4:2], _02_ } ^ celloutsig_1_0z[6:1];
  assign _01_[0] = _00_;
  assign { out_data[128], out_data[96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_4z, celloutsig_0_5z };
endmodule
