/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [23:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire celloutsig_0_11z;
  wire [3:0] celloutsig_0_12z;
  wire celloutsig_0_14z;
  wire [9:0] celloutsig_0_15z;
  wire celloutsig_0_18z;
  wire celloutsig_0_1z;
  wire celloutsig_0_21z;
  wire celloutsig_0_25z;
  wire celloutsig_0_26z;
  wire [6:0] celloutsig_0_2z;
  wire [9:0] celloutsig_0_3z;
  reg [18:0] celloutsig_0_4z;
  wire [4:0] celloutsig_0_5z;
  wire celloutsig_0_6z;
  reg [7:0] celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire [4:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire celloutsig_1_11z;
  wire celloutsig_1_13z;
  wire celloutsig_1_18z;
  wire [3:0] celloutsig_1_19z;
  wire [15:0] celloutsig_1_1z;
  wire [3:0] celloutsig_1_3z;
  reg [2:0] celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire [7:0] celloutsig_1_7z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_8z = ~celloutsig_0_1z;
  assign celloutsig_0_14z = ~celloutsig_0_11z;
  assign celloutsig_1_11z = celloutsig_1_6z | ~(in_data[159]);
  assign celloutsig_0_21z = celloutsig_0_2z[6] | ~(celloutsig_0_14z);
  assign celloutsig_0_15z = { celloutsig_0_3z[4], celloutsig_0_10z, celloutsig_0_7z } & { celloutsig_0_1z, celloutsig_0_11z, celloutsig_0_7z };
  assign celloutsig_1_1z = { in_data[182:170], celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z } & in_data[189:174];
  assign celloutsig_1_19z = { celloutsig_1_7z[2:0], celloutsig_1_5z } / { 1'h1, in_data[106:105], celloutsig_1_11z };
  assign celloutsig_1_13z = { in_data[103:102], celloutsig_1_11z, celloutsig_1_0z } >= celloutsig_1_1z[13:10];
  assign celloutsig_0_18z = celloutsig_0_2z[6:3] && celloutsig_0_12z;
  assign celloutsig_0_10z = celloutsig_0_9z[3] & ~(celloutsig_0_7z[6]);
  assign celloutsig_0_3z = in_data[29:20] * { in_data[17:9], celloutsig_0_1z };
  assign celloutsig_1_7z = ~ { celloutsig_1_4z[2:1], celloutsig_1_0z, celloutsig_1_3z, celloutsig_1_5z };
  assign celloutsig_0_12z = ~ { in_data[62:61], celloutsig_0_6z, celloutsig_0_11z };
  assign celloutsig_0_5z = celloutsig_0_4z[8:4] | { celloutsig_0_4z[6:3], celloutsig_0_1z };
  assign celloutsig_0_2z = { celloutsig_0_0z[5:0], celloutsig_0_1z } | { in_data[48:43], celloutsig_0_1z };
  assign celloutsig_1_6z = & in_data[154:140];
  assign celloutsig_0_6z = celloutsig_0_4z[1] & celloutsig_0_0z[6];
  assign celloutsig_0_25z = celloutsig_0_10z & celloutsig_0_18z;
  assign celloutsig_1_0z = in_data[191] & in_data[125];
  assign celloutsig_1_5z = ^ in_data[181:176];
  assign celloutsig_1_3z = { in_data[145:143], celloutsig_1_0z } - in_data[133:130];
  assign celloutsig_0_9z = { in_data[60:57], celloutsig_0_8z } ^ celloutsig_0_4z[9:5];
  assign celloutsig_0_1z = ~((celloutsig_0_0z[5] & in_data[47]) | in_data[95]);
  always_latch
    if (!celloutsig_1_19z[0]) celloutsig_0_0z = 24'h000000;
    else if (!clkin_data[0]) celloutsig_0_0z = in_data[40:17];
  always_latch
    if (clkin_data[64]) celloutsig_1_4z = 3'h0;
    else if (clkin_data[32]) celloutsig_1_4z = { celloutsig_1_3z[2:1], celloutsig_1_0z };
  always_latch
    if (!celloutsig_1_19z[0]) celloutsig_0_4z = 19'h00000;
    else if (clkin_data[0]) celloutsig_0_4z = { in_data[37:20], celloutsig_0_1z };
  always_latch
    if (celloutsig_1_19z[0]) celloutsig_0_7z = 8'h00;
    else if (clkin_data[0]) celloutsig_0_7z = { in_data[61:55], celloutsig_0_6z };
  assign celloutsig_1_18z = ~((celloutsig_1_5z & celloutsig_1_13z) | (celloutsig_1_1z[14] & celloutsig_1_6z));
  assign celloutsig_0_11z = ~((celloutsig_0_9z[4] & celloutsig_0_1z) | (celloutsig_0_2z[2] & celloutsig_0_5z[1]));
  assign celloutsig_0_26z = ~((celloutsig_0_15z[9] & celloutsig_0_25z) | (celloutsig_0_6z & celloutsig_0_21z));
  assign { out_data[128], out_data[99:96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_25z, celloutsig_0_26z };
endmodule
