/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [22:0] _00_;
  wire celloutsig_0_0z;
  wire [25:0] celloutsig_0_10z;
  wire [8:0] celloutsig_0_11z;
  wire [24:0] celloutsig_0_16z;
  wire celloutsig_0_1z;
  wire [10:0] celloutsig_0_2z;
  wire [11:0] celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire [5:0] celloutsig_0_58z;
  reg [11:0] celloutsig_0_59z;
  wire [5:0] celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire [5:0] celloutsig_0_9z;
  wire [6:0] celloutsig_1_0z;
  wire [7:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [12:0] celloutsig_1_3z;
  wire [10:0] celloutsig_1_4z;
  reg [5:0] celloutsig_1_5z;
  wire [11:0] celloutsig_1_7z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_2z = ~(celloutsig_1_1z | in_data[165]);
  assign celloutsig_0_0z = in_data[43] | in_data[29];
  assign celloutsig_0_58z = _00_[20:15] + celloutsig_0_16z[14:9];
  assign celloutsig_0_2z = { in_data[45:36], celloutsig_0_1z } + { in_data[19:13], celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_1z };
  reg [10:0] _05_;
  always_ff @(posedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _05_ <= 11'h000;
    else _05_ <= celloutsig_0_3z[10:0];
  assign _00_[20:10] = _05_;
  assign celloutsig_0_4z = { celloutsig_0_3z[6:0], celloutsig_0_0z } === celloutsig_0_2z[8:1];
  assign celloutsig_1_19z = in_data[183:179] === celloutsig_1_4z[6:2];
  assign celloutsig_0_1z = { in_data[48:47], celloutsig_0_0z, celloutsig_0_0z } > { in_data[83:82], celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_1_1z = in_data[127] & ~(in_data[109]);
  assign celloutsig_0_8z = celloutsig_0_6z[1] & ~(in_data[42]);
  assign celloutsig_0_3z = { in_data[19], celloutsig_0_2z } % { 1'h1, celloutsig_0_2z[10:1], in_data[0] };
  assign celloutsig_1_0z = in_data[137:131] % { 1'h1, in_data[105:100] };
  assign celloutsig_0_6z = { in_data[56:52], celloutsig_0_1z } % { 1'h1, in_data[39:35] };
  assign celloutsig_0_9z = { celloutsig_0_3z[8:5], celloutsig_0_0z, celloutsig_0_4z } % { 1'h1, in_data[34:33], celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_7z };
  assign celloutsig_0_10z = { in_data[72:69], celloutsig_0_0z, celloutsig_0_3z, celloutsig_0_7z, celloutsig_0_0z, celloutsig_0_9z, celloutsig_0_8z } % { 1'h1, celloutsig_0_4z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_8z, celloutsig_0_7z, celloutsig_0_9z, celloutsig_0_9z, celloutsig_0_1z, celloutsig_0_6z, in_data[0] };
  assign celloutsig_0_16z = { celloutsig_0_6z, celloutsig_0_7z, celloutsig_0_4z, celloutsig_0_9z, celloutsig_0_11z, celloutsig_0_0z, celloutsig_0_1z } % { 1'h1, celloutsig_0_10z[22:1], celloutsig_0_0z, celloutsig_0_4z };
  assign celloutsig_1_3z = { in_data[110:99], celloutsig_1_2z } * { in_data[179:169], celloutsig_1_1z, celloutsig_1_2z };
  assign celloutsig_1_7z = celloutsig_1_3z[12:1] * { celloutsig_1_5z[4:1], celloutsig_1_0z, celloutsig_1_1z };
  assign celloutsig_1_4z = ~ { celloutsig_1_3z[3:0], celloutsig_1_0z };
  assign celloutsig_0_7z = | celloutsig_0_3z[11:3];
  assign celloutsig_1_18z = { celloutsig_1_7z[7:1], celloutsig_1_2z } << { in_data[175], celloutsig_1_0z };
  assign celloutsig_0_11z = { celloutsig_0_3z[11], celloutsig_0_4z, celloutsig_0_7z, celloutsig_0_8z, celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_7z, celloutsig_0_1z } >> in_data[21:13];
  always_latch
    if (!clkin_data[32]) celloutsig_0_59z = 12'h000;
    else if (celloutsig_1_18z[0]) celloutsig_0_59z = celloutsig_0_16z[15:4];
  always_latch
    if (clkin_data[96]) celloutsig_1_5z = 6'h00;
    else if (!clkin_data[128]) celloutsig_1_5z = { celloutsig_1_4z[9:5], celloutsig_1_2z };
  assign { _00_[21], _00_[8] } = { celloutsig_0_8z, celloutsig_0_1z };
  assign { out_data[135:128], out_data[96], out_data[37:32], out_data[11:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_58z, celloutsig_0_59z };
endmodule
