/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [23:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire celloutsig_0_11z;
  reg [11:0] celloutsig_0_12z;
  wire celloutsig_0_19z;
  reg [18:0] celloutsig_0_1z;
  wire celloutsig_0_22z;
  wire celloutsig_0_2z;
  wire celloutsig_0_34z;
  wire celloutsig_0_3z;
  reg [4:0] celloutsig_0_40z;
  wire [13:0] celloutsig_0_41z;
  wire celloutsig_0_4z;
  wire [8:0] celloutsig_0_5z;
  wire [18:0] celloutsig_0_6z;
  wire [14:0] celloutsig_0_8z;
  reg [19:0] celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire celloutsig_1_12z;
  wire [20:0] celloutsig_1_13z;
  wire [3:0] celloutsig_1_15z;
  wire celloutsig_1_16z;
  wire [2:0] celloutsig_1_18z;
  wire [4:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [2:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire [5:0] celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_19z = ~((celloutsig_0_1z[0] | celloutsig_0_8z[0]) & (celloutsig_0_3z | celloutsig_0_5z[5]));
  assign celloutsig_0_2z = in_data[86] | in_data[74];
  assign celloutsig_0_4z = ~(celloutsig_0_3z ^ in_data[2]);
  assign celloutsig_1_6z = ~(in_data[170] ^ celloutsig_1_1z);
  assign celloutsig_1_2z = in_data[122:120] + in_data[144:142];
  assign celloutsig_1_1z = in_data[168:160] && celloutsig_1_0z[9:1];
  assign celloutsig_1_9z = in_data[156:149] && { celloutsig_1_0z[12:8], celloutsig_1_2z };
  assign celloutsig_0_34z = ! celloutsig_0_0z[10:3];
  assign celloutsig_0_3z = ! in_data[40:27];
  assign celloutsig_1_4z = ! { celloutsig_1_2z[2], celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_3z };
  assign celloutsig_1_7z = ! celloutsig_1_5z[4:1];
  assign celloutsig_0_41z = { celloutsig_0_12z[3:1], celloutsig_0_22z, celloutsig_0_34z, celloutsig_0_5z } % { 1'h1, celloutsig_0_0z[17:5] };
  assign celloutsig_1_5z = { in_data[129:127], celloutsig_1_2z } % { 1'h1, in_data[102:100], celloutsig_1_4z, celloutsig_1_1z };
  assign celloutsig_1_15z = in_data[138:135] % { 1'h1, celloutsig_1_7z, celloutsig_1_7z, celloutsig_1_7z };
  assign celloutsig_1_19z = { celloutsig_1_15z[2:1], celloutsig_1_16z, celloutsig_1_3z, celloutsig_1_8z } % { 1'h1, celloutsig_1_5z[2:0], celloutsig_1_3z };
  assign celloutsig_1_3z = | celloutsig_1_2z;
  assign celloutsig_1_8z = | { celloutsig_1_6z, celloutsig_1_5z[4:3], celloutsig_1_4z, celloutsig_1_2z, celloutsig_1_1z };
  assign celloutsig_0_10z = | celloutsig_0_0z[7:3];
  assign celloutsig_1_10z = ^ celloutsig_1_5z[5:3];
  assign celloutsig_1_16z = ^ { celloutsig_1_15z[2:0], celloutsig_1_3z };
  assign celloutsig_0_11z = ^ { celloutsig_0_0z[15:3], celloutsig_0_10z };
  assign celloutsig_0_22z = ^ celloutsig_0_12z[6:1];
  assign celloutsig_0_6z = celloutsig_0_0z[20:2] <<< { celloutsig_0_0z[11:3], celloutsig_0_5z, celloutsig_0_4z };
  assign celloutsig_0_8z = celloutsig_0_1z[17:3] <<< celloutsig_0_6z[15:1];
  assign celloutsig_1_13z = { celloutsig_1_0z[15:6], celloutsig_1_12z, celloutsig_1_12z, celloutsig_1_1z, celloutsig_1_5z, celloutsig_1_9z, celloutsig_1_11z } - { celloutsig_1_0z[19:1], celloutsig_1_11z, celloutsig_1_7z };
  assign celloutsig_0_5z = celloutsig_0_0z[8:0] - celloutsig_0_1z[9:1];
  assign celloutsig_1_18z = { in_data[140:139], celloutsig_1_7z } - celloutsig_1_13z[10:8];
  always_latch
    if (!clkin_data[64]) celloutsig_0_0z = 24'h000000;
    else if (celloutsig_1_19z[0]) celloutsig_0_0z = in_data[39:16];
  always_latch
    if (!clkin_data[32]) celloutsig_0_40z = 5'h00;
    else if (celloutsig_1_19z[0]) celloutsig_0_40z = { celloutsig_0_12z[4:1], celloutsig_0_19z };
  always_latch
    if (!clkin_data[96]) celloutsig_1_0z = 20'h00000;
    else if (clkin_data[0]) celloutsig_1_0z = in_data[137:118];
  always_latch
    if (clkin_data[64]) celloutsig_0_12z = 12'h000;
    else if (!celloutsig_1_19z[0]) celloutsig_0_12z = { celloutsig_0_1z[14:7], celloutsig_0_2z, celloutsig_0_2z, celloutsig_0_11z, celloutsig_0_11z };
  always_latch
    if (clkin_data[32]) celloutsig_0_1z = 19'h00000;
    else if (celloutsig_1_19z[0]) celloutsig_0_1z = in_data[54:36];
  assign celloutsig_1_11z = ~((in_data[148] & celloutsig_1_10z) | (celloutsig_1_8z & celloutsig_1_2z[1]));
  assign celloutsig_1_12z = ~((celloutsig_1_5z[0] & celloutsig_1_11z) | (in_data[152] & celloutsig_1_10z));
  assign { out_data[130:128], out_data[100:96], out_data[36:32], out_data[13:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_40z, celloutsig_0_41z };
endmodule
