/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [8:0] _00_;
  wire celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire [4:0] celloutsig_0_2z;
  wire celloutsig_0_54z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire celloutsig_1_12z;
  wire celloutsig_1_15z;
  wire [4:0] celloutsig_1_18z;
  wire [10:0] celloutsig_1_19z;
  wire [9:0] celloutsig_1_1z;
  wire [3:0] celloutsig_1_2z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [3:0] celloutsig_1_6z;
  wire [9:0] celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire [13:0] celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_54z = ~out_data[33];
  assign celloutsig_1_4z = ~in_data[96];
  assign celloutsig_1_15z = ~celloutsig_1_12z;
  assign celloutsig_0_0z = ~(in_data[6] ^ in_data[25]);
  assign celloutsig_0_1z = ~(in_data[79] ^ celloutsig_0_0z);
  assign celloutsig_1_1z = in_data[153:144] + { in_data[107:100], celloutsig_1_0z, celloutsig_1_0z };
  reg [2:0] _07_;
  always_ff @(posedge celloutsig_1_18z[0], posedge clkin_data[96])
    if (clkin_data[96]) _07_ <= 3'h0;
    else _07_ <= celloutsig_0_2z[3:1];
  assign out_data[34:32] = _07_;
  always_ff @(negedge clkin_data[32], negedge clkin_data[128])
    if (!clkin_data[128]) _00_ <= 9'h000;
    else _00_ <= { in_data[152:145], celloutsig_1_0z };
  assign celloutsig_1_10z = { celloutsig_1_6z, _00_ } == { _00_[8:1], celloutsig_1_6z, celloutsig_1_0z };
  assign celloutsig_1_8z = { celloutsig_1_1z[8:1], celloutsig_1_0z } > { celloutsig_1_5z, celloutsig_1_6z, celloutsig_1_5z, celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_5z };
  assign celloutsig_1_5z = { in_data[140:130], _00_, celloutsig_1_2z, celloutsig_1_2z } || { celloutsig_1_0z, _00_, celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_2z };
  assign celloutsig_1_12z = celloutsig_1_7z[1] & ~(celloutsig_1_1z[1]);
  assign celloutsig_0_2z = { in_data[1], celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_1z, celloutsig_0_0z } % { 1'h1, celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_1z };
  assign celloutsig_1_9z = { _00_[5:3], celloutsig_1_7z, celloutsig_1_4z } * { celloutsig_1_1z[2:1], celloutsig_1_0z, celloutsig_1_8z, celloutsig_1_7z };
  assign celloutsig_1_2z = celloutsig_1_0z ? in_data[149:146] : { celloutsig_1_1z[3:1], 1'h0 };
  assign celloutsig_1_6z = ~ { _00_[8:6], celloutsig_1_4z };
  assign celloutsig_1_18z = ~ in_data[146:142];
  assign celloutsig_1_0z = | in_data[142:119];
  assign celloutsig_1_19z = { _00_[5:1], celloutsig_1_6z, celloutsig_1_15z, celloutsig_1_8z } >> { celloutsig_1_9z[13:4], celloutsig_1_10z };
  assign celloutsig_1_7z = { in_data[188:180], celloutsig_1_4z } ^ { celloutsig_1_1z[1], _00_ };
  assign { out_data[132:128], out_data[106:96], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_54z };
endmodule
