/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [25:0] celloutsig_0_0z;
  wire celloutsig_0_15z;
  wire [13:0] celloutsig_0_16z;
  wire celloutsig_0_1z;
  wire [3:0] celloutsig_0_2z;
  wire [14:0] celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire [29:0] celloutsig_0_5z;
  wire [13:0] celloutsig_0_6z;
  reg [27:0] celloutsig_0_7z;
  wire celloutsig_1_0z;
  wire [14:0] celloutsig_1_10z;
  wire celloutsig_1_14z;
  wire celloutsig_1_17z;
  reg [10:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [2:0] celloutsig_1_1z;
  reg [2:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire [5:0] celloutsig_1_4z;
  wire [18:0] celloutsig_1_6z;
  wire [2:0] celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_4z = ~(celloutsig_0_1z | celloutsig_0_3z[6]);
  assign celloutsig_1_3z = ~(in_data[124] | in_data[127]);
  assign celloutsig_1_14z = ~(celloutsig_1_6z[13] | celloutsig_1_2z[0]);
  assign celloutsig_1_19z = ~((celloutsig_1_6z[1] | celloutsig_1_17z) & (celloutsig_1_14z | celloutsig_1_9z[1]));
  assign celloutsig_1_0z = ~((in_data[173] | in_data[151]) & (in_data[166] | in_data[105]));
  assign celloutsig_0_2z = - in_data[89:86];
  assign celloutsig_1_4z = - { celloutsig_1_3z, celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_3z };
  assign celloutsig_1_10z = - { in_data[164:152], celloutsig_1_3z, celloutsig_1_0z };
  assign celloutsig_1_17z = ^ celloutsig_1_2z;
  assign celloutsig_0_1z = ^ celloutsig_0_0z[23:16];
  assign celloutsig_0_15z = ^ celloutsig_0_7z[7:4];
  assign celloutsig_0_0z = in_data[25:0] << in_data[29:4];
  assign celloutsig_0_5z = { in_data[27:0], celloutsig_0_1z, celloutsig_0_4z } << { in_data[59:31], celloutsig_0_4z };
  assign celloutsig_1_9z = { celloutsig_1_2z[2:1], celloutsig_1_0z } << in_data[122:120];
  assign celloutsig_0_16z = celloutsig_0_7z[17:4] >> in_data[63:50];
  assign celloutsig_1_1z = { in_data[125:124], celloutsig_1_0z } >> { in_data[137:136], celloutsig_1_0z };
  assign celloutsig_0_6z = in_data[30:17] >>> celloutsig_0_5z[27:14];
  assign celloutsig_1_6z = in_data[133:115] >>> { in_data[170:164], celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_4z };
  assign celloutsig_0_3z = { celloutsig_0_0z[21:11], celloutsig_0_2z } >>> celloutsig_0_0z[20:6];
  always_latch
    if (!clkin_data[64]) celloutsig_1_18z = 11'h000;
    else if (!clkin_data[0]) celloutsig_1_18z = celloutsig_1_10z[14:4];
  always_latch
    if (clkin_data[32]) celloutsig_0_7z = 28'h0000000;
    else if (!celloutsig_1_18z[0]) celloutsig_0_7z = { celloutsig_0_3z[14:7], celloutsig_0_1z, celloutsig_0_2z, celloutsig_0_4z, celloutsig_0_6z };
  always_latch
    if (!clkin_data[64]) celloutsig_1_2z = 3'h0;
    else if (clkin_data[0]) celloutsig_1_2z = { in_data[163], celloutsig_1_0z, celloutsig_1_0z };
  assign { out_data[138:128], out_data[96], out_data[32], out_data[13:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_15z, celloutsig_0_16z };
endmodule
