/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire [13:0] celloutsig_0_1z;
  reg [6:0] celloutsig_0_2z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire celloutsig_1_16z;
  wire celloutsig_1_18z;
  wire [3:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire [8:0] celloutsig_1_7z;
  wire celloutsig_1_8z;
  input [31:0] clkin_data;
  wire [31:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_0z = ~(in_data[101] & in_data[129]);
  assign celloutsig_1_18z = ~(celloutsig_1_10z & celloutsig_1_8z);
  assign celloutsig_1_8z = ~celloutsig_1_1z;
  assign celloutsig_1_10z = ~celloutsig_1_3z;
  assign celloutsig_1_7z = { in_data[109:106], celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_5z, celloutsig_1_5z } + { in_data[132:131], celloutsig_1_6z, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_6z, celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_0z };
  assign celloutsig_1_6z = { in_data[149:143], celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_0z, celloutsig_1_3z } > in_data[167:157];
  assign celloutsig_1_16z = in_data[134:131] || { celloutsig_1_7z[7:6], celloutsig_1_5z, celloutsig_1_2z };
  assign celloutsig_1_1z = { in_data[183:182], celloutsig_1_0z } < in_data[122:120];
  assign celloutsig_0_1z = in_data[45:32] % { 1'h1, in_data[60:49], celloutsig_0_0z };
  assign celloutsig_1_5z = | in_data[142:139];
  assign celloutsig_1_2z = ~^ in_data[124:111];
  assign celloutsig_0_0z = ^ in_data[90:87];
  assign celloutsig_1_3z = ^ { in_data[174:173], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_1z };
  assign celloutsig_1_19z = { celloutsig_1_6z, celloutsig_1_16z, celloutsig_1_2z, celloutsig_1_4z } >> { celloutsig_1_7z[7:5], celloutsig_1_0z };
  always_latch
    if (celloutsig_1_19z[0]) celloutsig_0_2z = 7'h00;
    else if (!clkin_data[0]) celloutsig_0_2z = celloutsig_0_1z[9:3];
  assign celloutsig_1_4z = ~((celloutsig_1_2z & celloutsig_1_3z) | (celloutsig_1_0z & celloutsig_1_1z));
  assign { out_data[128], out_data[99:96], out_data[45:32], out_data[6:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_1z, celloutsig_0_2z };
endmodule
