/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire _01_;
  wire [13:0] _02_;
  wire celloutsig_0_11z;
  reg [5:0] celloutsig_0_13z;
  wire celloutsig_0_1z;
  reg [13:0] celloutsig_0_24z;
  wire celloutsig_0_26z;
  wire [7:0] celloutsig_0_27z;
  wire celloutsig_0_28z;
  wire [12:0] celloutsig_0_2z;
  wire [7:0] celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire [12:0] celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire [2:0] celloutsig_0_7z;
  wire [3:0] celloutsig_1_0z;
  reg [5:0] celloutsig_1_14z;
  wire celloutsig_1_17z;
  wire [2:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [7:0] celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [2:0] celloutsig_1_3z;
  wire [7:0] celloutsig_1_4z;
  wire celloutsig_1_5z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_5z = ~(celloutsig_1_2z | celloutsig_1_3z[2]);
  assign celloutsig_0_11z = ~(celloutsig_0_7z[1] | celloutsig_0_5z[4]);
  assign celloutsig_0_1z = ~(in_data[59] | in_data[58]);
  assign celloutsig_0_26z = ~(celloutsig_0_5z[1] | celloutsig_0_2z[4]);
  assign celloutsig_1_2z = ~(celloutsig_1_1z[0] | in_data[118]);
  assign celloutsig_0_6z = _00_ | ~(celloutsig_0_3z[4]);
  assign celloutsig_1_18z = celloutsig_1_3z + { celloutsig_1_17z, celloutsig_1_5z, celloutsig_1_17z };
  reg [13:0] _10_;
  always_ff @(posedge clkin_data[0], posedge celloutsig_1_18z[0])
    if (celloutsig_1_18z[0]) _10_ <= 14'h0000;
    else _10_ <= in_data[41:28];
  assign { _02_[13], _01_, _02_[11:5], _00_, _02_[3:0] } = _10_;
  assign celloutsig_1_19z = celloutsig_1_14z[2:0] === celloutsig_1_3z;
  assign celloutsig_0_28z = { celloutsig_0_27z[4], celloutsig_0_11z, celloutsig_0_7z } === celloutsig_0_24z[8:4];
  assign celloutsig_0_4z = { celloutsig_0_2z, celloutsig_0_2z } >= { _01_, _02_[11:5], _00_, _02_[3:0], celloutsig_0_2z };
  assign celloutsig_1_0z = in_data[100:97] % { 1'h1, in_data[169:167] };
  assign celloutsig_1_1z = { in_data[162:159], celloutsig_1_0z } % { 1'h1, in_data[113:107] };
  assign celloutsig_1_3z = { celloutsig_1_1z[2], celloutsig_1_2z, celloutsig_1_2z } % { 1'h1, celloutsig_1_1z[6:5] };
  assign celloutsig_0_5z = _02_[7] ? { celloutsig_0_2z[12:10], celloutsig_0_3z, celloutsig_0_4z, celloutsig_0_1z } : in_data[32:20];
  assign celloutsig_0_3z = in_data[33:26] | celloutsig_0_2z[10:3];
  assign celloutsig_0_2z = { _01_, _02_[11:5], _00_, _02_[3:0] } | { _02_[11:5], _00_, _02_[3:0], celloutsig_0_1z };
  assign celloutsig_1_17z = | celloutsig_1_14z;
  assign celloutsig_1_4z = { in_data[187:184], celloutsig_1_0z } << celloutsig_1_1z;
  assign celloutsig_0_7z = { celloutsig_0_3z[2:1], celloutsig_0_6z } >> celloutsig_0_2z[7:5];
  assign celloutsig_0_27z = celloutsig_0_5z[7:0] >> { celloutsig_0_13z, celloutsig_0_26z, celloutsig_0_11z };
  always_latch
    if (!clkin_data[32]) celloutsig_1_14z = 6'h00;
    else if (clkin_data[96]) celloutsig_1_14z = celloutsig_1_4z[5:0];
  always_latch
    if (celloutsig_1_18z[0]) celloutsig_0_13z = 6'h00;
    else if (!clkin_data[64]) celloutsig_0_13z = in_data[31:26];
  always_latch
    if (!celloutsig_1_18z[0]) celloutsig_0_24z = 14'h0000;
    else if (!clkin_data[64]) celloutsig_0_24z = { _02_[13], _01_, _02_[11:5], _00_, _02_[3:0] };
  assign { _02_[12], _02_[4] } = { _01_, _00_ };
  assign { out_data[130:128], out_data[96], out_data[39:32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_27z, celloutsig_0_28z };
endmodule
