/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [6:0] _00_;
  wire celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire celloutsig_0_5z;
  wire [3:0] celloutsig_0_7z;
  wire celloutsig_1_0z;
  wire [4:0] celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire celloutsig_1_18z;
  wire [2:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  reg [7:0] celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_1z = ~((in_data[22] | celloutsig_0_0z) & (in_data[10] | in_data[65]));
  assign celloutsig_1_7z = ~((celloutsig_1_2z | celloutsig_1_2z) & (celloutsig_1_0z | celloutsig_1_4z));
  assign celloutsig_1_2z = in_data[114] ^ celloutsig_1_0z;
  reg [5:0] _04_;
  always_ff @(negedge clkin_data[0], posedge celloutsig_1_18z)
    if (celloutsig_1_18z) _04_ <= 6'h00;
    else _04_ <= { celloutsig_0_7z, celloutsig_0_0z, celloutsig_0_2z };
  assign out_data[37:32] = _04_;
  always_ff @(posedge clkin_data[32], negedge clkin_data[64])
    if (!clkin_data[64]) _00_ <= 7'h00;
    else _00_ <= { celloutsig_1_11z, celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_1z, celloutsig_1_0z, celloutsig_1_9z, celloutsig_1_1z };
  assign celloutsig_0_0z = in_data[51:34] >= in_data[89:72];
  assign celloutsig_0_3z = { in_data[22:19], celloutsig_0_1z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_2z, celloutsig_0_1z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_0z } >= { in_data[40:34], celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_2z, celloutsig_0_0z, celloutsig_0_1z };
  assign celloutsig_1_0z = in_data[143:141] >= in_data[131:129];
  assign celloutsig_1_6z = celloutsig_1_5z[4:2] > { celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_2z };
  assign celloutsig_1_8z = { in_data[118:106], celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_4z, celloutsig_1_2z, celloutsig_1_6z, celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_7z, celloutsig_1_1z, celloutsig_1_4z } > { in_data[141:132], celloutsig_1_2z, celloutsig_1_7z, celloutsig_1_2z, celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_6z };
  assign celloutsig_1_9z = { in_data[186:182], celloutsig_1_6z, celloutsig_1_0z } > { celloutsig_1_6z, celloutsig_1_8z, celloutsig_1_3z, celloutsig_1_6z, celloutsig_1_8z, celloutsig_1_2z, celloutsig_1_0z };
  assign celloutsig_1_11z = { celloutsig_1_10z, celloutsig_1_9z, celloutsig_1_7z, celloutsig_1_2z, celloutsig_1_6z } > in_data[156:148];
  assign celloutsig_1_18z = in_data[144] & ~(celloutsig_1_8z);
  assign celloutsig_1_1z = in_data[128:124] != in_data[155:151];
  assign celloutsig_1_4z = { in_data[101:97], celloutsig_1_2z } != { in_data[187:186], celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_1z };
  assign celloutsig_1_10z = { in_data[168], celloutsig_1_3z, celloutsig_1_8z, celloutsig_1_6z, celloutsig_1_1z } | { celloutsig_1_7z, celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_6z, celloutsig_1_2z };
  assign celloutsig_0_5z = | { celloutsig_0_3z, celloutsig_0_1z, in_data[44:34], in_data[13:5] };
  assign celloutsig_0_2z = | { celloutsig_0_1z, in_data[13:5] };
  assign celloutsig_1_19z = { _00_[3:2], celloutsig_1_4z } ~^ in_data[142:140];
  assign celloutsig_0_7z = { in_data[73:71], celloutsig_0_0z } ~^ in_data[24:21];
  always_latch
    if (clkin_data[64]) celloutsig_1_5z = 8'h00;
    else if (!clkin_data[96]) celloutsig_1_5z = { in_data[115:111], celloutsig_1_4z, celloutsig_1_1z, celloutsig_1_2z };
  assign celloutsig_1_3z = ~((celloutsig_1_2z & celloutsig_1_1z) | (celloutsig_1_1z & celloutsig_1_1z));
  assign { out_data[1], out_data[6:2] } = ~ { celloutsig_0_5z, in_data[55:51] };
  assign { out_data[128], out_data[98:96], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, out_data[1] };
endmodule
