/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire [2:0] celloutsig_0_10z;
  wire celloutsig_0_11z;
  wire [4:0] celloutsig_0_15z;
  wire celloutsig_0_16z;
  wire celloutsig_0_1z;
  wire [6:0] celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire [6:0] celloutsig_0_6z;
  reg [6:0] celloutsig_0_7z;
  reg [8:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire [4:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [10:0] celloutsig_1_1z;
  wire [8:0] celloutsig_1_2z;
  wire [3:0] celloutsig_1_3z;
  reg [17:0] celloutsig_1_5z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_0z = in_data[57] | in_data[5];
  assign celloutsig_1_3z = { celloutsig_1_1z[9:7], celloutsig_1_0z } & { celloutsig_1_2z[5:4], celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_0_2z = in_data[57:51] & { in_data[64:63], celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_0z };
  assign celloutsig_0_1z = in_data[27] & ~(in_data[1]);
  assign celloutsig_1_18z = - celloutsig_1_1z[4:0];
  assign celloutsig_0_3z = & in_data[78:58];
  assign celloutsig_1_19z = & { celloutsig_1_5z[9:6], celloutsig_1_3z, celloutsig_1_2z };
  assign celloutsig_1_0z = | in_data[166:164];
  assign celloutsig_0_16z = celloutsig_0_2z[6] & celloutsig_0_9z[0];
  assign celloutsig_0_10z = celloutsig_0_6z[2:0] >> celloutsig_0_6z[5:3];
  assign celloutsig_1_1z = { in_data[169:160], celloutsig_1_0z } >> in_data[167:157];
  assign celloutsig_1_2z = in_data[159:151] >> celloutsig_1_1z[10:2];
  assign celloutsig_0_6z = { celloutsig_0_2z[5:0], celloutsig_0_4z } ~^ celloutsig_0_2z;
  assign celloutsig_0_15z = celloutsig_0_7z[4:0] ^ { celloutsig_0_10z[2:1], celloutsig_0_1z, celloutsig_0_11z, celloutsig_0_0z };
  assign celloutsig_0_4z = ~((in_data[66] & celloutsig_0_3z) | celloutsig_0_3z);
  assign celloutsig_0_11z = ~((celloutsig_0_2z[1] & celloutsig_0_3z) | celloutsig_0_4z);
  always_latch
    if (clkin_data[64]) celloutsig_0_7z = 7'h00;
    else if (!celloutsig_1_18z[0]) celloutsig_0_7z = celloutsig_0_2z;
  always_latch
    if (clkin_data[32]) celloutsig_0_9z = 9'h000;
    else if (celloutsig_1_18z[0]) celloutsig_0_9z = { celloutsig_0_0z, celloutsig_0_4z, celloutsig_0_7z };
  always_latch
    if (clkin_data[96]) celloutsig_1_5z = 18'h00000;
    else if (clkin_data[0]) celloutsig_1_5z = { celloutsig_1_1z[2:0], celloutsig_1_1z, celloutsig_1_3z };
  assign { out_data[132:128], out_data[96], out_data[36:32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_15z, celloutsig_0_16z };
endmodule
