/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire [2:0] celloutsig_0_1z;
  wire [6:0] celloutsig_0_2z;
  wire [8:0] celloutsig_0_3z;
  wire celloutsig_0_5z;
  wire [15:0] celloutsig_1_0z;
  wire celloutsig_1_13z;
  wire celloutsig_1_18z;
  wire [4:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [19:0] celloutsig_1_3z;
  wire [5:0] celloutsig_1_4z;
  wire [9:0] celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire celloutsig_1_9z;
  input [31:0] clkin_data;
  wire [31:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_5z = ~((celloutsig_0_2z[3] | in_data[53]) & (celloutsig_0_3z[3] | celloutsig_0_1z[1]));
  assign celloutsig_0_2z = { celloutsig_0_1z[1], celloutsig_0_1z, celloutsig_0_1z } + { in_data[62:57], celloutsig_0_0z };
  reg [8:0] _02_;
  always_ff @(negedge celloutsig_1_19z[0], posedge clkin_data[0])
    if (clkin_data[0]) _02_ <= 9'h000;
    else _02_ <= { in_data[14], celloutsig_0_2z, celloutsig_0_0z };
  assign out_data[8:0] = _02_;
  assign celloutsig_1_5z = celloutsig_1_3z[11:2] & celloutsig_1_0z[10:1];
  assign celloutsig_1_19z = celloutsig_1_5z[9:5] & celloutsig_1_4z[4:0];
  assign celloutsig_1_4z = { celloutsig_1_0z[15], 2'h3, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_1z } / { 1'h1, celloutsig_1_0z[4:3], 1'h1, celloutsig_1_1z, in_data[96] };
  assign celloutsig_1_6z = celloutsig_1_3z[15:8] > celloutsig_1_3z[18:11];
  assign celloutsig_1_9z = { celloutsig_1_0z[11], celloutsig_1_4z } > { celloutsig_1_4z, 1'h1 };
  assign celloutsig_1_18z = celloutsig_1_3z[14:2] > { celloutsig_1_3z[18:7], celloutsig_1_13z };
  assign celloutsig_1_0z = in_data[172:157] % { 1'h1, in_data[190:176] };
  assign celloutsig_1_3z = in_data[177:158] * { celloutsig_1_0z[9:8], 2'h3, celloutsig_1_0z };
  assign celloutsig_0_3z = { celloutsig_0_2z[6:1], celloutsig_0_1z } * in_data[33:25];
  assign celloutsig_1_13z = { celloutsig_1_0z[8:3], celloutsig_1_1z } !== { celloutsig_1_5z[7:3], celloutsig_1_9z, celloutsig_1_6z };
  assign celloutsig_0_0z = & in_data[58:48];
  assign celloutsig_1_1z = & in_data[164:162];
  assign celloutsig_0_1z = in_data[9:7] >> { celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z };
  assign { out_data[128], out_data[100:96], out_data[32] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_5z };
endmodule
