/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire [2:0] celloutsig_0_1z;
  wire [28:0] celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire celloutsig_0_5z;
  reg [36:0] celloutsig_0_6z;
  wire celloutsig_1_0z;
  wire [4:0] celloutsig_1_12z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [3:0] celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [8:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [15:0] celloutsig_1_6z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_2z = !(in_data[98] ? in_data[184] : celloutsig_1_0z);
  assign celloutsig_1_4z = !(celloutsig_1_1z[1] ? celloutsig_1_1z[1] : celloutsig_1_1z[3]);
  assign celloutsig_1_5z = !(celloutsig_1_3z[1] ? celloutsig_1_4z : celloutsig_1_3z[0]);
  assign celloutsig_0_3z = !(celloutsig_0_2z[5] ? celloutsig_0_1z[0] : celloutsig_0_1z[1]);
  assign celloutsig_1_8z = celloutsig_1_3z[0] | celloutsig_1_6z[13];
  assign celloutsig_1_19z = celloutsig_1_3z[4] | in_data[105];
  assign celloutsig_0_0z = in_data[17:14] == in_data[32:29];
  assign celloutsig_0_5z = { in_data[78:74], celloutsig_0_1z, celloutsig_0_3z, celloutsig_0_3z } == { in_data[94:89], celloutsig_0_0z, celloutsig_0_1z };
  assign celloutsig_1_9z = { in_data[147:138], celloutsig_1_1z, celloutsig_1_0z } == { in_data[172:170], celloutsig_1_8z, celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_5z };
  assign celloutsig_1_18z = { celloutsig_1_3z[8], celloutsig_1_9z, celloutsig_1_9z } == celloutsig_1_12z[4:2];
  assign celloutsig_1_0z = in_data[177] & ~(in_data[166]);
  assign celloutsig_0_1z = in_data[50:48] * { celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_1_6z = { in_data[118:107], celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_5z, celloutsig_1_4z } * in_data[144:129];
  assign celloutsig_1_3z = - { in_data[187:186], celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_1z, celloutsig_1_0z };
  assign celloutsig_1_12z = - { in_data[135:132], celloutsig_1_5z };
  assign celloutsig_0_2z = - in_data[58:30];
  assign celloutsig_1_1z = { in_data[191:190], celloutsig_1_0z, celloutsig_1_0z } - in_data[163:160];
  always_latch
    if (!celloutsig_1_18z) celloutsig_0_6z = 37'h0000000000;
    else if (!clkin_data[0]) celloutsig_0_6z = { in_data[93:64], celloutsig_0_3z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_5z };
  assign { out_data[128], out_data[96], out_data[32:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_5z, celloutsig_0_6z[33:2] };
endmodule
