/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [6:0] celloutsig_0_0z;
  wire celloutsig_0_12z;
  wire [3:0] celloutsig_0_13z;
  wire [5:0] celloutsig_0_1z;
  reg [8:0] celloutsig_0_2z;
  reg [3:0] celloutsig_0_3z;
  wire [19:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire [2:0] celloutsig_0_6z;
  wire [12:0] celloutsig_0_7z;
  wire [3:0] celloutsig_0_9z;
  wire [9:0] celloutsig_1_0z;
  wire [3:0] celloutsig_1_10z;
  reg [3:0] celloutsig_1_11z;
  wire celloutsig_1_17z;
  wire [2:0] celloutsig_1_18z;
  wire [11:0] celloutsig_1_19z;
  wire [2:0] celloutsig_1_1z;
  wire [8:0] celloutsig_1_2z;
  wire [12:0] celloutsig_1_3z;
  reg [16:0] celloutsig_1_4z;
  wire [12:0] celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire [4:0] celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_5z = | celloutsig_0_0z;
  assign celloutsig_0_12z = | { celloutsig_0_9z[1], celloutsig_0_7z, celloutsig_0_2z, celloutsig_0_1z, celloutsig_0_0z };
  assign celloutsig_1_8z = | celloutsig_1_2z[3:0];
  assign celloutsig_1_17z = | { celloutsig_1_11z, celloutsig_1_7z[8:6] };
  assign celloutsig_0_0z = in_data[86:80] - in_data[45:39];
  assign celloutsig_0_4z = { celloutsig_0_2z[8:4], celloutsig_0_2z, celloutsig_0_1z } - { in_data[83:68], celloutsig_0_3z };
  assign celloutsig_0_6z = celloutsig_0_2z[6:4] - celloutsig_0_3z[3:1];
  assign celloutsig_0_7z = { celloutsig_0_0z[4:0], celloutsig_0_5z, celloutsig_0_0z } - { celloutsig_0_3z[3:1], celloutsig_0_0z, celloutsig_0_6z };
  assign celloutsig_0_9z = celloutsig_0_4z[9:6] - celloutsig_0_4z[16:13];
  assign celloutsig_0_13z = { celloutsig_0_3z[0], celloutsig_0_6z } - celloutsig_0_3z;
  assign celloutsig_0_1z = celloutsig_0_0z[5:0] - celloutsig_0_0z[5:0];
  assign celloutsig_1_0z = in_data[165:156] - in_data[126:117];
  assign celloutsig_1_1z = in_data[126:124] - in_data[184:182];
  assign celloutsig_1_2z = in_data[138:130] - { in_data[114:109], celloutsig_1_1z };
  assign celloutsig_1_3z = { celloutsig_1_1z[2], celloutsig_1_1z, celloutsig_1_2z } - { celloutsig_1_0z[7:4], celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_1z };
  assign celloutsig_1_7z = { celloutsig_1_0z[7:5], celloutsig_1_0z } - celloutsig_1_3z;
  assign celloutsig_1_9z = { celloutsig_1_0z[7:4], celloutsig_1_8z } - in_data[171:167];
  assign celloutsig_1_10z = celloutsig_1_0z[5:2] - celloutsig_1_4z[11:8];
  assign celloutsig_1_18z = in_data[130:128] - in_data[101:99];
  assign celloutsig_1_19z = { celloutsig_1_3z[10:0], celloutsig_1_17z } - { celloutsig_1_9z, celloutsig_1_11z, celloutsig_1_18z };
  always_latch
    if (clkin_data[96]) celloutsig_0_3z = 4'h0;
    else if (celloutsig_1_19z[0]) celloutsig_0_3z = in_data[93:90];
  always_latch
    if (clkin_data[128]) celloutsig_1_4z = 17'h00000;
    else if (clkin_data[32]) celloutsig_1_4z = { celloutsig_1_3z[11:4], celloutsig_1_2z };
  always_latch
    if (clkin_data[64]) celloutsig_0_2z = 9'h000;
    else if (!celloutsig_1_19z[0]) celloutsig_0_2z = { in_data[24:23], celloutsig_0_0z };
  always_latch
    if (!clkin_data[128]) celloutsig_1_11z = 4'h0;
    else if (!clkin_data[32]) celloutsig_1_11z = celloutsig_1_10z;
  assign { out_data[130:128], out_data[107:96], out_data[32], out_data[3:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_12z, celloutsig_0_13z };
endmodule
