/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [11:0] celloutsig_0_0z;
  reg [15:0] celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire [7:0] celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire [5:0] celloutsig_1_0z;
  wire celloutsig_1_18z;
  wire [3:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [8:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire [4:0] celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  reg [23:0] celloutsig_1_7z;
  wire celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_1z = ~((celloutsig_1_0z[1] | celloutsig_1_0z[1]) & celloutsig_1_0z[4]);
  assign celloutsig_0_4z = ~((celloutsig_0_3z[5] | in_data[82]) & (in_data[0] | in_data[37]));
  assign celloutsig_0_2z = in_data[48] | ~(celloutsig_0_1z[11]);
  assign celloutsig_1_2z = in_data[132:124] + { in_data[171:164], celloutsig_1_1z };
  assign celloutsig_1_4z = celloutsig_1_2z[7:3] + celloutsig_1_2z[6:2];
  assign celloutsig_1_19z = { celloutsig_1_2z[3:1], celloutsig_1_9z } + { celloutsig_1_4z[2:0], celloutsig_1_1z };
  assign celloutsig_1_3z = celloutsig_1_2z[7:1] === { in_data[110:105], celloutsig_1_1z };
  assign celloutsig_0_5z = { celloutsig_0_1z[15:1], celloutsig_0_4z, celloutsig_0_4z } <= { in_data[52:50], celloutsig_0_2z, celloutsig_0_0z, celloutsig_0_4z };
  assign celloutsig_1_6z = celloutsig_1_2z[6:1] <= { in_data[100:97], celloutsig_1_5z, celloutsig_1_5z };
  assign celloutsig_0_6z = { in_data[46:39], celloutsig_0_2z, celloutsig_0_4z, celloutsig_0_5z } < in_data[57:47];
  assign celloutsig_0_0z = in_data[62:51] % { 1'h1, in_data[74:64] };
  assign celloutsig_1_5z = { celloutsig_1_2z[8:7], celloutsig_1_1z } !== celloutsig_1_2z[2:0];
  assign celloutsig_1_0z = in_data[187:182] | in_data[140:135];
  assign celloutsig_1_18z = celloutsig_1_6z & celloutsig_1_4z[4];
  assign celloutsig_0_3z = in_data[36:29] - celloutsig_0_1z[12:5];
  always_latch
    if (!celloutsig_1_19z[0]) celloutsig_0_1z = 16'h0000;
    else if (clkin_data[0]) celloutsig_0_1z = in_data[39:24];
  always_latch
    if (!clkin_data[64]) celloutsig_1_7z = 24'h000000;
    else if (!clkin_data[32]) celloutsig_1_7z = { celloutsig_1_4z[4:1], celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_6z, celloutsig_1_6z, celloutsig_1_2z, celloutsig_1_5z };
  assign celloutsig_1_9z = ~((celloutsig_1_7z[15] & celloutsig_1_0z[4]) | (celloutsig_1_0z[2] & celloutsig_1_4z[1]));
  assign { out_data[128], out_data[99:96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_5z, celloutsig_0_6z };
endmodule
