/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_1z;
  wire [6:0] celloutsig_1_0z;
  wire [2:0] celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  reg [2:0] celloutsig_1_1z;
  wire [4:0] celloutsig_1_2z;
  wire [47:0] celloutsig_1_3z;
  wire [8:0] celloutsig_1_4z;
  wire [3:0] celloutsig_1_5z;
  wire [2:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  reg [6:0] celloutsig_1_8z;
  wire [8:0] celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  reg [3:0] _00_;
  always_ff @(negedge celloutsig_1_19z, posedge clkin_data[0])
    if (clkin_data[0]) _00_ <= 4'h0;
    else _00_ <= in_data[17:14];
  assign out_data[35:32] = _00_;
  assign celloutsig_1_11z = { celloutsig_1_0z[2:0], celloutsig_1_0z, celloutsig_1_10z } <= { celloutsig_1_8z[4:0], celloutsig_1_10z, celloutsig_1_2z };
  assign celloutsig_1_19z = { celloutsig_1_10z[1], celloutsig_1_11z, celloutsig_1_5z, celloutsig_1_10z, celloutsig_1_6z, celloutsig_1_10z, celloutsig_1_7z, celloutsig_1_5z } <= { celloutsig_1_9z[6:1], celloutsig_1_18z, celloutsig_1_10z, celloutsig_1_6z, celloutsig_1_8z };
  assign celloutsig_1_0z = in_data[133:127] % { 1'h1, in_data[110:105] };
  assign celloutsig_1_7z = | in_data[151:146];
  assign celloutsig_0_1z = | in_data[7:3];
  assign celloutsig_1_18z = | { celloutsig_1_4z[6:4], celloutsig_1_0z };
  assign celloutsig_1_2z = { celloutsig_1_1z[1:0], celloutsig_1_1z } >> celloutsig_1_0z[5:1];
  assign celloutsig_1_3z = { in_data[180:141], celloutsig_1_1z, celloutsig_1_2z } >> { in_data[185:150], celloutsig_1_0z, celloutsig_1_2z };
  assign celloutsig_1_4z = { celloutsig_1_2z[4:3], celloutsig_1_0z } >> { in_data[181:180], celloutsig_1_0z };
  assign celloutsig_1_5z = celloutsig_1_0z[5:2] >> celloutsig_1_3z[14:11];
  assign celloutsig_1_6z = celloutsig_1_5z[2:0] >> celloutsig_1_2z[4:2];
  assign celloutsig_1_9z = { celloutsig_1_3z[36:32], celloutsig_1_6z, celloutsig_1_7z } >> celloutsig_1_3z[41:33];
  assign celloutsig_1_10z = celloutsig_1_3z[14:12] >> celloutsig_1_8z[5:3];
  always_latch
    if (clkin_data[32]) celloutsig_1_1z = 3'h0;
    else if (!clkin_data[64]) celloutsig_1_1z = celloutsig_1_0z[5:3];
  always_latch
    if (!clkin_data[32]) celloutsig_1_8z = 7'h00;
    else if (!clkin_data[64]) celloutsig_1_8z = celloutsig_1_4z[6:0];
  assign { out_data[128], out_data[96], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_1z };
endmodule
