/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  reg [13:0] celloutsig_0_1z;
  reg [2:0] celloutsig_0_2z;
  wire celloutsig_1_0z;
  wire [2:0] celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire [10:0] celloutsig_1_13z;
  wire celloutsig_1_14z;
  wire celloutsig_1_16z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [2:0] celloutsig_1_1z;
  wire celloutsig_1_2z;
  reg [17:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [5:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire [11:0] celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_2z = ~(in_data[190] & celloutsig_1_0z);
  assign celloutsig_1_4z = ~celloutsig_1_2z;
  assign celloutsig_1_19z = ~celloutsig_1_10z[1];
  assign celloutsig_1_0z = in_data[152:141] || in_data[186:175];
  assign celloutsig_1_8z = celloutsig_1_3z[15:13] || { celloutsig_1_5z, celloutsig_1_2z, celloutsig_1_2z };
  assign celloutsig_1_14z = { celloutsig_1_9z[4:3], celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_8z } || celloutsig_1_3z[12:8];
  assign celloutsig_1_16z = { celloutsig_1_9z[7:3], celloutsig_1_4z } || { celloutsig_1_6z[3], celloutsig_1_14z, celloutsig_1_4z, celloutsig_1_8z, celloutsig_1_7z, celloutsig_1_11z };
  assign celloutsig_1_18z = { celloutsig_1_13z[10:6], celloutsig_1_11z, celloutsig_1_5z, celloutsig_1_16z } || { celloutsig_1_13z[10:7], celloutsig_1_11z, celloutsig_1_1z };
  assign celloutsig_1_6z = celloutsig_1_5z ? celloutsig_1_3z[13:8] : { celloutsig_1_3z[4:0], celloutsig_1_2z };
  assign celloutsig_1_9z = celloutsig_1_3z[6] ? { celloutsig_1_3z[11:7], 1'h1, celloutsig_1_3z[5:0] } : { celloutsig_1_3z[13], celloutsig_1_1z, celloutsig_1_5z, celloutsig_1_0z, celloutsig_1_6z };
  assign celloutsig_1_11z = { celloutsig_1_6z[5:3], celloutsig_1_8z } != { in_data[128:127], celloutsig_1_0z, celloutsig_1_7z };
  assign celloutsig_0_0z = | in_data[26:16];
  assign celloutsig_1_7z = | { celloutsig_1_3z[8:1], celloutsig_1_1z };
  assign celloutsig_1_5z = ^ { celloutsig_1_3z[15:0], celloutsig_1_4z, celloutsig_1_4z, celloutsig_1_0z, celloutsig_1_1z };
  assign celloutsig_1_13z = { celloutsig_1_3z[13:4], celloutsig_1_0z } >>> { celloutsig_1_3z[12:8], celloutsig_1_6z };
  assign celloutsig_1_1z = in_data[154:152] - { in_data[147], celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_1_10z = celloutsig_1_1z - { celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_8z };
  always_latch
    if (clkin_data[96]) celloutsig_1_3z = 18'h00000;
    else if (clkin_data[64]) celloutsig_1_3z = in_data[189:172];
  always_latch
    if (celloutsig_1_10z[1]) celloutsig_0_1z = 14'h0000;
    else if (!clkin_data[32]) celloutsig_0_1z = { in_data[27:16], celloutsig_0_0z, celloutsig_0_0z };
  always_latch
    if (!celloutsig_1_10z[1]) celloutsig_0_2z = 3'h0;
    else if (!clkin_data[0]) celloutsig_0_2z = celloutsig_0_1z[10:8];
  assign { out_data[128], out_data[96], out_data[45:32], out_data[2:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_1z, celloutsig_0_2z };
endmodule
