/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire [5:0] celloutsig_0_11z;
  wire celloutsig_0_12z;
  wire celloutsig_0_14z;
  wire celloutsig_0_16z;
  wire celloutsig_0_17z;
  wire celloutsig_0_18z;
  reg [6:0] celloutsig_0_19z;
  wire celloutsig_0_21z;
  reg [3:0] celloutsig_0_22z;
  wire celloutsig_0_23z;
  wire celloutsig_0_25z;
  wire celloutsig_0_28z;
  wire celloutsig_0_30z;
  wire celloutsig_0_31z;
  reg [18:0] celloutsig_0_32z;
  wire [14:0] celloutsig_0_35z;
  wire celloutsig_0_38z;
  wire [17:0] celloutsig_0_39z;
  wire [6:0] celloutsig_0_5z;
  wire celloutsig_0_7z;
  wire [3:0] celloutsig_0_8z;
  reg [36:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire [12:0] celloutsig_1_12z;
  wire celloutsig_1_18z;
  reg [3:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  reg [2:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_0z = in_data[33] ? in_data[72] : in_data[91];
  assign celloutsig_1_2z = ~((in_data[143] | celloutsig_1_0z) & celloutsig_1_0z);
  assign celloutsig_0_16z = ~((1'h1 | 1'h1) & 1'h1);
  assign celloutsig_0_7z = ~((in_data[45] | 1'h1) & celloutsig_0_0z);
  assign celloutsig_0_25z = ~((1'h1 | celloutsig_0_16z) & celloutsig_0_16z);
  assign celloutsig_0_31z = 1'h1 | ~(celloutsig_0_21z);
  assign celloutsig_1_1z = celloutsig_1_0z | ~(celloutsig_1_0z);
  assign celloutsig_0_21z = celloutsig_0_14z ^ celloutsig_0_10z;
  assign celloutsig_1_4z = ~(in_data[161] ^ celloutsig_1_3z[2]);
  assign celloutsig_1_10z = ~(in_data[173] ^ celloutsig_1_4z);
  assign celloutsig_0_11z = { 2'h3, celloutsig_0_8z } / { 1'h1, in_data[88:86], 1'h1, celloutsig_0_16z };
  assign celloutsig_0_38z = { celloutsig_0_11z[5:1], celloutsig_0_35z, celloutsig_0_28z, celloutsig_0_28z, celloutsig_0_28z, celloutsig_0_17z } <= { celloutsig_0_32z[15:0], celloutsig_0_0z, celloutsig_0_16z, celloutsig_0_11z };
  assign celloutsig_0_14z = { in_data[68:66], celloutsig_0_5z[6], in_data[47:45], 8'hff } <= { celloutsig_0_9z[22:15], celloutsig_0_5z[6], in_data[47:45], 3'h7 };
  assign celloutsig_0_12z = celloutsig_0_9z[21:2] || 1'h1;
  assign celloutsig_0_23z = in_data[78:75] || 1'h1;
  assign celloutsig_0_17z = { celloutsig_0_10z, celloutsig_0_12z, celloutsig_0_16z } < celloutsig_0_8z[3:1];
  assign celloutsig_0_30z = { celloutsig_0_8z[3:1], celloutsig_0_21z, celloutsig_0_18z } != { celloutsig_0_21z, 1'h1, celloutsig_0_21z, celloutsig_0_16z, celloutsig_0_14z };
  assign celloutsig_0_39z = - { celloutsig_0_31z, celloutsig_0_30z, 1'h1, celloutsig_0_35z };
  assign celloutsig_1_12z = - { in_data[145:134], celloutsig_1_10z };
  assign celloutsig_1_18z = | { celloutsig_1_12z[4:2], celloutsig_1_3z };
  assign celloutsig_0_18z = | celloutsig_0_11z[5:1];
  assign celloutsig_1_0z = ^ in_data[183:166];
  assign celloutsig_0_10z = ^ { in_data[45], 3'h7 };
  assign celloutsig_0_35z = { celloutsig_0_19z[6:1], celloutsig_0_25z, celloutsig_0_28z, 2'h3, celloutsig_0_17z, celloutsig_0_16z, celloutsig_0_7z, celloutsig_0_28z, 1'h1 } <<< { celloutsig_0_32z[2:1], celloutsig_0_19z, celloutsig_0_11z };
  assign celloutsig_0_8z = { celloutsig_0_7z, celloutsig_0_7z, 1'h1, celloutsig_0_7z } <<< { in_data[59:58], celloutsig_0_7z, celloutsig_0_16z };
  always_latch
    if (clkin_data[64]) celloutsig_0_32z = 19'h00000;
    else if (!celloutsig_1_18z) celloutsig_0_32z = { celloutsig_0_9z[24:14], celloutsig_0_22z, celloutsig_0_21z, 1'h1, celloutsig_0_0z, 1'h1 };
  always_latch
    if (clkin_data[96]) celloutsig_1_3z = 3'h0;
    else if (clkin_data[32]) celloutsig_1_3z = { in_data[177:176], celloutsig_1_2z };
  always_latch
    if (clkin_data[96]) celloutsig_1_19z = 4'h0;
    else if (!clkin_data[32]) celloutsig_1_19z = { celloutsig_1_3z, celloutsig_1_1z };
  always_latch
    if (clkin_data[64]) celloutsig_0_9z = 37'h0000000000;
    else if (!celloutsig_1_18z) celloutsig_0_9z = { 2'h3, celloutsig_0_7z, celloutsig_0_7z, 1'h1, celloutsig_0_5z[6], in_data[47:45], 5'h1f, celloutsig_0_16z, celloutsig_0_16z, celloutsig_0_0z, celloutsig_0_16z, celloutsig_0_8z, celloutsig_0_0z, celloutsig_0_16z, celloutsig_0_8z, 1'h1, celloutsig_0_8z, celloutsig_0_8z };
  always_latch
    if (clkin_data[64]) celloutsig_0_19z = 7'h00;
    else if (celloutsig_1_18z) celloutsig_0_19z = { celloutsig_0_9z[7:3], celloutsig_0_7z, celloutsig_0_17z };
  always_latch
    if (!clkin_data[64]) celloutsig_0_22z = 4'h0;
    else if (!clkin_data[0]) celloutsig_0_22z = { celloutsig_0_11z[5:3], celloutsig_0_21z };
  assign celloutsig_0_28z = ~((celloutsig_0_23z & celloutsig_0_8z[2]) | (celloutsig_0_21z & celloutsig_0_16z));
  assign celloutsig_0_5z[6] = in_data[48] & in_data[16];
  assign celloutsig_0_5z[5:0] = { in_data[47:45], 3'h7 };
  assign { out_data[128], out_data[99:96], out_data[32], out_data[17:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_38z, celloutsig_0_39z };
endmodule
