/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [4:0] _00_;
  reg [21:0] _01_;
  reg [15:0] _02_;
  wire [2:0] celloutsig_0_0z;
  wire [21:0] celloutsig_0_10z;
  wire [4:0] celloutsig_0_11z;
  wire [5:0] celloutsig_0_13z;
  wire [7:0] celloutsig_0_17z;
  wire [24:0] celloutsig_0_18z;
  wire [5:0] celloutsig_0_1z;
  wire [13:0] celloutsig_0_2z;
  wire [11:0] celloutsig_0_3z;
  wire [22:0] celloutsig_0_4z;
  wire [8:0] celloutsig_0_5z;
  wire [4:0] celloutsig_0_6z;
  wire [4:0] celloutsig_0_7z;
  wire [4:0] celloutsig_0_9z;
  wire [14:0] celloutsig_1_0z;
  wire [16:0] celloutsig_1_18z;
  wire [4:0] celloutsig_1_19z;
  wire [22:0] celloutsig_1_1z;
  wire [2:0] celloutsig_1_2z;
  wire [5:0] celloutsig_1_4z;
  wire [20:0] celloutsig_1_5z;
  wire [22:0] celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  always_ff @(negedge clkin_data[32], posedge celloutsig_1_18z[0])
    if (celloutsig_1_18z[0]) _00_ <= 5'h00;
    else _00_ <= in_data[94:90];
  always_ff @(posedge clkin_data[64], negedge clkin_data[128])
    if (!clkin_data[128]) _01_ <= 22'h000000;
    else _01_ <= { celloutsig_1_1z[19:1], celloutsig_1_2z };
  always_ff @(negedge clkin_data[64], posedge clkin_data[96])
    if (clkin_data[96]) _02_ <= 16'h0000;
    else _02_ <= celloutsig_1_5z[18:3];
  assign celloutsig_0_0z = in_data[30:28] % { 1'h1, in_data[86:85] };
  assign celloutsig_0_3z = { celloutsig_0_1z[5:3], celloutsig_0_0z, celloutsig_0_1z } % { 1'h1, celloutsig_0_1z[4:0], celloutsig_0_1z[5:1], in_data[0] };
  assign celloutsig_1_18z = celloutsig_1_9z[20:4] % { 1'h1, celloutsig_1_1z[16:1] };
  assign celloutsig_1_19z = celloutsig_1_18z[9:5] % { 1'h1, celloutsig_1_18z[13:10] };
  assign celloutsig_0_4z = { in_data[51:38], celloutsig_0_0z, celloutsig_0_1z } % { 1'h1, celloutsig_0_3z[7:1], celloutsig_0_0z, celloutsig_0_3z };
  assign celloutsig_0_5z = celloutsig_0_2z[9:1] % { 1'h1, celloutsig_0_4z[21:14] };
  assign celloutsig_0_6z = celloutsig_0_1z[4:0] % { 1'h1, celloutsig_0_5z[3:0] };
  assign celloutsig_0_7z = celloutsig_0_4z[5:1] % { 1'h1, celloutsig_0_4z[8:5] };
  assign celloutsig_0_9z = { in_data[63:62], celloutsig_0_0z } % { 1'h1, _00_[3:0] };
  assign celloutsig_0_10z = in_data[24:3] % { 1'h1, in_data[25:23], celloutsig_0_7z, celloutsig_0_9z, celloutsig_0_0z, celloutsig_0_9z };
  assign celloutsig_0_11z = celloutsig_0_9z % { 1'h1, celloutsig_0_10z[4:1] };
  assign celloutsig_0_1z = { celloutsig_0_0z, celloutsig_0_0z } % { 1'h1, in_data[89:85] };
  assign celloutsig_0_13z = { celloutsig_0_1z[3], celloutsig_0_6z } % { 1'h1, celloutsig_0_7z };
  assign celloutsig_0_17z = in_data[12:5] % { 1'h1, celloutsig_0_11z[2], celloutsig_0_13z };
  assign celloutsig_0_18z = { in_data[15:3], celloutsig_0_13z, celloutsig_0_1z } % { 1'h1, in_data[91:68] };
  assign celloutsig_1_0z = in_data[190:176] % { 1'h1, in_data[181:168] };
  assign celloutsig_1_1z = { celloutsig_1_0z[11:4], celloutsig_1_0z } % { 1'h1, in_data[176:155] };
  assign celloutsig_1_2z = in_data[166:164] % { 1'h1, celloutsig_1_0z[4:3] };
  assign celloutsig_0_2z = in_data[54:41] % { 1'h1, in_data[36:27], celloutsig_0_0z };
  assign celloutsig_1_4z = celloutsig_1_0z[14:9] % { 1'h1, _01_[11:7] };
  assign celloutsig_1_5z = { celloutsig_1_1z[18:1], celloutsig_1_2z } % { 1'h1, in_data[163:156], celloutsig_1_4z, celloutsig_1_4z };
  assign celloutsig_1_9z = { in_data[132:116], celloutsig_1_4z } % { 1'h1, _02_[10], celloutsig_1_5z };
  assign { out_data[144:128], out_data[100:96], out_data[39:32], out_data[24:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_17z, celloutsig_0_18z };
endmodule
