/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_10z;
  reg [7:0] celloutsig_0_12z;
  wire [5:0] celloutsig_0_1z;
  wire [11:0] celloutsig_0_20z;
  reg [8:0] celloutsig_0_26z;
  wire celloutsig_0_28z;
  wire [4:0] celloutsig_0_29z;
  wire celloutsig_0_2z;
  wire [2:0] celloutsig_0_32z;
  wire [5:0] celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire [7:0] celloutsig_0_58z;
  wire celloutsig_0_59z;
  wire celloutsig_0_5z;
  reg [12:0] celloutsig_0_6z;
  wire [2:0] celloutsig_0_8z;
  reg [4:0] celloutsig_0_9z;
  wire [8:0] celloutsig_1_0z;
  wire [17:0] celloutsig_1_10z;
  wire [18:0] celloutsig_1_11z;
  wire [4:0] celloutsig_1_12z;
  reg [2:0] celloutsig_1_13z;
  wire celloutsig_1_14z;
  wire celloutsig_1_15z;
  wire celloutsig_1_16z;
  wire [4:0] celloutsig_1_17z;
  wire [9:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  reg [19:0] celloutsig_1_2z;
  wire [9:0] celloutsig_1_3z;
  wire [4:0] celloutsig_1_4z;
  reg [20:0] celloutsig_1_5z;
  wire [2:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_5z = ~celloutsig_0_3z[5];
  assign celloutsig_1_9z = ~celloutsig_1_4z[2];
  assign celloutsig_0_2z = ~in_data[56];
  assign celloutsig_1_14z = celloutsig_1_12z[2] | ~(celloutsig_1_3z[2]);
  assign celloutsig_1_19z = in_data[159] | ~(in_data[143]);
  assign celloutsig_0_28z = celloutsig_0_12z[1] | ~(celloutsig_0_26z[8]);
  assign celloutsig_0_4z = ! in_data[31:23];
  assign celloutsig_0_59z = ! { celloutsig_0_29z, celloutsig_0_32z };
  assign celloutsig_1_7z = ! celloutsig_1_3z[8:6];
  assign celloutsig_1_16z = ! { celloutsig_1_9z, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_14z, celloutsig_1_15z, celloutsig_1_9z, celloutsig_1_8z, celloutsig_1_0z, celloutsig_1_7z, celloutsig_1_15z, celloutsig_1_9z };
  assign celloutsig_0_0z = in_data[88:83] < in_data[40:35];
  assign celloutsig_1_1z = celloutsig_1_0z[6:0] < celloutsig_1_0z[7:1];
  assign celloutsig_1_8z = { celloutsig_1_5z[9:5], celloutsig_1_1z, celloutsig_1_7z } < celloutsig_1_2z[19:13];
  assign celloutsig_1_15z = { celloutsig_1_10z[1:0], celloutsig_1_12z } < { celloutsig_1_10z[16:14], celloutsig_1_9z, celloutsig_1_13z };
  assign celloutsig_0_10z = { in_data[81:75], celloutsig_0_0z, celloutsig_0_8z, celloutsig_0_0z, celloutsig_0_1z } < { celloutsig_0_9z[1], celloutsig_0_3z, celloutsig_0_1z, celloutsig_0_9z };
  assign celloutsig_1_10z = { in_data[116:113], celloutsig_1_9z, celloutsig_1_8z, celloutsig_1_7z, celloutsig_1_3z, celloutsig_1_1z } % { 1'h1, celloutsig_1_2z[9:3], celloutsig_1_6z, celloutsig_1_8z, celloutsig_1_6z, celloutsig_1_6z };
  assign celloutsig_1_18z = { celloutsig_1_17z[4:2], celloutsig_1_12z, celloutsig_1_1z, celloutsig_1_9z } % { 1'h1, in_data[165:157] };
  assign celloutsig_0_8z = { in_data[45:44], celloutsig_0_0z } % { 1'h1, celloutsig_0_6z[3:2] };
  assign celloutsig_0_29z = { in_data[35:32], celloutsig_0_28z } % { 1'h1, celloutsig_0_9z[3:0] };
  assign celloutsig_0_32z = celloutsig_0_20z[4:2] % { 1'h1, celloutsig_0_12z[6:5] };
  assign celloutsig_0_58z = - celloutsig_0_26z[8:1];
  assign celloutsig_1_3z = - { celloutsig_1_2z[9], celloutsig_1_0z };
  assign celloutsig_1_6z = - celloutsig_1_0z[8:6];
  assign celloutsig_0_20z = - { in_data[26:24], celloutsig_0_3z, celloutsig_0_8z };
  assign celloutsig_0_3z = - in_data[37:32];
  assign celloutsig_1_0z = in_data[143:135] <<< in_data[106:98];
  assign celloutsig_1_4z = celloutsig_1_2z[15:11] <<< { celloutsig_1_0z[4:1], celloutsig_1_1z };
  assign celloutsig_1_11z = celloutsig_1_5z[18:0] >>> { in_data[161], celloutsig_1_10z };
  assign celloutsig_1_12z = { celloutsig_1_5z[12], celloutsig_1_8z, celloutsig_1_9z, celloutsig_1_7z, celloutsig_1_9z } >>> celloutsig_1_4z;
  assign celloutsig_1_17z = { celloutsig_1_5z[17:14], celloutsig_1_16z } >>> celloutsig_1_11z[12:8];
  assign celloutsig_0_1z = { in_data[87:83], celloutsig_0_0z } >>> in_data[32:27];
  always_latch
    if (!clkin_data[32]) celloutsig_0_6z = 13'h0000;
    else if (celloutsig_1_18z[0]) celloutsig_0_6z = { in_data[83:82], celloutsig_0_2z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_5z, celloutsig_0_1z, celloutsig_0_4z };
  always_latch
    if (!clkin_data[64]) celloutsig_1_2z = 20'h00000;
    else if (clkin_data[0]) celloutsig_1_2z = { in_data[105:96], celloutsig_1_0z, celloutsig_1_1z };
  always_latch
    if (!clkin_data[64]) celloutsig_1_5z = 21'h000000;
    else if (clkin_data[0]) celloutsig_1_5z = { in_data[125:111], celloutsig_1_1z, celloutsig_1_4z };
  always_latch
    if (!clkin_data[64]) celloutsig_1_13z = 3'h0;
    else if (!clkin_data[0]) celloutsig_1_13z = celloutsig_1_2z[7:5];
  always_latch
    if (clkin_data[32]) celloutsig_0_9z = 5'h00;
    else if (celloutsig_1_18z[0]) celloutsig_0_9z = in_data[65:61];
  always_latch
    if (!clkin_data[32]) celloutsig_0_12z = 8'h00;
    else if (celloutsig_1_18z[0]) celloutsig_0_12z = { celloutsig_0_1z[5:3], celloutsig_0_10z, celloutsig_0_5z, celloutsig_0_8z };
  always_latch
    if (clkin_data[32]) celloutsig_0_26z = 9'h000;
    else if (!celloutsig_1_18z[0]) celloutsig_0_26z = in_data[52:44];
  assign { out_data[137:128], out_data[96], out_data[39:32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_58z, celloutsig_0_59z };
endmodule
