/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [2:0] _00_;
  reg [8:0] _01_;
  reg [14:0] _02_;
  reg [6:0] _03_;
  reg [6:0] _04_;
  wire celloutsig_0_0z;
  wire celloutsig_0_11z;
  wire celloutsig_0_12z;
  wire celloutsig_0_13z;
  wire celloutsig_0_14z;
  wire celloutsig_0_15z;
  wire celloutsig_0_16z;
  wire celloutsig_0_17z;
  wire celloutsig_0_18z;
  wire celloutsig_0_19z;
  wire [11:0] celloutsig_0_1z;
  wire celloutsig_0_21z;
  wire celloutsig_0_2z;
  wire celloutsig_0_30z;
  wire celloutsig_0_3z;
  wire celloutsig_0_44z;
  wire celloutsig_0_45z;
  wire [2:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire [5:0] celloutsig_0_7z;
  wire [5:0] celloutsig_0_8z;
  wire celloutsig_1_0z;
  wire [24:0] celloutsig_1_18z;
  wire [10:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_5z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_2z = ~(celloutsig_1_0z & in_data[154]);
  assign celloutsig_0_14z = ~(in_data[85] & celloutsig_0_8z[2]);
  assign celloutsig_0_15z = ~(celloutsig_0_11z & celloutsig_0_6z);
  assign celloutsig_0_21z = ~(in_data[19] & celloutsig_0_5z);
  assign celloutsig_0_44z = ~((celloutsig_0_21z | celloutsig_0_17z) & celloutsig_0_0z);
  assign celloutsig_0_18z = ~((celloutsig_0_17z | celloutsig_0_11z) & celloutsig_0_15z);
  assign celloutsig_0_0z = ~((in_data[5] | in_data[5]) & (in_data[8] | in_data[82]));
  assign celloutsig_0_45z = ~((celloutsig_0_30z | celloutsig_0_12z) & (celloutsig_0_17z | celloutsig_0_19z));
  assign celloutsig_0_16z = ~((celloutsig_0_14z | celloutsig_0_14z) & (celloutsig_0_0z | celloutsig_0_12z));
  assign celloutsig_1_1z = in_data[139] | in_data[166];
  assign celloutsig_1_3z = celloutsig_1_0z ^ celloutsig_1_1z;
  assign celloutsig_0_5z = ~(in_data[75] ^ celloutsig_0_2z);
  always_ff @(posedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _00_ <= 3'h0;
    else _00_ <= { celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_2z };
  always_ff @(posedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _01_ <= 9'h000;
    else _01_ <= { in_data[107:106], celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_5z, celloutsig_1_1z, celloutsig_1_2z };
  always_ff @(posedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _02_ <= 15'h0000;
    else _02_ <= { celloutsig_1_1z, _00_, celloutsig_1_3z, _01_, celloutsig_1_5z };
  always_ff @(negedge celloutsig_1_19z[0], posedge clkin_data[32])
    if (clkin_data[32]) _03_ <= 7'h00;
    else _03_ <= { celloutsig_0_7z, celloutsig_0_3z };
  always_ff @(negedge celloutsig_1_19z[0], posedge clkin_data[32])
    if (clkin_data[32]) _04_ <= 7'h00;
    else _04_ <= { in_data[39], celloutsig_0_8z };
  assign celloutsig_0_17z = { _03_[5:1], celloutsig_0_14z, celloutsig_0_15z } == { in_data[88:84], celloutsig_0_6z, celloutsig_0_6z };
  assign celloutsig_0_19z = { celloutsig_0_18z, celloutsig_0_4z, celloutsig_0_17z } == { _03_[2:1], celloutsig_0_16z, celloutsig_0_2z, celloutsig_0_13z };
  assign celloutsig_0_30z = _04_[4:1] && celloutsig_0_8z[3:0];
  assign celloutsig_0_1z = in_data[90:79] % { 1'h1, in_data[75:71], celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_0_4z = in_data[9:7] * celloutsig_0_1z[3:1];
  assign celloutsig_0_11z = { celloutsig_0_4z[2:1], celloutsig_0_8z, celloutsig_0_6z } != in_data[64:56];
  assign celloutsig_1_18z = - in_data[141:117];
  assign celloutsig_1_19z = - { _02_[9:0], celloutsig_1_3z };
  assign celloutsig_0_6z = in_data[30:26] !== { celloutsig_0_1z[2:1], celloutsig_0_3z, celloutsig_0_2z, celloutsig_0_3z };
  assign celloutsig_0_3z = & in_data[22:19];
  assign celloutsig_0_13z = & _03_[6:2];
  assign celloutsig_1_5z = _00_[1] & celloutsig_1_1z;
  assign celloutsig_1_0z = | in_data[109:107];
  assign celloutsig_0_2z = | in_data[24:21];
  assign celloutsig_0_7z = { celloutsig_0_0z, celloutsig_0_2z, celloutsig_0_4z, celloutsig_0_0z } >> { celloutsig_0_0z, celloutsig_0_3z, celloutsig_0_2z, celloutsig_0_6z, celloutsig_0_5z, celloutsig_0_3z };
  assign celloutsig_0_8z = { in_data[44:40], celloutsig_0_3z } ~^ { celloutsig_0_7z[4:3], celloutsig_0_6z, celloutsig_0_2z, celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_0_12z = ~((celloutsig_0_1z[6] & celloutsig_0_1z[4]) | (celloutsig_0_5z & celloutsig_0_0z));
  assign { out_data[152:128], out_data[106:96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_44z, celloutsig_0_45z };
endmodule
