/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [7:0] _01_;
  wire [8:0] celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire [13:0] celloutsig_0_4z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire celloutsig_1_11z;
  reg [11:0] celloutsig_1_12z;
  reg [21:0] celloutsig_1_15z;
  wire celloutsig_1_16z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire [14:0] celloutsig_1_4z;
  wire [3:0] celloutsig_1_6z;
  wire [13:0] celloutsig_1_7z;
  wire [11:0] celloutsig_1_8z;
  wire [3:0] celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_18z = celloutsig_1_3z ? celloutsig_1_9z[0] : celloutsig_1_16z;
  assign celloutsig_1_11z = !(celloutsig_1_7z[7] ? celloutsig_1_1z : celloutsig_1_2z);
  assign celloutsig_1_2z = ~((in_data[166] | celloutsig_1_0z) & in_data[190]);
  assign celloutsig_1_16z = ~((celloutsig_1_10z | celloutsig_1_12z[0]) & _00_);
  assign celloutsig_1_0z = ~((in_data[158] | in_data[186]) & (in_data[154] | in_data[186]));
  assign celloutsig_0_0z = in_data[43:35] + in_data[61:53];
  assign celloutsig_1_7z = { in_data[139:130], celloutsig_1_6z } + { in_data[138:127], celloutsig_1_3z, celloutsig_1_0z };
  assign celloutsig_1_8z = in_data[142:131] + in_data[169:158];
  reg [6:0] _10_;
  always_ff @(negedge clkin_data[0], negedge celloutsig_1_18z)
    if (!celloutsig_1_18z) _10_ <= 7'h00;
    else _10_ <= in_data[90:84];
  assign out_data[38:32] = _10_;
  reg [7:0] _11_;
  always_ff @(negedge clkin_data[32], posedge clkin_data[64])
    if (clkin_data[64]) _11_ <= 8'h00;
    else _11_ <= { celloutsig_1_4z[3], 1'h1, celloutsig_1_4z[1:0], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_2z };
  assign { _01_[7:6], celloutsig_1_9z[2], _01_[4:1], _00_ } = _11_;
  assign celloutsig_1_1z = in_data[125:120] && in_data[189:184];
  assign celloutsig_1_10z = { celloutsig_1_7z[7], celloutsig_1_2z, _01_[7:6], celloutsig_1_9z[2], _01_[4:1], _00_ } && { celloutsig_1_3z, celloutsig_1_2z, _01_[7:6], celloutsig_1_9z[2], _01_[4:1], _00_ };
  assign celloutsig_1_19z = celloutsig_1_8z[10:1] && { celloutsig_1_15z[8:0], celloutsig_1_2z };
  assign celloutsig_1_3z = { in_data[124:116], celloutsig_1_2z, celloutsig_1_0z } < in_data[160:150];
  assign celloutsig_0_1z = { in_data[75:74], celloutsig_0_0z } < in_data[22:12];
  assign celloutsig_1_6z = in_data[136:133] % { 1'h1, in_data[140:138] };
  assign celloutsig_0_4z = { in_data[42:30], celloutsig_0_1z } * { celloutsig_0_0z[8:4], celloutsig_0_0z };
  always_latch
    if (clkin_data[64]) celloutsig_1_12z = 12'h000;
    else if (!clkin_data[128]) celloutsig_1_12z = { in_data[145:140], celloutsig_1_1z, celloutsig_1_9z, celloutsig_1_11z };
  always_latch
    if (!clkin_data[64]) celloutsig_1_15z = 22'h000000;
    else if (!clkin_data[96]) celloutsig_1_15z = { celloutsig_1_8z[2:0], celloutsig_1_9z, celloutsig_1_11z, celloutsig_1_0z, celloutsig_1_12z, celloutsig_1_10z };
  assign { celloutsig_1_4z[4], celloutsig_1_4z[1:0], celloutsig_1_4z[3], celloutsig_1_4z[14:5] } = { celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_1z, celloutsig_1_0z, in_data[177:168] } ~^ { celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_3z, in_data[190:185], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_3z };
  assign { celloutsig_1_9z[3], celloutsig_1_9z[1:0] } = { _01_[6], _01_[4], celloutsig_1_3z } ~^ { celloutsig_1_4z[3], celloutsig_1_4z[1:0] };
  assign { _01_[5], _01_[0] } = { celloutsig_1_9z[2], _00_ };
  assign celloutsig_1_4z[2] = 1'h1;
  assign { out_data[128], out_data[96], out_data[13:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_4z };
endmodule
