/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [6:0] _00_;
  wire [8:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire [11:0] celloutsig_0_11z;
  wire celloutsig_0_12z;
  wire celloutsig_0_13z;
  wire [4:0] celloutsig_0_14z;
  reg [10:0] celloutsig_0_16z;
  wire celloutsig_0_19z;
  wire [18:0] celloutsig_0_1z;
  wire [15:0] celloutsig_0_20z;
  wire celloutsig_0_2z;
  wire [6:0] celloutsig_0_3z;
  wire [7:0] celloutsig_0_4z;
  wire celloutsig_0_6z;
  reg [16:0] celloutsig_0_7z;
  reg [43:0] celloutsig_0_9z;
  wire [5:0] celloutsig_1_0z;
  wire [11:0] celloutsig_1_11z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [22:0] celloutsig_1_1z;
  wire [18:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire [7:0] celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [63:0] clkin_data;
  wire [63:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_13z = celloutsig_0_10z ? celloutsig_0_10z : celloutsig_0_9z[12];
  assign celloutsig_0_2z = ~((in_data[52] | celloutsig_0_0z[6]) & (celloutsig_0_1z[12] | in_data[80]));
  assign celloutsig_1_9z = ~((celloutsig_1_6z | celloutsig_1_7z) & (celloutsig_1_6z | celloutsig_1_0z[2]));
  assign celloutsig_0_6z = ~(celloutsig_0_3z[0] ^ celloutsig_0_1z[16]);
  assign celloutsig_0_4z = celloutsig_0_0z[7:0] + celloutsig_0_1z[7:0];
  assign celloutsig_0_1z = in_data[32:14] + { in_data[6], celloutsig_0_0z, celloutsig_0_0z };
  always_ff @(posedge clkin_data[32], negedge clkin_data[0])
    if (!clkin_data[0]) _00_ <= 7'h00;
    else _00_ <= celloutsig_0_16z[8:2];
  assign celloutsig_0_20z = { celloutsig_0_11z[10:1], celloutsig_0_14z, celloutsig_0_19z } & { celloutsig_0_9z[32:29], celloutsig_0_2z, celloutsig_0_2z, celloutsig_0_19z, celloutsig_0_19z, _00_, celloutsig_0_13z };
  assign celloutsig_1_2z = { in_data[186:174], celloutsig_1_0z } & { celloutsig_1_1z[21:9], celloutsig_1_0z };
  assign celloutsig_1_19z = in_data[145:139] == celloutsig_1_11z[9:3];
  assign celloutsig_0_10z = celloutsig_0_4z[5:2] == celloutsig_0_7z[10:7];
  assign celloutsig_0_12z = { celloutsig_0_1z[16:12], celloutsig_0_6z } == celloutsig_0_1z[8:3];
  assign celloutsig_0_19z = celloutsig_0_14z[3:0] && { celloutsig_0_11z[7:5], celloutsig_0_12z };
  assign celloutsig_1_4z = in_data[156:150] && celloutsig_1_2z[9:3];
  assign celloutsig_1_0z = in_data[174:169] % { 1'h1, in_data[150:146] };
  assign celloutsig_1_1z = { in_data[121:105], celloutsig_1_0z } % { 1'h1, in_data[140:119] };
  assign celloutsig_1_8z = in_data[154] ? { in_data[172:166], celloutsig_1_6z } : { celloutsig_1_0z, celloutsig_1_4z, celloutsig_1_7z };
  assign celloutsig_1_18z = celloutsig_1_11z[9:6] !== celloutsig_1_8z[5:2];
  assign celloutsig_1_6z = { celloutsig_1_1z[18:11], celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_3z } !== celloutsig_1_1z[20:10];
  assign celloutsig_1_11z = ~ { celloutsig_1_1z[17:8], celloutsig_1_9z, celloutsig_1_4z };
  assign celloutsig_0_11z = ~ celloutsig_0_1z[12:1];
  assign celloutsig_0_0z = in_data[60:52] | in_data[60:52];
  assign celloutsig_0_3z = celloutsig_0_1z[6:0] | { celloutsig_0_0z[5:0], celloutsig_0_2z };
  assign celloutsig_0_14z = celloutsig_0_3z[5:1] | { celloutsig_0_11z[7:4], celloutsig_0_13z };
  assign celloutsig_1_3z = ^ { in_data[154:120], celloutsig_1_0z };
  assign celloutsig_1_5z = ^ celloutsig_1_1z[21:0];
  assign celloutsig_1_7z = ^ { celloutsig_1_4z, celloutsig_1_0z };
  always_latch
    if (!clkin_data[0]) celloutsig_0_7z = 17'h00000;
    else if (!celloutsig_1_19z) celloutsig_0_7z = celloutsig_0_1z[16:0];
  always_latch
    if (!clkin_data[0]) celloutsig_0_9z = 44'h00000000000;
    else if (!celloutsig_1_19z) celloutsig_0_9z = in_data[56:13];
  always_latch
    if (!clkin_data[0]) celloutsig_0_16z = 11'h000;
    else if (celloutsig_1_19z) celloutsig_0_16z = celloutsig_0_11z[10:0];
  assign { out_data[128], out_data[96], out_data[32], out_data[15:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_19z, celloutsig_0_20z };
endmodule
