/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  reg [9:0] celloutsig_0_4z;
  wire [14:0] celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire [23:0] celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire [8:0] celloutsig_1_13z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  reg [8:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire [12:0] celloutsig_1_5z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_1z = !(in_data[39] ? celloutsig_0_0z : in_data[89]);
  assign celloutsig_0_8z = ~celloutsig_0_1z;
  assign celloutsig_1_11z = ~celloutsig_1_7z;
  assign celloutsig_1_7z = ~((celloutsig_1_4z | celloutsig_1_5z[5]) & celloutsig_1_0z[3]);
  assign celloutsig_1_19z = ~((celloutsig_1_4z | celloutsig_1_7z) & celloutsig_1_18z);
  assign celloutsig_1_3z = in_data[179] | ~(in_data[158]);
  assign celloutsig_1_18z = celloutsig_1_4z | ~(celloutsig_1_13z[6]);
  assign celloutsig_1_4z = celloutsig_1_3z ^ in_data[151];
  assign celloutsig_0_0z = ~(in_data[5] ^ in_data[19]);
  assign celloutsig_1_8z = celloutsig_1_5z[9:0] || celloutsig_1_0z[21:12];
  assign celloutsig_0_2z = in_data[32:24] || in_data[70:62];
  assign celloutsig_1_13z = { celloutsig_1_5z[11:4], celloutsig_1_11z } * { celloutsig_1_2z[6:0], celloutsig_1_8z, celloutsig_1_10z };
  assign celloutsig_0_7z = - { in_data[32], celloutsig_0_1z, celloutsig_0_3z, celloutsig_0_4z, celloutsig_0_2z, celloutsig_0_3z };
  assign celloutsig_1_5z = - in_data[111:99];
  assign celloutsig_0_3z = | { in_data[22:18], celloutsig_0_2z, celloutsig_0_0z };
  assign celloutsig_1_10z = | in_data[140:137];
  assign celloutsig_1_0z = in_data[152:129] - in_data[169:146];
  always_latch
    if (!celloutsig_1_19z) celloutsig_0_4z = 10'h000;
    else if (clkin_data[0]) celloutsig_0_4z = in_data[78:69];
  always_latch
    if (!clkin_data[64]) celloutsig_1_2z = 9'h000;
    else if (clkin_data[32]) celloutsig_1_2z = in_data[173:165];
  assign { out_data[128], out_data[96], out_data[46:32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_7z, celloutsig_0_8z };
endmodule
