/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [2:0] _00_;
  reg [6:0] _01_;
  wire celloutsig_0_0z;
  wire celloutsig_0_11z;
  reg [6:0] celloutsig_0_12z;
  wire celloutsig_0_13z;
  wire celloutsig_0_14z;
  wire celloutsig_0_15z;
  reg [19:0] celloutsig_0_16z;
  wire celloutsig_0_17z;
  wire celloutsig_0_18z;
  wire celloutsig_0_19z;
  wire celloutsig_0_1z;
  wire celloutsig_0_20z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire celloutsig_0_4z;
  wire celloutsig_0_5z;
  reg [10:0] celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire celloutsig_0_9z;
  wire celloutsig_1_0z;
  reg [3:0] celloutsig_1_10z;
  wire celloutsig_1_11z;
  wire celloutsig_1_12z;
  wire celloutsig_1_14z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [223:0] clkin_data;
  wire [223:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  always_ff @(posedge clkin_data[160], posedge clkin_data[96])
    if (clkin_data[96]) _00_ <= 3'h0;
    else _00_ <= in_data[13:11];
  always_ff @(posedge clkin_data[192], negedge celloutsig_1_18z)
    if (!celloutsig_1_18z) _01_ <= 7'h00;
    else _01_ <= { celloutsig_0_2z, celloutsig_0_5z, celloutsig_0_5z, celloutsig_0_9z, celloutsig_0_0z, celloutsig_0_5z, celloutsig_0_3z };
  assign celloutsig_0_0z = in_data[53:51] > in_data[14:12];
  assign celloutsig_0_3z = in_data[51:41] > { in_data[32:24], celloutsig_0_1z, celloutsig_0_0z };
  assign celloutsig_1_11z = { celloutsig_1_9z, celloutsig_1_10z, celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_1z, celloutsig_1_7z, celloutsig_1_1z, celloutsig_1_7z, celloutsig_1_6z } > in_data[189:178];
  assign celloutsig_1_12z = { celloutsig_1_3z, celloutsig_1_6z, celloutsig_1_7z, celloutsig_1_9z } > { celloutsig_1_11z, celloutsig_1_6z, celloutsig_1_4z, celloutsig_1_8z };
  assign celloutsig_1_14z = { celloutsig_1_10z[0], celloutsig_1_7z, celloutsig_1_8z } > { in_data[159], celloutsig_1_5z, celloutsig_1_7z };
  assign celloutsig_1_18z = { celloutsig_1_11z, celloutsig_1_12z, celloutsig_1_14z } > { celloutsig_1_7z, celloutsig_1_5z, celloutsig_1_2z };
  assign celloutsig_0_4z = { in_data[28:24], celloutsig_0_1z, celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_3z } > { in_data[61:56], celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_3z };
  assign celloutsig_1_19z = { celloutsig_1_4z, celloutsig_1_14z, celloutsig_1_11z } > { celloutsig_1_1z, celloutsig_1_9z, celloutsig_1_0z };
  assign celloutsig_0_5z = in_data[80:78] > { celloutsig_0_3z, celloutsig_0_3z, celloutsig_0_1z };
  assign celloutsig_0_7z = { celloutsig_0_6z[7:5], celloutsig_0_1z, celloutsig_0_2z, celloutsig_0_2z } > { in_data[65:61], celloutsig_0_5z };
  assign celloutsig_0_9z = { celloutsig_0_6z[10:3], celloutsig_0_2z, celloutsig_0_5z, _00_, celloutsig_0_7z, celloutsig_0_7z, celloutsig_0_6z } > { in_data[66:53], celloutsig_0_2z, celloutsig_0_5z, celloutsig_0_5z, celloutsig_0_2z, celloutsig_0_5z, celloutsig_0_3z, _00_, celloutsig_0_4z, celloutsig_0_4z, celloutsig_0_3z };
  assign celloutsig_0_11z = { in_data[74:43], _00_, celloutsig_0_7z } > { in_data[74:57], _01_, celloutsig_0_6z };
  assign celloutsig_0_1z = in_data[88:58] > in_data[70:40];
  assign celloutsig_0_13z = { in_data[10:9], celloutsig_0_0z, celloutsig_0_7z, celloutsig_0_4z, celloutsig_0_11z } > in_data[36:31];
  assign celloutsig_0_14z = _01_[4:0] > { _01_[5:2], celloutsig_0_1z };
  assign celloutsig_0_15z = { celloutsig_0_12z[1], celloutsig_0_4z, celloutsig_0_11z, celloutsig_0_13z, celloutsig_0_1z, celloutsig_0_1z, celloutsig_0_2z } > { celloutsig_0_6z[8:7], celloutsig_0_4z, celloutsig_0_0z, celloutsig_0_3z, celloutsig_0_0z, celloutsig_0_5z };
  assign celloutsig_0_17z = { _01_[2:0], celloutsig_0_5z, celloutsig_0_1z } > { celloutsig_0_2z, celloutsig_0_2z, celloutsig_0_14z, celloutsig_0_15z, celloutsig_0_15z };
  assign celloutsig_0_18z = { _00_[2], celloutsig_0_13z, celloutsig_0_5z } > { celloutsig_0_11z, celloutsig_0_9z, celloutsig_0_0z };
  assign celloutsig_0_19z = { celloutsig_0_12z[4:2], celloutsig_0_5z } > { celloutsig_0_16z[7], celloutsig_0_7z, celloutsig_0_17z, celloutsig_0_5z };
  assign celloutsig_0_20z = { in_data[81], celloutsig_0_12z, celloutsig_0_12z, celloutsig_0_3z, celloutsig_0_2z, celloutsig_0_15z, celloutsig_0_15z, celloutsig_0_9z } > { celloutsig_0_16z[17:0], celloutsig_0_13z, celloutsig_0_18z };
  assign celloutsig_0_2z = in_data[91:84] > { in_data[67:64], celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_0z };
  assign celloutsig_1_0z = in_data[132:128] > in_data[173:169];
  assign celloutsig_1_1z = { in_data[132:130], celloutsig_1_0z } > in_data[183:180];
  assign celloutsig_1_2z = { in_data[121:117], celloutsig_1_1z } > { in_data[188:185], celloutsig_1_1z, celloutsig_1_1z };
  assign celloutsig_1_3z = in_data[118:107] > in_data[156:145];
  assign celloutsig_1_4z = in_data[144:123] > { in_data[135:122], celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_0z };
  assign celloutsig_1_5z = { in_data[118:105], celloutsig_1_3z, celloutsig_1_4z } > { in_data[187:186], celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_2z, celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_1z };
  assign celloutsig_1_6z = { in_data[145:138], celloutsig_1_5z } > { in_data[165:164], celloutsig_1_0z, celloutsig_1_3z, celloutsig_1_2z, celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_3z, celloutsig_1_3z };
  assign celloutsig_1_7z = { in_data[175:172], celloutsig_1_5z, celloutsig_1_3z, celloutsig_1_1z, celloutsig_1_3z, celloutsig_1_6z, celloutsig_1_4z } > { in_data[178:171], celloutsig_1_6z, celloutsig_1_3z };
  assign celloutsig_1_8z = { in_data[132:131], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_2z, celloutsig_1_7z } > { celloutsig_1_7z, celloutsig_1_3z, celloutsig_1_2z, celloutsig_1_6z, celloutsig_1_1z, celloutsig_1_1z, celloutsig_1_5z };
  assign celloutsig_1_9z = { in_data[128:125], celloutsig_1_7z } > { celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_6z, celloutsig_1_2z, celloutsig_1_6z };
  always_latch
    if (clkin_data[128]) celloutsig_1_10z = 4'h0;
    else if (!clkin_data[64]) celloutsig_1_10z = { celloutsig_1_1z, celloutsig_1_7z, celloutsig_1_8z, celloutsig_1_5z };
  always_latch
    if (clkin_data[96]) celloutsig_0_6z = 11'h000;
    else if (clkin_data[32]) celloutsig_0_6z = { in_data[47:44], celloutsig_0_3z, celloutsig_0_4z, celloutsig_0_2z, celloutsig_0_3z, celloutsig_0_5z, celloutsig_0_0z, celloutsig_0_1z };
  always_latch
    if (celloutsig_1_18z) celloutsig_0_12z = 7'h00;
    else if (clkin_data[0]) celloutsig_0_12z = { _01_[5:0], celloutsig_0_5z };
  always_latch
    if (!celloutsig_1_18z) celloutsig_0_16z = 20'h00000;
    else if (clkin_data[32]) celloutsig_0_16z = { _01_[3:1], celloutsig_0_1z, celloutsig_0_6z, celloutsig_0_7z, celloutsig_0_2z, celloutsig_0_13z, celloutsig_0_15z, celloutsig_0_15z };
  assign { out_data[128], out_data[96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_19z, celloutsig_0_20z };
endmodule
