/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [9:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire [15:0] celloutsig_0_11z;
  wire celloutsig_0_12z;
  wire [9:0] celloutsig_0_14z;
  reg [4:0] celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire [6:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  reg [3:0] celloutsig_0_77z;
  reg [5:0] celloutsig_0_78z;
  wire [14:0] celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire celloutsig_1_0z;
  reg [6:0] celloutsig_1_11z;
  wire celloutsig_1_12z;
  wire celloutsig_1_17z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [2:0] celloutsig_1_6z;
  wire [13:0] celloutsig_1_7z;
  wire celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_3z = ~((in_data[101] | celloutsig_1_1z) & in_data[143]);
  assign celloutsig_0_12z = ~((celloutsig_0_8z | celloutsig_0_10z) & celloutsig_0_11z[13]);
  assign celloutsig_1_1z = ~((celloutsig_1_0z | celloutsig_1_0z) & (in_data[169] | celloutsig_1_0z));
  assign celloutsig_1_9z = ~((celloutsig_1_0z | 1'h1) & (in_data[105] | celloutsig_1_7z[10]));
  assign celloutsig_1_17z = ~((celloutsig_1_12z | celloutsig_1_11z[5]) & (celloutsig_1_1z | celloutsig_1_12z));
  assign celloutsig_0_8z = in_data[85] | celloutsig_0_6z;
  assign celloutsig_1_0z = in_data[160] | in_data[173];
  assign celloutsig_1_4z = in_data[132] | celloutsig_1_1z;
  assign celloutsig_1_12z = celloutsig_1_11z[6] | celloutsig_1_9z;
  assign celloutsig_1_18z = celloutsig_1_12z | celloutsig_1_6z[0];
  assign celloutsig_1_19z = celloutsig_1_4z | celloutsig_1_17z;
  assign celloutsig_1_2z = { celloutsig_1_1z, celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z } >= { in_data[123:121], celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_0_2z = celloutsig_0_0z >= in_data[48:39];
  assign celloutsig_0_5z = | celloutsig_0_4z;
  assign celloutsig_0_6z = | celloutsig_0_1z[4:1];
  assign celloutsig_1_5z = | { celloutsig_1_3z, celloutsig_1_1z, celloutsig_1_0z };
  assign celloutsig_0_10z = | { celloutsig_0_4z, celloutsig_0_2z, in_data[94:78] };
  assign celloutsig_0_4z = in_data[57:51] - { in_data[83], celloutsig_0_2z, celloutsig_0_1z };
  assign celloutsig_0_7z = { celloutsig_0_1z[4:2], celloutsig_0_1z, celloutsig_0_5z, celloutsig_0_5z, celloutsig_0_1z } - { celloutsig_0_4z[4:0], celloutsig_0_1z, celloutsig_0_1z };
  assign celloutsig_1_6z = { celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_2z } - { in_data[152], celloutsig_1_3z, celloutsig_1_2z };
  assign celloutsig_1_7z = in_data[186:173] - { celloutsig_1_0z, celloutsig_1_4z, celloutsig_1_5z, celloutsig_1_0z, celloutsig_1_6z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_6z, celloutsig_1_2z };
  assign celloutsig_0_11z = { in_data[35:21], celloutsig_0_6z } - { celloutsig_0_7z[14:1], celloutsig_0_5z, celloutsig_0_2z };
  assign celloutsig_0_0z = in_data[37:28] ~^ in_data[87:78];
  assign celloutsig_0_14z = { celloutsig_0_12z, celloutsig_0_8z, celloutsig_0_4z, celloutsig_0_6z } ~^ in_data[60:51];
  always_latch
    if (!celloutsig_1_18z) celloutsig_0_77z = 4'h0;
    else if (!clkin_data[0]) celloutsig_0_77z = celloutsig_0_14z[8:5];
  always_latch
    if (celloutsig_1_18z) celloutsig_0_78z = 6'h00;
    else if (clkin_data[0]) celloutsig_0_78z = { celloutsig_0_0z[5:1], celloutsig_0_10z };
  always_latch
    if (clkin_data[64]) celloutsig_1_11z = 7'h00;
    else if (clkin_data[32]) celloutsig_1_11z = { celloutsig_1_7z[3:0], celloutsig_1_9z, celloutsig_1_2z, celloutsig_1_3z };
  always_latch
    if (celloutsig_1_18z) celloutsig_0_1z = 5'h00;
    else if (!clkin_data[0]) celloutsig_0_1z = in_data[49:45];
  assign { out_data[128], out_data[96], out_data[35:32], out_data[5:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_77z, celloutsig_0_78z };
endmodule
