/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [18:0] _00_;
  reg [26:0] _01_;
  wire [5:0] celloutsig_0_1z;
  wire celloutsig_0_7z;
  wire celloutsig_0_8z;
  wire [4:0] celloutsig_1_0z;
  wire [4:0] celloutsig_1_14z;
  wire [5:0] celloutsig_1_18z;
  wire [16:0] celloutsig_1_19z;
  wire [3:0] celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire [16:0] celloutsig_1_4z;
  wire [8:0] celloutsig_1_5z;
  wire [34:0] celloutsig_1_6z;
  wire [2:0] celloutsig_1_7z;
  wire celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_7z = ~(in_data[60] & celloutsig_0_1z[4]);
  assign celloutsig_1_9z = ~(celloutsig_1_2z & celloutsig_1_4z[5]);
  always_ff @(negedge celloutsig_1_18z[0], negedge clkin_data[32])
    if (!clkin_data[32]) _00_ <= 19'h00000;
    else _00_ <= in_data[61:43];
  always_ff @(negedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _01_ <= 27'h0000000;
    else _01_ <= celloutsig_1_6z[33:7];
  assign celloutsig_1_14z = celloutsig_1_4z[9:5] & { celloutsig_1_4z[13], celloutsig_1_2z, celloutsig_1_7z };
  assign celloutsig_1_18z = { celloutsig_1_14z, celloutsig_1_9z } / { 1'h1, celloutsig_1_5z[6:2] };
  assign celloutsig_1_2z = celloutsig_1_1z === in_data[182:179];
  assign celloutsig_1_3z = celloutsig_1_0z && { celloutsig_1_0z[1], celloutsig_1_1z };
  assign celloutsig_1_6z = celloutsig_1_0z[2] ? { in_data[174], celloutsig_1_0z[4:3], 1'h1, celloutsig_1_0z[1:0], celloutsig_1_2z, celloutsig_1_5z, celloutsig_1_4z, celloutsig_1_3z, celloutsig_1_2z } : in_data[160:126];
  assign celloutsig_0_1z = - _00_[11:6];
  assign celloutsig_0_8z = _00_[11:3] !== { in_data[72:70], celloutsig_0_1z };
  assign celloutsig_1_4z = { in_data[145:130], celloutsig_1_2z } | { in_data[159:145], celloutsig_1_2z, celloutsig_1_3z };
  assign celloutsig_1_5z = { in_data[181:177], celloutsig_1_1z } >> { in_data[132:125], celloutsig_1_3z };
  assign celloutsig_1_7z = in_data[124:122] >> in_data[190:188];
  assign celloutsig_1_1z = celloutsig_1_0z[3:0] <<< celloutsig_1_0z[3:0];
  assign celloutsig_1_19z = _01_[19:3] >>> in_data[128:112];
  assign celloutsig_1_0z = in_data[179:175] ^ in_data[127:123];
  assign { out_data[133:128], out_data[112:96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_7z, celloutsig_0_8z };
endmodule
