/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [15:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire celloutsig_0_11z;
  wire celloutsig_0_13z;
  reg [5:0] celloutsig_0_14z;
  reg [3:0] celloutsig_0_15z;
  wire [5:0] celloutsig_0_16z;
  wire celloutsig_0_17z;
  wire [7:0] celloutsig_0_18z;
  wire [10:0] celloutsig_0_1z;
  wire [11:0] celloutsig_0_2z;
  wire [12:0] celloutsig_0_3z;
  wire [4:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire [26:0] celloutsig_0_6z;
  wire [3:0] celloutsig_0_7z;
  wire [2:0] celloutsig_0_8z;
  reg [18:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  reg [2:0] celloutsig_1_12z;
  wire [4:0] celloutsig_1_15z;
  wire [15:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [7:0] celloutsig_1_1z;
  reg [6:0] celloutsig_1_2z;
  wire [14:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire [3:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  input [191:0] clkin_data;
  wire [191:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_10z = ~(celloutsig_0_7z[1] & celloutsig_0_5z);
  assign celloutsig_0_5z = ~(celloutsig_0_4z[4] | celloutsig_0_4z[0]);
  assign celloutsig_0_11z = ~(celloutsig_0_3z[7] | celloutsig_0_7z[3]);
  assign celloutsig_0_17z = ~((celloutsig_0_6z[3] | celloutsig_0_9z[15]) & (celloutsig_0_11z | celloutsig_0_10z));
  assign celloutsig_1_4z = ~((celloutsig_1_0z | celloutsig_1_0z) & (celloutsig_1_1z[4] | celloutsig_1_3z[1]));
  assign celloutsig_1_7z = celloutsig_1_6z[3] | ~(celloutsig_1_2z[6]);
  assign celloutsig_1_8z = celloutsig_1_3z[11] | ~(celloutsig_1_5z);
  assign celloutsig_1_0z = in_data[103] | in_data[125];
  assign celloutsig_1_5z = celloutsig_1_0z | celloutsig_1_3z[14];
  assign celloutsig_0_13z = ~(celloutsig_0_4z[1] ^ celloutsig_0_9z[11]);
  assign celloutsig_0_4z = celloutsig_0_2z[9:5] + in_data[24:20];
  assign celloutsig_0_2z = { celloutsig_0_0z[10], celloutsig_0_1z } + celloutsig_0_0z[13:2];
  assign celloutsig_0_3z = in_data[52:40] / { 1'h1, celloutsig_0_1z[1], celloutsig_0_1z };
  assign celloutsig_0_8z = celloutsig_0_1z[2:0] / { 1'h1, celloutsig_0_6z[6:5] };
  assign celloutsig_1_6z = celloutsig_1_2z[4:1] / { 1'h1, celloutsig_1_1z[2:1], celloutsig_1_0z };
  assign celloutsig_0_1z = in_data[79] ? in_data[38:28] : in_data[19:9];
  assign celloutsig_0_16z = celloutsig_0_14z[5] ? celloutsig_0_2z[10:5] : { celloutsig_0_4z[3:2], celloutsig_0_15z };
  assign celloutsig_1_1z[7:1] = in_data[178] ? { in_data[179], 1'h1, in_data[177:173] } : in_data[116:110];
  assign celloutsig_0_7z = - celloutsig_0_3z[11:8];
  assign celloutsig_0_0z = ~ in_data[77:62];
  assign celloutsig_1_15z = ~ { celloutsig_1_12z[0], celloutsig_1_6z };
  assign celloutsig_1_18z = ~ { celloutsig_1_2z[3:2], celloutsig_1_6z, celloutsig_1_12z, celloutsig_1_4z, celloutsig_1_15z, celloutsig_1_7z };
  assign celloutsig_0_18z = ~ { celloutsig_0_16z[5:1], celloutsig_0_8z };
  assign celloutsig_1_3z = ~ in_data[123:109];
  assign celloutsig_1_19z = | { celloutsig_1_18z, celloutsig_1_6z[2] };
  assign celloutsig_0_6z = { celloutsig_0_1z[10:2], celloutsig_0_4z, celloutsig_0_3z } >> { celloutsig_0_0z[14:5], celloutsig_0_0z, celloutsig_0_5z };
  always_latch
    if (!clkin_data[160]) celloutsig_1_12z = 3'h0;
    else if (clkin_data[64]) celloutsig_1_12z = { celloutsig_1_2z[4:3], celloutsig_1_8z };
  always_latch
    if (!clkin_data[128]) celloutsig_0_9z = 19'h00000;
    else if (!celloutsig_1_18z[0]) celloutsig_0_9z = in_data[88:70];
  always_latch
    if (!clkin_data[128]) celloutsig_0_14z = 6'h00;
    else if (clkin_data[0]) celloutsig_0_14z = { celloutsig_0_2z[7:3], celloutsig_0_13z };
  always_latch
    if (!clkin_data[96]) celloutsig_0_15z = 4'h0;
    else if (clkin_data[0]) celloutsig_0_15z = celloutsig_0_9z[13:10];
  always_latch
    if (clkin_data[160]) celloutsig_1_2z = 7'h00;
    else if (!clkin_data[32]) celloutsig_1_2z = { celloutsig_1_1z[7:2], celloutsig_1_0z };
  assign celloutsig_1_1z[0] = celloutsig_1_0z;
  assign { out_data[143:128], out_data[96], out_data[32], out_data[7:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_17z, celloutsig_0_18z };
endmodule
