/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [3:0] _01_;
  wire [5:0] _02_;
  reg [9:0] _03_;
  wire [20:0] celloutsig_0_1z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire [3:0] celloutsig_1_11z;
  wire celloutsig_1_12z;
  wire [5:0] celloutsig_1_14z;
  wire [2:0] celloutsig_1_16z;
  wire celloutsig_1_18z;
  wire [24:0] celloutsig_1_19z;
  wire celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire [3:0] celloutsig_1_4z;
  wire [2:0] celloutsig_1_6z;
  wire celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_2z = celloutsig_1_0z ? in_data[163] : _00_;
  assign celloutsig_1_3z = celloutsig_1_0z ? celloutsig_1_2z : in_data[152];
  assign celloutsig_1_4z = { _01_[3], celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_2z } + { in_data[136], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_2z };
  reg [2:0] _07_;
  always_ff @(posedge celloutsig_1_19z[0], posedge clkin_data[64])
    if (clkin_data[64]) _07_ <= 3'h0;
    else _07_ <= in_data[43:41];
  assign out_data[34:32] = _07_;
  reg [5:0] _08_;
  always_ff @(negedge clkin_data[0], posedge clkin_data[128])
    if (clkin_data[128]) _08_ <= 6'h00;
    else _08_ <= in_data[186:181];
  assign { _01_[3], _00_, _02_[3:0] } = _08_;
  always_ff @(negedge clkin_data[32], posedge clkin_data[96])
    if (clkin_data[96]) _03_ <= 10'h000;
    else _03_ <= { _00_, _02_[3:1], celloutsig_1_2z, celloutsig_1_4z, celloutsig_1_2z };
  assign celloutsig_1_6z = _03_[5:3] & celloutsig_1_4z[3:1];
  assign celloutsig_1_19z = { celloutsig_1_18z, celloutsig_1_6z, celloutsig_1_10z, celloutsig_1_14z, celloutsig_1_14z, celloutsig_1_3z, _01_[3], _00_, _02_[3:0], celloutsig_1_12z } & { celloutsig_1_14z[3], celloutsig_1_11z, celloutsig_1_10z, celloutsig_1_7z, celloutsig_1_12z, celloutsig_1_7z, celloutsig_1_14z, _03_ };
  assign celloutsig_1_18z = { _03_[2], _03_, celloutsig_1_12z, celloutsig_1_3z } < { in_data[164:163], _01_[3], _00_, _02_[3:0], celloutsig_1_7z, celloutsig_1_16z, celloutsig_1_10z };
  assign celloutsig_1_0z = in_data[170:157] < in_data[148:135];
  assign celloutsig_1_8z = { celloutsig_1_6z[1], celloutsig_1_3z, _01_[3], _00_, _02_[3:0], celloutsig_1_4z, _03_ } !== { in_data[177:171], celloutsig_1_2z, _01_[3], _00_, _02_[3:0], celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_3z, _01_[3], _00_, _02_[3:1] };
  assign celloutsig_1_9z = _03_[3:1] !== celloutsig_1_4z[3:1];
  assign celloutsig_1_10z = { _02_[3:2], celloutsig_1_8z, celloutsig_1_6z } !== { _03_[8:4], celloutsig_1_7z };
  assign celloutsig_1_16z = celloutsig_1_11z[2:0] | { _03_[1], celloutsig_1_0z, celloutsig_1_3z };
  assign celloutsig_0_1z = in_data[22:2] << in_data[62:42];
  assign celloutsig_1_11z = { _00_, _02_[3:1] } <<< { _00_, celloutsig_1_6z };
  assign celloutsig_1_14z = in_data[170:165] <<< { _01_[3], _00_, celloutsig_1_11z };
  assign celloutsig_1_7z = ~((in_data[177] & _03_[3]) | _03_[3]);
  assign celloutsig_1_12z = ~((celloutsig_1_10z & celloutsig_1_9z) | celloutsig_1_11z[0]);
  assign _01_[2:0] = { celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_2z };
  assign _02_[5:4] = { _01_[3], _00_ };
  assign { out_data[128], out_data[120:96], out_data[20:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_1z };
endmodule
