/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [9:0] celloutsig_0_1z;
  wire [8:0] celloutsig_0_4z;
  wire [2:0] celloutsig_0_5z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire [10:0] celloutsig_1_11z;
  wire celloutsig_1_14z;
  wire celloutsig_1_18z;
  wire [2:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [17:0] celloutsig_1_2z;
  wire [5:0] celloutsig_1_3z;
  wire [7:0] celloutsig_1_4z;
  wire [2:0] celloutsig_1_5z;
  wire [8:0] celloutsig_1_6z;
  wire [4:0] celloutsig_1_8z;
  input [31:0] clkin_data;
  wire [31:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_1z = ~((celloutsig_1_0z | celloutsig_1_0z) & (in_data[144] | celloutsig_1_0z));
  assign celloutsig_1_10z = ~(celloutsig_1_2z[6] ^ celloutsig_1_8z[3]);
  assign celloutsig_0_4z = celloutsig_0_1z[8:0] + in_data[37:29];
  assign celloutsig_1_5z = celloutsig_1_3z[4:2] / { 1'h1, celloutsig_1_2z[13:12] };
  assign celloutsig_1_14z = { celloutsig_1_11z[10:1], celloutsig_1_8z } == { in_data[164:162], celloutsig_1_11z, celloutsig_1_10z };
  assign celloutsig_1_2z = { in_data[135:120], celloutsig_1_1z, celloutsig_1_1z } % { 1'h1, in_data[182:166] };
  assign celloutsig_1_4z = { celloutsig_1_2z[8:2], celloutsig_1_0z } % { 1'h1, celloutsig_1_1z, celloutsig_1_3z };
  assign celloutsig_1_0z = in_data[182:153] != in_data[155:126];
  assign celloutsig_0_5z = ~ celloutsig_0_4z[2:0];
  assign celloutsig_1_11z = ~ celloutsig_1_2z[15:5];
  assign celloutsig_1_18z = | { celloutsig_1_11z[7:5], celloutsig_1_14z, celloutsig_1_5z, celloutsig_1_10z };
  assign celloutsig_1_3z = { in_data[126:122], celloutsig_1_1z } <<< { in_data[170:168], celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_1_8z = { celloutsig_1_4z[4:3], celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z } <<< { celloutsig_1_2z[6:3], celloutsig_1_0z };
  assign celloutsig_1_6z = in_data[104:96] - { celloutsig_1_5z[2], celloutsig_1_4z };
  assign celloutsig_1_19z = celloutsig_1_6z[6:4] - celloutsig_1_4z[3:1];
  always_latch
    if (!celloutsig_1_18z) celloutsig_0_1z = 10'h000;
    else if (!clkin_data[0]) celloutsig_0_1z = in_data[83:74];
  assign { out_data[128], out_data[98:96], out_data[40:32], out_data[2:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_4z, celloutsig_0_5z };
endmodule
