/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire _01_;
  wire [11:0] _02_;
  wire [6:0] _03_;
  wire [10:0] celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire [5:0] celloutsig_0_4z;
  wire [8:0] celloutsig_0_5z;
  wire [3:0] celloutsig_1_0z;
  wire [5:0] celloutsig_1_11z;
  wire celloutsig_1_13z;
  wire [15:0] celloutsig_1_18z;
  wire [7:0] celloutsig_1_19z;
  wire [5:0] celloutsig_1_1z;
  wire [4:0] celloutsig_1_2z;
  wire [2:0] celloutsig_1_3z;
  wire [10:0] celloutsig_1_4z;
  wire [9:0] celloutsig_1_5z;
  wire [7:0] celloutsig_1_7z;
  wire [7:0] celloutsig_1_8z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_13z = celloutsig_1_7z[5] ? _01_ : celloutsig_1_11z[0];
  assign celloutsig_0_2z = _00_ ? celloutsig_0_1z[9] : celloutsig_0_1z[1];
  reg [11:0] _06_;
  always_ff @(posedge celloutsig_1_19z[0], negedge clkin_data[32])
    if (!clkin_data[32]) _06_ <= 12'h000;
    else _06_ <= in_data[51:40];
  assign { _02_[11:3], _00_, _02_[1:0] } = _06_;
  reg [6:0] _07_;
  always_ff @(posedge clkin_data[0], posedge clkin_data[64])
    if (clkin_data[64]) _07_ <= 7'h00;
    else _07_ <= celloutsig_1_8z[7:1];
  assign { _03_[6:2], _01_, _03_[0] } = _07_;
  assign celloutsig_1_0z = in_data[103:100] & in_data[142:139];
  assign celloutsig_1_1z = { celloutsig_1_0z[3:2], celloutsig_1_0z } & in_data[173:168];
  assign celloutsig_1_2z = in_data[123:119] & celloutsig_1_1z[4:0];
  assign celloutsig_1_5z = { in_data[187:181], celloutsig_1_3z } & { celloutsig_1_1z, celloutsig_1_0z };
  assign celloutsig_0_1z = { _02_[10:3], _00_, _02_[1:0] } & { _02_[10:3], _00_, _02_[1:0] };
  assign celloutsig_0_5z = { celloutsig_0_4z[3:1], celloutsig_0_4z } * { in_data[89], celloutsig_0_4z, celloutsig_0_2z, celloutsig_0_2z };
  assign celloutsig_1_4z = in_data[170:160] * in_data[155:145];
  assign celloutsig_1_7z = { celloutsig_1_2z[1:0], celloutsig_1_1z } * in_data[166:159];
  assign celloutsig_1_8z = celloutsig_1_4z[10:3] * in_data[119:112];
  assign celloutsig_1_18z = { in_data[186:179], celloutsig_1_7z } * { _03_[5], celloutsig_1_13z, celloutsig_1_8z, celloutsig_1_1z };
  assign celloutsig_1_19z = { celloutsig_1_4z[9:5], celloutsig_1_3z } * celloutsig_1_18z[7:0];
  assign celloutsig_1_3z = in_data[186:184] | in_data[102:100];
  assign celloutsig_1_11z = celloutsig_1_5z[9:4] | { celloutsig_1_3z[2:1], celloutsig_1_0z };
  assign celloutsig_0_4z = in_data[20:15] >>> in_data[85:80];
  assign _02_[2] = _00_;
  assign _03_[1] = _01_;
  assign { out_data[143:128], out_data[103:96], out_data[37:32], out_data[8:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_4z, celloutsig_0_5z };
endmodule
