/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_16z;
  reg [4:0] celloutsig_0_17z;
  wire [7:0] celloutsig_0_1z;
  wire [6:0] celloutsig_0_3z;
  wire celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire [5:0] celloutsig_1_0z;
  reg [3:0] celloutsig_1_11z;
  wire [4:0] celloutsig_1_13z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [2:0] celloutsig_1_1z;
  wire [2:0] celloutsig_1_2z;
  wire [2:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_5z;
  wire celloutsig_1_6z;
  wire [9:0] celloutsig_1_7z;
  wire [24:0] celloutsig_1_8z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_7z = ~(celloutsig_0_3z[1] | celloutsig_0_0z);
  assign celloutsig_1_0z = in_data[119:114] / { 1'h1, in_data[170:166] };
  assign celloutsig_1_1z = in_data[164:162] / { 1'h1, celloutsig_1_0z[3:2] };
  assign celloutsig_1_19z = celloutsig_1_8z[24:6] > in_data[174:156];
  assign celloutsig_1_6z = { in_data[178:174], celloutsig_1_5z, celloutsig_1_0z, celloutsig_1_3z } > { in_data[165:158], celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_5z };
  assign celloutsig_1_18z = ! { celloutsig_1_11z[1], celloutsig_1_3z, celloutsig_1_5z, celloutsig_1_1z, celloutsig_1_13z, celloutsig_1_0z, celloutsig_1_11z };
  assign celloutsig_0_6z = ! celloutsig_0_1z[4:0];
  assign celloutsig_1_4z = ! in_data[170:153];
  assign celloutsig_1_5z = ! { celloutsig_1_0z[5:3], celloutsig_1_3z };
  assign celloutsig_1_8z = { in_data[189:188], celloutsig_1_1z, celloutsig_1_5z, celloutsig_1_7z, celloutsig_1_0z, celloutsig_1_6z, celloutsig_1_4z, celloutsig_1_4z } * { celloutsig_1_0z[4:0], celloutsig_1_6z, celloutsig_1_5z, celloutsig_1_5z, celloutsig_1_2z, celloutsig_1_4z, celloutsig_1_3z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_3z, celloutsig_1_5z };
  assign celloutsig_1_2z = ~ celloutsig_1_1z;
  assign celloutsig_1_3z = ~ celloutsig_1_2z;
  assign celloutsig_1_7z = ~ { in_data[150:148], celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_4z };
  assign celloutsig_0_3z = ~ celloutsig_0_1z[6:0];
  assign celloutsig_1_13z = ~ celloutsig_1_7z[8:4];
  assign celloutsig_0_0z = & in_data[39:3];
  assign celloutsig_0_1z = { in_data[70:64], celloutsig_0_0z } >> { in_data[14:8], celloutsig_0_0z };
  always_latch
    if (celloutsig_1_19z) celloutsig_0_17z = 5'h00;
    else if (clkin_data[0]) celloutsig_0_17z = { in_data[9:6], celloutsig_0_6z };
  always_latch
    if (clkin_data[64]) celloutsig_1_11z = 4'h0;
    else if (!clkin_data[32]) celloutsig_1_11z = { celloutsig_1_0z[5:3], celloutsig_1_6z };
  assign celloutsig_0_16z = ~((in_data[4] & celloutsig_0_1z[5]) | (celloutsig_0_7z & celloutsig_0_7z));
  assign { out_data[128], out_data[96], out_data[32], out_data[4:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_16z, celloutsig_0_17z };
endmodule
