/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire [7:0] celloutsig_0_0z;
  wire [5:0] celloutsig_0_12z;
  wire celloutsig_0_13z;
  wire [2:0] celloutsig_0_16z;
  wire [12:0] celloutsig_0_17z;
  reg [21:0] celloutsig_0_1z;
  wire celloutsig_0_28z;
  wire celloutsig_0_29z;
  wire celloutsig_0_2z;
  wire celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  reg [15:0] celloutsig_0_7z;
  reg [7:0] celloutsig_0_8z;
  wire [7:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire celloutsig_1_10z;
  reg [4:0] celloutsig_1_12z;
  wire celloutsig_1_13z;
  wire [23:0] celloutsig_1_14z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  reg [16:0] celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [3:0] celloutsig_1_3z;
  wire [6:0] celloutsig_1_4z;
  reg [5:0] celloutsig_1_6z;
  wire [4:0] celloutsig_1_7z;
  wire [15:0] celloutsig_1_8z;
  wire [5:0] celloutsig_1_9z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_19z = ~(celloutsig_1_18z | celloutsig_1_14z[19]);
  assign celloutsig_0_6z = ~(celloutsig_0_1z[0] | celloutsig_0_0z[3]);
  assign celloutsig_0_28z = ~(celloutsig_0_4z | celloutsig_0_13z);
  assign celloutsig_1_0z = ~(in_data[134] | in_data[118]);
  assign celloutsig_1_2z = celloutsig_1_1z[12] | celloutsig_1_0z;
  assign celloutsig_0_4z = in_data[59] | celloutsig_0_1z[8];
  assign celloutsig_0_29z = celloutsig_0_6z | celloutsig_0_17z[8];
  assign celloutsig_0_2z = ~(celloutsig_0_1z[7] ^ celloutsig_0_0z[4]);
  assign celloutsig_1_9z = celloutsig_1_6z / { 1'h1, celloutsig_1_6z[3:0], celloutsig_1_0z };
  assign celloutsig_0_12z = celloutsig_0_1z[16:11] / { 1'h1, celloutsig_0_9z[5:1] };
  assign celloutsig_0_16z = { celloutsig_0_0z[4:3], celloutsig_0_6z } / { 1'h1, in_data[41], celloutsig_0_2z };
  assign celloutsig_0_17z = { celloutsig_0_9z[3:1], celloutsig_0_16z, celloutsig_0_12z, celloutsig_0_2z } / { 1'h1, celloutsig_0_1z[16:5] };
  assign celloutsig_1_10z = { celloutsig_1_3z[1:0], celloutsig_1_3z, celloutsig_1_4z, celloutsig_1_6z, celloutsig_1_2z, celloutsig_1_6z[5], celloutsig_1_9z, celloutsig_1_2z, celloutsig_1_9z, celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_1z } === { celloutsig_1_1z[14:12], celloutsig_1_7z, celloutsig_1_6z, 7'h7f, celloutsig_1_0z, celloutsig_1_8z, 6'h3f, celloutsig_1_4z, celloutsig_1_0z, celloutsig_1_3z };
  assign celloutsig_1_13z = { in_data[163:154], celloutsig_1_6z } === { in_data[150:147], celloutsig_1_9z, celloutsig_1_2z, celloutsig_1_10z, celloutsig_1_3z };
  assign celloutsig_1_18z = { celloutsig_1_8z[4:1], celloutsig_1_7z, celloutsig_1_13z } === { celloutsig_1_14z[9:6], celloutsig_1_9z };
  assign celloutsig_0_13z = { celloutsig_0_8z[6:3], celloutsig_0_4z } === celloutsig_0_0z[7:3];
  assign celloutsig_0_5z = & in_data[93:84];
  assign celloutsig_1_3z = { in_data[179:177], celloutsig_1_2z } >> { in_data[100:98], celloutsig_1_0z };
  assign celloutsig_0_0z = in_data[45:38] - in_data[36:29];
  assign celloutsig_1_4z = { in_data[175:170], celloutsig_1_0z } - { celloutsig_1_1z[3:0], celloutsig_1_0z, celloutsig_1_2z, celloutsig_1_0z };
  assign celloutsig_1_7z = celloutsig_1_4z[4:0] - { celloutsig_1_3z[3:1], celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_1_8z = { celloutsig_1_6z[4:1], celloutsig_1_3z, celloutsig_1_2z, celloutsig_1_4z } - { celloutsig_1_7z[3:2], celloutsig_1_4z, celloutsig_1_2z, 6'h3f };
  assign celloutsig_1_14z = { celloutsig_1_8z[11:0], celloutsig_1_4z, celloutsig_1_12z } - in_data[187:164];
  assign celloutsig_0_9z = { celloutsig_0_7z[14:9], celloutsig_0_5z, celloutsig_0_4z } ^ celloutsig_0_0z;
  always_latch
    if (clkin_data[96]) celloutsig_1_6z = 6'h00;
    else if (!clkin_data[0]) celloutsig_1_6z = { in_data[108:104], celloutsig_1_0z };
  always_latch
    if (clkin_data[96]) celloutsig_1_12z = 5'h00;
    else if (clkin_data[0]) celloutsig_1_12z = celloutsig_1_8z[7:3];
  always_latch
    if (!clkin_data[64]) celloutsig_0_7z = 16'h0000;
    else if (celloutsig_1_19z) celloutsig_0_7z = { celloutsig_0_1z[12:0], celloutsig_0_6z, celloutsig_0_4z, celloutsig_0_6z };
  always_latch
    if (clkin_data[32]) celloutsig_0_8z = 8'h00;
    else if (!celloutsig_1_19z) celloutsig_0_8z = in_data[77:70];
  always_latch
    if (!clkin_data[32]) celloutsig_0_1z = 22'h000000;
    else if (!celloutsig_1_19z) celloutsig_0_1z = in_data[54:33];
  always_latch
    if (clkin_data[128]) celloutsig_1_1z = 17'h00000;
    else if (!clkin_data[0]) celloutsig_1_1z = in_data[188:172];
  assign { out_data[128], out_data[96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_28z, celloutsig_0_29z };
endmodule
