/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_13z;
  reg [7:0] celloutsig_0_14z;
  wire celloutsig_0_1z;
  wire [2:0] celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire [5:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire [3:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire [6:0] celloutsig_1_10z;
  wire [26:0] celloutsig_1_11z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [10:0] celloutsig_1_1z;
  wire [6:0] celloutsig_1_3z;
  reg [3:0] celloutsig_1_5z;
  wire [3:0] celloutsig_1_6z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_0z = ~(in_data[90] | in_data[47]);
  assign celloutsig_0_7z = celloutsig_0_3z ^ celloutsig_0_2z[0];
  assign celloutsig_1_0z = ~(in_data[177] ^ in_data[111]);
  assign celloutsig_1_10z = { celloutsig_1_6z[2:0], celloutsig_1_6z } & { celloutsig_1_1z[7:6], celloutsig_1_6z, celloutsig_1_0z };
  assign celloutsig_0_4z = in_data[36:31] / { 1'h1, in_data[71:69], celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_0_9z = in_data[81:78] / { 1'h1, celloutsig_0_2z[1], celloutsig_0_7z, celloutsig_0_7z };
  assign celloutsig_1_1z = { in_data[184:175], celloutsig_1_0z } % { 1'h1, in_data[155:147], in_data[96] };
  assign celloutsig_1_6z = celloutsig_1_5z % { 1'h1, celloutsig_1_1z[8:6] };
  assign celloutsig_1_3z = - celloutsig_1_1z[6:0];
  assign celloutsig_0_2z = - { in_data[78:77], celloutsig_0_0z };
  assign celloutsig_1_11z = - in_data[174:148];
  assign celloutsig_1_18z = celloutsig_1_11z[25] & celloutsig_1_5z[3];
  assign celloutsig_1_19z = celloutsig_1_10z[1] & celloutsig_1_11z[4];
  assign celloutsig_0_5z = ^ { in_data[5:3], celloutsig_0_3z };
  assign celloutsig_0_6z = ~((celloutsig_0_5z & celloutsig_0_4z[2]) | celloutsig_0_5z);
  assign celloutsig_0_1z = ~((in_data[29] & celloutsig_0_0z) | celloutsig_0_0z);
  assign celloutsig_0_13z = ~((in_data[12] & celloutsig_0_0z) | celloutsig_0_5z);
  always_latch
    if (celloutsig_1_18z) celloutsig_0_14z = 8'h00;
    else if (!clkin_data[0]) celloutsig_0_14z = { celloutsig_0_2z[0], celloutsig_0_3z, celloutsig_0_9z, celloutsig_0_1z, celloutsig_0_6z };
  always_latch
    if (clkin_data[64]) celloutsig_1_5z = 4'h0;
    else if (!clkin_data[32]) celloutsig_1_5z = celloutsig_1_3z[6:3];
  assign celloutsig_0_3z = ~((in_data[5] & celloutsig_0_1z) | (in_data[38] & celloutsig_0_0z));
  assign { out_data[128], out_data[96], out_data[32], out_data[7:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_13z, celloutsig_0_14z };
endmodule
