/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  reg [21:0] celloutsig_0_0z;
  wire [7:0] celloutsig_0_11z;
  wire celloutsig_0_12z;
  wire [2:0] celloutsig_0_17z;
  wire celloutsig_0_19z;
  wire celloutsig_0_1z;
  reg [5:0] celloutsig_0_21z;
  wire celloutsig_0_23z;
  wire celloutsig_0_24z;
  wire celloutsig_0_2z;
  wire [20:0] celloutsig_0_3z;
  wire [2:0] celloutsig_0_4z;
  reg [2:0] celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire [3:0] celloutsig_0_8z;
  wire [23:0] celloutsig_0_9z;
  wire celloutsig_1_0z;
  reg [3:0] celloutsig_1_11z;
  wire [3:0] celloutsig_1_12z;
  wire [3:0] celloutsig_1_13z;
  wire celloutsig_1_18z;
  wire [4:0] celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [9:0] celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire [12:0] celloutsig_1_7z;
  wire celloutsig_1_8z;
  wire [6:0] celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_18z = celloutsig_1_12z[3] ? celloutsig_1_9z[6] : celloutsig_1_13z[0];
  assign celloutsig_1_2z = !(celloutsig_1_1z ? in_data[116] : celloutsig_1_1z);
  assign celloutsig_1_8z = ~((celloutsig_1_7z[11] | celloutsig_1_0z) & celloutsig_1_7z[10]);
  assign celloutsig_0_24z = ~((celloutsig_0_17z[0] | celloutsig_0_7z) & celloutsig_0_3z[14]);
  assign celloutsig_1_0z = ~((in_data[169] | in_data[155]) & in_data[158]);
  assign celloutsig_0_23z = ~((celloutsig_0_0z[15] | celloutsig_0_0z[6]) & (celloutsig_0_21z[5] | celloutsig_0_8z[3]));
  assign celloutsig_0_7z = celloutsig_0_6z[1] | ~(celloutsig_0_3z[2]);
  assign celloutsig_0_19z = celloutsig_0_1z | ~(in_data[11]);
  assign celloutsig_1_4z = celloutsig_1_0z | ~(celloutsig_1_2z);
  assign celloutsig_0_1z = in_data[13] | in_data[23];
  assign celloutsig_0_11z = celloutsig_0_9z[10:3] + { celloutsig_0_4z, celloutsig_0_6z, celloutsig_0_2z, celloutsig_0_7z };
  assign celloutsig_1_7z = { celloutsig_1_3z[8:7], celloutsig_1_1z, celloutsig_1_3z } & in_data[150:138];
  assign celloutsig_1_9z = { celloutsig_1_3z[9:4], celloutsig_1_2z } / { 1'h1, celloutsig_1_7z[8:3] };
  assign celloutsig_1_13z = celloutsig_1_11z / { 1'h1, in_data[184:182] };
  assign celloutsig_0_2z = celloutsig_0_0z[10:6] === in_data[42:38];
  assign celloutsig_1_1z = in_data[150:130] > { in_data[148:129], celloutsig_1_0z };
  assign celloutsig_0_12z = celloutsig_0_1z & ~(celloutsig_0_1z);
  assign celloutsig_1_19z = ~ { celloutsig_1_3z[4], celloutsig_1_12z };
  assign celloutsig_1_12z = { celloutsig_1_7z[6:5], celloutsig_1_4z, celloutsig_1_8z } | celloutsig_1_11z;
  assign celloutsig_0_4z = celloutsig_0_0z[12:10] | celloutsig_0_0z[17:15];
  assign celloutsig_0_9z = { celloutsig_0_4z[2:1], celloutsig_0_3z, celloutsig_0_1z } | { celloutsig_0_6z[1:0], celloutsig_0_0z };
  assign celloutsig_0_17z = { celloutsig_0_4z[1:0], celloutsig_0_2z } | { celloutsig_0_11z[2:1], celloutsig_0_12z };
  assign celloutsig_0_3z = in_data[42:22] >> { celloutsig_0_0z[20:2], celloutsig_0_2z, celloutsig_0_1z };
  assign celloutsig_1_3z = { in_data[146:138], celloutsig_1_2z } >> { in_data[168:160], celloutsig_1_1z };
  assign celloutsig_0_8z = { celloutsig_0_0z[12], celloutsig_0_6z } - { celloutsig_0_1z, celloutsig_0_6z };
  always_latch
    if (!clkin_data[64]) celloutsig_0_0z = 22'h000000;
    else if (!clkin_data[0]) celloutsig_0_0z = in_data[53:32];
  always_latch
    if (!clkin_data[96]) celloutsig_1_11z = 4'h0;
    else if (clkin_data[32]) celloutsig_1_11z = in_data[105:102];
  always_latch
    if (clkin_data[64]) celloutsig_0_6z = 3'h0;
    else if (!clkin_data[0]) celloutsig_0_6z = in_data[72:70];
  always_latch
    if (celloutsig_1_19z[0]) celloutsig_0_21z = 6'h00;
    else if (clkin_data[0]) celloutsig_0_21z = { celloutsig_0_11z[4:0], celloutsig_0_19z };
  assign { out_data[128], out_data[100:96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_23z, celloutsig_0_24z };
endmodule
