/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire celloutsig_0_0z;
  wire celloutsig_0_1z;
  wire [27:0] celloutsig_0_2z;
  wire celloutsig_0_3z;
  reg [23:0] celloutsig_0_4z;
  wire celloutsig_0_5z;
  wire celloutsig_0_6z;
  wire celloutsig_0_7z;
  reg [8:0] celloutsig_1_0z;
  wire celloutsig_1_12z;
  wire [2:0] celloutsig_1_15z;
  wire [8:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire [10:0] celloutsig_1_1z;
  wire [21:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_6z;
  wire celloutsig_1_8z;
  wire [4:0] celloutsig_1_9z;
  input [95:0] clkin_data;
  wire [95:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_6z = ~celloutsig_0_5z;
  assign celloutsig_1_4z = ~celloutsig_1_3z;
  assign celloutsig_0_1z = ~celloutsig_0_0z;
  assign celloutsig_0_3z = celloutsig_0_2z[0] ^ celloutsig_0_0z;
  assign celloutsig_1_3z = celloutsig_1_0z[4] ^ celloutsig_1_2z[10];
  assign celloutsig_0_0z = ~(in_data[30] ^ in_data[64]);
  assign celloutsig_0_7z = { in_data[13:8], celloutsig_0_5z, celloutsig_0_3z, celloutsig_0_3z, celloutsig_0_1z } > { celloutsig_0_4z[18:12], celloutsig_0_6z, celloutsig_0_3z, celloutsig_0_1z };
  assign celloutsig_1_6z = { celloutsig_1_1z[9:8], celloutsig_1_4z, celloutsig_1_4z, celloutsig_1_3z, celloutsig_1_2z } > { celloutsig_1_1z[6:3], celloutsig_1_4z, celloutsig_1_0z, 1'h0, celloutsig_1_3z, celloutsig_1_1z };
  assign celloutsig_1_8z = { in_data[189:181], 1'h0 } > { celloutsig_1_0z[7:1], 1'h0, celloutsig_1_6z, celloutsig_1_6z };
  assign celloutsig_0_2z = celloutsig_0_0z ? in_data[68:41] : { in_data[60:34], celloutsig_0_1z };
  assign celloutsig_0_5z = in_data[21:9] != { celloutsig_0_2z[10:0], celloutsig_0_0z, celloutsig_0_0z };
  assign celloutsig_1_12z = in_data[137:121] != in_data[184:168];
  assign celloutsig_1_19z = { in_data[139], celloutsig_1_15z, celloutsig_1_8z } != { celloutsig_1_18z[7:4], celloutsig_1_12z };
  assign celloutsig_1_1z = { celloutsig_1_0z[6:5], celloutsig_1_0z } | in_data[123:113];
  assign celloutsig_1_2z = { in_data[150:149], celloutsig_1_1z, celloutsig_1_0z } <<< { celloutsig_1_1z, celloutsig_1_1z };
  assign celloutsig_1_15z = { celloutsig_1_2z[19:18], celloutsig_1_12z } - { celloutsig_1_9z[1:0], celloutsig_1_4z };
  assign celloutsig_1_9z = { celloutsig_1_1z[10:7], celloutsig_1_6z } ^ { celloutsig_1_1z[7:4], celloutsig_1_3z };
  assign celloutsig_1_18z = { celloutsig_1_2z[12:5], celloutsig_1_12z } ^ celloutsig_1_1z[9:1];
  always_latch
    if (!celloutsig_1_19z) celloutsig_0_4z = 24'h000000;
    else if (!clkin_data[0]) celloutsig_0_4z = { in_data[22:4], celloutsig_0_3z, celloutsig_0_3z, celloutsig_0_0z, celloutsig_0_1z, celloutsig_0_0z };
  always_latch
    if (clkin_data[64]) celloutsig_1_0z = 9'h000;
    else if (!clkin_data[32]) celloutsig_1_0z = in_data[147:139];
  assign { out_data[136:128], out_data[96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_6z, celloutsig_0_7z };
endmodule
