/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [9:0] _01_;
  wire celloutsig_0_0z;
  wire celloutsig_0_11z;
  wire [11:0] celloutsig_0_15z;
  reg [14:0] celloutsig_0_16z;
  wire celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire celloutsig_0_9z;
  wire celloutsig_1_0z;
  wire [17:0] celloutsig_1_10z;
  wire celloutsig_1_11z;
  reg [25:0] celloutsig_1_16z;
  wire celloutsig_1_18z;
  wire [7:0] celloutsig_1_19z;
  wire [12:0] celloutsig_1_1z;
  wire [2:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire celloutsig_1_6z;
  wire celloutsig_1_8z;
  wire [8:0] celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_1z = celloutsig_0_0z ? celloutsig_0_0z : in_data[11];
  assign celloutsig_1_0z = in_data[175] ? in_data[164] : in_data[174];
  assign celloutsig_1_8z = celloutsig_1_2z[1] ? celloutsig_1_6z : celloutsig_1_4z;
  assign celloutsig_0_0z = ~(in_data[64] & in_data[74]);
  assign celloutsig_0_9z = ~((celloutsig_0_0z | celloutsig_0_2z) & celloutsig_0_2z);
  assign celloutsig_1_4z = in_data[156] | celloutsig_1_0z;
  assign celloutsig_1_19z = celloutsig_1_16z[16:9] + celloutsig_1_16z[24:17];
  reg [9:0] _09_;
  always_ff @(posedge clkin_data[0], posedge clkin_data[32])
    if (clkin_data[32]) _09_ <= 10'h000;
    else _09_ <= in_data[35:26];
  assign { _01_[9:3], _00_, _01_[1:0] } = _09_;
  assign celloutsig_1_1z = { in_data[150:139], celloutsig_1_0z } & { in_data[142:131], celloutsig_1_0z };
  assign celloutsig_1_9z = { celloutsig_1_2z, celloutsig_1_4z, celloutsig_1_4z, celloutsig_1_2z, celloutsig_1_3z } & in_data[120:112];
  assign celloutsig_1_6z = { celloutsig_1_1z[4:2], celloutsig_1_4z } <= in_data[138:135];
  assign celloutsig_0_11z = _01_[6] & ~(celloutsig_0_9z);
  assign celloutsig_1_11z = celloutsig_1_10z[4] & ~(celloutsig_1_9z[6]);
  assign celloutsig_1_3z = { in_data[145:143], celloutsig_1_1z } !== { celloutsig_1_2z[1:0], celloutsig_1_1z, celloutsig_1_0z };
  assign celloutsig_0_2z = { in_data[48:41], celloutsig_0_0z, celloutsig_0_0z } !== in_data[74:65];
  assign celloutsig_1_10z = { celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_0z, celloutsig_1_4z } | in_data[117:100];
  assign celloutsig_1_18z = ~^ { in_data[180:176], celloutsig_1_8z, celloutsig_1_4z, celloutsig_1_11z };
  assign celloutsig_0_3z = ^ { in_data[21:1], celloutsig_0_0z, celloutsig_0_0z, celloutsig_0_2z, celloutsig_0_1z, celloutsig_0_1z };
  assign celloutsig_0_15z = in_data[84:73] - { in_data[83:73], celloutsig_0_11z };
  assign celloutsig_1_2z = { celloutsig_1_0z, celloutsig_1_0z, celloutsig_1_0z } ~^ in_data[116:114];
  always_latch
    if (clkin_data[64]) celloutsig_1_16z = 26'h0000000;
    else if (clkin_data[96]) celloutsig_1_16z = { celloutsig_1_10z[17:2], celloutsig_1_0z, celloutsig_1_9z };
  always_latch
    if (clkin_data[32]) celloutsig_0_16z = 15'h0000;
    else if (celloutsig_1_18z) celloutsig_0_16z = { celloutsig_0_15z[5], _01_[9:3], _00_, _01_[1:0], celloutsig_0_3z, celloutsig_0_9z, celloutsig_0_1z, celloutsig_0_1z };
  assign _01_[2] = _00_;
  assign { out_data[128], out_data[103:96], out_data[43:32], out_data[14:0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_15z, celloutsig_0_16z };
endmodule
