/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [2:0] _01_;
  reg [3:0] _02_;
  reg [8:0] _03_;
  reg [18:0] _04_;
  wire [17:0] celloutsig_0_0z;
  wire celloutsig_0_10z;
  wire celloutsig_0_12z;
  wire celloutsig_0_14z;
  wire celloutsig_0_15z;
  wire [4:0] celloutsig_0_1z;
  wire celloutsig_0_2z;
  wire celloutsig_0_3z;
  wire [2:0] celloutsig_0_4z;
  wire [6:0] celloutsig_0_5z;
  wire [10:0] celloutsig_0_6z;
  wire celloutsig_0_7z;
  wire celloutsig_1_0z;
  wire [11:0] celloutsig_1_10z;
  wire [30:0] celloutsig_1_12z;
  wire celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire [12:0] celloutsig_1_2z;
  wire celloutsig_1_3z;
  wire celloutsig_1_4z;
  wire [2:0] celloutsig_1_5z;
  wire celloutsig_1_6z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_0_12z = celloutsig_0_3z | ~(_00_);
  assign celloutsig_0_15z = celloutsig_0_1z[0] | ~(in_data[14]);
  assign celloutsig_1_18z = celloutsig_1_5z[1] | celloutsig_1_1z;
  assign celloutsig_0_7z = celloutsig_0_1z[2] | celloutsig_0_4z[2];
  assign celloutsig_1_1z = in_data[148] | celloutsig_1_0z;
  assign celloutsig_0_3z = celloutsig_0_2z ^ in_data[12];
  assign celloutsig_1_0z = ~(in_data[116] ^ in_data[159]);
  assign celloutsig_1_5z = { in_data[135:134], celloutsig_1_0z } + { celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_4z };
  reg [2:0] _13_;
  always_ff @(negedge celloutsig_1_18z, posedge clkin_data[64])
    if (clkin_data[64]) _13_ <= 3'h0;
    else _13_ <= celloutsig_0_1z[4:2];
  assign { _01_[2], _00_, _01_[0] } = _13_;
  always_ff @(posedge clkin_data[32], posedge clkin_data[96])
    if (clkin_data[96]) _02_ <= 4'h0;
    else _02_ <= { celloutsig_1_5z, celloutsig_1_3z };
  always_ff @(negedge clkin_data[32], negedge clkin_data[96])
    if (!clkin_data[96]) _03_ <= 9'h000;
    else _03_ <= { celloutsig_1_2z[8:5], celloutsig_1_0z, _02_ };
  always_ff @(posedge clkin_data[0], posedge clkin_data[96])
    if (clkin_data[96]) _04_ <= 19'h00000;
    else _04_ <= { in_data[148:131], celloutsig_1_4z };
  assign celloutsig_0_14z = { celloutsig_0_5z[1], celloutsig_0_2z, celloutsig_0_12z, celloutsig_0_2z, celloutsig_0_4z } == { celloutsig_0_10z, celloutsig_0_7z, celloutsig_0_1z };
  assign celloutsig_1_3z = { celloutsig_1_2z[11:4], celloutsig_1_1z } == celloutsig_1_2z[8:0];
  assign celloutsig_1_6z = in_data[142:125] == { in_data[156:155], celloutsig_1_2z, celloutsig_1_5z };
  assign celloutsig_1_19z = celloutsig_1_10z[8:5] >= celloutsig_1_12z[27:24];
  assign celloutsig_1_4z = { celloutsig_1_2z[12:9], celloutsig_1_3z, celloutsig_1_1z } >= celloutsig_1_2z[7:2];
  assign celloutsig_0_2z = { in_data[52:32], celloutsig_0_1z, celloutsig_0_0z, celloutsig_0_1z } > in_data[57:9];
  assign celloutsig_0_4z = celloutsig_0_1z[2:0] % { 1'h1, celloutsig_0_0z[2:1] };
  assign celloutsig_0_0z = in_data[34] ? in_data[90:73] : in_data[23:6];
  assign celloutsig_0_6z = celloutsig_0_3z ? celloutsig_0_0z[17:7] : { celloutsig_0_1z[2:0], 1'h0, celloutsig_0_5z };
  assign celloutsig_0_1z = in_data[53] ? celloutsig_0_0z[14:10] : celloutsig_0_0z[16:12];
  assign celloutsig_0_10z = celloutsig_0_6z[6:5] != celloutsig_0_1z[1:0];
  assign celloutsig_1_2z = - in_data[139:127];
  assign celloutsig_0_5z = { celloutsig_0_0z[13:8], celloutsig_0_2z } << { celloutsig_0_1z[2:1], celloutsig_0_1z };
  assign celloutsig_1_10z = { celloutsig_1_4z, celloutsig_1_1z, celloutsig_1_4z, celloutsig_1_6z, celloutsig_1_3z, celloutsig_1_3z, celloutsig_1_0z, celloutsig_1_3z, _02_ } >> in_data[173:162];
  assign celloutsig_1_12z = { celloutsig_1_2z[4:2], _03_, _04_ } >>> in_data[187:157];
  assign _01_[1] = _00_;
  assign { out_data[128], out_data[96], out_data[32], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_14z, celloutsig_0_15z };
endmodule
