/* Generated by Yosys 0.37+29 (git sha1 3c3788ee2, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module top(clkin_data, in_data, out_data);
  wire _00_;
  wire [3:0] _01_;
  reg [2:0] _02_;
  reg [9:0] _03_;
  wire [5:0] celloutsig_0_0z;
  wire celloutsig_0_2z;
  wire [7:0] celloutsig_1_0z;
  wire celloutsig_1_10z;
  wire [5:0] celloutsig_1_12z;
  wire celloutsig_1_13z;
  wire celloutsig_1_14z;
  wire celloutsig_1_16z;
  wire [4:0] celloutsig_1_18z;
  wire celloutsig_1_19z;
  wire celloutsig_1_1z;
  wire celloutsig_1_2z;
  wire [20:0] celloutsig_1_3z;
  wire [5:0] celloutsig_1_4z;
  wire [2:0] celloutsig_1_5z;
  wire celloutsig_1_7z;
  wire [11:0] celloutsig_1_8z;
  wire [17:0] celloutsig_1_9z;
  input [127:0] clkin_data;
  wire [127:0] clkin_data;
  input [191:0] in_data;
  wire [191:0] in_data;
  output [191:0] out_data;
  wire [191:0] out_data;
  assign celloutsig_1_1z = celloutsig_1_0z[6] ? in_data[118] : celloutsig_1_0z[0];
  assign celloutsig_1_2z = celloutsig_1_1z ? celloutsig_1_0z[0] : in_data[99];
  assign celloutsig_1_7z = ~_00_;
  assign celloutsig_1_10z = ~celloutsig_1_1z;
  reg [3:0] _08_;
  always_ff @(negedge clkin_data[0], posedge clkin_data[96])
    if (clkin_data[96]) _08_ <= 4'h0;
    else _08_ <= in_data[173:170];
  assign { _01_[3:2], _00_, _01_[0] } = _08_;
  reg [14:0] _09_;
  always_ff @(negedge celloutsig_1_18z[0], posedge clkin_data[32])
    if (clkin_data[32]) _09_ <= 15'h0000;
    else _09_ <= { in_data[10:8], celloutsig_0_0z, celloutsig_0_0z };
  assign out_data[46:32] = _09_;
  always_ff @(posedge clkin_data[0], negedge clkin_data[64])
    if (!clkin_data[64]) _02_ <= 3'h0;
    else _02_ <= { celloutsig_1_9z[13:12], celloutsig_1_10z };
  always_ff @(negedge clkin_data[0], posedge clkin_data[96])
    if (clkin_data[96]) _03_ <= 10'h000;
    else _03_ <= { in_data[172:170], celloutsig_1_2z, celloutsig_1_12z };
  assign celloutsig_1_14z = celloutsig_1_3z[9:6] > { celloutsig_1_12z[4:3], celloutsig_1_10z, celloutsig_1_1z };
  assign celloutsig_1_19z = { celloutsig_1_8z[2:0], celloutsig_1_14z, _01_[3:2], _00_, _01_[0], celloutsig_1_13z, celloutsig_1_4z, _01_[3:2], _00_, _01_[0], _03_, celloutsig_1_13z, _02_ } > { celloutsig_1_18z[2], celloutsig_1_13z, celloutsig_1_7z, celloutsig_1_16z, celloutsig_1_10z, celloutsig_1_10z, celloutsig_1_8z, celloutsig_1_1z, _02_, celloutsig_1_5z[2], celloutsig_1_5z[2], celloutsig_1_5z[0], celloutsig_1_16z, celloutsig_1_4z, celloutsig_1_14z };
  assign celloutsig_0_2z = in_data[26:16] > out_data[46:36];
  assign celloutsig_0_0z = ~ in_data[93:88];
  assign celloutsig_1_0z = ~ in_data[174:167];
  assign celloutsig_1_4z = ~ in_data[131:126];
  assign celloutsig_1_8z = ~ { _01_[3:2], _00_, celloutsig_1_2z, celloutsig_1_0z };
  assign celloutsig_1_12z = ~ celloutsig_1_0z[6:1];
  assign celloutsig_1_3z = { celloutsig_1_0z[6:4], celloutsig_1_2z, celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_0z } >> { celloutsig_1_0z[4:3], celloutsig_1_2z, celloutsig_1_1z, celloutsig_1_2z, celloutsig_1_0z, celloutsig_1_0z };
  assign celloutsig_1_18z = { celloutsig_1_4z[2:0], celloutsig_1_16z, celloutsig_1_7z } >> { _03_[3:0], celloutsig_1_1z };
  assign celloutsig_1_13z = ~((celloutsig_1_2z & celloutsig_1_5z[2]) | (celloutsig_1_7z & celloutsig_1_7z));
  assign celloutsig_1_16z = ~((_02_[2] & celloutsig_1_8z[3]) | (celloutsig_1_14z & celloutsig_1_2z));
  assign { celloutsig_1_5z[2], celloutsig_1_5z[0] } = ~ { celloutsig_1_2z, celloutsig_1_1z };
  assign { celloutsig_1_9z[8], celloutsig_1_9z[6:0], celloutsig_1_9z[17:9] } = ~ { celloutsig_1_5z[2], celloutsig_1_5z[0], celloutsig_1_4z, in_data[184:176] };
  assign _01_[1] = _00_;
  assign celloutsig_1_5z[1] = celloutsig_1_5z[2];
  assign celloutsig_1_9z[7] = celloutsig_1_9z[8];
  assign { out_data[132:128], out_data[96], out_data[0] } = { celloutsig_1_18z, celloutsig_1_19z, celloutsig_0_2z };
endmodule
