-- fp_exp_arria10.vhd

-- Generated using ACDS version 16.0 211

library IEEE;
library altera_fp_functions_160;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fp_exp_arria10 is
	port (
		a      : in  std_logic_vector(31 downto 0) := (others => '0'); --      a.a
		areset : in  std_logic                     := '0';             -- areset.reset
		clk    : in  std_logic                     := '0';             --    clk.clk
		q      : out std_logic_vector(31 downto 0)                     --      q.q
	);
end entity fp_exp_arria10;

architecture rtl of fp_exp_arria10 is
	component fp_exp_arria10_altera_fp_functions_160_lvppkfy is
		port (
			clk    : in  std_logic                     := 'X';             -- clk
			areset : in  std_logic                     := 'X';             -- reset
			a      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- a
			q      : out std_logic_vector(31 downto 0)                     -- q
		);
	end component fp_exp_arria10_altera_fp_functions_160_lvppkfy;

	for fp_functions_0 : fp_exp_arria10_altera_fp_functions_160_lvppkfy
		use entity altera_fp_functions_160.fp_exp_arria10_altera_fp_functions_160_lvppkfy;
begin

	fp_functions_0 : component fp_exp_arria10_altera_fp_functions_160_lvppkfy
		port map (
			clk    => clk,    --    clk.clk
			areset => areset, -- areset.reset
			a      => a,      --      a.a
			q      => q       --      q.q
		);

end architecture rtl; -- of fp_exp_arria10
