// Seed: 2481671588
module module_0 (
    input uwire id_0,
    output wand id_1,
    output supply0 id_2,
    input wand id_3,
    output wor id_4,
    output supply0 id_5,
    output tri id_6,
    input wire id_7,
    input supply1 id_8,
    output tri id_9,
    input wor id_10,
    input supply1 id_11,
    input supply1 id_12,
    input wand id_13,
    output supply0 id_14,
    input supply0 id_15,
    output wor id_16,
    input uwire id_17,
    input tri0 id_18
    , id_29,
    input wand id_19,
    input tri0 id_20,
    input supply1 module_0,
    input supply0 id_22,
    input tri0 id_23,
    inout supply0 id_24,
    input wand id_25,
    input tri0 id_26,
    output tri1 id_27
);
endmodule
module module_1 (
    input tri id_0,
    output wor id_1,
    input supply1 id_2,
    output wire id_3,
    input supply0 id_4,
    input tri id_5,
    input wor id_6,
    input tri0 id_7,
    inout tri id_8,
    input tri0 id_9,
    input tri1 id_10,
    output tri1 id_11,
    output uwire id_12
);
  module_0(
      id_0,
      id_11,
      id_8,
      id_5,
      id_11,
      id_12,
      id_8,
      id_10,
      id_10,
      id_8,
      id_5,
      id_0,
      id_6,
      id_8,
      id_8,
      id_7,
      id_1,
      id_8,
      id_7,
      id_2,
      id_6,
      id_2,
      id_0,
      id_10,
      id_8,
      id_7,
      id_7,
      id_11
  );
endmodule
