// Seed: 2034580301
module module_0 (
    input supply0 id_0,
    input wor id_1,
    output wand id_2,
    input wor id_3,
    input supply0 id_4,
    input wand id_5,
    input supply0 id_6,
    output tri1 id_7,
    input tri id_8,
    output tri id_9,
    input wor id_10,
    input tri0 id_11,
    output tri1 id_12,
    output wire id_13,
    input supply0 id_14,
    input tri id_15,
    input wand id_16,
    output supply1 id_17,
    output wand id_18,
    output wire id_19,
    input wor id_20,
    input tri1 id_21,
    input wand id_22,
    input tri1 id_23,
    output tri id_24,
    output tri id_25,
    inout wor id_26,
    input tri id_27
);
endmodule
module module_1 (
    input tri0 id_0,
    output tri id_1,
    input supply0 id_2,
    input uwire id_3,
    input wire id_4,
    inout wand id_5,
    input wand id_6,
    input uwire id_7,
    output wor id_8,
    input wand id_9,
    output tri1 id_10,
    output wire id_11,
    output tri1 id_12
);
  assign id_11 = 1;
  xor primCall (id_11, id_2, id_9, id_3, id_6, id_7, id_4, id_0, id_5);
  module_0 modCall_1 (
      id_0,
      id_5,
      id_8,
      id_5,
      id_2,
      id_9,
      id_7,
      id_12,
      id_6,
      id_8,
      id_5,
      id_0,
      id_12,
      id_8,
      id_5,
      id_7,
      id_7,
      id_8,
      id_11,
      id_11,
      id_6,
      id_2,
      id_0,
      id_0,
      id_11,
      id_1,
      id_5,
      id_2
  );
  assign modCall_1.id_3 = 0;
endmodule
