// Seed: 3618281505
module module_0 (
    input wand id_0,
    input wire id_1,
    input tri1 id_2,
    output tri0 id_3,
    input wor id_4,
    input tri0 id_5,
    input supply1 id_6,
    output tri id_7
    , id_52,
    input wire id_8,
    output tri0 id_9,
    input tri1 id_10,
    input uwire id_11,
    input tri0 id_12,
    input tri1 id_13,
    output tri id_14,
    input tri0 id_15,
    output supply1 id_16,
    input tri0 id_17,
    output wor id_18,
    output supply0 id_19,
    input tri0 id_20,
    input tri0 id_21,
    input wand id_22,
    output uwire id_23,
    input supply1 id_24,
    input tri id_25,
    input supply1 id_26,
    input tri id_27,
    input supply0 id_28,
    input uwire id_29,
    input supply0 id_30,
    input wor id_31,
    input wand id_32,
    output supply1 id_33,
    input uwire id_34,
    output wor id_35,
    input wire id_36,
    output supply0 id_37,
    input uwire id_38,
    input supply0 id_39,
    input tri0 id_40,
    output supply0 id_41,
    input supply1 id_42,
    input wor id_43,
    output tri1 id_44,
    output supply1 id_45,
    output wand id_46,
    input tri1 id_47,
    input supply0 id_48,
    input wire id_49,
    input tri0 id_50
);
  assign id_35 = 1;
  tri1 id_53;
  wire id_54, id_55;
  assign id_53 = 1'b0;
endmodule
module module_1 (
    input wire id_0,
    input tri1 id_1,
    input supply0 id_2,
    output wire id_3,
    input tri0 id_4,
    input wire id_5
    , id_11,
    input wire id_6,
    output wand id_7,
    output supply1 id_8,
    output logic id_9
);
  always id_9 <= 1'b0;
  module_0 modCall_1 (
      id_2,
      id_2,
      id_1,
      id_7,
      id_4,
      id_1,
      id_6,
      id_8,
      id_0,
      id_8,
      id_1,
      id_5,
      id_6,
      id_0,
      id_8,
      id_4,
      id_3,
      id_0,
      id_8,
      id_3,
      id_0,
      id_2,
      id_4,
      id_3,
      id_6,
      id_6,
      id_5,
      id_0,
      id_2,
      id_2,
      id_4,
      id_0,
      id_6,
      id_8,
      id_6,
      id_3,
      id_6,
      id_8,
      id_6,
      id_6,
      id_2,
      id_8,
      id_6,
      id_1,
      id_3,
      id_8,
      id_8,
      id_2,
      id_4,
      id_2,
      id_1
  );
  assign modCall_1.type_62 = 0;
endmodule
