// Seed: 2075760648
module module_0 (
    output supply0 id_0,
    input tri0 id_1,
    input supply1 id_2,
    output tri1 id_3,
    input supply1 id_4,
    input wand id_5,
    input tri1 id_6,
    input supply0 id_7,
    input wor id_8,
    input tri0 id_9,
    output tri id_10,
    input tri1 id_11,
    input tri0 id_12,
    input uwire id_13,
    output tri1 id_14,
    input tri0 id_15,
    input wire id_16,
    output wire id_17,
    input supply1 id_18,
    input wire id_19,
    output tri0 id_20,
    input tri1 id_21,
    input tri0 id_22,
    input wor id_23,
    input supply0 id_24,
    input wire id_25
    , id_29,
    output wor id_26,
    output supply0 id_27
);
endmodule
module module_1 (
    input  uwire id_0,
    input  tri0  id_1,
    output wire  id_2,
    output tri0  id_3,
    input  tri   id_4,
    input  wire  id_5,
    input  tri   id_6,
    output tri0  id_7
);
  wire id_9;
  module_0(
      id_3,
      id_1,
      id_1,
      id_3,
      id_5,
      id_5,
      id_6,
      id_1,
      id_0,
      id_0,
      id_7,
      id_0,
      id_5,
      id_1,
      id_3,
      id_0,
      id_6,
      id_7,
      id_1,
      id_5,
      id_2,
      id_4,
      id_6,
      id_5,
      id_6,
      id_0,
      id_3,
      id_3
  );
endmodule
