// Seed: 4065007101
module module_0 (
    input wand id_0,
    input wand id_1,
    output wire id_2,
    output tri0 id_3,
    output supply1 id_4,
    input wor id_5,
    input tri0 id_6,
    output wand id_7,
    output wand id_8,
    input tri id_9,
    output uwire id_10,
    input uwire id_11,
    input wire id_12,
    input uwire id_13,
    output uwire id_14,
    output uwire id_15,
    input supply0 id_16,
    output wand id_17,
    output uwire id_18,
    input uwire id_19,
    output uwire id_20,
    input wor id_21,
    input tri id_22,
    input wor id_23,
    input supply0 id_24,
    output tri id_25,
    output tri id_26,
    input wand id_27,
    output wand id_28,
    input supply1 id_29,
    input supply0 id_30,
    input wand id_31,
    output wand id_32
);
  wire id_34;
  wire id_35;
endmodule
module module_1 (
    input tri0 id_0,
    input wor id_1,
    input wire id_2,
    output wire id_3,
    output tri0 id_4,
    output wire id_5,
    input supply0 id_6,
    output tri1 id_7,
    output tri0 id_8,
    input supply1 id_9,
    input wor id_10,
    inout supply1 id_11,
    output wand id_12,
    input wor id_13,
    input wor id_14,
    input wire id_15,
    input uwire id_16,
    input supply1 id_17,
    output wand id_18,
    output uwire id_19
);
  assign #1 id_19 = 1;
  module_0(
      id_2,
      id_1,
      id_11,
      id_4,
      id_4,
      id_6,
      id_6,
      id_11,
      id_11,
      id_9,
      id_12,
      id_0,
      id_10,
      id_11,
      id_19,
      id_8,
      id_2,
      id_12,
      id_5,
      id_14,
      id_4,
      id_13,
      id_6,
      id_2,
      id_2,
      id_4,
      id_12,
      id_0,
      id_5,
      id_17,
      id_15,
      id_9,
      id_11
  );
endmodule
