// Seed: 2256643765
module module_1 (
    output supply1 id_0,
    input supply1 module_0,
    input wand id_2,
    output tri0 id_3,
    input wire id_4,
    input tri1 id_5,
    output uwire id_6,
    output tri1 id_7,
    input uwire id_8,
    input uwire id_9,
    output uwire id_10,
    output wire id_11,
    input wand id_12,
    input tri id_13,
    output uwire id_14,
    input uwire id_15,
    input tri1 id_16,
    input wor id_17,
    input tri id_18,
    input supply0 id_19,
    input wire id_20,
    output wor id_21,
    input tri0 id_22,
    input wand id_23,
    input supply0 id_24,
    output uwire id_25,
    input wire id_26,
    input wire id_27,
    output supply0 id_28,
    output supply1 id_29,
    input tri0 id_30
);
  wire id_32;
endmodule
module module_1 (
    input tri0 id_0,
    output supply1 id_1,
    input tri id_2,
    output supply1 id_3,
    output tri0 id_4,
    input uwire id_5,
    output supply0 id_6
);
  module_0(
      id_3,
      id_5,
      id_5,
      id_3,
      id_5,
      id_0,
      id_1,
      id_1,
      id_2,
      id_5,
      id_3,
      id_4,
      id_2,
      id_0,
      id_1,
      id_5,
      id_2,
      id_5,
      id_2,
      id_0,
      id_5,
      id_3,
      id_2,
      id_2,
      id_2,
      id_3,
      id_5,
      id_5,
      id_4,
      id_4,
      id_5
  );
endmodule
