// Seed: 295814484
module module_0 (
    input wire id_0,
    input uwire id_1,
    output uwire id_2,
    output wor id_3,
    input wire id_4,
    input wire id_5,
    input tri1 id_6,
    output supply1 id_7,
    output tri1 id_8,
    output tri id_9,
    input tri0 id_10,
    input tri1 id_11,
    output tri0 id_12,
    input wor module_0,
    input supply1 id_14,
    output tri id_15,
    input wire id_16,
    input tri1 id_17,
    input tri id_18,
    input wire id_19,
    input tri1 id_20,
    input tri0 id_21,
    input wor id_22,
    output wire id_23,
    output tri id_24,
    input supply0 id_25,
    input tri id_26,
    input supply0 id_27,
    output supply0 id_28,
    output tri1 id_29
    , id_52,
    input tri1 id_30
    , id_53,
    output supply1 id_31,
    input tri id_32
    , id_54,
    input tri0 id_33,
    input wire id_34,
    output supply1 id_35,
    input tri0 id_36,
    input tri id_37
    , id_55,
    input wand id_38,
    input supply0 id_39,
    output uwire id_40,
    input tri0 id_41,
    output uwire id_42,
    input tri1 id_43,
    input tri1 id_44,
    output wand id_45,
    output tri id_46,
    input wor id_47,
    input uwire id_48,
    output uwire id_49,
    output wire id_50
);
  wire id_56;
endmodule
module module_1 (
    input supply1 id_0,
    inout tri id_1
);
  supply1 id_3 = 1;
  module_0(
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_1,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_0,
      id_0,
      id_1,
      id_1,
      id_0,
      id_1,
      id_0,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1,
      id_1
  );
endmodule
