// Seed: 836388832
module module_0 (
    output supply0 id_0,
    output tri0 id_1,
    output wor id_2,
    output tri id_3,
    output supply0 id_4,
    output uwire id_5,
    input supply1 id_6,
    input wire id_7,
    output tri1 id_8,
    output tri0 id_9,
    input uwire id_10,
    output uwire id_11,
    input supply0 id_12,
    output supply0 id_13,
    input wor id_14,
    input tri1 id_15,
    input wand id_16,
    input tri1 id_17,
    input uwire id_18,
    input tri1 id_19,
    output wor id_20,
    output supply0 id_21,
    input tri0 id_22,
    output tri1 id_23,
    input tri1 id_24,
    output supply1 id_25,
    input tri0 id_26,
    output supply1 id_27,
    input wire id_28,
    input supply1 id_29,
    output wire id_30,
    input wor id_31,
    input tri1 id_32,
    output uwire id_33,
    input wire id_34,
    input wand id_35,
    input supply0 id_36,
    input supply0 id_37,
    output uwire id_38,
    input wand id_39,
    input tri1 id_40,
    input supply0 id_41,
    input tri0 id_42,
    input wor id_43,
    input supply0 id_44,
    output wand id_45,
    output wire id_46,
    input wand id_47,
    output wire id_48
    , id_84,
    input tri1 id_49,
    input tri0 id_50,
    output tri id_51,
    output tri0 id_52,
    output wand id_53,
    output wand id_54,
    input supply0 id_55,
    output wand id_56,
    input tri0 id_57,
    output supply0 id_58,
    input tri0 id_59,
    output tri0 id_60,
    output wor id_61,
    output supply0 id_62,
    input tri id_63,
    output tri1 id_64,
    output wand id_65
    , id_85,
    output supply1 id_66,
    input wire id_67,
    input tri id_68,
    input tri0 id_69,
    input tri0 id_70,
    input supply1 id_71,
    input supply0 id_72
    , id_86,
    input supply0 id_73,
    input tri0 id_74,
    input uwire id_75,
    input wire id_76,
    output tri id_77,
    input supply1 id_78,
    input uwire id_79,
    input supply0 id_80,
    output supply1 id_81,
    input wire id_82
);
  assign module_1.id_3 = 0;
  logic ["" : -1] id_87;
  ;
endmodule
module module_1 (
    output tri   id_0,
    input  uwire id_1,
    input  wand  id_2,
    input  wire  id_3
);
  module_0 modCall_1 (
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_0,
      id_2,
      id_1,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_3,
      id_2,
      id_3,
      id_2,
      id_2,
      id_3,
      id_0,
      id_0,
      id_2,
      id_0,
      id_2,
      id_0,
      id_3,
      id_0,
      id_1,
      id_2,
      id_0,
      id_3,
      id_3,
      id_0,
      id_3,
      id_1,
      id_1,
      id_2,
      id_0,
      id_3,
      id_2,
      id_1,
      id_1,
      id_2,
      id_2,
      id_0,
      id_0,
      id_2,
      id_0,
      id_1,
      id_1,
      id_0,
      id_0,
      id_0,
      id_0,
      id_1,
      id_0,
      id_1,
      id_0,
      id_2,
      id_0,
      id_0,
      id_0,
      id_3,
      id_0,
      id_0,
      id_0,
      id_1,
      id_2,
      id_2,
      id_2,
      id_1,
      id_2,
      id_3,
      id_3,
      id_2,
      id_2,
      id_0,
      id_1,
      id_1,
      id_3,
      id_0,
      id_3
  );
  assign id_0 = id_3;
endmodule
