// Seed: 2400987473
module module_0 (
    input tri id_0,
    output tri0 id_1
    , id_38,
    input wor id_2,
    output tri0 id_3,
    input wor id_4,
    input tri1 id_5,
    input supply0 id_6,
    output tri0 id_7,
    input supply0 id_8,
    input tri0 id_9,
    input tri0 id_10,
    input wand id_11,
    output uwire id_12,
    input supply1 id_13,
    output tri id_14,
    output supply1 id_15
    , id_39, id_40,
    input tri id_16,
    output supply1 id_17,
    output wand id_18,
    input wire id_19,
    input wire id_20,
    input tri0 id_21,
    output tri1 id_22,
    output uwire id_23,
    output tri0 id_24,
    output tri1 id_25,
    output tri id_26,
    output tri0 id_27,
    input supply1 id_28,
    output tri0 id_29,
    input supply0 id_30,
    output supply1 id_31,
    input wor id_32,
    input tri1 id_33,
    input supply1 id_34,
    output wand id_35,
    input tri1 id_36
);
endmodule
module module_1 (
    output wor id_0,
    input supply1 id_1,
    input supply1 id_2,
    input tri0 id_3,
    input supply1 id_4,
    output supply1 id_5
);
  wire id_7;
  module_0 modCall_1 (
      id_3,
      id_5,
      id_4,
      id_0,
      id_3,
      id_3,
      id_1,
      id_0,
      id_2,
      id_4,
      id_3,
      id_2,
      id_0,
      id_2,
      id_0,
      id_5,
      id_1,
      id_5,
      id_5,
      id_3,
      id_1,
      id_3,
      id_5,
      id_0,
      id_5,
      id_0,
      id_5,
      id_5,
      id_4,
      id_0,
      id_2,
      id_0,
      id_4,
      id_2,
      id_1,
      id_5,
      id_1
  );
endmodule
