// Seed: 1143045957
module module_0 (
    input supply0 id_0,
    output wor id_1,
    input wand id_2,
    input tri id_3,
    input supply1 id_4,
    input tri id_5,
    output supply1 id_6,
    input uwire id_7,
    input supply0 id_8,
    output supply1 id_9,
    input uwire id_10,
    input wor id_11,
    output wire id_12,
    input uwire id_13,
    input supply0 id_14,
    output wire id_15,
    input wand id_16,
    output supply0 id_17,
    input uwire id_18,
    output wand id_19,
    input tri0 id_20,
    output tri0 id_21,
    input supply0 id_22,
    output wor id_23,
    input tri0 id_24,
    output tri id_25,
    output supply1 id_26,
    input tri0 id_27,
    input wor id_28,
    input tri1 id_29,
    input supply0 id_30,
    input tri0 id_31,
    output wand id_32,
    input wire id_33,
    input wire id_34,
    output tri0 id_35,
    input tri1 id_36,
    input uwire id_37
);
endmodule
module module_1 (
    output tri1  id_0,
    output wire  id_1,
    output tri   id_2,
    input  uwire id_3,
    input  tri0  id_4,
    input  tri1  id_5
);
  wire id_7;
  ;
  module_0 modCall_1 (
      id_3,
      id_1,
      id_5,
      id_3,
      id_5,
      id_3,
      id_1,
      id_4,
      id_5,
      id_2,
      id_3,
      id_4,
      id_2,
      id_4,
      id_3,
      id_1,
      id_3,
      id_2,
      id_3,
      id_0,
      id_3,
      id_0,
      id_3,
      id_2,
      id_4,
      id_2,
      id_0,
      id_4,
      id_4,
      id_4,
      id_5,
      id_3,
      id_0,
      id_3,
      id_4,
      id_1,
      id_4,
      id_4
  );
endmodule
