// Seed: 3168151046
module module_0 (
    output wor id_0,
    output uwire id_1,
    input tri1 id_2,
    input tri0 id_3,
    input tri id_4,
    output tri1 id_5,
    output wor id_6,
    input wand id_7,
    output wor id_8,
    input wor id_9,
    input supply1 id_10
    , id_39,
    input supply1 id_11,
    input tri id_12,
    input supply1 id_13,
    input uwire id_14,
    input wire id_15,
    input wand id_16,
    output supply1 id_17,
    input supply0 id_18
    , id_40,
    input tri0 id_19,
    input supply1 id_20,
    input wire id_21,
    output supply1 id_22,
    output tri1 id_23,
    input tri id_24,
    output tri0 id_25,
    input supply0 id_26,
    output supply1 id_27,
    input supply0 id_28,
    input supply1 id_29,
    input tri1 id_30,
    output tri1 id_31
    , id_41, id_42,
    output tri1 id_32,
    input wor id_33,
    output tri0 id_34,
    input uwire id_35,
    input supply1 id_36,
    output tri0 id_37
);
  logic [1 'b0 : -1] id_43, id_44;
endmodule
module module_1 (
    output uwire id_0,
    input uwire id_1,
    output wand id_2,
    output wor id_3,
    output wire id_4,
    input wire id_5,
    output supply1 id_6,
    output wor id_7
);
  supply0 id_9 = -1;
  module_0 modCall_1 (
      id_3,
      id_3,
      id_1,
      id_1,
      id_5,
      id_3,
      id_6,
      id_1,
      id_3,
      id_5,
      id_1,
      id_5,
      id_5,
      id_1,
      id_1,
      id_1,
      id_1,
      id_4,
      id_1,
      id_5,
      id_5,
      id_1,
      id_2,
      id_2,
      id_1,
      id_0,
      id_1,
      id_6,
      id_5,
      id_1,
      id_5,
      id_2,
      id_0,
      id_1,
      id_4,
      id_1,
      id_1,
      id_0
  );
  assign modCall_1.id_30 = 0;
endmodule
