// Seed: 2745160817
module module_0 (
    output tri1 id_0,
    input tri id_1,
    input tri0 id_2,
    output tri id_3,
    input tri1 id_4,
    input tri0 id_5,
    input supply1 id_6,
    input wire id_7,
    input wire id_8,
    input tri id_9,
    input supply1 id_10,
    output tri id_11,
    input uwire id_12,
    input wire id_13,
    output uwire id_14,
    input wor id_15,
    input uwire id_16,
    input wor id_17,
    input wire id_18,
    output wire id_19,
    output wire id_20,
    input wor id_21,
    output supply1 id_22,
    output tri id_23,
    input wand id_24,
    output wire id_25,
    output supply1 id_26,
    input supply1 id_27,
    input supply0 id_28,
    input supply1 id_29,
    output wire id_30
    , id_42,
    output tri id_31,
    output tri1 id_32,
    input supply1 id_33,
    input wand id_34,
    output tri id_35,
    output tri0 id_36,
    output uwire id_37,
    output wor id_38,
    input tri1 id_39,
    output tri id_40
);
  wire id_43;
  wire id_44, id_45, id_46;
  assign module_1.id_0 = 0;
endmodule
module module_1 (
    input tri1 id_0,
    input uwire id_1,
    input tri0 id_2,
    output wand id_3,
    input wire id_4,
    input supply0 id_5,
    input wand id_6
);
  wire id_8;
  module_0 modCall_1 (
      id_3,
      id_5,
      id_5,
      id_3,
      id_6,
      id_4,
      id_5,
      id_6,
      id_6,
      id_0,
      id_0,
      id_3,
      id_5,
      id_6,
      id_3,
      id_2,
      id_0,
      id_2,
      id_5,
      id_3,
      id_3,
      id_6,
      id_3,
      id_3,
      id_0,
      id_3,
      id_3,
      id_4,
      id_0,
      id_4,
      id_3,
      id_3,
      id_3,
      id_4,
      id_1,
      id_3,
      id_3,
      id_3,
      id_3,
      id_4,
      id_3
  );
  assign id_3 = 1'h0;
endmodule
