// Seed: 3968488502
module module_0 (
    output uwire id_0,
    output supply1 id_1,
    input tri id_2,
    input wand id_3,
    input supply1 id_4,
    input wor id_5,
    output tri id_6,
    input supply1 id_7,
    output wor id_8,
    output wand id_9,
    input supply0 id_10,
    input wor id_11,
    input tri id_12,
    input wire id_13,
    input wire id_14,
    input supply0 id_15,
    output supply0 id_16,
    output tri1 id_17,
    output wor id_18,
    input tri id_19,
    input tri1 id_20,
    input tri0 id_21,
    output wand id_22,
    input wire id_23,
    output wor id_24,
    output wire id_25,
    output tri0 id_26,
    output supply0 id_27,
    output tri id_28,
    input supply1 id_29,
    output tri0 id_30,
    input tri1 id_31
);
endmodule
module module_1 #(
    parameter id_9 = 32'd12
) (
    input tri1 id_0,
    input tri1 id_1,
    output tri0 id_2,
    output wire id_3,
    input wor id_4,
    input supply0 id_5,
    output wand id_6,
    input uwire id_7,
    input tri1 id_8,
    output wire _id_9
);
  logic [id_9 : -1] id_11;
  module_0 modCall_1 (
      id_6,
      id_2,
      id_4,
      id_8,
      id_4,
      id_5,
      id_6,
      id_1,
      id_2,
      id_2,
      id_1,
      id_0,
      id_5,
      id_1,
      id_8,
      id_5,
      id_3,
      id_2,
      id_3,
      id_7,
      id_5,
      id_0,
      id_2,
      id_0,
      id_2,
      id_3,
      id_3,
      id_3,
      id_2,
      id_5,
      id_3,
      id_0
  );
  assign modCall_1.id_13 = 0;
endmodule
